### ISSUE TITLE
Support for Go benchmarks

### ISSUE THREAD

**Issue by janhancic** [thought-machine/please#1013]
Go has a very handy feature where once can write benchmarks in similar fashion as tests: https://golang.org/pkg/testing/#hdr-Benchmarks

To run them one passes `-bench` to the `go test` command (note that there are other very useful command line arguments for this). This then runs the benchmarks in the given file and produces output that looks something like this (taken from [this article](https://dave.cheney.net/high-performance-go-workshop/gopherchina-2019.html)):

```
% go test -bench=. -cpu=1,2,4 ./examples/fib/
goos: darwin
goarch: amd64
BenchmarkFib20             30000             39115 ns/op
BenchmarkFib20-2           30000             39468 ns/op
BenchmarkFib20-4           50000             40728 ns/op
PASS
ok      _/Users/dfc/devel/high-performance-go-workshop/examples/fib     5.531s
```

Being able to run this through Please would be greatly beneficial as it would allow developers that rely on Please to build their Go projects to more easily optimise their code.

In its basic form this feature should just allow one to essentially add `-bench` (& others) to the `plz test` command. But ideally we could also capture this output so that it can be feed into some other system that could keep track of the results over time.

**Comment by Tatskaari** [comment]
I've implemented some rudimentary support for this via go_benchmark in #1014

I think we'll leave parsing the output of this and collecting those over time to the CI system. 

One note is that because this isn't using `go test` the args are slightly different. For example `-test.cpu=1,2,3` instead of jsut `-cpu=1,2,3`

**Comment by janhancic** [comment]
Amazing turnaround, thanks @Tatskaari!
