### ISSUE TITLE
Does PLZ support NodeJS as third party libs to build the artifacts or pull it from npm artifactory 

### ISSUE THREAD

**Issue by dixitneha** [thought-machine/please#1030]

**Comment by Tatskaari** [comment]
We support yarn in our auxiliary repo: https://github.com/thought-machine/pleasings/tree/master/js

**Comment by Tatskaari** [comment]
I've done some work with some more work on our yarn rules. You can find an example project using a yarn workspace at the link above. Let me know what you think.
