### ISSUE TITLE
Remote ex: Errors marshalling proto messages when uploading build actions

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1037]
We're getting errors on un-marshalling protos when uploading build actions to mettle. These errors seem to happen fairly infrequently considering how often this method is called and it succeeds on retry. 

Here's some examples of the messages: 

```
Failed to upload build action: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: can't skip unknown wire type 7

Failed to upload build action: rpc error: code = Internal desc = grpc: failed to unmarshal the received message unexpected EOF

Failed to upload build action: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: can't skip unknown wire type 4
```

It seems pretty random what wire type you get and sometimes it fails with an unexpected EOF. This might just be something to do with our internal network at Thought Machine. Messages might be getting corrupted somehow however there's not much between the clients and mettle.

**Comment by Tatskaari** [comment]
Turns out this was to do with flair not please itself.

**Comment by iswaverly** [comment]
I got the same issue on other project. It would of great help if you could share how you solve it.

**Comment by Tatskaari** [comment]
It was an issue with our remote execution server I believe. Something to do with processing progress updates out of order (@peterebden  would know more).

Though if you're not using our remote execution servers then I doubt you'd be hitting the same issue as us.
