### ISSUE TITLE
Conflicting Go package names

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1074]
When introducing Please to a large project, the following error ocurred:

```
    //internal/helm:_test#lib
Error building target //internal/helm:_test#lib: exit status 1
internal/helm/envresolver_integration_test.go, line 21, column 2: internal compiler error: conflicting package heights 44 and 12 for path "testing"

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

Based on examining the code, the culprit was a custom `testing` package that was imported alongside the `testing` package from the standard library.

When I tried to reproduce this issue, I found that packages with the same name can potentially conflict and simply overwrite each other.
(My guess is that if the official `testing` package gets imported in a transitive dependency and then higher in the chain there is another testing package, you get the package height error above.)

I reproduced the issue here: https://github.com/sagikazarmark/please-issues/tree/master/package-height

I also added a potential solution.

**Comment by Tatskaari** [comment]
I think this makes a lot of sense but your solution doesn't do what I'd expect it to do. 

It will place the output in `plz-out/gen/please-issues/package-height/lib/testing/pkg/linux_amd64/lib/testing.a`

When what I assume you want is `plz-out/gen/pkg/linux_amd64/please-issues/package-height/lib/testing.a`. 

I think the real way to solve this would require a little help from please to allow rules to tweak their output locations. This would go a long way to help the go rules.

**Comment by sagikazarmark** [comment]
Right, I might have overlooked something, but I guess the solution explained above should work.

**Comment by sagikazarmark** [comment]
I was thinking about this issue (and GOPATH with please in general): with the `"link:plz-out/go"` label and using `plz-out/go` as the GOPATH, these issues would magically go away, wouldn't they?

I could use some advice on this one, because better module support in please is so close, but the GOPATH and linked include path magic confuses the whole thing. 🙂

**Comment by sagikazarmark** [comment]
I've been experimenting with the go build tool and I found two ways to link packages properly:

1. Generate a file with a list of package mappings from import path to archive file

We need to extract two/three bits of information from each (Go) dependency:

- If the dependency is a _package_ then its import path
- If the dependency is a _module_, then the list of compiled packages in it
- The list of compiled archive files for each packages

(This is true for the current `go_get` rule as well)

I don't think this is easy to do with please, but the official Go build tool uses this solution, because it loads archive files from caches.

2. Help with saving outputs in a single place

Currently this can be achieved with symlinks, but there is no "official" way to use the globally symlinked pkg directory and it doesn't work well with cross-compiling.


Compared to the current solution (look for src/ and pkg/ to determine GOPATHS), these two would be less hacky and work universally (for example: it doesn't work with separate Go modules sharing an import path root and an internal package. Go complains not being in the same GOPATH, whereas in module mode that's not a requirement)

**Comment by sagikazarmark** [comment]
I guess #1158 fixes this issue.

**Comment by Tatskaari** [comment]
> I guess #1158 fixes this issue.

Do you have an example to easily verify?

**Comment by sagikazarmark** [comment]
Here is the original repository reproducing the issue: https://github.com/sagikazarmark/please-issues/tree/master/package-height

**Comment by Tatskaari** [comment]
Nice, looks like this will be resolved in the next please release (when it exits beta)
