### ISSUE TITLE
Please should descend into the package directory when running go test

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1075]
The go tool executes test binaries inside the package directory, which lets tests use resources relative to the package path. Please on the other hand executes the test binary in the test run root. I think it should descend into package directory and run from there.

My use cases:

- read a file from a higher directory passed as data to the test
- read files from `testdata` in the same package passed as data to the test

WDYT?

**Comment by sagikazarmark** [comment]
From `go help testflag`: 

> When 'go test' runs a test binary, it does so from within the
> corresponding package's source code directory. Depending on the test,
> it may be necessary to do the same when invoking a generated test
> binary directly.

**Comment by Tatskaari** [comment]
Sounds like a reasonable idea. I've had annoyances where test data is loaded differently by my IDE and go tools vs. how please actually runs the test. I'd probably class this as a breaking change though so probably will have to be done for please 16.0.0. 

What do you think @peterebden?

**Comment by peterebden** [comment]
This would be a seriously breaking change, yes. I have thought this before but I'm not very enthusiastic since it makes Go tests work differently to other languages.

Maybe we could have some way of opting into this or a config option? That would make it a lot easier in terms of an upgrade path.

**Comment by sagikazarmark** [comment]
> since it makes Go tests work differently to other languages.

Well, it makes it work differently to regular Go tests, which means the test code is not compatible with both please and the Go toolkit at the same time, which sounds worse to me.

A global option sounds like an acceptable solution (I doubt anyone would want to control this per rule)

**Comment by Tatskaari** [comment]
Will consider this for v16

**Comment by sagikazarmark** [comment]
🎉
