### ISSUE TITLE
Preload rules from a third-party repository

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1084]
Similarly how please downloads itself on the first run (using the wrapper script or a pinned version), it could also download and preload rules from third-party repositories/remote locations.

I see the downsides of this idea as well, but the only alternative I can imagine (apart from copy-pasting files) is using submodules.

I understand that subinclude is exactly for this use case, but it's rather annoying when you want to override a core rule, especially if that's temporary.

**Comment by Tatskaari** [comment]
You can include stuff from remote repos via subrepo rules and please will download these on demand. Is there a reason you want them pre-loaded? 

As for it being annoying to have to sub-include them everywhere, perhaps we can have a config option for globally included rules?

**Comment by sagikazarmark** [comment]
Yeah, I can see why it is hard and probably a bit unreliable, but I think it's worth a look.

**Comment by peterebden** [comment]
FYI there is a config option `parse.preloadbuilddefs`, but the preloaded rules have to be files within the repo. Does that help for your case at all? We use it for a similar kind of thing internally (overriding core rules, as well as adding some additional ones that are used widely enough that we don't want to `subinclude` them everywhere).

**Comment by sagikazarmark** [comment]
I kinda want to avoid duplicating the rules in every repo. I could use things like git submodules, but meh.....I don't like that option either.

**Comment by sagikazarmark** [comment]
Nope 🙂

**Comment by sagikazarmark** [comment]
Isn't this already implemented?

**Comment by Tatskaari** [comment]
yes it is via:
```
[Parse]
PreloadSubinclude = //build/defs:foo
```

https://please.build/config.html#parse
