### ISSUE TITLE
Use semver for beta versions 

### ISSUE THREAD

**Issue by nmpowell** [thought-machine/please#1093]
Use semver for beta versions.

Currently we have `Downgrading to Please version 15.0.0-beta10 (currently 15.0.0-beta8)` because the standard syntax is `beta.10 > beta.8` rather than `beta10`, I believe.

Beta versions are quite frequent so this must be fairly common...

https://semver.org/ has `Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.`

**Comment by Tatskaari** [comment]
Thanks, you're right. We noticed this too. Will do it next time. :)
