### ISSUE TITLE
Go cross-compile doesn't work unless the standard library is compiled manually first

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1108]
The current please rules for Go do not compile the standard library, it expects it to be done and the result available in GOROOT.

For the host os and arch this is not a problem, because the Go installers usually compile the stdlib as part of the installation process. For cross-compiling this is a problem, but it can be easily solved by compiling the standard library in the GOROOT manually, for example:

```bash
sudo GOOS=linux go install -v std
```

(`sudo` is required because GOROOT is usually in /usr/local which is not writable for regular users)

It might make sense to add this to the documentation somewhere (apologies if it's already there).

Inspecting the output of `go build -x ...` shows that it actually compiles the standard library as well:

```
/usr/local/go/pkg/tool/darwin_amd64/compile -o $WORK/b028/_pkg_.a -trimpath "$WORK/b028=>" -p crypto/subtle -std -complete -buildid 5C3uhrVGPvbT2p5erT6a/5C3uhrVGPvbT2p5erT6a -goversion go1.14.6 -D "" -importcfg $WORK/b028/importcfg -pack -c=4 ./constant_time.go
```

Personally, I like this approach, because it makes the build depend on the environment less, but I have no idea how to properly implement this in please (other than adding stdlib dependencies to build rules, which doesn't sound good)

**Comment by Tatskaari** [comment]
This might be something i can address when i get round to writing the go_toolchain rules cc #771
