### ISSUE TITLE
Limit Max Amount of Parallel HTTP Cache Requests

### ISSUE THREAD

**Issue by fkorotkov** [thought-machine/please#1111]
It seems there is no limit on how many requests can be done simultaneously which can overwhelm either network or remote cache. It might be reasonable to limit the amount of parallel cache requests based on amount of CPUs or do like Bazel and limit by a [configurable flag with a default of 100](https://github.com/bazelbuild/bazel/blob/62475e738f1206a06dbda0d2638015c2c2fb1c88/src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java#L60-L69)

**Comment by Tatskaari** [comment]
Cache requests are probably not CPU bound but we can probably try and limit this to some configurable number like you suggest.
