### ISSUE TITLE
go_test() errors with some specifics packages names

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#1139]
Using please 15.1.0, i found some errors on go_test().

With a simple BUILD file:

```
go_test(
    name = "test",
    srcs = ["runtime_test.go"],
)
```

And a go test file "runtime_test.go":

```
package runtime

import "testing"

func Test(t *testing.T) {}
```

Running `plz test :test` results in:

```
Build stopped after 110ms. 1 target failed:
    //:test
Error building target //:test: exit status 1
panic: found import cycle while visiting runtime

goroutine 1 [running]:
cmd/link/internal/ld.dfs(0xc0007144e0, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2555 +0x254
cmd/link/internal/ld.dfs(0xc0007145b0, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2559 +0xfb
cmd/link/internal/ld.dfs(0xc0007144e0, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2559 +0xfb
cmd/link/internal/ld.dfs(0xc000715c70, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2559 +0xfb
cmd/link/internal/ld.dfs(0xc00084ec30, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2559 +0xfb
cmd/link/internal/ld.dfs(0xc000715d40, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2559 +0xfb
cmd/link/internal/ld.dfs(0xc000088c30, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2559 +0xfb
cmd/link/internal/ld.dfs(0xc000714270, 0xc00004f060, 0xc00004f048)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2559 +0xfb
cmd/link/internal/ld.postorder(0xc000beda00, 0x2f, 0x40, 0xb, 0x878800, 0x6ddfcc)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:2545 +0x10f
cmd/link/internal/ld.(*Link).loadlib(0xc0006ee000)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/lib.go:637 +0x9f1
cmd/link/internal/ld.Main(0x84cdc0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x69ac6f, 0x1b, 0x697756, 0x14, ...)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/main.go:208 +0xb5f
main.main()
        /usr/lib/go-1.13/src/cmd/link/main.go:65 +0x1d6
```

Same thing with other packages names that are imported by `testing`, like `io` or `fmt`.

With package names that are imported by the generated go main test file, like `os`or `strings`, `plz test :test` returns:

```
Build stopped after 70ms. 1 target failed:
    //:_test#main_lib
Error building target //:_test#main_lib: exit status 1
test_main.go, line 34, column 22: undefined: "os".Args
test_main.go, line 37, column 16: undefined: "os".Getenv
test_main.go, line 42, column 5: undefined: "os".Args
test_main.go, line 47, column 2: undefined: "os".Exit
```

But with other packages names, like `package test`, everything works well.

```
//:test 1 test run in 2ms; 1 passed
    Test  PASS  0s
1 test target and 1 test run in 2ms; 1 passed. Total time 260ms.
```

**Comment by Tatskaari** [comment]
I'm going to have a look into this however I suspect it's some edge case with having duplicate packages with the same name. 

One workaround might be to specify an import path in your .plzconfig:

```
[go]
importpath = github.com/some-person/some-project
```

**Comment by sfirmery** [comment]
Thanks for you reply.

I already have an `importpath` defined. So, i've tried without it.

Without `importpath`, for packages names like `io` or `runtime`, i have:

```
Build stopped after 80ms. 1 target failed:
    //:_test#main_lib
Error building target //:_test#main_lib: exit status 1
test_main.go, line 11, column 2: internal compiler error: conflicting package heights 5 and 13 for path "io"

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

And for packages names that are imported by test main file, the error is the same as with a `importpath` defined.

**Comment by Tatskaari** [comment]
yeah sorry, I realised that wasn't going to work (and deleted my comment shamelessly) 

There's a problem with the way we symlink things around to set up the import path. I'm working on a fix.

**Comment by Tatskaari** [comment]
A quick update: this is proving to be a bit of an ordeal to fix. I've got a draft PR that demonstrates one potential approach #1154

Might not get this fixed until v16 though as it's not very backwards compatible. Do you have a workaround?

**Comment by sfirmery** [comment]
Thanks for the update. I've just prefixed the package name to avoid those names.

**Comment by sagikazarmark** [comment]
#1158 is the solution after all, and I guess it's actually backwards compatible, isn't it?

**Comment by Tatskaari** [comment]
Yup! Thanks mark. You can try it out if you set this in your plz config:
```
[please]
version = 15.2.1-beta.2
```

I'll do a proper release once I'm more comfortable with the change. It has quite a lot of surface area.

**Comment by Tatskaari** [comment]
15.3.0 has been release which resolves this issue :D

**Comment by sfirmery** [comment]
Sorry for my late reply, it works now! Thanks!
