### ISSUE TITLE
Add retry to HTTP cache

### ISSUE THREAD

**Issue by robxu9** [thought-machine/please#1140]
I've recently started to use a HTTP cache for please as part of moving some of my personal builds to using Gitlab CI. I've noticed that the HTTP cache doesn't seem to handle errors well - for example, if there are timeouts on reading or writing to the cache, or unexpected EOFs because the cache connection breaks for whatever reason.

I'm wondering if it would be good to have a retry for the HTTP cache on any sort of error - that way, when a connection timeout or EOF (or any other weird error) occurs, please doesn't just assume the files don't exist in the cache and then goes on to rebuild the entire tree.

Context: Right now, for Gitlab CI, I have an rclone service acting as a sidecar so that it can proxy webdav calls to S3. Ideally, it might also be good to have an S3-compatible cache as well, but retries would be good in general, so I figure that's probably the better thing to tackle here.

(I'd be happy to send an initial PR for this if this sounds like a good idea, but I wanted to run the idea by here first.)

**Comment by peterebden** [comment]
Yup, makes sense to me. We should be able to use https://github.com/hashicorp/go-retryablehttp for it.
Very happy if you want to send a PR for it, thanks for offering to help!

Do you know what would be needed for S3 to work? The protocol is very simple and from a brief look I thought it might work as is.

**Comment by robxu9** [comment]
Can do!

S3 is pretty simple, yeah - GetObject/PutObject (and a couple other APIs), and authentication in the form of signing requests with credentials. The easiest way would be to pull in the AWS SDK for Go in and use that, and then rely on the user to configure the credentials, endpoint, bucket name, and (optional) prefix.

**Comment by peterebden** [comment]
OK, I thought maybe there was an HTTP API we could use against the HTTP cache.

My preference would be to use something like gocloud so we're agnostic to the specific backend (and could then swap in e.g. GCS too). Mild concern about these being quite a heavy dependency, but it's getting a bit off-topic here :)

**Comment by robxu9** [comment]
gocloud is probably the better way, yeah. But agreed, we're diverging - I can open another issue for that :)
