### ISSUE TITLE
Rethink distribution strategy

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#1145]
Currently we distribute plz as a tarball with plz itself and a series of helper binaries in it.
This has served us well for a long time but does have some finicky consequences; particularly the way those helper binaries are located is a little ick (we have to add the plz install location to the PATH) which is especially obvious for remote execution. We're also forcing the download of a bunch of things people might not need (for example users always download the Java bits, even if they have no intention of building any Java code).

I think we should move towards a different model where the primary download is simply the plz binary. Anything else can be fetched by it within the repo; it might be useful to beef up `plz init` and provide a convenient builtin to make those available.

We will obviously have to keep shipping the tarball for some time for compatibility reasons. However I think we should move the Java stuff completely out and serve it through the `java_toolchain` rule; they can be easily downloaded from Maven. Further in the future we might do the same for more language-specific stuff to slim down the "core" distribution even more.

Some work may be needed on the sandbox tool due to the unique way it gets invoked.

**Comment by Tatskaari** [comment]
could end up being related to #1192

**Comment by Tatskaari** [comment]
Essentially done. We might want to get rid of `get.please.build` and just encourage people to link the wrapper script into their path.
