### ISSUE TITLE
Exit code is zero despite failing build

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1148]
I noticed in a CI job, that despite the failing build the job itself didn't fail:

![Screenshot 2020-08-22 at 19 02 57](https://user-images.githubusercontent.com/1226384/90961554-19676080-e4aa-11ea-817d-618abef1d8d8.png)

The command in question is `./pleasew build //...` in this repo: https://github.com/sagikazarmark/moddown

I tried to reproduce it locally as well as using the `plz` binary directly, both exited with zero exit code, despite the build failure.

On a related note: I experience similar behavior when running a target with a _data_ dependency that fails to build: Please attempts to run the target, despite the failed dependency.

I'm not sure if this is by design, I could reason about using `//...` would always result in a zero exit code being a catch-all filter, but even then, it would be nice to have a parameter to disable this behavior and return with a non-zero exit code.

**Comment by peterebden** [comment]
This isn't intentional; it's to do with the failed target being for a different architecture. Should be reasonably straightforward to fix.
