### ISSUE TITLE
Certain combinations of rules can affect incrementality

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#1150]
For example:
```
genrule(
    name = "rule1",
    outs = ["test.txt"],
    cmd = "echo 'blah' > $OUT",
)

genrule(
    name = "rule2",
    srcs = [":rule1"],
    outs = ["test2.txt"],
    cmd = "mv $SRC $OUT",
)
```
Both `test.txt` and `test2.txt` end up being the same file, and we overwrite the xattrs on it with whatever was built last. Hence `plz build //:rule2` continually outputs:
```
Need to rebuild //tools:rule1, rule has changed (was +034SJPA+Wwnyid/oGLGOzoP6Y4, need 0AYWuE4OrfEv/ib+4d4XLycTQ5w)
```
except that of course rule1 is not changing.
This seems like a tricky one. It's possible that we may be best not doing anything here.

**Comment by RichardoC** [comment]
Is it the correct behaviour that we allow rule2 to change the files created by rule1? I was expecting that this would be discouraged as it has caused more nonsense than I have expected
