### ISSUE TITLE
plz run in subdirectories

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1159]
`plz run` is currently incapable of running a target in a subdirectory of a project. The working directory will always be the root.

While there are cases where this is definitely an advantage, in other cases it's a limitation.

I'm not sure why please works this way, so it might be historical or a deliberate decision, but it would be nice to be able to run targets in subdirectories.

WDYT?

**Comment by peterebden** [comment]
It was a deliberate decision originally in that most stuff happens relative to the repo root. It'd be hard to change as a default policy now (we would have a heap of stuff  that would break as a result) but would be very happy to have a flag for it if that works for you?

**Comment by sagikazarmark** [comment]
A flag would be perfect.
