### ISSUE TITLE
Trim down the please distribution

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1167]
There are many things in the please distribution that aren't universal to every project. These should be defined in the build language as build rules and configured in .plzconfig when needed. plz init should help set this up. On this list is:

- lsp server
- javac worker and junit runner
- go filter and go test 
- pex
- sandbox

We might want some nice way to check these have been configured correctly in the rules that use them. Perhaps get_config can have some smarts and hint the user do something like `plz init java` if they try and use a java rule when java isn't configured.

**Comment by Tatskaari** [comment]
No!

**Comment by peterebden** [comment]
Bad bot!

**Comment by Tatskaari** [comment]
I think this is essentially done. At least the groundwork is there. We just need to migrate the language rules into their own repos.
