### ISSUE TITLE
go.mod is not created in plz-out

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1173]
In theory, the following rule should result in Please creating a `go.mod` file in `plz-out`:

```
genrule(
    name = "go.mod",
    cmd = "",
    labels = ["go"],
)
```

But it's not created.

**Comment by peterebden** [comment]
Looks like we only trigger it off filegroups, so this works:
```
filegroup(
    name = "go.mod",
    labels = ["go"],
)
```
The original intention was that it'd get picked up if you built a `go_library` or similar. Is there a need to have it work in other cases too?

**Comment by sagikazarmark** [comment]
There are cases where I don't use `go_library` (yet).

**Comment by peterebden** [comment]
OK, I don't think there is much reason I can't genericise this. It was just mimicking some (much) older Python stuff.
