### ISSUE TITLE
pleasew doesn't work in CI

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1174]
When running `plz build` or `./pleasew build` locally (on Mac), it builds all targets.

`./pleasew build` doesn't build anything on GitHub CI (linux). Need to add `./...` for it to work.

Not sure, if it's GitHub CI related or not. Sounds like a shell quirk to me.

**Comment by sagikazarmark** [comment]
It looks like this is intentional: https://github.com/thought-machine/please/blob/master/src/please.go#L828

Not sure if it makes sense to read from stdin, but it's a feature.

**Comment by Tatskaari** [comment]
We have `plz build -` to explicitly opt into this feature... I'm not convinced this was the intention here. cc: @peterebden ?

**Comment by peterebden** [comment]
I'm not sure why it differs when run from the wrapper script though?

The intention there was to try to do something a bit more intuitive. It's very easy to do something like `plz query <stuff> | plz build` and not realise it's ignoring the results of the query. Happy for someone to take another charge at it if we think it's not helping.

**Comment by Tatskaari** [comment]
@sagikazarmark I've not been able to reproduce this locally. I suppose this is something specific to the github CI's shell. Do you have any ideas? I think I'll close this again unless you have any ideas.

**Comment by sagikazarmark** [comment]
@Tatskaari I suppose you have tried it in a noninteractive shell, right?
