### ISSUE TITLE
Missing import config from ASM library

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1181]
When a Go library contains Assembly code, but also depends on other libraries, its dependencies are missing from the import config.

You can find an example reproducing this issue in https://github.com/sagikazarmark/please-issues/tree/master/go-asm-importconfig

The build fails with:

```
Error building target //:main: exit status 1
cannot find package golang.org/x/sys/internal/unsafeheader (using -importcfg)
/usr/local/go/pkg/tool/darwin_amd64/link: cannot open file : open : no such file or directory
```

Tried it with #1177 as well, it fails with the same error.

**Comment by sagikazarmark** [comment]
It looks like it's caused by the the go lib rule not exporting its dependencies.

**Comment by Tatskaari** [comment]
I'm running linux and moddown isn't an ELF so I can't test this but I think the latest version of #1177 should fix this for you.

**Comment by sagikazarmark** [comment]
Hm, the latest version should download the correct binary, but the readme said `darwin_amd64`, so that's why it didn't work for you (probably). I fixed the readme to use host os/arch.

**Comment by sagikazarmark** [comment]
Also, I'll give the updated go rules a try

**Comment by sagikazarmark** [comment]
Indeed, the updated version of #1177 fixed it! Thanks!
