### ISSUE TITLE
Passing environment variables to tests

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1185]
Some tests might have external dependencies (eg. integration tests talking to a database => needs a DSN for the database).

Is there a way to pass environment variables to tests?

**Comment by peterebden** [comment]
PassEnv (https://github.com/thought-machine/please/blob/9cd0a141ae5b84610203ab955b818ef8dd5ad59d/src/core/config.go#L366) is what you want - it is in the `build` config rather than `test` but should apply to both.

**Comment by sagikazarmark** [comment]
Wouldn't those affect the build cache as well? This is kind of a runtime information. I think it would be nice to have a way to pass env vars to the test process only, without affecting the build itself. WDYT?

**Comment by Tatskaari** [comment]
There's PassUnsafeEnv which does exactly that but we pretend like it doesn't exist because we're purists. ;)

**Comment by sagikazarmark** [comment]
Neat, thanks!

**Comment by sagikazarmark** [comment]
@Tatskaari actually, it does seem to trigger a rebuild 😕 

See https://github.com/sagikazarmark/viperx/pull/10

**Comment by sagikazarmark** [comment]
It looks like [getBuildEnv](https://github.com/thought-machine/please/blob/19e902ba4782c16873304f1a50bfd86720c891b3/src/core/config.go#L583) is used to calculate the build hash and it includes unsafe env vars. So this is actually a bug.

Can you please reopen it @Tatskaari?
