### ISSUE TITLE
go_test labeled with manual is still getting built

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1188]
I have a `go_test` target that fails to build, so I labeled it with `manual`, but its internal targets are still getting built, causing a failure. I guess because they don't receive the `manual` label.

I see two possible solutions:

1. Internal targets should also receive all labels.
2. If the list of labels contains `manual`, internal targets should be labeled with manual too.

Personally, I prefer the second option, but it's more work. I couldn't find a `contains` function for lists, so I guess that would be the first step.

Although I found this issue in `go_test`, I guess every other rule is also affected.

I'd be happy to take a stab at some PRs if we can agree on a solution.

**Comment by peterebden** [comment]
I think we should probably pass the labels to all of them. I don't think we should need to treat `manual` specially here.

**Comment by sagikazarmark** [comment]
Great, that simplifies things a lot!
