### ISSUE TITLE
Remove --nocache

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#1212]
I've spent more time trying to explain this flag than any other. Users expect it to behave like `plz build --rebuild` but it actually just disables caches (so it's actually equivalent to `-o cache.dir: -o cache.httpurl:`).

Since we now have equivalents like `--rerun`, let's save some trouble by removing it. Probably best to issue a warning with a suggestion about alternatives for a while.

**Comment by Tatskaari** [comment]
I have found this kinda useful when working on please in the caching space however that's not a good reason to keep it. I can just comment out the code path.

**Comment by peterebden** [comment]
Yeah, for cases like that I think using the `-o` flags is sufficient; it doesn't need to be a top-level flag given that's a fairly niche use case.

**Comment by janhancic** [comment]
👍 this is a good change!

**Comment by peterebden** [comment]
Bad bot!

**Comment by janhancic** [comment]
plz stop stale bot

**Comment by peterebden** [comment]
Surely we have done this by now...

**Comment by peterebden** [comment]
Yes, in #1612 , so stale-bot  was _sort of_ right...
