### ISSUE TITLE
Handling spaces in SRCS

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1215]
Spaces still cause issues when working with files in the `$SRCS` variable:

`SRCS=path to/file path to/other_file`

Shell will always handle the above as four separate paths instead of two.

There isn't an obvious solution I can think of, but the biggest problem in my opinion is not knowing the cause of the problem. For example, all you could see in such case is this error from `cp`:

```
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```

Previous issues related to spaces: #338 #849

**Comment by noxxious** [comment]
Isn't $SRCS built from exact filegroup/glob entries ? So it should be fairly easy to escape the spaces in each item, before joining them into $SRCS for invocation.

**Comment by Tatskaari** [comment]
@noxxious You forget bash was designed by pre-humans before we developed a working frontal cortex. 

There's no way (to my knowledge) to export a variable with a space separated list where the items themselves can have spaces. Bash unhelpfully strips out your escaped spaces and replaces with unescaped ones:
```bash
export TEST="space folder/main.go" && cat $TEST # fails to find space and folder/main.go
export TEST=\"space folder/main.go\" # this one throws a syntax error
export TEST="\"space folder/main.go\"" && cat $TEST # same as first
export TEST=space\ folder/main.go && cat $TEST # same as first
```

The best I can really do is throw an exception if any of the file paths have spaces in them...

**Comment by sagikazarmark** [comment]
Don't think this has been resolved

**Comment by sagikazarmark** [comment]
Bump
