### ISSUE TITLE
Create native file rule

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1218]
I've been working on a rule that generated a configuration file from inputs. I noticed that there is no native rule that creates files from text, so I needed to create it from bash.

I think it would make sense to have a `file` or `file_content` rule that just writes some content to a file.

**Comment by Tatskaari** [comment]
Would you want this to be a special rule in please such that please creates the file in it's internals? Ideally we'd reduce the amount of magic that please contains in its go code.

I think we could add a rule in misc that does something like this:

```python
def file(....):
  return build_rule(
    name = name,
    cmd = f'{{ cat > "$OUT" << EOF\n{content}\nEOF\n}}',
    ...
  )
```
Though I feel this has limited value. Was there a reason you don't like doing this in bash?

**Comment by sagikazarmark** [comment]
TBH, anything that's not just issuing commands on existing files feels weird to me. I'm also continuously being bitten by differences between linux and mac (though not particularly in this case).

A file rule doesn't sound like magic to me, it's a simple utility for generating files.

So ultimately my two reasons are:
- Go provides better interoperability between OSes
- A file rule is generic enough for implementing it in the core

**Comment by Tatskaari** [comment]
I've come across a few more good reasons to implement one of these: 

1) There's a limit to the number of arguments you can pass to bash so this can be a way to get around that. 
2) The `echo "" > file.txt` requires an extra level of escaping. 

It would be good to make sh_cmd() use this in v16 to reduce the number of escapes.
