### ISSUE TITLE
Update docs: please.lang doesn't work...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#1235]
Unless something is actually broken, I suspect the [docs](https://please.build/config.html) are wrong:

```
[please]
	lang = en_US.UTF-8
```

```
10:25:46.196 WARNING: Error in config file: warning:
can't store data at section "please", variable "Lang"
```

**Comment by Tatskaari** [comment]
Looks like the lang setting was under the incorrect section in the docs. Will fix that up. Sorry for the confusion.
