### ISSUE TITLE
pleasew ignores profile and arch specific configuration

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1253]
I guess it's an edge case, but the config parsing in the `pleasew` script ignores profile and arch and the config key matching is not perfect either.

For example, if I have a `version` or `location` under the buildconfig section, that would also count as version and location configuration.

**Comment by Tatskaari** [comment]
Ah yeah, thanks for raising! Seems like a lot of logic to reimplement in bash though and that scares me. We'd have to parse the incoming flags... Is this something that's causing problems? If not I think i might close as wont-fix. 

if it is, perhaps this little wrapper script should just download please into `plz-out` and ask please to install itself from there or something...

**Comment by sagikazarmark** [comment]
Yeah, I agree that `pleasew` shouldn't reimplement any weird parsing logic. I did it in [setup-please-action](https://github.com/sagikazarmark/setup-please-action) though, because TS is much better equipped for this kind of job.

In a local environment downloading two Please instances is probably not a huge deal, but in CI, I think it makes sense to spare the extra HTTP requests which is why I created that action.

**Comment by sagikazarmark** [comment]
It feels like a wontfix to me. On CI, custom integrations can resolve this issue. Locally it's not a big deal.

**Comment by swanysimon** [comment]
I'm just starting to play around with Please and this caused me some headache trying to figure out what was going on. I read through the docs and saw that things would be placed in `~/.please`, so to keep my home directory clean I created a `~/.config/please/plzconfig` file to point the download to my `XDG_DATA_HOME`:

```
✓ cat ~/.config/please/plzconfig 
[please]
location = ~/.local/share/please
```

I immediately hit a problem:

```shell
✓ ./pleasew build
Downloading Please 15.12.0 to /Users/simon/.please/15.12.0...
Should be good to go now, running plz...
Build stopped after 20ms. 1 target failed:
    //:pleasings
jarcat not found in path /Users/simon/.local/share/please:/usr/local/bin:/usr/bin:/bin
```

Not a great introduction to the tool. I've made a quick first pass I'll attach here, but it's not too hard to get the non-profile configurations loaded in the correct order and hopefully those more familiar with the tool can make more informed decisions on the correct way forward.

[pleasew_quickfix_patches.tar.gz](https://github.com/thought-machine/please/files/5863114/pleasew_quickfix_patches.tar.gz)

**Comment by sagikazarmark** [comment]
@swanysimon I don't think adding XDG support would be too hard, although changing the data dir would certainly be a breaking change.

I've opened a separate issue for tracking XDG support.

As a side note, you probably also need to change the `downloadlocation` config which would make `pleasew` work for you. (Without that, please will still be downloaded into `~/.please`)

**Comment by swanysimon** [comment]
Ah good catch. I didn't have a need to change it so didn't scroll further down the file once builds started working. Attaching the a tarball with an additional commit to find the `download location`.

[pleasew_quickfix_patches_v2.tar.gz](https://github.com/thought-machine/please/files/5863175/pleasew_quickfix_patches_v2.tar.gz)

I'd love XDG support out of the box! Happy to move my attention to the new issue.
