### ISSUE TITLE
versionchecksum missing from config documentation

### ISSUE THREAD

**Issue by RichardoC** [thought-machine/please#1274]
https://please.build/config.html has no documentation for versionchecksum, and how to set multiple hashes as valid.

**Comment by Tatskaari** [comment]
Ah good catch, I can update that but in the meantime you can just add multiple versionchecksum entries under [please]:

```
[please]
version = ...
versionchecksum = <mac-checksum>
versionchecksum  = <linux-checksum>
...
```

**Comment by peterebden** [comment]
Thanks both! 

As a general FYI some of this information is also available from `plz help versionchecksum`, which mentions properties that can be repeated.
