### ISSUE TITLE
please build/test fails when there are extra spaces in the command line

### ISSUE THREAD

**Issue by noxxious** [thought-machine/please#1275]
If there are extra spaces provided in the command line between the action and the target plz interprets it as an additional target of "//' and fails, i.e. 'plz build     ///...'.

**Comment by peterebden** [comment]
This is the equivalent of doing `plz build "" //src:please` I think? It is not an issue if put into a shell like `plz build     //src:please` since Bash breaks the spaces.

I'm not sure this is a bug if so.

**Comment by noxxious** [comment]
I have this failing with 'plz build "${PLZ_ARGS}" //...'  when PLZ_ARGS is empty.

**Comment by peterebden** [comment]
Right, so you're explicitly passing it an empty string, most tools would not ignore that, e.g. `ls ""` fails with `ls: cannot access '': No such file or directory`

Can you fix it by removing the quotes? `plz build $PLZ_ARGS //...` seems like it might do what you want?

**Comment by Tatskaari** [comment]
@noxxious hope this helps. I'm going to close this. Let me know if there's anything else. :)
