### ISSUE TITLE
Document generate commands

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1307]
Today I've spent 10 minutes looking for the right command to regenerate rules. I even started in the rules directory, but the README doesn't say anything about code generation. Eventually, I checked the `BUILD` file and found the right command.

I also found that `plz autofix` doesn't work.

**Comment by Tatskaari** [comment]
ah, looks like we removed the buildify alias. I'll fix `plz autofix` and add something about that to the readme. 

I did make the test suggest a fix for you:
```
    echo "rules/rules.go is out of date, plz run //rules:generate"
``` 

Though I guess this might not come out when running an aggregated test run. You'd need to re-run just that test to see it's output.

**Comment by sagikazarmark** [comment]
I think circle highlights the problem properly.
