### ISSUE TITLE
VSCode integration with source jars

### ISSUE THREAD

**Issue by Anton-Rodionov** [thought-machine/please#1308]
"please" stores source jars as *_src.jar while the maven default is *-sources.jar. That's totally fine, but IDEs like VSCode try to attach sources by searching for *-sources.jar, so don't work seamlessly with "please".

https://code.visualstudio.com/docs/java/java-project (refer to the "Attach source jars" paragraph)

We should allow to customize the filename.

https://github.com/thought-machine/please/blob/afcfd42eabfd40158a983042c96f32ce963368f6/rules/java_rules.build_defs#L435

**Comment by Tatskaari** [comment]
Great idea! Sadly this breaks hashes and I think that's probably going to cause some frustration so I'm going to push this to v16.

**Comment by Tatskaari** [comment]
If you want to check this out earlier, you'll be able to do

```
[featureflags]
MavenJar = true

**Comment by Anton-Rodionov** [comment]
Cool, thanks @Tatskaari, that's a nice feature!
