### ISSUE TITLE
Add semver helper functions

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1312]
I recently had to download a binary that changed the URL pattern after a specific version. I was able to handle it by using multiple download URLs in `remote_file`, but I was wondering if it would make sense to implement native semver helper functions to do that more efficiently.

For example a `version_compare(constraint, version)` would have been useful in my case.

I'd be happy to work on a PR, but wanted to ask your opinion first.

https://github.com/Masterminds/semver seems like a good semver library.

**Comment by Tatskaari** [comment]
I'm not overly enthusiastic but it seems relevant enough to what please does so I'd be happy to accept a PR. Doing this sort of thing in pure asp sound like a really bad idea. I think we already use `github.com/coreos/go-semver/semver` in please already so I'd use that or migrate us to Masterminds if you think it's better.

**Comment by sagikazarmark** [comment]
> Doing this sort of thing in pure asp sound like a really bad idea.

What do you think would be a better solution?

> I'd use that or migrate us to Masterminds if you think it's better.

The Masterminds one might be more actively maintained if that matters.

**Comment by Tatskaari** [comment]
> What do you think would be a better solution?

Sorry, I meant as you suggested: make them built in functions. 

> The Masterminds one might be more actively maintained if that matters.

Yeah, happy for you to switch. Should be fairly easy to swap them out.

**Comment by sagikazarmark** [comment]
Nope, still valid, just didn't find the time to send PRs.

**Comment by sagikazarmark** [comment]
A little bit more details why Mastermind is better (for documentation; from https://replit.com/@sagikazarmark/coreos-semver-test):

```go
package main

import (
	"fmt"

	"github.com/coreos/go-semver/semver"
)

func main() {
	// Cannot parse string starting with "v"
	// v := semver.New("v1.0.4")

	v := semver.New("1.0.4")
	v2 := semver.New("2.0.0")

	// Only direct comparison, no features like tilde or carret
	// Syntax is weird
	fmt.Println((*v).Compare(*v2))

	// Misc: 
	//   - has external dependencies
	//   - doesn't support go modules
}
```

I'll send a PR for adding `semver_compare` as a builtin function and a separate PR for replacing the existing semver package.
