### ISSUE TITLE
$SRCS vs. $PKG_DIR and "workspace" directories

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1313]
It's not immediately obvious which convention should users follow when creating build rules:

- use `$SRCS` for determining source files/directories
- use `$PKG_DIR` to find the current package and user files from there

Builtin rules in Please are not consistent:

- most of them use `$SRCS`
- some of them (eg. `cgo_library`) use `$PKG_DIR` (and `*.go`)

Personally, I think the source file approach is better, because it makes build rules more "portable".

For example in my [please-go-modules](https://github.com/sagikazarmark/please-go-modules/) experiment I generate build targets for Go packages (including cgo). The files in those cases would naturally be outside of the package library. I use a [hack](https://github.com/sagikazarmark/please-go-modules/blob/8c0a1f526b6ed2f5864aacc363a2065c5a0adfcd/build_defs/go_module.build_defs#L82-L130) (`output_dir`) to trick Please into copying files into the package dir (but it has a number of limitations, like not being able to have multiple rules of the same kind in the same package).

Sadly, build tools often require files to be inside the working directory implicitly (for example header files in case of `cgo_library`).

I think there is room for improvement here. For example, we could add a rule for preparing a "workspace" directory with all (or selected) sources inside. There are a bunch of edge cases to cover (ie. if a "source file" is a directory, should we copy the directory or the files inside, etc), so I think it would make sense to implement it as a native rule. Haven't thought it through completely though.

In the specific example, the cgo build could prepare said workspace, enter the directory and run the build there. It would work universally for code coming from a different directory as well as a regular package.

The alternative is a better version of the above mentioned hack (exporting files as if they were part of the package).

**Comment by peterebden** [comment]
Generally `$SRCS` is better but in some cases `$PKG_DIR` might be needed (if you need to operate on a directory for some reason). `go_test` uses `$PKG_DIR/*.go` in order to unify its immediate sources with the sources of the library under test (since they all need to be compiled together). It's possible the rule you mention might help with that?

**Comment by sagikazarmark** [comment]
> It's possible the rule you mention might help with that?

The idea is that there is a "workspace" dir (different from, but not completely orthogonal to the package dir) where the sources are copied to. Unlike the package dir (which contains files from the actual package) the workspace dir could "merge" (ie. copy) sources from several directories (listed in `$SRCS` for example).

The advantage of this concept is that you can still use a directory based approach (`$WORKSPACE/*.go`), but files from different sources are brought together to form the "package".

As for `go_test`: I like Bazel's concept of "embedding": https://github.com/thought-machine/please/issues/1184#issuecomment-704569137

**Comment by sagikazarmark** [comment]
Bump

**Comment by Tatskaari** [comment]
I think you can achieve something like this by making a filegroup for your sources:

```
def some_rule(name:str, srcs:list, ...):

    src = filegroup(
        srcs = srcs,
        ...
    )
    return build_rule(name = name, srcs = [src], ...)
```

Filegroups re-export their sources in their package, which in this case will be the current package. This means you can access them via `$PKG_DIR/*.go` or similar. Does that help? I'm not so keen on introducing a workspace dir as I think it would be too similar to package dir conceptually.

**Comment by Tatskaari** [comment]
To clarify, the `srcs` variable passed to the filegroup would be all the rules that produce the `.go` files you would've added to your workspace. I don't think we need a new abstraction for this. 


In the case of `cgo_library()`, we might be able to just split out the headers and go srcs into named sources:
```
build_rule(
    srcs = {"go": srcs, "hdrs": hdrs},
)
```

Then we can `go tool cgo $SRCS_GO` avoiding the glob. 

Going to close this one. Let me know if I'm missing anything.
