### ISSUE TITLE
Platform specfic targets

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1323]
Certain targets are only required (and can only built on) for certain platforms. For example: certain dependencies might only be required by linux.

My current approach is an if, combined with a custom `select_config` rule:

```
if select_config([{
    "os": "linux",
    "cpu": "amd64",
}]):
    go_library(name = "logrus", srcs = [":_logrus#go_source"], cover = False, import_path = "github.com/sirupsen/logrus", visibility = ["PUBLIC"], deps = select({"//example/third_party/go/__config:darwin_amd64": [], "//example/third_party/go/__config:linux_amd64": ["//example/third_party/go/golang.org/x/sys/unix"], "default": []}))
```

The problem is: it's more generated code, and the buildifier package formats the target itself on a single line.

Is there a better way to represent platform specific targets? (It's not the end of the world, but it's hard to read and more changes in a VCS)

**Comment by sagikazarmark** [comment]
Maybe something like this could work:

```
genrule(
    name = "platformtest",
    cmd = "echo 'asd'",
    labels = ["os:linux"],
)
```

Alternatively, I guess the `manual` label can be used to prevent it from being built automatically.

**Comment by peterebden** [comment]
You could also write it like
```
if CONFIG.OS == "linux":
    go_library(
        ....
    )
```

**Comment by sagikazarmark** [comment]
That's probably not enough as I also use the cpu/arch as a discriminator.

**Comment by peterebden** [comment]
```
if CONFIG.OS == "linux" and CONFIG.ARCH == "amd64":
```
?

**Comment by sagikazarmark** [comment]
And then the possibility of having several of these conditions (like build on all platforms, but linux_386). 😄 

I should probably add that this is generated code. The `select_config` rule I created actually works well, but the formatter formats the code like in the above example and overall, it's not really readable. Using labels would be a nice solution IMHO.

But if there isn't a better or already existing solution, I guess `select_config` is fine.

**Comment by Tatskaari** [comment]
We could have a `platform()` rule that can be used to match a specific platform:

```
def platform(os : str =  CONFIG.OS, arch: str = CONFIG.ARCH, ...) -> bool: 
    return os == CONFIG.OS && arch == CONFIG.ARCH ....

if platform(os = "linux"):
   genrule(...)
```

Otherwise, we could label rules:

```
labels = ['os:linux', 'arch:amd64']
```

Then please could exclude them. Perhaps both are useful?

**Comment by sagikazarmark** [comment]
> Then please could exclude them. I'm not sure how we'd do `everything except linux_386` though. Perhaps both are useful?

I think it's ok to require being explicit, so if someone wants to limit a rule to certain platforms, all platforms should be listed.

My use case comes from generating rules for Go package dependencies. I have a list of platforms for each package.

Either `is_platform` or labels could work. `is_platform` is something I do with the aforementioned `select_config` rule (which is quite similar to `config_setting` under the hood).

Labels would result in nicer (to read) rules though. Ifs in BUILD files makes targets harder to read IMHO.

Something like this should work IMHO:

```
labels = ['os:linux', 'os:darwin', 'arch:amd64']
```

which should result in the target being built on `linux_amd64` and `darwin_amd64`. I could also imagine a `platform:linux_amd64` label.

If no such labels are attached to a rule, it should be built on all platforms.

If we want to support exclusions we could do:

```
labels = ['arch:!amd64']
```

Maybe something mimicking Go's build tags would make sense?

These are just some random ideas, I haven't actually thought them through.

**Comment by Tatskaari** [comment]
I don't mind the labels approach but it's significantly more work. The `is_platform()` function is trivial and could be very useful orthogonality to that though so I've gone ahead and implemented that.

**Comment by sagikazarmark** [comment]
How is it going to work with rules used as tools? 😄 

I don't mind a simple solution, but I think it'd be nice to document its limitations. `is_platform` won't affect the build graph I guess since its evaluated runtime (whereas labels could).

**Comment by Tatskaari** [comment]
What do you mean? If you wrap a build rule with an if statement, it won't be included in the build graph when it's false. The only way to dynamically affect the build graph is with pre-build and post-build functions. 

For tools, `CONFIG.OS` will always be set to `CONFIG.HOSTOS` so I think this should work as you'd expect in most situations.

**Comment by sagikazarmark** [comment]
I guess this can be closed, since `is_platform` is implemented.
