### ISSUE TITLE
Overwritten output file in root BUILD 

### ISSUE THREAD

**Issue by JavierZunzunegui** [thought-machine/please#1353]
I have found the output file of targets in the root directory gets overwritten by the output of files in other directories, if the file names clash and the child depends on the root target.

A reproducible example:

BUILD:
```
build_rule(
  name = 'foo',
  srcs = None,
  deps = [],
  cmd = "echo 'foo file' > ${OUT}",
  outs = ["out.txt"],
  entry_points = None,
  binary = False,
  visibility = ["PUBLIC"],
)
```

bar/BUILD:
```
build_rule(
  name = 'bar',
  srcs = None,
  deps = ["//:foo"], # note this dependency
  cmd = "echo 'bar file' > ${OUT}",
  outs = ["out.txt"],        # same output file
  entry_points = None,
  binary = False,
  visibility = ["PUBLIC"],
)
```

Then:

`please build :foo`      => plz-out/gen/out.txt       = "foo file"
`please build bar:bar` => plz-out/gen/bar/out.txt = "bar.file" **and plz-out/gen/out.txt = "foo file"**

I have not seen the same issue if the BUILD is not in root, or if the child does not depend on the root target.

**Comment by Tatskaari** [comment]
You're modifying `out.txt` from `:foo` in place in `//bar`. All sources are linked into the build directory - for performance reasons they aren't copied so you shouldn't do that. I'm wondering if we should revisit this though. I might try and determine the performance impact of copying them in place because this confusion seems to crop

**Comment by JavierZunzunegui** [comment]
(more for my understanding than anything else)
I would have imagined that `//:foo` is evaluated before `//bar:bar` such that the `out.txt` gets copied to `plz-out/gen/out.txt`, then `//bar:bar` is evaluated resulting (apparently) in overwriting `out.txt` and copying it to `plz-out/gen/bar/out.txt`, but in this scenario `plz-out/gen/out.txt` would be as expected since it is already copied, which it isn't. What is wrong in understanding of how please works here?

**Comment by Tatskaari** [comment]
Both out.txt and bar/out.txt end up being symlinks to the same file:

1. //:foo creates `plz-out/gen/out.txt` with "foo file" inside it
2. //bar:bar then symlinks out.txt into it's build directory 
3. //bar:bar then overrides out.txt with "bar file" (which also modifies plz-out/gen/out.txt)
4. //bar:bar then symlinks it's output to bar/out.txt

**Comment by Tatskaari** [comment]
Turns out that building a non-trivial portion of our codebase is over twice as slow if we copy the file instead of linking them. I think it would be a hard sell.

**Comment by JavierZunzunegui** [comment]
And is it something that could be checked on the rules themselves so that it is not allowed, in a similar way to how one can't declare an output to a directory that already exists?
