### ISSUE TITLE
Allow single items for TOOLS

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1364]
It's almost never useful to provide a list of tools to the tools argument. We should make tools accept strings:

```
tools = CONFIG.MY_TOOL,
```
and 
```
tools = {
   "MY_TOOL": CONFIG.MY_TOOL,
},
```

**Comment by Tatskaari** [comment]
@PeterBocan This is a fairly easy one to pick up if you were looking for a different ticket :)

**Comment by PeterBocan** [comment]
sign me up, @Tatskaari
