### ISSUE TITLE
Create DATA env var for sh_binary rule

### ISSUE THREAD

**Issue by jakechorleytm** [thought-machine/please#1372]
Currently you can pass data to the `sh_binary` rule but you have to access it manually in the script. It should be available as `$DATA`. 

As a bonus would be great to accept a dictionary so that separate pieces of data can easily be referenced.

**Comment by Tatskaari** [comment]
The env vars that are available to sh_binary when it runs are the host machines. It's just running the .sh file. I suppose we could replace $DATA with the value it had at build time. 

I think what you might want is $(out_location //path/to:rule).

**Comment by peterebden** [comment]
There is `plz run --env` which populates some env vars, maybe it should populate the DATA ones too.

**Comment by Tatskaari** [comment]
> There is `plz run --env` which populates some env vars, maybe it should populate the DATA ones too.

Potentially but ideally the .sh file should be portable i.e. I should be able to `plz export` the rule and execute the .sh command without please.

**Comment by Tatskaari** [comment]
I've just noticed that variable expansion doesn't seem to work on sh_binary()... 

I'll see if I can get something sensible to work here.

**Comment by Tatskaari** [comment]
I've done as Peter suggested and made $DATA available when doing `plz run --env`. I've also added $TOOLS which I think makes some sense. 

 I thought about allowing the build env access to $DATA which would allow the sh_binary() rule to embed this in the preamble of the .sh file it generates but I think that needs some thought... the data files won't actually be available inside the build directory.

**Comment by jakechorleytm** [comment]
Awesome. Thanks @Tatskaari
