### ISSUE TITLE
Secrets in Please

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1389]
Typically build systems allow the build to access the host machines environment variables and user config however in Please this is tightly controlled. Please currently has a couple mechanisms to expose secrets to build actions however they're not ideal:

1) `genrule()` and `gentest()` have a secrets argument which can be used to tell a rule about some secret file on disk: `secrets = ['~/.some_config/secret.json']` 
2) Environment variables can be set in `[BuildEnv]` in `.plzconfig`. These must start with `SECRET_` which is limiting. 

Ideally, secrets shouldn't contribute to the rule's hash, and as of #1387 neither of these methods do.

There are a few problems with this approach:
1) Some tools require secrets to be stored in environment variables with a specific name e.g. `AWS_SECRET_ACCESS_KEY`
2) Adding items to `BuildEnv` makes them available to ALL rules... ideally only rules that specify they need them set, should have them set. 
3) There's no way to use these secrets with `plz run`.

## Proposal
The current `secrets = []` works well for files. To handle env based secrets, Please can allow any secret env variables to be defined in a `[SecretEnv]` section of the config. These variables can then follow any format. Unlike `[BuildEnv]` these variables will only be set if the rules specify they require them: 

### .plzconfig.local
```
[SecretEnv]
AWS_SECRET_ACCESS_KEY = ...
AWS_ACCESS_KEY_ID = ...
```
### //build/s3/BUILD
```
genrule(
    name = "s3_sync",
    cmd = "aws s3 sync $SRCS s3://my_bucket > $OUT",
    srcs = ...,
    out = ["s3_sync.log"],
    secret_env = [
        "AWS_SECRET_ACCESS_KEY", 
        "AWS_ACCESS_KEY_ID",
    ],
)
```

We can then make any secrets a rule says it requires available to `plz run --env`. This could be especially useful to make deploying services to k8s or pushing images to docker registries painless. 

## Possible improvements
Requiring developers etc. to save their secrets to disk within the Please repo is risky. There's a chance they might accidentally commit this stuff in or maybe saving secrets to disk just doesn't sit well with the organisation.  

More and more, secrets are often stored in a secrets provider i.e hashicorp vault. As a stretch goal, perhaps we could support running an arbitrary build action to fetch secrets:

### .plzconfig
```
[SecretProvider "//tools/secret_providers:vault"]
secrets = "AWS_SECRET_ACCESS_KEY", "AWS_ACCESS_KEY_ID"
```
or perhaps:
```
[SecretEnv]
AWS_SECRET_ACCESS_KEY = //tools/secret_providers:vault
AWS_ACCESS_KEY_ID = //tools/secret_providers:vault
```

### //build/s3/BUILD
```
genrule(
    name = "s3_sync",
    cmd = "aws s3 sync $SRCS s3://my_bucket > $OUT",
    srcs = ...,
    out = ["s3_sync.log"],
    secret_env = [
        "AWS_SECRET_ACCESS_KEY", 
        "AWS_ACCESS_KEY_ID",
    ],
)
```
In this case, `//tools/secret_providers:vault` must be a binary rule. We can define a standard CLI interface e.g. `plz run //tools/secret_providers:vault -- AWS_SECRET_ACCESS_KEY` should print that secret to stdout. Logging secrets to stdoput seems scary. Please must be careful to not leak this secret to disk or the terminal. 

We'd need to consider if this would be too intrusive to the build step. We don't want the CI build stopping because it's interactively waiting for LDAP creds on the command line.

**Comment by Tatskaari** [comment]
We currently have `env =[]` on `build_rule()`. I imagine `secret_env = []` would be fairly easy to implement and would help with this quite a lot.

**Comment by tisc0** [comment]
Hi,
6 months passed without any serious answer from the team, nor basic documentation of how it's basically supposed to work: does NOT "feel amazing to use" to me :/
