### ISSUE TITLE
Integrate Javascript build rules

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#14]
We have internal rules for building JS. Is not so obvious how best to separate them from our private repo but would be super nice to have them included.

**Comment by abijr** [comment]
Is this getting progress? or is there an implementation plan for this? 

I'd like to have this this feature and I might be interested in contributing to this depending on the complexity, if the plan to port the internal went kaput.

**Comment by peterebden** [comment]
Not so much progress as we might like unfortunately (cough cough @csdigi :-P).

We've written up a basic set of rules here:
https://github.com/thought-machine/pleasings/tree/master/js
which have support for third-party libraries using Yarn and basic js compiling. I'm pretty happy with the Yarn stuff but the rest of it is very basic still.

The main issue we see right now is how best to get incrementality. The only way seems to be to invoke webpack (or similar) in one step at the end, which leads to a complete recompile on any change which ultimately isn't that satisfying an experience. What would be ideal would be compiling each `js_library` into an individual output that can be relatively efficiently combined later - I don't know of any tooling to really work that way though.

I'm not that familiar with JS tooling though so I might well be missing things here.

**Comment by abijr** [comment]
Thanks for the rules!

As for incrementality, I've looked a bit into it. I cannot think of anything that would make it generic and not particular to a JS tool such as webpack.

**Comment by peterebden** [comment]
I don't mind requiring a specific tool (be it webpack or something else), we'll eventually have to require something I'm sure. Would be happy just to have something working reasonably using any framework right now :)

**Comment by nekinie** [comment]
what about something like rollup?

**Comment by peterebden** [comment]
I'm not that familiar with rollup (we use webpack internally). I'm not sure if it solves the incrementality issue I mentioned earlier or not? Very interesting if so...

**Comment by peterebden** [comment]
Closing this until we have a real plan here - I wonder about adapting something like https://github.com/bazelbuild/rules_typescript.
