### ISSUE TITLE
Document releases

### ISSUE THREAD

**Issue by msiebuhr** [thought-machine/please#1406]
I've been poking around with using please for a small-ish Go project, and ended up finding the release docs a quite useful source of information (ex. https://please.build/milestones/15.9.0.html). Yet I only found it through a lucky break with [Hacker News](https://news.ycombinator.com/item?id=25209465).

It would be obvious to provide a link from, say <https://github.com/thought-machine/please/releases/tag/v15.9.0> (which also has _quite_ different release notes), but a "news" or "releases" section on <https://please.build/> would also be nice.

**Comment by Tatskaari** [comment]
Hahah that post was such a flop :broken_heart: 

Yeah actually that would be great! I'm thinking I also want a home for generic "blogs" where I doing feature write-ups. For example I'm currently working on redoing how we build Go code to better support modules. Jetbrains have a generic blog feed where they post their newslettersas well as this sort of writeup:

https://blog.jetbrains.com

I think I'm going to aim to do the same.
