### ISSUE TITLE
__init__.py files not being added to all ancestor directories

### ISSUE THREAD

**Issue by csdigi** [thought-machine/please#142]
This is now causing a bit of an issue with people's local test / debug flow, as well as tools such as linter. Seems to have been broken in the move from parse time to build time creation.

**Comment by peterebden** [comment]
This should be fixed on master (in ea692b0bc22d5596d1b0a85ad3074fe8be74f17f), will keep this open until I'm happy to release 5.3.0.

**Comment by peterebden** [comment]
Fixed in 5.3.0.
