### ISSUE TITLE
plz fmt does not support assert, raise, or string lit concat

### ISSUE THREAD

**Issue by robxu9** [thought-machine/please#1434]
`plz fmt` fails whenever it sees an `assert` or `raises` keyword, or python string literal concatenation

A reproducable file for `assert` and `raises`:

```py

def test_assert(x):
  assert x == 42

def test_raise():
  raise Exception("NO")

```

And the `plz fmt` command fails on the `remote/remote.build_defs` file in the `pleasings` repo (I've copied it manually over to my setup because every time I did just `plz build` it tried to build the entire repo alongside it).

I'm guessing this is because Please uses Bazel's buildifier, and Skylark doesn't have support for those features.

**Comment by Tatskaari** [comment]
Yeah you're right. We've forked their thing so have the capacity to fix this but just haven't had time yet :(

If you're keen, the fork is here: https://github.com/peterebden/buildtools

**Comment by peterebden** [comment]
Would love to fix this. Unfortunately their grammar is written in yacc and I'm pretty unsure how best to extend it (I added fstrings which was pretty easy, but this needs significantly more).

FWIW I think we should actually ditch `raises` from our syntax - I might log a separate issue for that.

**Comment by robxu9** [comment]
I think ditching `raise` isn't a bad idea; you can probably just replace it with another builtin function (i.e. [fail](https://docs.bazel.build/versions/master/skylark/lib/globals.html#fail)).

**Comment by peterebden** [comment]
Yup, I've raised #1634 which is the first step of that.

I'm not super keen on losing `assert` (but that might actually be doable with a bit of yacc-ing maybe). Don't really love implicit string concatenation though, would be happy to see that go (but I put it in originally because the migration looked highly tedious otherwise - maybe we should just bite that bullet tho).
