### ISSUE TITLE
Invalid pip option "--system" when using Pip/Python installed via Pyenv on Ubuntu/Debian

### ISSUE THREAD

**Issue by xinkecf35** [thought-machine/please#1450]
**Description**
While using `pip_library` build rules with the Python interpreter set to one installed by Pyenv, the build fails with the following error: "no such option: --system". As far as I can tell, this is due to the addition of the flag to counter the fact that Debian distributions of `python-pip` have it such that `--user` is enabled by default.

Issue was produced on a Ubuntu 20.04.1 LTS, Pyenv version 1.2.21 with Python version 3.9.1. Also reproducible in Debian 10.7 with Pyenv version 1.2.18 with Python version 3.8.3. Note that issue does not occur when using Pyenv on macOS version 10.15.6. Please version 15.11.0 was tested, but the issue effects versions 15.8 and up. 

**Reproduction steps**
- Install latest pyenv with [pyenv-installer](https://github.com/pyenv/pyenv-installer)
- Follow setup instructions for Pyenv to be initialized in user's shell and home directory
- Set `Path` under `build` section of `.plzconfig` to point at pyenv shims and versions, e.g. `/home/<user>/.pyenv/shims`, 
 `/home/<user/.pyenv/bin`
- Add any pip package and build said package

Sample build log is as follows [here](https://gist.github.com/xinkecf35/e72cbf9d4090f42bc3cd1d17501209a7)

**Possible resolution**
Easiest thing might be an explicit check to see if Pyenv is being used and therefore not use `--system` as part of the pip command, but that feels brittle and suboptimal.

**Comment by peterebden** [comment]
Ugh. The `--system` thing is already a hack to counteract breakage Debian introduced earlier; we are essentially detecting that it's a Debian system and hence we think we need to add that flag.

I guess options here include either (1) just remove the flag in some future version and stop supporting 16.04 / 18.04 or (2) have some explicit config property to add it. I think (2) is probably nicer, although obviously undesirable for us to have to work around the foibles of pip.

**Comment by xinkecf35** [comment]
For what’s it worth, I feel option two is probably the most practical option at this given moment. Option one would be nice, but I don’t know how people will feel about the lack of support for at least for 18.04 given it’s EOL is sometime in 2023

**Comment by xinkecf35** [comment]
@peterebden To follow up on this, if a config property were to be added (assuming that's the desire approach), what would be config property do and look like it? It would be a simple boolean flag to turn off some of `SYS_FLAG` guessing? Or would it be more of a string property where one could specific additional flags?

I am assuming the latter option is probably not desired given that passing flags to `pip_library` is already a thing, but I am curious as to your thoughts.

**Comment by Tatskaari** [comment]
I tried removing this flag last month but it's broken on the current ubuntu version we use here at Thought Machine so I figured it wasn't time to remove it yet. I think the config option is probably the way to go for now. I foresee lots of angry users who're still on older ubuntu/debian versions not being too happy they need to update their OS to use the next version of Please. 

> For what it’s worth, I feel option two is probably the most practical option at this given moment. Option one would be nice, but I don’t know how people will feel about the lack of support for at least for 18.04 given it’s EOL is sometime in 2023

I guess we can remove it properly once 18.04 passes it's EOL.

**Comment by peterebden** [comment]
Sorry, been off over the holidays... and yes agreed, I think the config option is probably needed. I guess there's a question about whether we should do the OS detection bit at all or just set it by default on Linux and let people switch it off if needed?

**Comment by raroldan** [comment]
Sadly this also breaks on Linux Mint 19.3.

**Comment by Tatskaari** [comment]
The disable vendor flag should enable you guys to work around this. 

If you have different users on different OSs you can set this per system in /etc. See https://please.build/config.html for more info.
