### ISSUE TITLE
Arbitrary go_library name in go_binary deps:  can't find import

### ISSUE THREAD

**Issue by ekhabarov** [thought-machine/please#1457]
# Issue description

Repo for reproducing the issue: https://github.com/ekhabarov/plz-target-name-in-deps

### app/prober/BUILD

```python
go_library(
    name = "prober",
    srcs = ["prober.go"],
    visibility = ["//app/..."],
    import_path = "github.com/ekhabarov/plz-target-name-in-deps/app/prober",
)

```
### app/BUILD
```python
go_binary(
    name = "bin",
    srcs = [ "main.go" ],
    deps = [ "//app/prober:prober" ],
)
```

### Result
```shell
% plz clean
Cleaning in background; you may continue to do pleasing things in this repo in the meantime.

% plz build //app/prober:prober
Build finished; total time 10.47s, incrementality 0.0%. Outputs:
//app/prober:prober:
  plz-out/gen/app/prober/prober.a

% plz build //app:bin
Build finished; total time 550ms, incrementality 57.1%. Outputs:
//app:bin:
  plz-out/bin/app/bin

% file plz-out/bin/app/bin
plz-out/bin/app/bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
```

### Diff
```diff
diff --git a/app/BUILD b/app/BUILD
index 20a209b..ef3d916 100644
--- a/app/BUILD
+++ b/app/BUILD
@@ -1,6 +1,6 @@
 go_binary(
     name = "bin",
     srcs = [ "main.go" ],
-    deps = [ "//app/prober:prober" ],
+    deps = [ "//app/prober:lib" ],
 )

diff --git a/app/prober/BUILD b/app/prober/BUILD
index 770e102..d7e86f4 100644
--- a/app/prober/BUILD
+++ b/app/prober/BUILD
@@ -1,5 +1,5 @@
 go_library(
-    name = "prober",
+    name = "lib",
     srcs = ["prober.go"],
     visibility = ["//app/..."],
     import_path = "github.com/ekhabarov/plz-target-name-in-deps/app/prober"
```

### Result
```shell
% plz clean
Cleaning in background; you may continue to do pleasing things in this repo in the meantime.

% plz build //app/prober:lib
Build finished; total time 10.37s, incrementality 0.0%. Outputs:
//app/prober:lib:
  plz-out/gen/app/prober/lib.a

% plz build //app:bin
Build stopped after 200ms. 1 target failed:
    //app:_bin#lib
Error building target //app:_bin#lib: exit status 1
app/main.go, line 8, column 2: can't find import: "github.com/ekhabarov/plz-target-name-in-deps/app/prober"
```

### Expected result
```shell
% plz build //app:bin
Build finished; total time 550ms, incrementality 57.1%. Outputs:
//app:bin:
  plz-out/bin/app/bin
```

**Comment by Tatskaari** [comment]
This isn't really recommended. You shouldn't have two go_library rules in the same BUILD file. With that being said let me explain what's going on. 

Please doesn't parse the go files so it can't use the package as it is defined in the source code. There are just too many edge cases for this to be reasonable. Instead Please tries to infer the package based on the parameters you provide it. It does this in such a way that the output of the rule is always `{go_import_path}/path/to/package/name.a`. If name matches the parent folder this all works as you'd expect. In your case you'd have to import it as `github.com/ekhabarov/plz-target-name-in-deps/app/prober/lib`.

You can override the output of your rule like so:

```
go_library(
    name = "lib",
    out = "prober.a",
    srcs = ["prober.go"],
    visibility = ["//app/..."],
)
```

Which will allow you to import as `github.com/ekhabarov/plz-target-name-in-deps/app/prober`

**Comment by ekhabarov** [comment]
@Tatskaari thanks for the detailed explanation. 

In my case I have only one `go_library` inside `app/prober` package and one `go_binary` inside `app` package which uses `go_library` from first package. I think target name should not be strictly linked to Go package name, at least it's not obvious even from the docs. 

#1478 has an one of possible solution, but it also adds one more parameter. Is it possible to use package name from source files instead?
