### ISSUE TITLE
Android and iOS support?

### ISSUE THREAD

**Issue by mrbluecoat** [thought-machine/please#1461]
Sorry if this has been answered elsewhere, but does Please support (or plan to support) Android and/iOS builds natively or does someone have shell rules for Gradle and Xcode?

P.S. cool tool!

**Comment by Tatskaari** [comment]
I'm afraid I'm spread a bit too thin to provide first party support for android and iOS. We had some rules in the pleasings repo (a set of auxiliary 1.5th (?) party rules) a while back:

https://github.com/thought-machine/pleasings/commit/b538d20a9079e141d34c847dd27b0a0ef49cb785

If you want to ressurect them, feel free. Hopefully that gives you somewhere to start.
