### ISSUE TITLE
Additional `plz run parallel ...` output options

### ISSUE THREAD

**Issue by VJftw** [thought-machine/please#1493]
Hello!

I'm a big fan and user of `plz run parallel ...` for running multiple binary targets at the same time. However, the output of the targets is always interleaved. making it very difficult to follow the output of distinct targets.

Is there any appetite for adding additional output options? e.g. Taking inspiration from [GNU Parallel](https://www.gnu.org/software/parallel/parallel_tutorial.html#Controlling-the-output), we could offer the following:
 - Capture output for each target and print it all out by target after they all complete `--output=group`
 - Capture output for each target and print a target's output when that target completes `--output=group_immediate`
 - If any targets error, only print output for those targets `--output=errors_only`
 - Prefix interleaving output with target name similar to how docker-compose up shows container output `--output=prefixed_target`

---
In terms of implementation, I think we'll achieve most of this by writing the stdout/stderr into files in `plz-out/tmp` and then regurgitating those files when the conditions above are met depending on the `output` flag.

I'm happy to self-assign this and work on it when I get time, just want to verify if this is something that we'd like :)

**Comment by Tatskaari** [comment]
There's `plz-out/log` for logs of various kinds. We could make each target write their logs to a unique file there. We could also prefix the log messages with:

```
[//some:taget] WARNING: oops
```
We have a custom log backend already so hooking into this shouldn't be that hard.

**Comment by peterebden** [comment]
FYI there's `plz run parallel --quiet` which is pretty much the same as `--output=errors_only`. Seems reasonable that we might want other options too though!

**Comment by VJftw** [comment]
I think this was done in #1768, thanks!
