### ISSUE TITLE
Error when building on macOS - go not found in path 

### ISSUE THREAD

**Issue by mauriceyap** [thought-machine/please#1502]
When running `./bootstrap.sh` from the Please source code repo root, I get this error message:
```
Build stopped after 60ms. 1 target failed:
    //third_party/go:_logging#get
go not found in path /private/var/folders/fv/97gpjrvn5lzc1hj73rzg5plc0000gn/T/go-build624847951/b001/exe:/usr/local/bin:/usr/bin:/bin
exit status 2
```

## My system
It's a new machine so no weird stuff going on.
- OS: macOS Catalina 10.15.7
- Machine: 2020 13-inch MacBook Pro (A2251)
- Go: Installed Go 1.15.7 as per [the official guide](https://golang.org/doc/install) immediately prior to trying to build Please
- `which go` gives `/usr/local/go/bin/go`

## Ideas
I believe this is caused by the `DefaultPath` variable in `src/core/config.go` - it does not include the location where the `go` binary lives - namely `/usr/local/go/bin/go`.

I propose fixing this by adding `/usr/local/go/bin/go` to this `DefaultPath` array. I did this locally and it fixed the issue, meaning I was able to build and install Please from source. Is this the correct approach to solve this problem? I'd be happy to raise a small PR with this if so.

Thanks!

**Comment by Tatskaari** [comment]
The justification for this is we don't want to add "arbitrary" paths to this array. Please is meant to be a multi-language build system so while that might be the standard path that go is installed to, it's still a language specific thing. You still have to add it to $PATH in your .bashrc so likewise you have to tell Please where go is installed too.
