### ISSUE TITLE
C# Support

### ISSUE THREAD

**Issue by AveryJensen** [thought-machine/please#1503]
I would love if you could support building projects in C# via Mono!

**Comment by hartmannr76** [comment]
Just curious, why mono over .NET core? 
I imagine things using this would likely be newer projects and it feels like starting with core would be a better direction.
I randomly stumbled on this project though and love the concept!! I may prod around to see how I can help

**Comment by AveryJensen** [comment]
@hartmannr76
Mono is a compiler; .NET core is a library.

**Comment by hartmannr76** [comment]
.NET core sdk has a cross platform compiler. From what I've seen over the years, things have moved away from Mono in favor of Core (which is not just becoming the mainline .NET)

**Comment by Tatskaari** [comment]
The biggest questions I have are around third party dependencies. I've not been in touch with C# for a long time so I'm not sure what the standard is these days. I know in the past, some have tried to integrate with NuGet but have had trouble. 

Do mono and Roslyn have the same command lines now? I thought those projects got integrated so hopefully it doesn't matter which we support. We can just leave this up to a config option just like we do for clang and gcc. 

@hartmannr76 Welcome, glad you like what you see! If you want to help, the best place to start is [here](https://please.build/codelabs.html), specifically the custom build rules codelab. I'd put these rules in a third party repo as I'm unlikely to be able to provide first party support for C# especially given how diverse its usages are.

**Comment by hartmannr76** [comment]
The majority of projects I've seen and worked on in .NET have been using NuGet. The MSBuild team has integrated usage of it into existing project files so it's definitely become much easier to work with.

Last I heard, Mono was going to merge with the rest of the framework as of .NET 6. Which I think targets this year. 

I'll start working through the codelabs (I usually dedicate my mornings to side-projects so I apologize if I'm a bit slower with it 😄 ) and see what I can get building.

**Comment by namtzigla** [comment]
This is as far as I got:


```
def nuget(name:str, version:str, visibility:list =None,toolchain:str = CONFIG.DOTNET_TOOL):
    return build_rule(
        name = name, 
        visibility = visibility,
        outs = [
          f'{name}-{version}.nuget-dep',
          f'{name}/{version}/{name}.{version}.nupkg',
        ],
        # TODO find a way to get around copying the output of the remote_file rule  
        srcs = [remote_file(
          name = name,
          _tag = 'download',
          url = f'https://api.nuget.org/v3-flatcontainer/{name}/{version}/{name}.{version}.nupkg',
          out =f'.download/{name}.{version}.nupkg',
        )],
        cmd = ' && '.join([
          f'mkdir -p {name}/{version}',
          f'cp $SRCS {name}/{version}',
          f'echo " package {name} -v {version} --package-directory $PKG -n " > {name}-{version}.nuget-dep'
        ]),
        tools = {
          'dotnet': [toolchain],
        }
    )

def dotnet_library(name:str, namespace:str = None,  template:str= 'classlib', srcs:list = None, visibility:list = None, 
    toolchain:str = CONFIG.DOTNET_TOOL, deps:list=[]):
    if namespace == None:
      namespace = package_name().replace('/','.')


    return build_rule(
        name = name, 
        srcs = srcs, 
        visibility = visibility,
        deps = deps,
        tools = {
          'dotnet': [toolchain],
        },
        cmd = ' && '.join([
            f'NAMESPACE="{namespace}"',
            # $(grep -h namespace $SRCS | uniq  | sed -e "s/namespace //" | sed -e "s/{//" | tr -d [:blank:])' if namespace == None else f'NAMESPACE={namespace}',
            f"$TOOLS_DOTNET new {template} -n $NAMESPACE -o . ",
            'for i in $(find . -name "*.nuget-dep"); do $TOOLS_DOTNET add ${NAMESPACE}.csproj  $(cat $i) ; done',
            "$TOOLS_DOTNET pack -c Release -o ${NAMESPACE}/1.0.0  ",
            f'echo " package ${NAMESPACE} -v 1.0.0 --package-directory $PKG -n "> ${NAMESPACE}-1.0.0.nuget-dep',
            f'ls ${NAMESPACE}-1.0.0.nuget-dep ${NAMESPACE}/1.0.0/${NAMESPACE}.1.0.0.nupkg ${NAMESPACE}.csproj',
        ]),
        outs = {
          'nuget-dep': [f'{namespace}-1.0.0.nuget-dep'],
          'nupkg':[f'{namespace}/1.0.0/{namespace}.1.0.0.nupkg'],
          'csproj':[f'{namespace}.csproj'],
        },
        requires = ['nuget-dep','nupkg'],
    )

def dotnet_test(name:str, srcs:list, visibility:list=None, toolchain:str = CONFIG.DOTNET_TOOL, deps:list=[]): 
    return build_rule(
        name = name, 
        visibility = visibility,
        srcs = [dotnet_library(name=f"_test#lib", namespace = 'Test', template = 'mstest', srcs = srcs, toolchain = toolchain, deps = deps)],
        deps = deps,
        tools = {
            'dotnet': [toolchain],
        },
        test = True,
        test_cmd = '',
    )
```

The nuget rule works and it creates entries for a local nuget repo that should work, but this is the only thing that actually works.
I was trying to generate .csproj files in each dotnet_library but injecting the dependency turned out to be a nightmare, it seems that there is no way to specify the dependency directory on a disk and I wasn't able to convince dotnet to use my nuget cache  structure.

**Comment by namtzigla** [comment]
This is how I was downloading the dotnet sdk but since you added the endpoints you can do a better job here
```
if CONFIG.HOSTOS == 'linux':
    XHOSTOS = 'linux'
elif CONFIG.HOSTOS == 'darwin':
    XHOSTOS = 'osx'

build_rule(
    name = 'dotnet_sdk',
    srcs = [remote_file(
        name = 'dotnet',
        _tag = 'download',
        url = [
            f'https://download.visualstudio.microsoft.com/download/pr/8db2b522-7fa2-4903-97ec-d6d04d297a01/f467006b9098c2de256e40d2e2f36fea/dotnet-sdk-3.1.301-{XHOSTOS}-x64.tar.gz',
            f'https://download.visualstudio.microsoft.com/download/pr/d8bc3271-b869-4dc3-96db-d91c574bacc7/b2fbdac38ca4ac71194a41cdd97f1d82/dotnet-sdk-3.1.301-{XHOSTOS}-x64.tar.gz',
            f'https://download.visualstudio.microsoft.com/download/pr/cb535978-7eb4-4bcb-8e85-98c3d42eae3f/1acdc320ba87e1d840242ee4b930b026/dotnet-sdk-3.1.301-{XHOSTOS}-x64.zip',
        ],
    )],
    cmd = """
    mkdir -p dotnet_sdk
    tar xf $SRCS -C dotnet_sdk
    """,
    outs = ["dotnet_sdk"]
)

build_rule(
    name = 'dotnet',
    binary = True,
    tools = {
        'dotnet_sdk':[':dotnet_sdk'],
    },
    cmd = """
    set -H
    cat > $OUTS << EOF
#!/bin/sh 
export DOTNET_ROOT=$TOOLS_DOTNET_SDK
export PATH=\\\$DOTNET_ROOT/bin:\\\$PATH
exec $TOOLS_DOTNET_SDK/dotnet "\\\$@"
EOF
    """,
    visibility = ['PUBLIC'],
    outs = ['dotnet']
)
```

**Comment by namtzigla** [comment]
also this is a dotnet_grpc plugin definition

```

dotnet_grpc = proto_language(
    language = 'dotnet',
    extensions = ['.cs','.csproj'],
    use_file_names = False,
    func = lambda name, srcs, deps, test_only: dotnet_library(
        name = name,
        srcs = srcs,
        deps = deps + [
            '//third_party/dotnet:Google.Protobuf',
            '//third_party/dotnet:Grpc'
        ],
        # test_only = test_only,

    ),
    protoc_flags = ['--csharp_out=$TMP_DIR', '--plugin=protoc-gen-grpc-csharp=$TOOLS_DOTNET', '--grpc-csharp_out=$TMP_DIR'],
    tools = ['//third_party/proto:grpc_csharp_plugin'],
)

remote_file(
    name = 'grpc_csharp_plugin',
    url = f'http://public.tcncloud.com/grpc/v1.26.0/{CONFIG.HOSTOS}_{CONFIG.HOSTARCH}/grpc_csharp_plugin',
    binary = True,
)

```

**Comment by joaocc** [comment]
Hi. Any news on adding C# support to Please? Thanks

**Comment by Tatskaari** [comment]
> Hi. Any news on adding C# support to Please? Thanks

HI! We don't use C# internally at Thought Machine, and the build team is pretty small so I don't think I can reasonably support C# as a first party language. If anybody here wants to try and productionise the rules above, I'd be more than happy to help!

We're building out a new API for extending Please with build definitions, called the plugins API. This should help facilitate third party languages. We're working on finalising this API but will get a codelab and some documentation out soon, however there are a few examples here: [java](https://github.com/please-build/java-rules), [python](https://github.com/please-build/python-rules), [C/C++](https://github.com/please-build/cc-rules), [proto](https://github.com/please-build/proto-rules)
