### ISSUE TITLE
Source code debug information is not generated on MacOS

### ISSUE THREAD

**Issue by idemura** [thought-machine/please#1508]
I'm testing please build on a small project now. It is written in C, I use MacOS and clang 12:
```
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
When I try to use LLDB on generated binary, I only see assembly. While the same binary works perfectly and I'm able to run it. This is my BUILD file:
```
c_library(
    name = "adt",
    srcs = glob(["adt/*.c"]),
    hdrs = glob(["adt/*.h"]),
    deps = [":types"],
)

c_binary(
    name = "adt_test",
    srcs = glob(["adt/tests/*.c"]),
    hdrs = glob(["adt/tests/*.h"]),
    deps = [
        ":adt",
        ":testing",
    ],
)

c_library(
    name = "testing",
    srcs = glob(["testing/*.c"]),
    hdrs = glob(["testing/*.h"]),
    deps = [":types"],
)

c_library(
    name = "types",
    srcs = glob(["types/*.c"]),
    hdrs = glob(["types/*.h"]),
)
```
and plz_config:
```
[Cpp]
CCTool = clang
DefaultOptCflags = --std=c17 -Wall -Werror -march=native -O2 -DNDEBUG
DefaultDbgCflags = --std=c17 -Wall -Werror -march=native -O0 -g
```
I build with `-c dbg`. I also use `-v debug` to make sure command lines correct. As I was suggesting on gitter, I add logs for 
`plz build --shell -c dbg` but it unfortunately fails:
```
igor@mbp owl_llvm % plz build --shell -c dbg
Build stopped after 30ms. 1 target failed:
    //src:types
can't prepare temporary directory for //src:types; filegroups don't have temporary directories
```
But works ok without --shell.

**Comment by idemura** [comment]
PS: Please was installed with Homebrew

**Comment by Tatskaari** [comment]
@peterebden  Any idea what might be going on here? I've not set up clang/gcc with debug flags before. 

Re: --shell not working there: unfortunately c_library() and c_binary() return multiple types of results (headers, and compiled artifacts) so these are grouped up as a filegroup. It might make more sense if you `plz query print //src:all` to see what's going on. 

Essentially, if you want to use `--shell`, you have to target the internal rule directly: `plz build -c dbg --shell //src:_types#lib`

I've opened #1514 which I think gives a more helpful message.

**Comment by peterebden** [comment]
Hi! It's been a little while since I've tried to debug a C target in anger but have had it working before. This seems to work as I'd expect with gdb:
```
plz build -c dbg //test/c_rules:select
...
gdb plz-out/bin/test/c_rules/select
...
(gdb) b input_timeout
Breakpoint 2 at 0x731: file test/c_rules/select.c, line 9.
(gdb) run
Breakpoint 2, input_timeout (fd=0, seconds=5) at test/c_rules/select.c:9
9       int input_timeout(int fd, unsigned int seconds) {
(gdb) p seconds
$1 = 5
```

**Comment by peterebden** [comment]
OK, seems like this is a MacOS issue; it is also working OK using LLDB on Ubuntu, but indeed on a Mac it indeed doesn't seem to know about any of the symbols 🤔

**Comment by Tatskaari** [comment]
Right so the way to add debug symbols in macOS is different to linux. The apple version of clang in xcode creates you a `{name}.dSYM` file which can be generated via `dsymutil`.  `clang -g -o foo foo.o` will do this automatically for you but it can also be done via `dsymutils main` retrospectively. 

In the next Please release (early next week) there will be a config option to output this information. You'll need to add this to your `.plz_config_darwin_amd64`:

```
[cpp]
DsymTool = dsymutil
```
