### ISSUE TITLE
Website: Scrolling doesn't work on firefox 

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1512]
User reports that they're using firefox on linux and the anchor links don't work: 

https://please.build/lexicon.html#misc

**Comment by AveryJensen** [comment]
Firefox also locks up on macOS Big Sur, Safari works fine though.

**Comment by Tatskaari** [comment]
Yeah I'm able to reproduce on my machine. It seems like if you scroll it does eventually move but firefox seems to think the page is much longer than it really is... Very strange.

**Comment by Tatskaari** [comment]
Ah, i'm getting this in the js console: 
```
Too many calls to Location or History APIs within a short timeframe.
```
