### ISSUE TITLE
Go module hierarchy

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1516]
When a module is found at a subpath of another module, Please complains about outputting files in the same directory:

```
08:24:47.959 WARNING: /Users/marksk/Projects/banzaicloud/pipeline/third_party/go/BUILD.plz: Target //third_pa
rty/go:_k8s.io__klog__v2#download outputs files into the directory src/k8s.io/klog, which is separately output by 
//third_party/go:_k8s.io__klog#download. This can cause errors based on build order - you should add a dependency
```

This is definitely going to be an issue with new major versions (eg. `k8s.io/klog` and `k8s.io/klog/v2`).

Here is an example:

```starlark
go_mod_download(
    name = "k8s.io__klog",
    _tag = "download",
    module = "k8s.io/klog",
    version = "v1.0.0",
)

go_module(
    name = "k8s.io__klog",
    download = ":_k8s.io__klog#download",
    install = ["."],
    module = "k8s.io/klog",
    visibility = ["PUBLIC"],
    deps = [],
)

go_mod_download(
    name = "k8s.io__klog__v2",
    _tag = "download",
    module = "k8s.io/klog/v2",
    version = "v2.3.0",
)

go_module(
    name = "k8s.io__klog__v2",
    download = ":_k8s.io__klog__v2#download",
    install = ["."],
    module = "k8s.io/klog/v2",
    visibility = ["PUBLIC"],
    deps = [":github.com__go-logr__logr"],
)
```

**Comment by Tatskaari** [comment]
Ah good point. I think we can get this to work. Unfortunately, we've got a feature flag that gates our new `please_go_install` method of compiling falling back to `go install` which relies on a valid GOPATH so we can't easily change the paths up.
 
The new please_go_install tool doesn't have any restrictions on the location of the source root. What we can do is change the download location when this flag is enabled to just be the rule name. That way two rules can never output into the same directory. 

By the way, `_tag` is means to be private and I don't think you need to deal with internal rules. I expected the rules to be used more like this: 
```
go_mod_download(
    name = "k8s.io__klog_download",
    module = "k8s.io/klog",
    version = "v1.0.0",
)

go_module(
    name = "k8s.io__klog",
    download = ":k8s.io__klog_download",
    module = "k8s.io/klog",
    visibility = ["PUBLIC"],
)

go_mod_download(
    name = "k8s.io__klog__v2_download",
    module = "k8s.io/klog/v2",
    version = "v2.3.0",
)

go_module(
    name = "k8s.io__klog__v2",
    download = ":k8s.io__klog__v2_download",
    module = "k8s.io/klog/v2",
    visibility = ["PUBLIC"],
    deps = [":github.com__go-logr__logr"],
)
```

**Comment by sagikazarmark** [comment]
> By the way, `_tag` is means to be private and I don't think you need to deal with internal rules. I expected the rules to be used more like this:

Personally, I like using tags. It's more explicit than suffixing a rule name. Why are tags considered private?
I was actually considering opening an issue/PR for something like this:

```starlark
go_mod_download(
    name = "k8s.io__klog",
    _tag = "download",
    module = "k8s.io/klog",
    version = "v1.0.0",
)

go_module(
    name = "k8s.io__klog",
    download = tagged_name("k8s.io__klog", "download"),
    install = ["."],
    module = "k8s.io/klog",
    visibility = ["PUBLIC"],
    deps = [],
)
```

It's syntactic sugar, but makes using tagged names easier.

**Comment by Tatskaari** [comment]
It's a convention all build rules follow so far. Please presents build rules as producing a single build target which is uniquely identified by its name. In reality, Please needs to create a number of sub-rules to get the job done but these are hidden from the users. 

If you pass `_tag` to `go_mod_download(name = "my_download")`, there will be no `":my_download"` because it's actually called `:_my_download#tag_name`. There's no technical reason not to do this. Please treats them pretty much identically, but none of the build rules Please ships with do this so consumers of your rules will have to adjust to that.
