### ISSUE TITLE
Missing two params in this error message 

### ISSUE THREAD

**Issue by namtzigla** [thought-machine/please#1527]
This line:
https://github.com/thought-machine/please/blob/27c71154ca98280d919397b93c5c28a7ff0ea60b/src/fs/hash.go#L188
should probably look like:
```
 log.Warning("Symlink %s has an absolute target %s, that will likely be broken later", p, deref) 
```

**Comment by Tatskaari** [comment]
Thanks for raising :) Fixed in #1530
