### ISSUE TITLE
please_go_install: Add a test case for modules only compilable on one platform

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1529]
Let's make sure that `go_module` targets can be built even when the underlying module has no Go files for a specific platform (ie. it shouldn't just fail)

Otherwise users need to wrap those targets in a `is_platform` condition (and use `select` for dependencies). See https://github.com/sagikazarmark/please-go-modules/blob/71298754c95d55acbc7166ebfd37ef860d213d72/example2/third_party/go/BUILD.plz#L52

**Comment by Tatskaari** [comment]
What should the rule output in this case? In the example above, it must output a `log.a` file. 

Please will only compile the module if it's depended on by something in the build graph. I suppose if you're doing a `plz build` it will pick up everything. If you were to query changes or build a specific target, presumably this target won't get picked up.

**Comment by sagikazarmark** [comment]
> Please will only compile the module if it's depended on by something in the build graph.

That's true, if targets are guarded by `is_platform` calls and targets are packages, not modules. If you build an entire module in a single `go_module` target without `is_platform` and `select`, it will reference all build targets including ones only required on a specific platform.

For example:

- moduleA
  - linux.go requires moduleB (therefore moduleA requires moduleB)
- moduleB
  - linux.go (only compiled on linux)
 

In the above example, moduleB has no output on darwin, but it's still part of the build graph.

**Comment by Tatskaari** [comment]
I've made some changes in this direction as I encountered some issues with `...` trying to compile packages that have no sources for a given platform. This fixes it at the package level (when using wildcards) but I'm struggling to understand the use case for an entire module not producing an output. If you say `install = ["log"]` that rule has to produce a `log.a`. 

Can you give me an example of a module that has no sources for a given platform? The example above seems to produce a log.a but I don't see any build tags that would change that per platform?
