### ISSUE TITLE
Export outputs to their respective packages

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1544]
Trying to run golangci lint on a project that contains generated go files. As you can guess it fails badly because of the missing imports.

I thought I'd just export the generated code with the following command:

```shell
plz export outputs --include generated -o .
```

This results in everything being exported to the root directory. A possible solution is exporting artifacts to their respective packages (with an option maybe?).

**Comment by Tatskaari** [comment]
The idea was to have `plz-out/go` that presents a valid go path of all go sources (generated or otherwise). Have you looked into that option? I don't think it has a go.mod but that should be a relatively easy fix.

**Comment by sagikazarmark** [comment]
bump
