### ISSUE TITLE
Document go_module via plz help

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#1552]
`plz help` is my primary source of `plz` docs.  Can the `go_module` rule be added to `plz help`?  Or, is there a reason it's not visible yet?

```
❯ plz help go_module
Sorry OP, can't halp you with go_module

Maybe you meant cc_module ?
 Or have a look on the website: https://please.build
```

**Comment by Tatskaari** [comment]
There was a reason: it was experimental. That's not really true anymore so I'm happy to publicise it.
