### ISSUE TITLE
bootstrap.sh failed at running tests

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#1560]
Environment: Ubuntu 20.04 amd64
Please version: latest commit
Go version: 1.15.0

$ ./bootstrap.sh 
Building Please...
Build finished; total time 47.36s, incrementality 0.0%. Outputs:
//src:please:
  plz-out/bin/src/please
Building the tools...
Build finished; total time 12.74s, incrementality 86.6%. Outputs:
//package:installed_files:
  plz-out/bin/package/build_langserver
  plz-out/bin/package/jarcat
  plz-out/bin/package/javac_worker
  plz-out/bin/package/junit_runner.jar
  plz-out/bin/package/please
  plz-out/bin/package/please_go_filter
  plz-out/bin/package/please_go_install
  plz-out/bin/package/please_go_test
  plz-out/bin/package/please_pex
  plz-out/bin/package/please_sandbox
Running tests...
Clang not found, excluding Clang tests
32-bit gcc libraries not found, excluding cross-compile tests
Build stopped after 2m39.08s. 1 target failed:
    //third_party/python:_tensorflow#srcs
Error building target //third_party/python:_tensorflow#srcs: exit status 1
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1)
ERROR: No matching distribution found for tensorflow==1.13.1

**Comment by PeterBocan** [comment]
I got the same issue.

**Comment by peterebden** [comment]
Please doesn't need tensorflow per se. We have a test that uses it since there was some historic related issue.

In the meantime you can either run `bootstrap.sh --skip_tests` if you don't want any tests, or `bootstrap.sh --exclude python3` (or similar) to exclude a particular set of tests.

**Comment by Tatskaari** [comment]
Bah seems like the version of tensorflow we were using in the tests vanished... but only on some versions of python because the CI still passes. Damn you pip! Tempted to move the pip rules out of the core of please in the v16 release. What do you think @peterebden ?

**Comment by peterebden** [comment]
100% in favour. Pip is very temperamental and hard to support, it would be nice to separate that from core plz.

**Comment by dmitris** [comment]
also got this error trying to run `./bootstrap.sh`:
```
Messages:
18:05:50.954   ERROR: //third_party/python:_tensorflow#srcs failed:
Error building target //third_party/python:_tensorflow#srcs: exit status 1
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1
```
as well as:
```
18:06:04.270   ERROR: //third_party/python:_h5py#srcs failed:
Error building target //third_party/python:_h5py#srcs: exit status 1
18:06:35.468   ERROR: //third_party/python:_pandas#srcs failed:
Error building target //third_party/python:_pandas#srcs: exit status 1
18:07:33.386   ERROR: //third_party/python:_numpy#srcs failed:
Error building target //third_party/python:_numpy#srcs: exit status 1
```
