### ISSUE TITLE
Question: what's the correct way to pass many args to command?

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#1561]
Sometime I need to pass lots of file paths to a command, as many as then shell complains that too many args are in the command. Is there any mechanism to allow large amount of info be passed to command? Such as create a temporary file (created by Please and only return its name), like:

```
fp = temporary_file(strVar)
cmd = f'mycommand --config-file={fp}'
```

The file can be ~/.tmp/123e4567-e89b-12d3-a456-426614174000 or whatever.

Thanks.

**Comment by Tatskaari** [comment]
If you're hitting the bash limit for the number of args you can pass to a command, there's nothing Please can do about that. If you can, you should pass the command a directory instead. 

There was a feature request a while back for a `native_file()` build rule that would take in a string as an argument and write that to a file: https://github.com/thought-machine/please/issues/1218

That would avoid bash and allow you to generate a file from the build language, avoiding bash. Would this help?

**Comment by linuxerwang** [comment]
> If you're hitting the bash limit for the number of args you can pass to a command, there's nothing Please can do about that. If you can, you should pass the command a directory instead.
> 
> There was a feature request a while back for a `native_file()` build rule that would take in a string as an argument and write that to a file: #1218
> 
> That would avoid bash and allow you to generate a file from the build language, avoiding bash. Would this help?

Exactly what I want. Hope to get it soon. Thanks!

**Comment by Tatskaari** [comment]
Okay I will close this and re-open that one then :)
