### ISSUE TITLE
Run a script with --in_wd using out_exe

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1572]
I found myself wanting to run multiple binaries built/downloaded by Please in a sequence with different arguments.

I quickly realized that `plz run` itself won't work (I actually wanted to setup an alias), so I came up with a simple script:

```
sh_cmd(
    name = "mycmd",
    cmd = [
        "$(out_exe //cmd) arg1",
        "$(out_exe :other_cmd) arg2",
    ],
    deps = [
        ":other_cmd",
        "//cmd",
    ],
)
```

The problem is `out_exe` outputs a relative path to the executables which makes the script fail when running it with `plz run --in_wd`.

One possible solution is adding replacements resolving absolute paths (I attempted to implement them in #1171, but @peterebden advised against it: https://github.com/thought-machine/please/pull/1171#discussion_r483181275)

**Comment by Tatskaari** [comment]
We could make plz set `$OLD_WD` when using `--in_wd`?

**Comment by sagikazarmark** [comment]
How would that solve the issue?

Do you mean like:

```
sh_cmd(
    name = "mycmd",
    cmd = [
        "\\\$OLD_WD/$(out_exe //cmd) arg1",
        "\\\$OLD_WD/$(out_exe :other_cmd) arg2",
    ],
    deps = [
        ":other_cmd",
        "//cmd",
    ],
)
```

Maybe call it `PLZ_ROOT` instead?

**Comment by Tatskaari** [comment]
Going to track this in #1604
