### ISSUE TITLE
Enable ability to mark pip_library as binaries

### ISSUE THREAD

**Issue by xinkecf35** [thought-machine/please#1577]
**Problem Statement:**
It would be nice to able to run `pip_library` directly with their known entry points. Immediate examples I am thinking of are [flake8](https://flake8.pycqa.org/en/latest/) and [black](https://github.com/psf/black). In effect, I want to be able to a reasonably degree implement a `lint` alias but using pip packages. 

**Possible Solution and Implementation:**
From a discussion on Gitter, it's a little more difficult to do here because we need identify the entry point. Fortunately, packages distributed on PyPI normally indicate their entry points as part of their `setup.py` and thus distributed as part of their distribution information.

To actually execute the downloaded packages, I would like to create a virtualenv(venv) of some form and place the relevant libraries into that virtualenv and activate it as part of executing the library with Please. The approach described seems to be most advisable pattern given general guidance about using pip packages in general and taking cues from [pipx](https://github.com/pipxproject/pipx).
 
I should preface the above and say that the above approach is the first thing I thought of. I am very new to the world of Python Packaging and dealing with the details of how packages advertise their entry points in order to be runnable so feedback is welcome.

**Comment by Tatskaari** [comment]
I've had a look into this before and didn't get very far. I think there's a RECORD file or something that pip puts in the package directory after an install that contains some pertinent information. I'm not very ramped up with Python especially with pip as we don't use pip internally at Thought Machine. I'd very much appreciate some help with this.

**Comment by xinkecf35** [comment]
Yes, I was doing some initial poking around with a couple samples packages and the Python Packaging [documentation](https://packaging.python.org/specifications/entry-points/) and saw there's a `entry_points.txt` file in the `dist-info` metadata for pip packages that advertises console scripts with the respective function. I imagine that file should be helpful in determining what to expose as the binary.

As far as the venv library is concerned, my understanding is that it is provides a limited subset of what the virtualenv package does in terms of creating a isolated Python environment and it's part of the Python standard library versions 3.3 and up. At the moment, it is the only way I know of to set up a Pip package and expose runnable packages without polluting the system space. Seeing as Please ships with it's own PEX too due to speed considerationsl, I'll understand any reservations in trying to use Python directly for the implementation.

I still need to do some more research and exploration on the subject, right now I am trying to determine what exactly is setup for you in a virtualenv as well as what pip install exactly does when it sets it up. Ideally, once I have a better understanding of that, I can better determine how to setup a virtualenv for this or even remove that proposed dependency entirely.

**Comment by peterebden** [comment]
As far as I know the 'binaries' that pip installs are pretty basic:
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from black import patched_main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(patched_main())
```
Maybe we just need a little Python script that gets invoked at build time to read the setup.py and produce that? 
(We could also do without by putting an explicit instruction about the entrypoint on the `pip_library` but it would be nicer if you didn't have to do that)

**Comment by xinkecf35** [comment]
@peterebden Thank you the suggestion, I will definitely try it. I think between the above and the presence of the `entry_point.txt` file I imagine an explicit `entrypoint` instruction should not be necessary. The only other thing is working out how to incorporate the dependencies, but I am guessing with the above script, I imagine the next step is just to use the `please_pex_tool` to package that all up?
