### ISSUE TITLE
Enable GoTestRootCompat by default

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1589]
`GoTestRootCompat` was added to allow the go test binary to descend into the package directory. This was important to keep compatibility with `go test`.

Can we enable it by default in v16?

**Comment by Tatskaari** [comment]
We valued keeping compatibility with the other languages over compatibility with `go test`. I consider Please a multi-language build system first, and having nuances between the way Please builds and tests different languages doesn't sit well with me. I think I still feel this way. If compatibility with `go test` is important to you, enabling the config option isn't much of a burden.

**Comment by sagikazarmark** [comment]
I understand.
