### ISSUE TITLE
v16 migration notes

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1590]
The full migration notes can be found [here](https://please.build/milestones/16.0.0.html)

## Installation (#1573)
Please now installs the wrapper script (`pleasew`) into the "path" (`~/.please/bin/plz`). This avoids a lot of issues with the previous approach where we put a symlink to the active version of Please on the path. Now deleting Please versions will not break your Please installs. This only affects new installs and ultimately should be quite transparent to the user. 

I recommend doing `ln pleasew /usr/bin/plz` to install please system wide and relying on `pleasew` to keep your please version up to date. 

## Remove PleaseGoInstall feature flag (#1578)
`go_module()` will now use the `please_go_install` tool to install modules rather than `go install ...`. There are some slight incompatibilities. Namely `install = ["foo/..."]` will not install `foo.a`. To mitigate this, use `install = ["foo", "foo/..."]`. By the time v16 comes out, I hope to have worked through such issues.
 
## Remove `out` param from `go_library()` etc. (#1581)
This used to control the expectged package name for the library. There's now a `package = "foo"` parameter which is semantically more meaningful. To migrate, change `out = "foo.a"` to `package = "foo"`.

**Comment by peterebden** [comment]
### Remote execution

Removed some old settings around locating things remotely; there are obsolete with the new installation setup. ([#1599](https://github.com/thought-machine/please/pull/1599))

### Sandboxing

`please_sandbox` now creates a new PID namespace for the process and remounts the root filesystem as read-only ([#1618](https://github.com/thought-machine/please/pull/1618) , [#1622](https://github.com/thought-machine/please/pull/1622)).
Well-behaved build actions should not care about these changes.

**Comment by Tatskaari** [comment]
# Maven hashes
The hashes for all maven jars is now different. We now hash the downloaded .jar and _sources.jar separately rather than the sum of them together. There's a new parameter `sources_hash` to check the `_sources.jar`. These will match the sha256 on maven central etc. 

# go_module() installs
`go_module()` now installs the parent package when using `foo/...`. Before you would have to add `install = ["foo", "foo/..."]` whereas now `foo/...` is enough. 

 # --prepare is now deprecated
This was a weak precursor to --shell and has no real use. In v17 it will be removed. 

# Various fixes/changes around go proto rules
Ultimately this should be pretty transparent however the go proto rules are "sourcerelative" which means the generated .pg.go files land in the package directory rather than a nested directory matching their import path. This doesn't have much bearing on the compiled output but if you cared about where the generated sources live, this is something to be aware of. 

# Please downloads tools by default
In v15, Please installed it's tools under `~/.please` and would add these to the PATH for builds/tests. In v16, there's a new internal `//_please` package that will download these tools as needed. To opt out of this, you will have to install the tools from the releases page, and set the various config values as such:

```
[java]
JarcatTool = jarcat
```

# Go imports: duplicated base name
We no longer allow the go package to duplicate it's base name in imports i.e. `example.com/foo` can no longer be imported as `exmaple.com/foo/foo`. 

# plz-out/log/test_results.xml no longer contains stdout/stderr for successful tests
If this was important to you, you may set:
```
[Test]
StoreTestOutputOnSuccess = true
```

# Removed deprecated --nocache
This was miss-leading most people who typically wanted one of `plz build --rebuild` or `plz test --rerun`. To actually run without the cache us the flags `-o cache.dir: -o cache.httpurl:` to disable the dir and http caches respectively. 

# Removed `//:pleasings` 
Please no longer includes pleasings by default. To add pleasings back in, run `plz init pleasings`

# Removed `metadata` on `build_rule()`
This undocumented feature turned out to be not very useful, and rather complex to implement. To pass metadata between rules, use labels instead which are far more reliable. 
 
# Fix long standing bug where go rules included some transitive dependencies
Go rules have been pulling in some transitive dependencies in some cases. We no longer do this and as a result, the imports in the .go source files must match the deps on the go rules. Tools like [wollemi](https://github.com/tcncloud/wollemi) can help automatically keep these in sync.
