### ISSUE TITLE
problem running tests using python_test

### ISSUE THREAD

**Issue by afterthought** [thought-machine/please#1596]
Hi. Looking for advice on the right path forward. The python binary rules [pass the --add_init_py flag](https://github.com/thought-machine/please/blob/master/rules/python_rules.build_defs#L309) to the jarcat tool. As I configured unit tests under the python_test rule I found that this flag isn't desired for a certain library we use. This library is reading all files in a folder expecting them to be a certain type of file. It breaks when it finds the __init__.py file in the folder at runtime. I copied the python_test rule locally to remove that flag and prove my theory. Is this flag something that you'd consider exposing as a rule param? Alternatively, i'll need to decide how to proceed. Using a fork or a different strategy.

Thanks....

**Comment by pdkhang2411** [comment]
This was on Please's google group since 2018, still no sign of the flag. Best bet is probably a fork or just patch the python rules locally like you have done.
https://groups.google.com/g/please-build/c/aMRLQcaXOmY

**Comment by afterthought** [comment]
Thanks. I'm not a python expert, but i do find this "feature" suspect for third party libraries. Seems like it's best to trust the library author as a default position and not start altering the library on them. Thanks for the google groups link @pdkhang2411 .

**Comment by peterebden** [comment]
We could consider having this as a flag. It seems awkward though (since the only way you know you have to add it is for the thing to fail and then you have to figure out what it is).

I wonder if we can identify the third-party packages and not descend into them? Possibly we can just use the PYTHON_MODULE_DIR setting to pick where we expect them to be.
