### ISSUE TITLE
'zip_safe' flag not working as described in python_binary and python_test rules

### ISSUE THREAD

**Issue by pdkhang2411** [thought-machine/please#1597]
The document:
"zip_safe (bool) - Allows overriding whether the output is marked zip safe or not. If set to explicitly True or False, the output will be marked appropriately; by default it will be safe unless any of the transitive dependencies are themselves marked as not zip-safe."

However, looking at the python_rules.build_defs file, I see no implementation of this behavior in those two rules. Tried adding zip_safe = False on a python_binary target and the output is still marked as ZIP_SAFE = True in the __main__.py file.

**Comment by peterebden** [comment]
The implementation of that flag is here: https://github.com/thought-machine/please/blob/ae52068a09d5cf40d3be453f8e3245ada19e9b44/rules/python_rules.build_defs#L594

There is a test on this in the repo too: https://github.com/thought-machine/please/blob/ae52068a09d5cf40d3be453f8e3245ada19e9b44/test/python_rules/BUILD#L57

Possibly this doesn't work if the binary itself is marked as `zip_safe=False` rather than one of the dependencies?

**Comment by pdkhang2411** [comment]
> The implementation of that flag is here: https://github.com/thought-machine/please/blob/ae52068a09d5cf40d3be453f8e3245ada19e9b44/rules/python_rules.build_defs#L594

The function searches for a 'py:zip-unsafe' label, which is only added to the target by the 'zip_safe' flag in the **python_library** rule: https://github.com/thought-machine/please/blob/ae52068a09d5cf40d3be453f8e3245ada19e9b44/rules/python_rules.build_defs#L46-L47
The actual 'zip_safe' flag given to **python_binary** and **python_test** rules has no effect on the zip safe-ness of their output whatsoever, the rules always behave as default: safe unless any of the transitive dependencies are marked as unsafe. No "overriding", no "mark the output appropriately if set to explicitly True or False".

> There is a test on this in the repo too: https://github.com/thought-machine/please/blob/ae52068a09d5cf40d3be453f8e3245ada19e9b44/test/python_rules/BUILD#L57

Like I mentioned above, the test you link tests the 'zip_safe' flag of **python_library** rule: a deps of python_test is zip unsafe leading to the output of python_test zip unsafe. It doesn't test the 'zip_safe' flag of **python_test**.

> Possibly this doesn't work if the binary itself is marked as zip_safe=False rather than one of the dependencies?

Yes! In my case, some of the unit tests are zip-unsafe. I want to mark the tests themselve, rather than marking one of their dependencies (which are perfectly zip-safe) as zip-unsafe, or create a zip-unsafe 'dummy' deps, just for thing to work.
