### ISSUE TITLE
Make plz root available for `plz run --in_wd`

### ISSUE THREAD

**Issue by brianbianco** [thought-machine/please#1604]
There are some situations where knowing what the plz root is could be useful.  It's generally frowned upon to do this, but as with all things there is always an exception to the rule.

**Comment by Tatskaari** [comment]
As discussed on gitter (for others reading this), this  would only be for `plz run --in_wd`. Setting it in the other contexts (build, and test) would break a core tenant of Please.

**Comment by sagikazarmark** [comment]
We should make sure that scripts can be written in a way that works universally w/o `--in_wd` (so they don't have to check variable existence, etc).
