### ISSUE TITLE
Please diff

### ISSUE THREAD

**Issue by pratikbalar** [thought-machine/please#1608]
First thanks for the amazing tool,

Now I have this #1592  TL;DR I'm building multiple docker images with please in our **monorepo** where all docker files are put in the **root** of repo because of the dependencies stuff. now, my question is I want to build docker image based on changes in repo so you know when CI runs not all docker images will push/build and only changed one push/build.

something like this: 
```python
subinclude("//pleasing//docker")

docker_image(
    name = "abc",
    dockerfile = "abc.Dockerfile",
    srcs = ["abc","efg","abc.go"],
    visibility = ["PUBLIC"],
    version = f'$(echo "$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)")'
)
docker_image(
    name = "xyz",
    dockerfile = "xyz.Dockerfile",
    srcs = ["xyz","efg","xyz.go"],
    visibility = ["PUBLIC"],
    version = f'$(echo "$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)")'
)
```

and in CI I'm running 
```bash
./pleasew run //:abc_push
./pleasew run //:xyz_push
```
so now if there is a change in `xyz` directory, target `abc` is also running and building docker image. which is not appropriate because `abc` image/srcs has no change since it's getting list of `srcs`!!. so am I missing something or please is not doing `git diff`stuff

**Comment by fenos** [comment]
I would be very much interested as well in understanding what a good `git diff` workflow could be to run specific tasks that have some file changed in them, (not only docker tasks, but any)

I hope someone can give a more broader view on this 🤔

**Comment by peterebden** [comment]
Hi! 
Doing git operations like this within build rules is generally an anti-pattern; Please won't know to rebuild them when that changes, and it isn't even possible if you're using more advanced features like sandboxing or remote execution. We generally version Docker images by a hash of what's going into them in order to avoid that (I think the open source ones contain the same logic by default).

On your specific question though, the relevant command for a diff workflow is `plz query changes` which will take the git changeset and produce the set of targets that would change; you can chain that into others like `plz query changes --include_dependees=transitive | plz test -` to run all affected tests.

**Comment by pratikbalar** [comment]
Thanks for the quick reply,

I added exactly as you said but `plz run ...` instead of `plz test ...` Now I'm getting this
```bash
./pleasew query changes --include_dependees=transitive | ./pleasew --plain_output -v debug --show_all_output run -
```
CI log
```log
10:01:48.837   DEBUG: Found repo root at /root/xxx
10:01:48.837   DEBUG: Attempting to read config from /etc/please/plzconfig...
10:01:48.837   DEBUG: Attempting to read config from /root/.config/please/plzconfig...
10:01:48.837   DEBUG: Attempting to read config from /root/xxx/.plzconfig...
10:01:48.838   DEBUG: Read config from /root/xxx/.plzconfig
10:01:48.838   DEBUG: Attempting to read config from /root/xxx/.plzconfig_linux_amd64...
10:01:48.838   DEBUG: Attempting to read config from /root/xxx/.plzconfig.local...
10:01:48.838   DEBUG: Attempting to acquire lock plz-out/.lock...
10:01:48.838   DEBUG: Acquired lock plz-out/.lock
10:01:48.839    INFO: Total cache size: 0 B
10:01:48.839   DEBUG: Loading built-in build rules...
10:01:48.859   DEBUG: Parser initialised
10:01:48.860 CRITICAL: unable to check diff vs. origin/master: exit status 128
10:01:48.861   DEBUG: Original target scan complete
10:01:48.861    INFO: Shutting down cache workers...
10:01:48.862   DEBUG: Shut down all cache workers
10:01:48.862 CRITICAL: //:_STDIN expanded to too many targets: []
```

**Comment by Tatskaari** [comment]
> Thanks for the quick reply,
> 
> I added exactly as you said but `plz run ...` instead of `plz test ...`
> 
> ```shell
> ./pleasew query changes --include_dependees=transitive | ./pleasew --plain_output -v debug --show_all_output run -
> ```
> 
> Now I'm getting this CI log
> 
> ```
> 10:01:48.837   DEBUG: Found repo root at /root/xxx
> 10:01:48.837   DEBUG: Attempting to read config from /etc/please/plzconfig...
> 10:01:48.837   DEBUG: Attempting to read config from /root/.config/please/plzconfig...
> 10:01:48.837   DEBUG: Attempting to read config from /root/xxx/.plzconfig...
> 10:01:48.838   DEBUG: Read config from /root/xxx/.plzconfig
> 10:01:48.838   DEBUG: Attempting to read config from /root/xxx/.plzconfig_linux_amd64...
> 10:01:48.838   DEBUG: Attempting to read config from /root/xxx/.plzconfig.local...
> 10:01:48.838   DEBUG: Attempting to acquire lock plz-out/.lock...
> 10:01:48.838   DEBUG: Acquired lock plz-out/.lock
> 10:01:48.839    INFO: Total cache size: 0 B
> 10:01:48.839   DEBUG: Loading built-in build rules...
> 10:01:48.859   DEBUG: Parser initialised
> 10:01:48.860 CRITICAL: unable to check diff vs. origin/master: exit status 128
> 10:01:48.861   DEBUG: Original target scan complete
> 10:01:48.861    INFO: Shutting down cache workers...
> 10:01:48.862   DEBUG: Shut down all cache workers
> 10:01:48.862 CRITICAL: //:_STDIN expanded to too many targets: []
> ```

`plz run` only accepts one arg. `plz run sequential` or `plz run parallel` is what you're looking for :)

**Comment by pratikbalar** [comment]
tried 
```bash
./pleasew query changes --include_dependees=transitive | ./pleasew --plain_output -v debug --show_all_output run sequential -
```
but still
```log
Should be good to go now, running plz...
11:22:01.677   DEBUG: Found repo root at /root/nvisnx-services
11:22:01.677   DEBUG: Attempting to read config from /etc/please/plzconfig...
11:22:01.677   DEBUG: Attempting to read config from /root/.config/please/plzconfig...
11:22:01.677   DEBUG: Attempting to read config from /root/nvisnx-services/.plzconfig...
11:22:01.678   DEBUG: Read config from /root/nvisnx-services/.plzconfig
11:22:01.678   DEBUG: Attempting to read config from /root/nvisnx-services/.plzconfig_linux_amd64...
11:22:01.678   DEBUG: Attempting to read config from /root/nvisnx-services/.plzconfig.local...
11:22:01.680   DEBUG: Attempting to acquire lock plz-out/.lock...
11:22:01.680   DEBUG: Acquired lock plz-out/.lock
11:22:01.680    INFO: Total cache size: 0 B
11:22:01.680   DEBUG: Loading built-in build rules...
Should be good to go now, running plz...
11:22:01.706   DEBUG: Parser initialised
11:22:01.729 CRITICAL: unable to check diff vs. origin/master: exit status 128
11:22:01.730   DEBUG: Original target scan complete
11:22:01.731    INFO: Shutting down cache workers...
11:22:01.731   DEBUG: Shut down all cache workers
```

did you check `CRITICAL: unable to check diff vs. origin/master: exit status 128`? it last comments as well this

**Comment by Tatskaari** [comment]
Looks like it's getting and exit code from `git diff --name-only origin/master...HEAD --relativeto ...`. I don't think you can check against a remote branch like that. `--since master` should work.

**Comment by Tatskaari** [comment]
Perhaps you can try running that command manually and see what git says?

**Comment by pratikbalar** [comment]
you mean this

**Comment by Tatskaari** [comment]
No I mean the git command. Looks like it comes out as:
```
git diff --name-only origin/master...HEAD -- /path/to/repo
```

**Comment by pratikbalar** [comment]
tried (_im in git repo_)
```bash
git diff --name-only origin/master...HEAD -- .
git diff --name-only origin/master...HEAD -- ./xyz
git diff --name-only origin/master...HEAD -- xyz.Dockerfile
```
all 
```log
fatal: bad revision 'origin/master...HEAD'
```

**Comment by pratikbalar** [comment]
so if I do change branch then it shows me changes but generally, it shows me all the targets regardless of changes
`[master]$ ./pleasew query changes --include_dependees=transitive --since please-monorepo`
```logs
//:_abc#docker_context
//:_pleasings#download
//:_xyz#docker_context
//:abc
//:abc_fqn
//:abc_load
//:abc_push
//:abc_run
//:abc_save
//:abc_tar
//:pleasings
//:xyz
//:xyz_fqn
//:xyz_load
//:xyz_push
//:xyz_run
//:xyz_save
//:xyz_tar
```

**Comment by Tatskaari** [comment]
> so if I do change branch then it shows me changes but generally, it shows me all the targets regardless of changes
> `[master]$ ./pleasew query changes --include_dependees=transitive --since please-monorepo`
> 
> ```
> //:_abc#docker_context
> //:_pleasings#download
> //:_xyz#docker_context
> //:abc
> //:abc_fqn
> //:abc_load
> //:abc_push
> //:abc_run
> //:abc_save
> //:abc_tar
> //:pleasings
> //:xyz
> //:xyz_fqn
> //:xyz_load
> //:xyz_push
> //:xyz_run
> //:xyz_save
> //:xyz_tar
> ```
> 
> but `[master]$ ./pleasew query changes --include_dependees=transitive --since master`
> `[none]`

With the first example, it's showing the files that are different between your two branches. The second is comparing master to master which isn't going to find anything. Generally on a premerge PR, you'll be on a feature branch e.g. `[please-monorepo] plz query changes --since master`.

**Comment by pratikbalar** [comment]
but the thing is I'm adding `plz query changes --since ${CIRCLE_BRANCH}` in my circle CI but it won't show me anything it's just like `[master]$ ./pleasew query changes --include_dependees=transitive --since master`
