### ISSUE TITLE
latest_version set to un-released version

### ISSUE THREAD

**Issue by steakunderscore** [thought-machine/please#1615]
Currently https://get.please.build/latest_version returns `16.0.0-prerelease.4, which is an un-released version`. This api is used to know when to pull the new version of please. I suspect a bug has been introduced in the release process which now allows this to be set to prerelease versions.

For context this api is used to know when to update the [Arch Linux AUR package](https://aur.archlinux.org/packages/please-bin/) with [this update script](https://aur.archlinux.org/cgit/aur.git/tree/update-version.sh?h=please-bin).

**Comment by peterebden** [comment]
We also need to update the latest_version file to point to the right thing.

**Comment by Tatskaari** [comment]
> We also need to update the latest_version file to point to the right thing.

Okay thanks, just done that.
