### ISSUE TITLE
Update gopsutil

### ISSUE THREAD

**Issue by swills** [thought-machine/please#1639]
Hi,

Could you update the build to use a newer version of gopsutil? The reason I ask is the version in use is quite old and missing [support for FreeBSD arm64](https://github.com/shirou/gopsutil/blob/master/disk/disk_freebsd_arm64.go), forcing [local patches](https://svnweb.freebsd.org/ports/head/devel/please/files/patch-gopsutil_aarch64?view=markup&pathrev=568168) to get it working there.

If I'm reading right, this was fixed in gopsutil v[2.20.1](https://github.com/shirou/gopsutil/releases/tag/v2.20.1) (released Feb 1, 2020), but the build is using either [v2.18.12](https://github.com/thought-machine/please/blob/f6e9b0fbd480b227580e8f1d7ca782ae76e1e17c/go.sum) (released Dec 25, 2018) or [v2.17.09](https://github.com/thought-machine/please/blob/6b63da5d0f2a00594cce010c75b4541aeb095790/third_party/go/BUILD) (released Sep 24, 2017). The latest version is [3.21.2](https://github.com/shirou/gopsutil/releases/tag/v3.21.2) (release March 1 2021).

Thanks!

**Comment by peterebden** [comment]
Sure thing - latest master is now on 3.21.2!
