### ISSUE TITLE
Go third-party dependency naming conventions

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1669]
In the Please repo, third-party dependencies are named after the last segment in the package URL (eg. `github.com/pkg/errors` -> `errors`). I'm not really a fan of that style, because:

- It's not generator friendly
- It doesn't handle collisions

I've been playing with a different style: use the full name, but replace slashes with something else (eg. `github.com/pkg/errors` -> `github.com__pkg__errors`).

It's probably obvious that this is so ugly, I want to carve out my eyes every time I look at them.

I was wondering if we could find a better naming convention or at least come up with some tooling to make BUILD files easier to read.

For example:

```starlark
go_library(
    name = "mylib",
    deps = [
        go_pkg("github.com/pkg/errors"),
    ],
)
```

`go_pkg` would magically replace the package name with the appropriate rule. It probably needs more thinking.

**Comment by Tatskaari** [comment]
In Please we name them by hand so there's no real convention. I don't have any strong feelings on naming conventions for these things. I think you've basically come up with one for your generator which makes sense for people who use that. I wonder if we could use `.` for slashes so it would become `github.com.pkg.errors` which evokes some similarity with python and java paths. The problem with this is that it's no bi-directional; `github.com` could be `github/com` or remain as `github.com`. I don't think that's generally a problem though.
