### ISSUE TITLE
Custom Go protobuf plugin

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1684]
Currently consumers can either use `proto_library` or `grpc_library` to generate Go code (and compiled library archive). The gRPC one will call the standard Go plugin as well.

That, however, doesn't leave room for custom protobuf compilers.

Unfortuantely, having multiple targets outputting a go library in the same package doesn't really work.

**Comment by Tatskaari** [comment]
> That, however, doesn't leave room for custom protobuf compilers.

You can add a new proto_language()/grpc_language() and pass them in through `languages` on proto_library()/grpc_library() or the `proto.languages` config option. If you want to have the current 2 plugins and a third one, you'll have to copy the languages into your repo and change up the flags they pass to protoc. 

> Unfortuantely, having multiple targets outputting a go library in the same package doesn't really work.

It's fine as far as please is concerned; you just have to give them different names.

**Comment by sagikazarmark** [comment]
For the record, I've created a custom build rule that can be used to add custom go plugins: sagikazarmark/mypleasings#39

Usage:

```starlark
proto_library(
    name = "proto",
    srcs = ["my.proto"],
    languages = {
        "go": go_proto_language(
            plugins = {
                "myplugin": ":myplugin",
            },
            grpc = True,
        ),
    },
)
```

**Comment by perrydunn** [comment]
@sagikazarmark Please could you let me know if the above works with the [newer protoc-gen-go and protoc-gen-go-grpc](https://grpc.io/docs/languages/go/quickstart/#prerequisites)? Looking at the [source](https://github.com/protocolbuffers/protobuf-go/blob/master/cmd/protoc-gen-go/main.go#L45) I'm fearing not.

**Comment by sagikazarmark** [comment]
I believe it should. Don't get confused by the term "plugin": I borrowed it from somewhere (maybe Please?), but it doesn't refer to the Go generator's gRPC plugin. If you take a look at the linked PR, you'll see that enabling the `grpc` plugin will be translated into adding a new generator to the `protoc` command with the name `go-grpc`.

**Comment by perrydunn** [comment]
Thanks @sagikazarmark, your custom rule is super helpful
