### ISSUE TITLE
go vet is not part of go_test

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1706]
I'm not 100% sure if this is something that we can solve in Please (not being able to use `go list` and all), but the go test tool runs go vet under the hood now. This catches issues like wrong format string for a certain type.

Today I found an issue in our codebase where go vet yielded an error (thus causing go test to fail), but neither `plz test` nor our linter caught it (actually, it was disabled for some reason).

Again, not sure if this is something we can fix here, just wanted to point out a difference between `go test` and `go_test`. Might be useful for people in the future searching for this issue or it can serve as a reminder to add it to the documentation.

**Comment by Tatskaari** [comment]
Yeah I assume that `go vet` needs a full valid go project and can't work off an import config? I don't think Please will be able to easily replicate that. I'm surprised your linter didn't pick it up though.
