### ISSUE TITLE
Fix the download script for arm once v16 is cut

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1764]
The script at get.please.build downloads the amd version of Please on arm systems. Once we have v16 out, we can change this to download the arm version.

**Comment by linuxerwang** [comment]
I got tons of repeated errors:

```
4 errors occurred:
        * Get "https://get.please.build/third_party/python/py3/parse-1.15.0-linux_arm.whl": x509: certificate signed by unknown authority
        * Get "https://get.please.build/third_party/python/py3/parse-1.15.0.whl": x509: certificate signed by unknown authority
        * Error retrieving https://files.pythonhosted.org/packages/py3/p/parse/parse-1.15.0-py3-none-any.whl: 404 Not Found
        * Error retrieving https://files.pythonhosted.org/packages/py2.py3/p/parse/parse-1.15.0-py2.py3-none-any.whl: 404 Not Found
```

**Comment by Tatskaari** [comment]
> I got tons of repeated errors:
> 
> ```
> 4 errors occurred:
>         * Get "https://get.please.build/third_party/python/py3/parse-1.15.0-linux_arm.whl": x509: certificate signed by unknown authority
>         * Get "https://get.please.build/third_party/python/py3/parse-1.15.0.whl": x509: certificate signed by unknown authority
>         * Error retrieving https://files.pythonhosted.org/packages/py3/p/parse/parse-1.15.0-py3-none-any.whl: 404 Not Found
>         * Error retrieving https://files.pythonhosted.org/packages/py2.py3/p/parse/parse-1.15.0-py2.py3-none-any.whl: 404 Not Found
> ```

Seems like it can't find a wheel for your arch. Are you trying to bootstrap on arm? I don't know if we're going to support running all the tests on arm any time soon (or ever). You can still bootstrap please but skip running the tests with `./bootstrap.sh --skip_tests`. Perhaps we can update the script to do that automatically on architectures we don't plan on supporting those tests for.

**Comment by Tatskaari** [comment]
p.s. the only thing blocking this change is that I can't seem to get the CPU resource usage library to work. It keeps throwing unimplemented errors.

**Comment by linuxerwang** [comment]
@Tatskaari  ./bootstrap.sh --skip_tests gives the same errors (tried on v16.3.0). Thanks.

**Comment by Tatskaari** [comment]
Oh sorry, it's trying to build the pex tool as part of the bootstrap. Looks like `https://get.please.build/third_party/python/py3/parse-1.15.0.whl` exits. I wonder why your computer doesn't trust that authority. It's signed by `USERTrust RSA Certification Authority`, and the cert is valid until November. Perhaps you need to install their cert on your system.

**Comment by linuxerwang** [comment]
@Tatskaari  My linux is quite old. Adding the cert fixed the issue. Thank you so much!

**Comment by linuxerwang** [comment]
Failed at a 32/64 bits issue:
_build/google.golang.org/protobuf/internal/protobuild/build.go, line 114, column 16: constant 4294967295 overflows int
My arm machine has a 32bits cpu.
