### ISSUE TITLE
Issue with cached data from HTTP cache

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#1767]
Hello, I'm having an issue v16 and HTTP cache.

HTTP cache server is an Apache with mod_dav using container image `bytemark/webdav:2.4`.

With dir cache and HTTP cache defined, and a simple test like:

```
gentest(
    name="test",
    srcs = ["some_file"],
    test_cmd = "exit 0",
    no_test_output=True,
)
```

Results data from HTTP cache are incorrect.

Here is how to reproduce:

```
plz test //:test       # put the result in the HTTP cache
plz clean //:test && plz test //:test    # clean the local dir cache and then get the results from the HTTP cache
plz test //:test      # test is reran instead of use results in local dir cache
```

In the debug of the last test command, there is:

```
DEBUG: Rerunning //:test, results file has incorrect hash
```

**Comment by Tatskaari** [comment]
Hey! Looks like it works to some extent because the http-cache-test ci step shows it restoring results from the cahce. I tried your test locally with our HTTP cache and I got this:
```
11:09:18.162   DEBUG: Need to rebuild //:test, metadata file is missing
11:09:18.162   DEBUG: Output file plz-out/bin/.test_results_test does not exist for //:test
11:09:18.162   DEBUG: //:test: /home/jpoole/.cache/please/test/cEIFlxAjpuLHTOhjUGo5wegvhLA= doesn't exist in dir cache
11:09:18.162   DEBUG: performing request: [method GET url http://127.0.0.1:1771/704205971023a6e2c74ce863506a39c1e82f84b0]
11:09:18.166   DEBUG: Storing //:test: .test_results_test in dir cache...
11:09:18.166   DEBUG: Not re-running test //:test; got cached results.
11:09:18.167    INFO: Shutting down cache workers...
11:09:18.167   DEBUG: Shut down all cache workers
```

I suspect that the xattrs are being lost somehow. Is this something that started with v16 or do you get the same issue on v15?

**Comment by sfirmery** [comment]
Yes, the restoration of the results from the cache works for me too, on the first run after the `plz clean`.

But, if I run it another time, the test is not using the cache and I got:

```
DEBUG: Rerunning //src/api:lint, results file has incorrect hash
````

Previously, I used the v14 with grpc cache.

**Comment by Tatskaari** [comment]
Oh very sorry. Okay, can reproduce. Will get a fix out shortly.
