### ISSUE TITLE
Issue with bootstraping on apple silicon

### ISSUE THREAD

**Issue by zhong-yi-yu** [thought-machine/please#1772]
When bootstraping on apple silicon, it'll take a test on protoc and try to download protoc from source.

However, there's currently no package for `osx-aarch-_64`, and when it tries to download it, it throws out trouble and stop the whole testing process.

The specific error is down below:

```
 //third_party/proto:_protoc#download
1 error occurred:

* Error retrieving https://github.com/protocolbuffers/protobuf/releases/download/v3.15.2/protoc-3.15.2-osx-aarch_64.zip: 404 Not Found
```

**Comment by Tatskaari** [comment]
Hey! Thanks for testing this out. You can do `./bootstrap.sh --skip_tests` to skip running all tests if you just want to bootstrap Please. Come v16, there's actually an arm binary distribution of Please, which you can install off the releases page if you're just looking to install it. 

I'll try and get bootstrapping working on arm64 eventually, though I think we probably just need to wait for the protoc guys (and others) to release an arm binary. It's probably not worth the effort to figure out how to compile this from source.
