### ISSUE TITLE
`watch --run` not killing original process

### ISSUE THREAD

**Issue by tannerntannern** [thought-machine/please#1779]
First, thank you for such a nice build system!  I am new to tools like bazel, buck, pants, please, etc, but please has so far been the easiest to wrap my head around and requires less boilerplate than the others.

I am facing an issue that was possibly covered in #599, but it doesn't seem to be resolved in my testing.  My issue involves running a flask webserver and using `plz watch --run ...` for local development.  It appears that the original process isn't killed before please tries to restart it, so I get the expected "address in use" error.

I have an easy minimal reproducible example available here where I document the steps to reproduce in more detail: https://github.com/tannerntannern/plz-watch-run-flask-reprex

It's using Please 16.0.1 and my testing was done on macOS 10.15.6

**Comment by Tatskaari** [comment]
Glad you're enjoying it so far! Thanks for raising this with an example to reproduce. Looks like we thought about this, and tried to solve it, but didn't pass the context through... 

I just did a Please release today so you'll probably have to wait until next Tuesday for `16.1.0`. Apologies for the delay.
