### ISSUE TITLE
Allow junit-directory to be overridden 

### ISSUE THREAD

**Issue by thecapdan** [thought-machine/please#1802]
When running behave tests as a pex with the --in_tmp_dir flag, we are unable to retrieve the test results xml (required to be parsed downstream).

It would be nice if we could override the value set by [behave.py](https://github.com/thought-machine/please/blob/master/tools/please_pex/pex/behave.py#L29)

**Comment by dontm** [comment]
@Tatskaari any chance we might get this soon plz? 🙏

**Comment by Tatskaari** [comment]
I've raised a PR that will check the `RESULTS_FILE` env var. Is that good for you? I don't really want to introduce a flag parsing library.

**Comment by thecapdan** [comment]
as long as we can access the results, that's great. thanks
