### ISSUE TITLE
flake on build-linux-alt for unrelated changes 

### ISSUE THREAD

**Issue by RichardoC** [thought-machine/please#1811]
During build-linux-alt

glob_build_test
filegroup_not_require_test
filegroup_require_test

All failed with 
"Test failed
fork/exec /bin/bash: text file busy"

https://app.circleci.com/pipelines/github/thought-machine/please/2777/workflows/1bc75298-f547-42e1-97f1-a5597c926cc7/jobs/24322

Successful rerun
https://app.circleci.com/pipelines/github/thought-machine/please/2777/workflows/fc5ddf87-27be-408b-9125-a86deb8c5f67/jobs/24327/steps

**Comment by Tatskaari** [comment]
Yeah I've noticed this and have tried to get to the bottom of it. It happens on all the CI agents for all builds not just linux-alt. It doesn't seem like there's much we can do about it on the surface. there's some related info here:

https://discuss.circleci.com/t/aufs-related-text-file-busy-error/27648
