### ISSUE TITLE
go.mod with private repositories

### ISSUE THREAD

**Issue by windrunner99** [thought-machine/please#1812]
Hallo I am currently porting a project from make to please. I ran into a problem with a private repository being in my go.mod file. When I am trying to use the `go_module` rule it seems like the command `$TOOL mod download -x -modcacherw -json {module}@{version} | tee mod.json` in the rule does return a non json formatted error. 
For example when building the rule: 
```
go_module(
    name = "tools",
    install = [
        "cover",
        "go/...",
    ],
    module = "golang.org/x/tools",
    version = "2ae76fd1560b622911f444c1e66b70a857e1de67",
)
```

When running `plz build --shell //third_party/go:_tools\#get` and then manually running `$TOOL mod download -x -modcacherw -json golang.org/x/tools@2ae76fd1560b622911f444c1e66b70a857e1de67 | tee mod.json` I would expect something like this:
```
{
        "Path": "golang.org/x/tools",
        "Version": "v0.0.0-20180223181923-2ae76fd1560b",
        "Info": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.info",
        "GoMod": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.mod",
        "Zip": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.zip",
        "Dir": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/golang.org/x/tools@v0.0.0-20180223181923-2ae76fd1560b",
        "Sum": "h1:aWHhLrCK6M09ynxREKKzQtFDRaNECkGsnDpZxdrJlVE=",
        "GoModSum": "h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ="
}
```
But I am receiving something like this:
```
...
get https://proxy.golang.org/github.com/golang/protobuf/@v/v1.4.0-rc.1.mod
get https://proxy.golang.org/github.com/golang/protobuf/@v/v1.4.0-rc.1.mod: 200 OK (0.033s)
get https://proxy.golang.org/google.golang.org/protobuf/@v/v0.0.0-20200109180630-ec00e32a8dfd.mod
get https://proxy.golang.org/google.golang.org/protobuf/@v/v0.0.0-20200109180630-ec00e32a8dfd.mod: 200 OK (0.032s)
go: private.repository.com/my/package@v1.0.0: reading private.repository.com/my/package/go.mod at revision v1.0.0: unknown revision v1.0.0
```

In fact I can get the wanted result be deleting the go.mod file or installing one of the packages from the private repository with a custom go mod download rule and compiling it with a go_module rule. Can somebody help me with the integration of private repositories with please and maybe explain to me this interaction with go mod download? Currently running on please 16.0.1. 
I am sorry if this issue is a bit chaotic, it's my first time writing a GitHub issue.

**Comment by sagikazarmark** [comment]
The logs you see are sent to stderr. Since fetching the module fails from the proxy, there is nothing sent to stdout (I guess)

First, you will need something like #1546 then you need to figure out how to authenticate with your private repository (eg. .netrc file or SSH).

I agree that Please should help with this, but with the above info you can probably implement a custom download rule that disables the proxy (using GONOPROXY) for private packages and authenticates properly.

Hope that helps.

**Comment by windrunner99** [comment]
Thanks for your answer. Sure, I already have such a rule that downloads the code using a .netrc file and passes it to the `go_module` rule via the download field. My problem is now that every `go_module` needs this private download rule at least for building a clean project. 

I realised that when building a clean project (with clean I mean no plz-out directory included) the go.mod file in the plz-out directory is first created when successfully running a build command. This results in the behaviour of plz taking my project go.mod file ( with all my public and private dependencies ) for downloading the the module and checking every single dependency what is extremely slow. In comparison, if I manually add a plz-out directory with the please-ignore go.mod file in it and run `plz build` the problem disappears because go is using the please-ignore go.mod file for downloading which is empty and therefor does not check the private repositories.

You can also see this when building the [please server](https://github.com/thought-machine/please-servers) project. The first plz build command almost takes 5 minutes for me. Where as when I'm adding the please-ignore go.mod myself it takes roughly one minute. 

Is this an intended behaviour or a bug? It seems rather useless using the project go.mod file when building with please. Currently the `go_mod_download` rule has two different behaviours depending on the presence of a go.mod in the plz-out directory. My suggestion would be to always add the please-ignore go.mod file when initialising the plz-out directory.

**Comment by windrunner99** [comment]
My workaround would be not to add a plz alias `init` that add a plz-out folder and the please-ignore go.mod file that must be run before running `plz build`. 
But I think we can agree that this is very laborious.

**Comment by sagikazarmark** [comment]
In theory, the `go mod download` command should not take the go.mod file into account when downloading a specific version of a module since it's primary purpose is populating the cache.

Also, I believe that the go.mod file should be created early on. If that's not the case, then it's probably a bug. But even then, go mod download with a specific module should not take the project go.mod file into account.

**Comment by Tatskaari** [comment]
> Is this an intended behaviour or a bug? 

This is a bug for sure! That go.mod file isn't meant to affect builds at all. It's just there to stop tooling like IDEs and linters  looking in plz-out. I think we should be creating a go.mod in the `go_mod_download()` build rule to avoid this. 

> I already have such a rule that downloads the code using a .netrc file

Oh interesting. Perhaps we can do something to facilitate this in Please. I guess it's expecting to find this in `$HOME` so we which is set to the root of the build dir. We would need to somehow put that there... not sure how that would look configuration wise though. 

> My problem is now that every go_module needs this private download rule at least for building a clean project.

You could write a custom `go_module()` rule that wraps your private download rule and passes it to our `go_module()` rule so you don't have to do this every time.

**Comment by sagikazarmark** [comment]
> > My problem is now that every go_module needs this private download rule at least for building a clean project.
> 
> You could write a custom `go_module()` rule that wraps your private download rule and passes it to our `go_module()` rule so you don't have to do this every time.

.netrc and GO* env var support should be enough IMHO

**Comment by windrunner99** [comment]
> > My problem is now that every go_module needs this private download rule at least for building a clean project.
> 
> You could write a custom `go_module()` rule that wraps your private download rule and passes it to our `go_module()` rule so you don't have to do this every time.

Sure I could do this as well, but it still does effect build time on an empty project. 
I am just very confused that you are both telling me that the go.mod file does not have an impact on a `go mod download ` command with a specific module specified.
Because when I again run `plz build --shell //third_party/go:_tools\#get` like in the issue, this time with an empty go.mod file in plz-out, and running 
`$TOOL mod download -x -modcacherw -json golang.org/x/tools@2ae76fd1560b622911f444c1e66b70a857e1de67 | tee mod.json` I get exactly what I want with `go mod` only requesting the /x/tools proxy entires: 
```
bash-3.2$  $TOOL mod download -x -modcacherw -json golang.org/x/tools@2ae76fd1560b622911f444c1e66b70a857e1de67 | tee mod.json
# get https://proxy.golang.org/golang.org/x/tools/@v/2ae76fd1560b622911f444c1e66b70a857e1de67.info
# get https://proxy.golang.org/golang.org/x/tools/@v/2ae76fd1560b622911f444c1e66b70a857e1de67.info: 200 OK (0.232s)
{
        "Path": "golang.org/x/tools",
        "Version": "v0.0.0-20180223181923-2ae76fd1560b",
        "Info": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.info",
        "GoMod": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.mod",
        "Zip": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.zip",
        "Dir": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/golang.org/x/tools@v0.0.0-20180223181923-2ae76fd1560b",
        "Sum": "h1:aWHhLrCK6M09ynxREKKzQtFDRaNECkGsnDpZxdrJlVE=",
        "GoModSum": "h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ="
}

```
Running the save command with for example the `github.com/rs/zerolog v1.21.0` module in this go.mod I get:
```
bash-3.2$  $TOOL mod download -x -modcacherw -json golang.org/x/tools@2ae76fd1560b622911f444c1e66b70a857e1de67 | tee mod.json
# get https://proxy.golang.org/github.com/rs/zerolog/@v/v1.21.0.mod
# get https://proxy.golang.org/github.com/rs/zerolog/@v/v1.21.0.mod: 200 OK (0.216s)
# get https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.mod
# get https://proxy.golang.org/github.com/coreos/go-systemd/@v/v0.0.0-20190321100706-95778dfbb74e.mod
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.1.0.mod
# get https://proxy.golang.org/github.com/rs/xid/@v/v1.2.1.mod
# get https://proxy.golang.org/github.com/coreos/go-systemd/@v/v0.0.0-20190321100706-95778dfbb74e.mod: 200 OK (0.018s)
# get https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.mod: 200 OK (0.018s)
# get https://proxy.golang.org/github.com/rs/xid/@v/v1.2.1.mod: 200 OK (0.018s)
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.1.0.mod: 200 OK (0.018s)
# get https://proxy.golang.org/golang.org/x/sync/@v/v0.0.0-20201020160332-67f06af15bc9.mod
# get https://proxy.golang.org/github.com/yuin/goldmark/@v/v1.2.1.mod
# get https://proxy.golang.org/golang.org/x/mod/@v/v0.3.0.mod
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20201021035429-f5854403a974.mod
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20210119212857-b64e53b001e4.mod
# get https://proxy.golang.org/golang.org/x/xerrors/@v/v0.0.0-20200804184101-5ec99f83aff1.mod
# get https://proxy.golang.org/golang.org/x/mod/@v/v0.3.0.mod: 200 OK (0.022s)
# get https://proxy.golang.org/github.com/yuin/goldmark/@v/v1.2.1.mod: 200 OK (0.022s)
# get https://proxy.golang.org/golang.org/x/sync/@v/v0.0.0-20201020160332-67f06af15bc9.mod: 200 OK (0.022s)
# get https://proxy.golang.org/golang.org/x/xerrors/@v/v0.0.0-20200804184101-5ec99f83aff1.mod: 200 OK (0.022s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20210119212857-b64e53b001e4.mod: 200 OK (0.022s)
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20201021035429-f5854403a974.mod: 200 OK (0.022s)
# get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20191011191535-87dc89f01550.mod
# get https://proxy.golang.org/golang.org/x/xerrors/@v/v0.0.0-20191011141410-1b5146add898.mod
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20191119224855-298f0cb1881e.mod
# get https://proxy.golang.org/golang.org/x/xerrors/@v/v0.0.0-20191011141410-1b5146add898.mod: 200 OK (0.018s)
# get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20191011191535-87dc89f01550.mod: 200 OK (0.018s)
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20191119224855-298f0cb1881e.mod: 200 OK (0.018s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20200930185726-fdedc70b468f.mod
# get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20200622213623-75b288015ac9.mod
# get https://proxy.golang.org/golang.org/x/text/@v/v0.3.3.mod
# get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20200622213623-75b288015ac9.mod: 200 OK (0.023s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20200930185726-fdedc70b468f.mod: 200 OK (0.023s)
# get https://proxy.golang.org/golang.org/x/text/@v/v0.3.3.mod: 200 OK (0.024s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20190412213103-97732733099d.mod
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20190404232315-eb5bcb51f2a3.mod
# get https://proxy.golang.org/golang.org/x/sync/@v/v0.0.0-20190423024810-112230192c58.mod
# get https://proxy.golang.org/golang.org/x/xerrors/@v/v0.0.0-20190717185122-a985d3407aa7.mod
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20190620200207-3b0461eec859.mod
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20190404232315-eb5bcb51f2a3.mod: 200 OK (0.021s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20190412213103-97732733099d.mod: 200 OK (0.021s)
# get https://proxy.golang.org/golang.org/x/sync/@v/v0.0.0-20190423024810-112230192c58.mod: 200 OK (0.014s)
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20190620200207-3b0461eec859.mod: 200 OK (0.017s)
# get https://proxy.golang.org/golang.org/x/xerrors/@v/v0.0.0-20190717185122-a985d3407aa7.mod: 200 OK (0.018s)
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180917221912-90fa682c2a6e.mod
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180917221912-90fa682c2a6e.mod: 200 OK (0.014s)
# get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20190308221718-c2843e01d9a2.mod
# get https://proxy.golang.org/golang.org/x/text/@v/v0.3.0.mod
# get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20190308221718-c2843e01d9a2.mod: 200 OK (0.016s)
# get https://proxy.golang.org/golang.org/x/text/@v/v0.3.0.mod: 200 OK (0.017s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20190215142949-d0b11bdaac8a.mod
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20190215142949-d0b11bdaac8a.mod: 200 OK (0.014s)
# get https://proxy.golang.org/golang.org/x/tools/@v/2ae76fd1560b622911f444c1e66b70a857e1de67.info
# get https://proxy.golang.org/golang.org/x/tools/@v/2ae76fd1560b622911f444c1e66b70a857e1de67.info: 200 OK (0.017s)
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.mod
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.mod: 200 OK (0.016s)
# get https://proxy.golang.org/sumdb/sum.golang.org/supported
# get https://proxy.golang.org/sumdb/sum.golang.org/supported: 410 Gone (0.019s)
# get https://sum.golang.org/lookup/golang.org/x/tools@v0.0.0-20180223181923-2ae76fd1560b
# get https://sum.golang.org/lookup/golang.org/x/tools@v0.0.0-20180223181923-2ae76fd1560b: 200 OK (0.087s)
# get https://sum.golang.org/tile/8/0/x001/213
# get https://sum.golang.org/tile/8/1/065.p/245
# get https://sum.golang.org/tile/8/1/004
# get https://sum.golang.org/tile/8/0/x016/885.p/70
# get https://sum.golang.org/tile/8/2/000.p/65
# get https://sum.golang.org/tile/8/0/x001/213: 200 OK (0.024s)
# get https://sum.golang.org/tile/8/1/065.p/245: 200 OK (0.031s)
# get https://sum.golang.org/tile/8/1/004: 200 OK (0.031s)
# get https://sum.golang.org/tile/8/0/x016/885.p/70: 200 OK (0.032s)
# get https://sum.golang.org/tile/8/2/000.p/65: 200 OK (0.032s)
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.zip
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.zip: 200 OK (0.057s)
{
        "Path": "golang.org/x/tools",
        "Version": "v0.0.0-20180223181923-2ae76fd1560b",
        "Info": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.info",
        "GoMod": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.mod",
        "Zip": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/cache/download/golang.org/x/tools/@v/v0.0.0-20180223181923-2ae76fd1560b.zip",
        "Dir": "/path/to/project/plz-out/tmp/library/go/_tools#get._build/go/pkg/mod/golang.org/x/tools@v0.0.0-20180223181923-2ae76fd1560b",
        "Sum": "h1:aWHhLrCK6M09ynxREKKzQtFDRaNECkGsnDpZxdrJlVE=",
        "GoModSum": "h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ="
}

```
So obviously, without knowing what it actually does, `go mod` is requesting every single module in the go.mod file and it dependencies. This is what is what takes ages when using the project go.mod file because a large dependency tree results in ages of fetch time. And then this is also  running concurrently in every single download rule.
I would appreciate if somebody tells me if there is a misconception on my side.

**Comment by Tatskaari** [comment]
I didn't say it didn't ;P 

It seems that it is looking for a go.mod file and it will indeed try and download everything there. I just meant that the `go.mod` file in `plz-out` wasn't meant to fix this. It was there solely to stop the IDE (and other tools) poking their noses into `plz-out` when they shouldn't.

The PR I opened yesterday makes the `go_mod_download()` rule create a dummy `go.mod` which should solve that problem. 

> .netrc and GO* env var support should be enough IMHO

yeah I'm just trying to figure out how we might make the .netrc available to the rule. I don't think this is go specific. Seems like something we'd want to support across the BUILD system. 

It would be reasonable to set the GO* env variables based on the `.plzconfig` in `_set_go_env()` though.
