### ISSUE TITLE
error: unknown symbol

### ISSUE THREAD

**Issue by WPRobson** [thought-machine/please#1813]
Have been trying to set up please to use but keep getting "error: Unknown symbol" even when trying to run the examples found at https://github.com/thought-machine/please-examples. even running the most basic of BUILD files throws up this error I am trying to run this on WSL2.

![plz unknow symbol](https://user-images.githubusercontent.com/9500236/118422565-5d933480-b6bb-11eb-8c99-9daed357b72f.PNG)

![plz unknow symbol2](https://user-images.githubusercontent.com/9500236/118422761-be227180-b6bb-11eb-957e-6cdda9508f4a.PNG)

**Comment by Tatskaari** [comment]
My best guess is it's a `\r`. Did you close this with the windows version of git? I think that can re-write files to have `\r\n` when checked out and then set it back to `\n` when you check them in. I think I'll make the interpreter just ignore the `\r`, but in the meantime, you can try stripping them out. That should fix your issue.

**Comment by peterebden** [comment]
Maybe we should teach the parser about `\r` if this is going to come up.

**Comment by Tatskaari** [comment]
> Maybe we should teach the parser about `\r` if this is going to come up.

Yup! On it ;)

**Comment by WPRobson** [comment]
Yeah can confirm it was to with line endings! cloned the examples repo with the linux version of git and that worked much better.  Sorry about that, thanks for the help :)
