### ISSUE TITLE
plz query changes doesn't work as expected for a filegroup in root directory

### ISSUE THREAD

**Issue by paulannetts** [thought-machine/please#1821]
Tested on 15.7.1, 16.0.1 and 16.1.0-beta3, MacOS Big Sur and Ubuntu 20.04.

Repro:
1. create a file in the please root, say "important_file_1.txt".
2. Add a BUILD file to pull this into a `filegroup`

```
filegroup(
    name = "important_1",
    srcs = [
        "./important_file_1.txt",
    ]
)
```

3. type `plz query changes important_file_1.txt`

Expected:
Would return `//:important_1`

Actual:
Returns no output

This works in a sub-directory, but not if the file is in the root directory.

**Comment by tiagovtristao** [comment]
Thanks for raising @paulannetts.

Fixed in https://github.com/thought-machine/please/pull/1855
