### ISSUE TITLE
Bug: plz build gotk3 raises error

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#1822]
Ubuntu 20.04.2 LTS
go version go1.16.3 linux/amd64
Please version 16.0.1

Traditional "go install" works fine, but "plz build" fails.

To help debug, I created a github repo: https://github.com/linuxerwang/plz-gotk3.

```
$ plz build //third_party/go:gotk3
...
please_go install -> ln third_party/go/gotk3/glib/glib_extension.go third_party/go/gotk3/glib/glib_since_2_64.go third_party/go/gotk3/glib/gfile.go.h third_party/go/gotk3/glib/giostream.go.h third_party/go/gotk3/glib/glib.go.h third_party/go/gotk3/glib/glib_since_2_44.go.h third_party/go/gotk3/glib/glib_since_2_46.go.h third_party/go/gotk3/glib/gpermission.go.h third_party/go/gotk3/glib/gvariant.go.h third_party/go/gotk3/glib/gvarianttype.go.h _build/github.com/gotk3/gotk3/glib
please_go install -> (cd third_party/go/gotk3/glib; /home/ubuntu/plz-gotk3/plz-out/bin/third_party/go/toolchain/bin/go tool cgo -objdir /_build/github.com/gotk3/gotk3/glib application.go connect.go gaction.go gactiongroup.go gactionmap.go gasyncresult.go gbinding.go gcancellable.go gfile.go gicon.go giostream.go glib.go glib_export.go glib_since_2_42.go glib_since_2_44.go glib_since_2_46.go glistmodel.go gmain_context.go gpermission.go gsimpleactiongroup.go gsource.go gvariant.go gvariantbuilder.go gvariantclass.go gvariantdict.go gvariantiter.go gvarianttype.go list.go menu.go notifications.go settings.go settings_backend.go settings_schema.go settings_schema_source.go slist.go)
/home/ubuntu/plz-gotk3/plz-out/tmp/third_party/go/_gotk3#a_rule._build/third_party/go/gotk3/glib/application.go, line 3, column 11: fatal error: gio/gio.h: No such file or directory
    3 | // #include <gio/gio.h>
      |           ^~~~~~~~~~~
compilation terminated.
2021/05/20 22:41:17 exit status 1
```

Note that gio.h exists:

```sh
$ ll /usr/include/glib-2.0/gio/gio.h 
-rw-r--r-- 1 root root 5646 Oct  1  2020 /usr/include/glib-2.0/gio/gio.h
```

and

```sh
$ pkg-config --libs --cflags gio-2.0 glib-2.0 gobject-2.0                          
-pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lgio-2.0 -lgobject-2.0 -lglib-2.0
```

and cgo pkg-config seems correctly set (since "go install" can build without issue):
https://github.com/gotk3/gotk3/blob/master/glib/glib.go#L21

Also note that if everything works fine gotk3 compilation is very slow (lots of cgo, over 10 minutes), so please be patient.

Can someone please help? Thanks!

**Comment by Tatskaari** [comment]
Ah, it doesn't look like we're respecting the package config. I thought the cflags on the `build.Package` struct would include these... turns out that's not the case. Will see if I can get this to compile and get it into a release next week for you.

**Comment by Tatskaari** [comment]
I'm able to build their hello gotk3 example however I want a smaller module to add a test for pkg config. Will try and find one on Monday unless you happen to know of any?

**Comment by linuxerwang** [comment]
> I'm able to build their hello gotk3 example however I want a smaller module to add a test for pkg config. Will try and find one on Monday unless you happen to know of any?

Great news. No, I don't smaller modules which uses gotk3, please we can create one based on the gotk3 exxamples.
