### ISSUE TITLE
Typo in configuration docs (RcpUrl)

### ISSUE THREAD

**Issue by fwip** [thought-machine/please#1824]
There's a small typo in the documentation for the config settings:

```RcpUrl
Base URL of the RPC cache.
Not set to anything by default which means the cache will be disabled.
```

https://github.com/thought-machine/please/blob/d8ecf68d942fc1b8897726901d2be056e0a4ebc1/docs/config.html#L687

`RcpUrl` should probably be `RpcUrl.`

**Comment by Tatskaari** [comment]
These config options don't actually exist anymore.. I've removed them in #1838
