### ISSUE TITLE
Shellchecking the `pleasew` file

### ISSUE THREAD

**Issue by eankeen** [thought-machine/please#1827]
Many people have [shellcheck](https://www.shellcheck.net) plugins within their editors, which show shellcheck linting results directly in the editor. In the case of `pleasew`, parts of the script are a bit hard to read due to the linting tips / warnings:

![image](https://user-images.githubusercontent.com/24364012/119426896-9bb2d880-bcf9-11eb-8fa5-8556c563c139.png)

I propose changing the `pleasew` to get rid of these annotations by:

- replacing backtick subshell notation with `"$()"` (although these aren't technically equivalent, there is all but one place where adding the quotes would hurt because word splitting would occur anyways (the exception being the last for loop)

- adding `shellcheck disable=SC2086` before every line that `$PLZ_ARGS` wordsplits when the exec builtin is used

- adding `shellcheck disable=SC2045` before the last for loop (`for x in $(ls "$DIR"); do`). Of course a fix could be made since "iteration over ls output is fragile", but i'd rather not make any functional changes to the script

Thoughts?
Edwin

**Comment by Tatskaari** [comment]
We don't use shellcheck so I don't really want to start adding linter hints for it to our code base. What are the lint warnings from shellcheck? Are they legitimate? I'd be happy to accept a PR to migrate to `$()` if it's recommended and/or functionally equivalent.

**Comment by eankeen** [comment]
Ah, I suppose it would make sense not to add linter hints in this case then

Out of the three types of linter warnings, 2 are legitimite and 1 is a false positive

1. False positive

Example of false positive is on line 25

```sh
exec "$TARGET" ${PLZ_ARGS:-} "$@"
```

Lint code is [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) - of course here the word splitting is intentional for the arguments

2. Legitimate 1

Example of this is on line 11, lint code is [SC2006](https://github.com/koalaman/shellcheck/wiki/SC2006)

```sh
LOCATION=`grep -i "^location" .plzconfig 2>/dev/null | cut -d '=' -f 2 | tr -d ' '`
```

Replacing backticks with `$()` would make no difference in behavior and remove the strikethrough

3. Legitimate 2

For the last for loop
```sh
for x in $(ls "$DIR"); do
    ln -sf "${DIR}/${x}" "$LOCATION"
done
```

**Comment by Tatskaari** [comment]
It's just `pleasew` in the root of the repo. The one in assets is just so we can build Please with go for bootstrapping. 

Yeah, we shouldn't be using tabs in that file i don't think. Thanks :)

**Comment by eankeen** [comment]
I have made a PR with the changes, lemmie know if I should make any other changes :)

**Comment by Tatskaari** [comment]
Thanks :) There's some flakiness on the java toolchain downloads for no good reason...
