### ISSUE TITLE
Docker image building

### ISSUE THREAD

**Issue by matthen** [thought-machine/please#1851]
I would be interested to see some of the techniques people use to build docker images including binaries build by please. In particular strategies that make use of the build cache.

One technique I have used is to use `docker run` to build a binary in the correct environment, with a directory cache mounted to the docker container. Then you can do a docker build that copies in the resulting binary.

Another technique is to use multi-stage builds. The first build copies the source code in, and builds the binary. The second one just copies the binary from the first build. But in this case it is difficult to make use of the cache.

**Comment by Tatskaari** [comment]
Sorry for the very slow reply. The issues on the Pleasings repo got lost. I've just set up some better tooling to try and collate issues across all our repos so this won't happen going forward. 

There's a number of approaches people have taken for this. As you're aware the standard docker images are not incremental. 

The ideal solution is to implement "distroless" images. These build up OCI containers from scratch without using containerisation. Essentially, you just copy files into a tarball in the correct format. This is the approach we use internally here at Thought Machine. TCN have open sourced their approach to this here: https://github.com/tcncloud/please.containers

The next best thing is the podman/buildah approach. This gets us some of the way to incremental builds but isn't as straight forward as the above approach. The advantage of this is that you don't have to abandon Dockerfile's. The rules can be found here: https://github.com/thought-machine/pleasings/tree/master/oci
