### ISSUE TITLE
"definitions" of go_binary is broken when other build tags exist

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#1853]
@Tatskaari  I believe this is caused by the fix for #1832.

```
$ plz --version
Please version 16.1.0
```

With this fix I can build gotk3, but as long as it's in "deps",  the "definitions" in go_binary() will not set the versions correctly. Please see this example: https://github.com/linuxerwang/plz-gotk3. It runs with the correct version printed, but in this file: https://github.com/linuxerwang/plz-gotk3/blob/master/cmd/BUILD.plz, if you un-comment the line with "//third_party/go:gotk3", then version "1.0.0" will not be set to version.Version variable, thus it prints "DEVELOPMENT" instead of "1.0.0".

Again, gotk3 needs about 10 minutes to build, so please be patient.

Thanks!

**Comment by Tatskaari** [comment]
Sorry about this. It seems we don't handle both ld flags and definitions on the same target. I'll get this released in the next Please release. I should have that out in a couple days.
