### ISSUE TITLE
Codegen & symlink failing

### ISSUE THREAD

**Issue by raphaelfff** [thought-machine/please#1879]
Having a rule with a `codegen` label, being a dep of an another rule, leads to the following warning:

    10:23:45.146 WARNING: Symlink package/proto/proto.pb.go has an absolute target /ws/plz-out/gen/package/proto/proto.pb.go, that will likely be broken later

That I think is related to the fact that the build is failing with:

    Error preparing sources for //package:_mod#dl: symlink /ws/plz-out/gen/package/proto/proto.pb.go plz-out/tmp/package/_mod#dl._build/package/proto/proto.pb.go: file exists

**Comment by raphaelfff** [comment]
To add a bit more details, i think its due to the file being caught by a `glob('**/*')` (because it has been linked because it has the `codegen` label), and provided as an output of the rule generating it...

**Comment by Tatskaari** [comment]
Hi! Yeah that will do it. I'm thinking about adding some xattrs to the generated symlinks so that glob can exclude them automatically.

**Comment by raphaelfff** [comment]
Ahhh, i ve been scratching my head on this one for a couple days now... I would say that's actually bug a bug more than an enhancement, that actually prevents from using please...

**Comment by raphaelfff** [comment]
Actually, i think the rule for symlink should be: If a the file already exist, ignore if its the same source or if the link points to the same location

**Comment by raphaelfff** [comment]
Not stale

**Comment by Tatskaari** [comment]
Oops sorry for not updating this issue. This was fixed by #2052
