### ISSUE TITLE
`plz tool lps` dies with a segmentation fault

### ISSUE THREAD

**Issue by bmustiata** [thought-machine/please#1889]
Happens on version: 16.1.1

Steps to reproduce:
1. create an empty folder
2. `plz init`
3. `plz tool lps`

Trying to run it with logs, doesn't yield much more:

```
23:20:31.617   DEBUG: Attempting to read config from /etc/please/plzconfig...
23:20:31.617   DEBUG: Attempting to read config from /etc/xdg/xdg-xfce/plzconfig...
23:20:31.617   DEBUG: Attempting to read config from /etc/xdg/plzconfig...
23:20:31.617   DEBUG: Attempting to read config from /etc/xdg/plzconfig...
23:20:31.617   DEBUG: Attempting to read config from /home/raptor/.config/please/plzconfig...
23:20:31.617   DEBUG: Attempting to read config from .plzconfig...
23:20:31.618   DEBUG: Read config from .plzconfig
23:20:31.618   DEBUG: Attempting to read config from .plzconfig_linux_amd64...
23:20:31.618   DEBUG: Attempting to read config from .plzconfig.local...
Segmentation fault
```

**Comment by tiagovtristao** [comment]
Hi @bmustiata, I've reproduced the steps a few times and it doesn't die with a segfault. My logs are very similar to yours:

```
11:31:00.105   DEBUG: Attempting to read config from /etc/please/plzconfig...
11:31:00.106   DEBUG: Read config from /etc/please/plzconfig
11:31:00.106   DEBUG: Attempting to read config from /etc/xdg/xdg-ubuntu/plzconfig...
11:31:00.106   DEBUG: Attempting to read config from /etc/xdg/plzconfig...
11:31:00.106   DEBUG: Attempting to read config from /home/ttristao/.config/please/plzconfig...
11:31:00.106   DEBUG: Read config from /home/ttristao/.config/please/plzconfig
11:31:00.106   DEBUG: Attempting to read config from .plzconfig...
11:31:00.106   DEBUG: Read config from .plzconfig
11:31:00.106   DEBUG: Attempting to read config from .plzconfig_linux_amd64...
11:31:00.106   DEBUG: Attempting to read config from .plzconfig.local...
```

**Comment by Tatskaari** [comment]
Please will log out the stack trace in `plz-out/log/build.log`. Perhaps we can get  lsp to log similarly?

**Comment by bmustiata** [comment]
Ok, so it seems it was some broken `python` installation that was existing in my `/usr/local/`. Strangely enough, I was only able to connect the dots when trying to locally build `please`, and getting a bunch of errors like this:

```
    //third_party/python:_scipy#srcs                                                                   
Error building target //third_party/python:_scipy#srcs: exit status 2                                  
                                                                                                       
Usage:                                                                                                 
  /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...        
  /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...         
  /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...                                 
  /usr/bin/python3 -m pip install [options] [-e] <local project path> ...                              
  /usr/bin/python3 -m pip install [options] <archive url/path> ...                                     
                                                                                                       
no such option: --system                                                                               
```

To be honest some stack trace would have been nice to try to tell me what's going on.

**Comment by Tatskaari** [comment]
> Ok, so it seems it was some broken `python` installation that was existing in my `/usr/local/`. Strangely enough, I was only able to connect the dots when trying to locally build `please`, and getting a bunch of errors like this:
> 
> ```
>     //third_party/python:_scipy#srcs                                                                   
> Error building target //third_party/python:_scipy#srcs: exit status 2                                  
>                                                                                                        
> Usage:                                                                                                 
>   /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...        
>   /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...         
>   /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...                                 
>   /usr/bin/python3 -m pip install [options] [-e] <local project path> ...                              
>   /usr/bin/python3 -m pip install [options] <archive url/path> ...                                     
>                                                                                                        
> no such option: --system                                                                               
> ```
> 
> To be honest some stack trace would have been nice to try to tell me what's going on.

Looking at your logs, it seems that Please was the thing that repotted the segfault... I initially thought it was the LSP logs we were looking at. 

Please does catch panics and repots the stack trace as best it can. I have no idea how it could have failed so bad that even the go runtime couldn't recover. If you can provide some more information that might help us understand how passing the `--system` flag to pip caused a segfault, I would be happy to try and improve logging around that. 

I'll close this issue for now though.

**Comment by bmustiata** [comment]
I don't know what was going on, since it makes not a lot of sense.

It seems the `pip` module somehow was the one from a custom Python 2 installation (I don't have any reasonable explanation of how, and why). It seems the `--system` flag isn't available on Python 2's pip. So even if the execution happened with `python3` something went downhill and the `pip` from Python 2 was used. Since `plz` is statically linked, my theory is that there's some wrong error handling in `plz`, so when `pip` dies spectacularly this causes the segfault.

I hope that helps.
