### ISSUE TITLE
Please should make sure that two rules don't output the same path

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#1939]
Things like this should not be prossible:
https://github.com/thought-machine/please/pull/1934

NB: this might only be a problem for filegroups. 

Please should throw an error if it sees that two rules would output to the same location in plz-out. We might have to do this at build time as we need to account for dynamic outputs. 

Another related issue is when one rule outputs into the same path twice:

```
outs = ["foo", "foo/bar"]
```

In this case we should make sure we process the output `foo` first to avoid nuking `foo/bar` when we output it.

**Comment by tiagovtristao** [comment]
Another similar scenario is highlighted below:

```python
genrule(
    name = "test",
    cmd = "true",
    deps = [                     
        ":filegroup",                   
        ":genrule",                           
    ]       
)                                                    
genrule(
    name = "genrule",
    cmd = [
        "mkdir $OUTS",  
    ],                               
    outs = ["src"],                                              
)
filegroup(
    name = "filegroup",  
    srcs = glob(["src/**"]),
)
```

What's happening here is that `genrule` is deleting `src` directory in out while `filegroup` is trying to prepare from it. The directory deletion is happening as the old and new hashes seem to differ.

A warning/error message should be displayed to the user in theses cases.

**Comment by tiagovtristao** [comment]
A couple of known issues related to this issue were fixed in https://github.com/thought-machine/please/pull/1816. Closing this for now.
