### ISSUE TITLE
impure build target

### ISSUE THREAD

**Issue by aav** [thought-machine/please#1979]
Is there a way to create a target, which is, so to say, impure. By impure, I mean that it depends not only on its inputs but also on something external and stateful. For example on the clock.

In other words, I would like to have a target that has no input, and produces a file, containing the current time. I would write something like this:

`genrule(
    name = "timestamp",
    out = "timestamp.txt",
    cmd = "echo $(date --iso-8601=seconds) > $OUT"
)`

It works great for the first time. But in subsequent runs it's doesn't produce a new result. 

Perhaps it is possible to disable caching for a specific target?

**Comment by Tatskaari** [comment]
No I'm afraid not. If there's no change in the input, Please doesn't know when to rebuild the target so would have to build it every time. This probably isn't what you want. Is there a more specific use-case you have in mind for this? Perhaps there's another more idiomatic way?

**Comment by aav** [comment]
Yes, it's clear that such a target would build every time. The use-case is simple - I want to include build a build timestamp, every time I do the build. So even, if nothing has been changed - I may want to re-run certain parts of the build (those, which depend on a timestamp target).

**Comment by aav** [comment]
I found a way to pass a variable to a build process.

`BUILD_TIMESTAMP=$(date --iso-8601=seconds) plz build //buildinfo:generate`
