### ISSUE TITLE
Installation on plain ubuntu 16.04 (./bootstrap.sh)

### ISSUE THREAD

**Issue by mindreframer** [thought-machine/please#199]
First of all: `please` looks awesome! 
It is just that installation process to develop `please` is kinda involved...

After spending some time assembling all the required dependencies on plain Ubuntu I feel stuck... 

I have also tried to reproduce the .travis.yml env, but still this fails with different problems... 

Is there any "blessed" bash script / docker image, that would produce a working consistent environment to build `please`? That would be awesome! 

Error Stacktrace: 

https://gist.github.com/mindreframer/23fd6bddbfaacf4bc84ee43e9be6e88c

![screen shot 2017-04-13 at 14 35 23](https://cloud.githubusercontent.com/assets/1232/25004823/7f25a1c8-2056-11e7-900d-66d566924ee7.png)

**Comment by peterebden** [comment]
Thanks! There is not a blessed docker image but it's a good idea, as you say there's a fair set of dependencies (Go / Python / Java / protobufs...). I will try to rustle something up for it!

**Comment by mindreframer** [comment]
@peterebden thx for the response! Really looking forward to it! 

Another question: 
- would you be interested if I contribute a small example project with multiple Go apps / services, that compiles with plz, has some unit tests, integration tests and works properly within off-the-shelf editors (Sublime Text / Atom / Visual Studio Code)? I think a small focussed example repo would help beginners to evaluate `please`. 

Also I am a bit surprised how little promotion happens on the interwebs for `please`, I monitor that space quite actively and was really surprised to find `please` in search results. Maybe I suggest following things to improve discoverability: 

- more word combinations with "monorepo", "trunk based development", "reproducible builds" in the docs
- entry here: https://en.wikipedia.org/wiki/List_of_build_automation_software
- a dedicated twitter account with some tweets targeting https://twitter.com/monorepi, https://twitter.com/bazelbuild, https://twitter.com/pantsbuild
- established hashtag( #please is not really descriptive and easy to google, maybe #pleasebuild ?) 
- dedicated github team (github.com/pleasebuild) + all the satellite projects

Of course this all assuming you want this project to get a little more popular. As I have understood, your fearless leader Paul does not approve the time dedicated to plz 😝 . 

Cheers and have a nice day! 
Roman

**Comment by peterebden** [comment]
I've added an example Dockerfile showing how to set up Ubuntu for plz. It doesn't shed a lot of light into your problem earlier though unfortunately - looks like that's a python2 / python3 mismatch?

I'll set up a Docker repo for it at some point, hopefully we'll add more images over time.

> would you be interested if I contribute a small example project with multiple Go apps / services, that compiles with plz, has some unit tests, integration tests and works properly within off-the-shelf editors (Sublime Text / Atom / Visual Studio Code)? I think a small focussed example repo would help beginners to evaluate please.
Yes, definitely!
I have seen your comments on `please-examples`, but not had a chance to look into it yet. Code completion is definitely something we could do more on...

> Of course this all assuming you want this project to get a little more popular. 
We do (the boss has given up complaining about it now!), just lacking a bit of time really. Thanks for the suggestions though, they sound good!

**Comment by mindreframer** [comment]
@peterebden Glad to hear that you have green light to continue development on `please`! 

I have started a small example project here : https://github.com/mindreframer/please-go-example. It feels more like a hack, than properly recommended project structure though... 

How do you guys deal with it? Do you give up on intellisense completely?

**Comment by Tatskaari** [comment]
Just closing off some old issues. The installation process is much simpler now.
