### ISSUE TITLE
Test upload does not have a timeout

### ISSUE THREAD

**Issue by fische** [thought-machine/please#1996]
The HTTP call in [uploadResults](https://github.com/thought-machine/please/blob/master/src/test/xml_results.go#L439-L469) does not have a timeout set, meaning that it won't error if the connection works but the HTTP handler on the server does not return a response. The non-interactive output with remote execution is also very confusing as it only shows `0 workers busy`:
```
$ nc -l -p 12345 &
$ PLZ_OVERRIDES=test.upload:http://localhost:12345 plz test --profile remote -p -v 2 --colour :test 
11:53:21.069  NOTICE: Build running for 10s, 897 / 898 tasks done, 0 workers busy
11:53:31.070  NOTICE: Build running for 20s, 897 / 898 tasks done, 0 workers busy
```

**Comment by Tatskaari** [comment]
Fixed by #2008
