### ISSUE TITLE
WIP: example project structure for golang

### ISSUE THREAD

**Issue by mindreframer** [thought-machine/please#202]
https://github.com/mindreframer/please-go-example

Autocompletion on generated artefacts (plz-out/gen/proto/kitten.pb.go) is not working yet. Any suggestions on this? 

Besides: this is for sure not the most flexible setup (polyglot / etc), are there any recommended guidelines how to keep editors/IDEs happy? 

Best, 
Roman

**Comment by agenticarus** [comment]
This should now be addressed by the addition of `plz-out/go` which provides a more traditional go directory structure.
