### ISSUE TITLE
Proxy support in called commands

### ISSUE THREAD

**Issue by nimish** [thought-machine/please#205]
Unfortunately I have to live behind a corporate proxy, which means that the commands that have to traverse that proxy need to be aware of it.

Normall just setting HTTP_PROXY/http_proxy should be enough in the environment, but please doesn't pass it through (https://github.com/thought-machine/please/blob/master/src/core/build_env.go)

Pip supports a `--proxy` but some other tools don't.

**Comment by peterebden** [comment]
Makes sense, can take a look sometime; it's not really difficult but will need to be passed through to a few separate sub-tools. Hopefully most things can pick it up from an env var so most build rules won't need to be aware.
