### ISSUE TITLE
`go_module`'s `name` is currently required to match that of the produced binary

### ISSUE THREAD

**Issue by tiagovtristao** [thought-machine/please#2055]
At the moment, `name` has to match the binary filename produced when the package is installed, otherwise the rule will fail. If the `name` wasn't `dlv` then the following rule would fail to build:

```python
go_module(
  name = "dlv",
  binary = True,
  install = [
    "cmd/dlv"
  ],
  module = "github.com/go-delve/delve",
  ...
)
```

**Comment by Tatskaari** [comment]
This might be a regression, and should really be fixed in the plugin.
