### ISSUE TITLE
Working pex example with complex dependency (numpy)

### ISSUE THREAD

**Issue by nimish** [thought-machine/please#207]
Hi all,

I'm trying to get a pex file built that depends on a complex pypi library, numpy in this case, which includes C extensions.

Files are here:

https://gist.github.com/nimish/0c16fcfb5e9643f67440a87fd8d09c3f

`plz build` produces example.pex, but I get a "no module named numpy" when run.

If I drop `zip_safe=False` from the numpy declaration, nothing seems to change.

**Comment by peterebden** [comment]
This case works for me:
```
$ plz run //:example
nan
```
Can you provide any more information - have you changed `.plzconfig` at all? What is the Python interpreter (`/usr/bin/python` etc)?
Thanks!

**Comment by nimish** [comment]
Updated the gist with .plzconfig. I'm also running `./pleasew build //:example'

If I run the generated pip3 command:

`pip3 install --no-deps --no-compile --no-cache-dir --target=. -q -b build --proxy=http://my.company's.proxy nump==1.12.1`

I get: `No such file or directory: '/tmp/<random>/lib/python`
