### ISSUE TITLE
`add_deps()` should validate that the target is not built already

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#2076]
With a target that use `add_exported_deps()` in `post_build`, and another that depend on the first.
The `add_exported_deps()` add multiple dependencies from multiple folders.

First, there is an error when building some dependencies:

```
plz clean
plz build //:use_exported_deps --rebuild
Build stopped after 40ms. 1 target failed:
    //:use_exported_deps
cannot calculate hash for plz-out/gen/third_party/dep_1/dep_1: file does not exist
```

It works well when using `add_deps()` or building them separately with `plz build //third_party/...`.

Then building the target that depend on the one that use `add_exported_deps()` may fail (it works sometimes):

```
plz build //:use_exported_deps --rebuild
19:08:53.883 CRITICAL: Target //third_party/dep_1:dep_1 not found in build graph
```

Here is an example repository: https://github.com/sfirmery/please_add_deps_issue
Using Please version 16.8.0.

**Comment by Tatskaari** [comment]
Seems we're missing some validation here, so i can understand the confusion. A build rule can't (or shouldn't be able to) add deps to itself in a post-build function. The target has already been built at that point so it doesn't make sense to change its build time dependencies. I can see why you'd want to be able to add exported deps as they can have an effect on dependent targets but I leaning towards restricting this too, as I still don't think it works quite as you might expect. 


To solve your problem I think you'd do something liek this:

```
def _add_exported_deps(to):
    def post_build(name, output):
        for line in output:
            add_exported_dep(to, line)
    return post_build

def some_build_rule(name:str):
    dep_generator = build_rule(
        name = name,
        tag = "dep_generator",
        cmd = "for i in {1..10}; do echo \"//third_party/dep_${i}:dep_${i}\"; done",
        srcs = ["deps"],
        post_build = _add_exported_deps(name)
    )

    return filegroup(
        name = name,
        srcs = [dep_generator],
    )


some_build_rule(name = "test")
```

**Comment by sfirmery** [comment]
Yes, my goal is to dynamically add dependencies to some targets.

Thanks a lot, it works like this!
