### ISSUE TITLE
Follow symlink outputs (maybe opt-in)

### ISSUE THREAD

**Issue by burdiyan** [thought-machine/please#2079]
I know that I'm doing something that's against the rules of Please. But I've been doing the same thing in Bazel and it handles this use case well, so maybe Please could also do this.

The idea is to allow `build_rule` to produce outputs that are symlinks to files generated in the source tree, and make Please follow the symlink to determine if the rule is dirty.

Right now Please won't rerun the rule if the file that symlink points to changes or disappears. And Bazel does this.

Bazel still warns you if you're using genrule for that, but if you're doing it via a custom rule - it works. Would be great if Please could do the same.

**Comment by burdiyan** [comment]
I’ve just seen this in the docs. Looks like this was added after the last time I’ve looked into Please. Will get more info on that.

But my use case is actually the other way around: I want to store symlink for files in the source tree inside plz-out. This is totally possible now in Please, but it will only check the existence of the symlink and won’t follow it to check the contents.

**Comment by Tatskaari** [comment]
> Speaking of Bazel, this is how you can declare a symlink output in an action: https://docs.bazel.build/versions/main/skylark/lib/actions.html#declare_symlink

Oh wait, if I understand correctly, the actions are similar to the `cmd = ""` on a `build_rule()`. If you wanted to output a symlink, you could `ln -s` and declare it as an output. Are you just asking if we can make Please handle that better by following the symlink and hashing it's target rather than the symlink itself?

**Comment by burdiyan** [comment]
> Oh wait, if I understand correctly, the actions are similar to the `cmd = ""` on a `build_rule()`. If you wanted to output a symlink, you could `ln -s` and declare it in the `outs = []` list. Are you just asking if we can make Please handle that better by following the symlink and hashing it's target rather than the symlink itself?

@Tatskaari right, exactly that! I guess consequentially, this should only be allowed if `local = True` so that the output doesn't get cached, and rule doesn't get executed remotely.

**Comment by burdiyan** [comment]
The use case is a bit beyond the goals of Please, because it can become a foot gun for hermeticity. But if you know what you're doing you'll be fine. The idea is to provide more convenience trading off some reproducibility/hermeticity/correctness. 

For example, this could be used to run `yarn install` whenever `yarn.lock` changes.

One could create rule like that:

```
build_rule(
    name = "yarn",
    srcs = ["package.json", "yarn.lock"],
    outs = ["node_modules/.yarn-integrity"], # This file is created by Yarn
    cmd = """
# Escape from the $TMP_DIR and go to the source tree. The actual process doesn't matter.
yarn install
ln -s node_modules/.yarn-install $OUT
"""
) 
```

You can still do this now, but if you remove `.yarn-integrity` file Please won't detect that it needs to rerun the rule.

**Comment by burdiyan** [comment]
Update: 

I've been playing around with Bazel a bit, and it actually follows the symlink by default. If you want to create a symlink and treat it as a symlink without dereferencing (which is what Please does by default) you have to you `ctx.declare_symlink` action in the Bazel rule.

Would it be hard to change this behavior in Please or make symlink dereferencing opt-in?

**Comment by burdiyan** [comment]
I've seen that there's been many GitHub issues created over time from people requesting different ways to turn the "convenience/reproducibility" gauge more to the convenience side. Seems like it's common for simpler projects to trade off some of the reproducibility and correctness for more convenience. I think this symlink trick gives enough flexibility for not very ugly workarounds, and probably is the easiest to implement in code than any other solution I could think of.

**Comment by Tatskaari** [comment]
Sorry for the slow reply, I was sick that week and missed your responses. I think this generally makes sense but requires some careful thinking. I'll add it to the backlog for v17 (we're gearing up to start work on that as we speak).
