### ISSUE TITLE
In some cases, get_labels() don't return all labels

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#208]
Hi,

I'm trying to build some C++ files, but `includes` defines in dependencies are not return by `get_labels()` in some cases.

With a BUILD file like:

```
cc_library(
  name = 'lib1',
  hdrs = ['lib1/include/lib.hpp'],
  includes = ['lib1/include']
)

cc_library(
  name = 'another_lib',
  deps = [':lib1'],
)

cc_library(
  name = 'last_lib',
  deps = ['another_lib'],
)
```

In this case, `get_labels()` return something like `['cc:inc:lib1/include']`.

But if i add `  srcs = ['another_lib.cpp'],` to 'another_lib', `get_labels()` no longer return `['cc:inc:lib1/include']`.

**Comment by peterebden** [comment]
`get_labels` stops its search when it hits rules where `output_is_complete = True` - this isn't super well documented, but the idea is that if you pull in a `cc_binary` for some reason, you don't need to care about its dependencies.

Anyway, the behaviour here is clearly wrong as you point out, it's likely to do with the way Please parallelises compilation when there are multiple srcs. I'll look into it.

**Comment by sfirmery** [comment]
Works well. Thanks.
