### ISSUE TITLE
Cross-compiling with --arch doesn't work when using label wildcards. 

### ISSUE THREAD

**Issue by windrunner99** [thought-machine/please#2084]
Hello I realised a while ago that since the update from please 16.2.1 my cross compile aliases for my docker images are not working anymore. 
The command `plz run parallel -i docker-build --arch linux_amd64 //...` is producing 3 different outputs on 7 minor releases.

1. On version 16.0.0 to 16.2.1 it actually build all the images as expected linux amd64. 
2. On version 16.3.0 to 16.5.1 it only finds one target and then gets stuck.
![Screenshot 2021-09-22 at 13 48 52](https://user-images.githubusercontent.com/84197834/134338241-f63331e7-f3fa-42d0-8542-bef168acef5c.png)
3. On version 16.6.0 to current (16.9.0) it prints the following:
![Screenshot 2021-09-22 at 13 53 25](https://user-images.githubusercontent.com/84197834/134338813-db300257-5721-48d5-99c2-7330c9f69a1e.png)

**Comment by Tatskaari** [comment]
We introduced a big change to the scheduler to improve performance in 16.3.0. Unfortunately, it seems it has broken something with your build rules. Sorry about that. 

Cross compilation does work in general, but it seems that it doesn't work with wildcards anymore. Let me see if I can figure out why.
