### ISSUE TITLE
Allow to disable cache on a per-rule basis

### ISSUE THREAD

**Issue by burdiyan** [thought-machine/please#2090]
I was not able to find if there's a way in Please to disable cache for a specific target. I'm talking about both dir cache and remote cache.

I've seen that you can disable caching in .plzconfig by specifying an empty dir (which BTW blows up with nil dereferencing), but I couldn't find if it's possible to disable cache for a specific rule.

I'm more familiar with Bazel, and there you can do it by using `no-cache` tag (which is equivalent of `labels` in Please).

**Comment by Tatskaari** [comment]
> which BTW blows up with nil dereferencing

Oops, I've fixed that here: #2092

> I was not able to find if there's a way in Please to disable cache for a specific target.

There's no way to disable the cache for a specific target. I don't think individual build targets should be concerned about how they're being cached. This seems like a plaster for a problem in the way the build action works. 

 > I'm more familiar with Bazel, and there you can do it by using no-cache tag (which is equivalent of labels in Please).
 
 Looks like this only disables the remote cache, not caching in general? I'm not sure what motivated that feature but it feels wrong that rules have any control over the caching behavior.

**Comment by burdiyan** [comment]
My use case is yet again to break out of some strict rules of the build system and introduce some well-known and controlled side effects.

In this particular case I wanted to have a rule that runs always. So I make the rule to depend on an environment variable, which I set to a random value from the outside before running `plz`. I think I don't need anymore, but still it was an interesting experiment.

It was mostly working but there were 2 problems.

1. The rule would pollute the cache even when producing the same output, because Please dir cache works based on the inputs hash rather than output hash. So if inputs change but output stay the same the output would be cached twice. And in this case, since rule runs every time it pollutes the cache quickly. I know you can configure limits for the cache.

2. I don't remember when exactly this was happening, but sometimes please would not detect to rebuild the rule, and would recover the output file from the cache, without running the desired side effects.

I know that all of this is not the indented use case of Please.
