### ISSUE TITLE
How to hack on Please in VS Code?

### ISSUE THREAD

**Issue by burdiyan** [thought-machine/please#2106]
I was trying to get my hands into the Please codebase, but I'm unable to make the code completion work in my editor (VS Code). I'm using `gopls` (Go's language server) and I enabled experimental workspace mode which seems to be the only way to attempt to make multi-module workspaces to work.

Still, the editor complains with `found module "example" twice in the workspace"` and no IntelliSense features work in the editor. This seems to be because there're multiple `go.mod` file in the source tree that are named "example" in the tests modules.

What editor do you use for hacking on Please?

**Comment by Tatskaari** [comment]
I think I've mostly resolved this by adding in some dummy `go.mod` files that should stop the editor complaining about problems under those test data folders. Closing this issue now but do let me know if it's still freaking out.

**Comment by burdiyan** [comment]
@Tatskaari Thanks! It works now in the default mode!

But if multi-module workspace is enabled with `build.experimentalWorkspaceModule` setting in VS Code for `gopls` it still fails with: `Error loading workspace: found module "example" twice in the workspace`, because those dummy go.mod files all have the same module name.

**Comment by Tatskaari** [comment]
Yeah, I mean we're doing "naughty" stuff that isn't technically valid for go build (but Please can handle perfectly fine). This stuff is quite useful to set up various test scenarios so I don't really care that much. 

Regarding that error though, we can probably just set all the dummy go.mod files to have unique module names. Feel free to have a play around and see if you can get it to work.
