### ISSUE TITLE
Resources for nodejs?

### ISSUE THREAD

**Issue by y-nk** [thought-machine/please#2131]
Hello,

I'm brand new in the agnostic monorepo world, between bazel/pants/ and please. Please seems the most attractive to me since it's rather new and small (compared to the overwelhming ecosystem of the others).

That being said, I'm lacking of resources to get started, especially regarding hoisting of dependencies (which is a hot topic in the javascript world as you may imagine). I'm really willing to help, dedicate my time and document my efforts to push forward this tool, but i lack of a kickstart to do so. I can't even get to build and package my very first hello world node server into a docker image...

Could you guys give any pointers ?

**Comment by tiagovtristao** [comment]
Lerna provides management of different JS packages within the same repository/monorepo, while leveraging dependency hoisting which is JS-specific.
Please allows you to manage different packages of different languages within the same repository/monorepo. It will rebuild only what has changed (i.e. faster compilation which allow you to iterate faster) and guarantee that your bundles won't suffer from issues on the environment where they are built in. Please creates a sandboxed environment where your bundles will always build the same way and won't be affected by external behaviour.

**Comment by y-nk** [comment]
@tiagovtristao I couldn't find this repo, but it looks very clean so i can use it to reproduce my usecase. I'll dive into it and give feedbacks :) Until now i was hacking around https://github.com/kevinsimper/nodejs-please-build-example but it didn't really suit me.

To be clear what i'm looking for is building a monorepo for a microservice oriented backend with a majority of services in nodejs (hence our first try with lerna) but i'd like to keep the door open for go, python services too.

Anyway, thanks a lot :) If i can be of any help let me know 🙏
