### ISSUE TITLE
Is there any plan for auto-generating BUILD files?

### ISSUE THREAD

**Issue by moorara** [thought-machine/please#2156]
Is there a similar tool like [gazelle](https://github.com/bazelbuild/bazel-gazelle) for *Please*?

If no, is there any pan for addressing this use-case? For example, is there any plan on Please roadmap for building this feature into please cli? Or should I start forking gazelle and modifying to work with Please?

**Comment by Tatskaari** [comment]
There's https://github.com/tcncloud/wollemi which is very similar.
