### ISSUE TITLE
What's the idiomatic way to extend Please?

### ISSUE THREAD

**Issue by moorara** [thought-machine/please#2157]
For adding new rules to Please, what's the supported approach?

Does please support plugins or should we fork please? For example, how can I add support for generating GraphQL source code to Please?

**Comment by Tatskaari** [comment]
Historically, rules are added to some git repo. The git repo is then added to the host repo via `subrepo()` or it's wrappers: 
```
github_repo(
  name = "pleasings",
  repo = "thought-machine/pleasings",
  revision = "master",
)
```

You can then use the build definitions like so `subinclude(///pleasings//js:js)`. 

We've recently been working on the plugin API though. This follows a similar pattern but makes configuring your build definitions far easier. We've not written any tutorials for them yet, but you can read the documentation here: https://please.build/config.html#plugindefinition

There are a few examples for the various built in languages too:
- https://github.com/please-build/python-rules
- https://github.com/please-build/java-rules
- https://github.com/please-build/cc-rules
