### ISSUE TITLE
Enable hard linking of generated sources for those that want to check them in

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#2158]
Link generated sources currently symlinks files into the source tree. For those that want to check these in, hard links would be preferable. We should allow the following: 

```
LinkGeneratedSources = True ; symlinks
LinkGeneratedSources = soft ; symlinks
LinkGeneratedSources = hard ; hardlinks
```

**Comment by rauanmayemir** [comment]
This is actually a good starter task for me to get familiar with plz. Is there any example of such 'polymorphic' option with either bool or variant?

**Comment by Tatskaari** [comment]
> This is actually a good starter task for me to get familiar with plz. Is there any example of such 'polymorphic' option with either bool or variant?

Apologies, I didn't see your comment. I've gone ahead and just done this. I just bound it to a string but you could in theory write your own marshaller and handle this more elegantly.
