### ISSUE TITLE
Ability to generate compilation database for C and C++ projects

### ISSUE THREAD

**Issue by rHermes** [thought-machine/please#2166]
A lot of tools for autocompletion in C/C++, rely on a compilation database to do so. There is a plugin for bazel, https://github.com/grailbio/bazel-compilation-database, which will generate such a file for bazel projects, but I can't find any mention of a similar feature for please.

Is this something it might be possible to add to please?

**Comment by peterebden** [comment]
The JSON compilation database isn't something I was aware of, but it looks like it should definitely be possible to generate one for Please. It appears like we could do it with a fairly straightforward script, although the Bazel version you linked seems to be slightly more than that, so maybe I need to understand it a bit more.

FYI that this would likely end up in https://github.com/please-build/cc-rules (we are beginning to migrate most languages out of the core of Please so we can detach their updates from Please releases). I think that'll actually make it a bit easier to include into a project though.

**Comment by peterebden** [comment]
https://github.com/please-build/cc-rules/pull/12 adds a tool to do this for the new C and C++ plugin. It is a little basic, can discuss further in that repo if more specific work is needed in the area.
