### ISSUE TITLE
Gentest with srcs has no files in workspace

### ISSUE THREAD

**Issue by kevinsimper** [thought-machine/please#2169]
```
gentest(
    name = "test",
    srcs = [":stacker"],
    test_cmd = "docker run --rm -p 3000:3000 --name stacker-test $(cat $SRC) sh -c 'NODE_OPTIONS=--experimental-vm-modules npx jest'",
)
```

Then when running
```
$ plz test --shell //stacker:test
```

the workspace is empty for files.

I have another genrule that works great with the same `srcs = [":stacker"],`.

```
$ plz --version
Please version 16.13.0
```

**Comment by peterebden** [comment]
I think you want this to be `data` rather than `srcs` if you want it to turn up at test time (`srcs` are for build time).

**Comment by kevinsimper** [comment]
@peterebden Ah that is the reason, the docs does also say it, but it is not totally clear when reading for when is source used 😄 
```
data |   | list or dict | Runtime data files for the test.
```
https://please.build/lexicon.html#gentest
