### ISSUE TITLE
How to pass the same BuildEnv to two packages when running in parallel?

### ISSUE THREAD

**Issue by mrsauravsahu** [thought-machine/please#2175]
here's the repo in question - https://github.com/mrsauravsahu/souvenirs/tree/main

I have two packages, both requiring a `SERVICE_NAME` environment variable to build. 
When running a `plz run parallel <targets>`, how can I set different values for the same `SERVICE_NAME` variable?

**Comment by Tatskaari** [comment]
Hmm... there's no way to parameterise a build target like that I'm afraid. It's a little out of the remit of the `plz run parallel` subcommand. One way to get that to work would be to have two separate `sh_cmd()` targets that can set that up for you:

```python
sh_cmd(
    name = "run_foo",
    data = [":service_runner"], # This is the target you're trying to run
    cmd = "SERVICE_NAME=foo $(out_exe :service_runner)",
)

sh_cmd(
    name = "run_bar",
    data = [":service_runner"], # This is the target you're trying to run
    cmd = "SERVICE_NAME=bar $(out_exe :service_runner)",
)
```

Though if your just trying to run a service with some args, you might want to just do:

```
sh_cmd(
    name = "run_local",
    data = [":service"], # This is the target you're trying to run
    cmd = "$(out_exe :service) --port 8080",
)
```

**Comment by mrsauravsahu** [comment]
This works well for now.
