### ISSUE TITLE
How to make go modules available to other tools?

### ISSUE THREAD

**Issue by moorara** [thought-machine/please#2180]
When a repo only uses *Please* for managing dependencies and building artifacts, one challenge is how to work on that repo in VS Code for example, run tests from IDE, so on?

Is there any built-in rule or a tool that we can **deterministically** generate the `go.mod` and `go.sum` files from the `BUILD` file only for the current package/directory and its dependencies?

**Comment by Tatskaari** [comment]
Not exactly, however you can get all the packages that please installs via, `plz query print`.

I think you can do: 
```
$ go get $(plz query print --label go_module: //third_party/go/...)
```
