### ISSUE TITLE
cache miss when switching between plz test and plz cover

### ISSUE THREAD

**Issue by bit-shifter** [thought-machine/please#2211]
It seems that when switching between test and cover, more is being built than is necessary when no code change has taken place

Consecutive invocations of test or cover, yield cached results, but flipping between yields the problem.

**Comment by peterebden** [comment]
I think this is as expected; depending on the language, we may need to recompile the code in order to instrument it for coverage (e.g. for Go, C or C++). Languages like Python or Java are able to avoid this by doing the instrumentation at test runtime and shouldn't need to rebuild.

**Comment by Tatskaari** [comment]
Sorry, we were looking into this together and I asked Ewan to raise a ticket.

If you do `plz test :test` then `plz cover :test`, `plz test :test` should restore from the cache. It looks like it's restoring the test binary, but not the test.results file.

**Comment by Tatskaari** [comment]
I had a bit of a look into this but didn't get anywhere. Unfortunately unlikely to fix this any time soon, and we've moved to remote execution now so we're not really suffering from this anymore.
