### ISSUE TITLE
Simplify remote cache usage by utilizing a cli-command to upload/download files 

### ISSUE THREAD

**Issue by towe75** [thought-machine/please#2234]
Hi, thank you for all your hard work!

I'm looking into your remote cache support and try to fit it into our internal workflow/setup. We're migrating from a homegrown buildsystem with a S3 backed cache ATM, so i'd like to keep at least the authorization, bucket etc.

I followed your documentation and placed, in my playground, a http proxy between please and AWS S3. I tried https://github.com/lostintime/aws-s3-webdav and also  https://github.com/sagikazarmark/blob-proxy and both are working fine.

This setup is ok'ish for a developer workstation but it takes some effort to run it on automated, shared, remote buildservers for CI because it's one more component to manage and also security is a concern.

I wondered why we're not using a command-line approach. At the end we only want two features: upload bunch-of-files to a remote tar object, stream remote tar and unpack bunch-of-files to local folder. My idea is to define a download and (optional) upload command line tool in e.g. pleaseconfig and to leverage env-variables as well as stdin/stdout as a simple interface.
Even a shell script with vanilla aws-cli or e.g. minio client could then be used to leverage a remote cache without a lot of fiddling, no 3rd party background service is involved. 

WDYT about this idea? I recon that it would be somewhat slower because it has to launch a tool for each up/download but somebody with high performance needs can still use the existing http interface.

**Comment by peterebden** [comment]
Seems like a good approach to me! It's essentially an additional cache implementation which should be no problem to support.

If performance was a concern we could possibly consider persisting a process - but might not be worth it since it will likely make the protocol rather more complex.
