### ISSUE TITLE
Bug: blacklisting hidden directories in the root breaks //... wildcard

### ISSUE THREAD

**Issue by burdiyan** [thought-machine/please#2241]
When I run `plz build //...` nothing happens. I do have targets declared, and wildcard works fine for nested directories, e.g. `//foo/...`, but not for root.

Fails the same with `plz query alltargets //...` (not actually fails, but shows no output).

**Comment by burdiyan** [comment]
Oh, turns out it happens because I have `BlacklistDirs = ".yarn"` in my `.plzconfig` file. The wildcard looks like it's failing if I blacklist any dot-named directory (but only if it actually exist, otherwise it works fine).

**Comment by Tatskaari** [comment]
Hmm interesting. I've tried to reproduce that but it seems to work for me: 

https://github.com/Tatskaari/please/tree/fix-hidden-blacklist/test/parse/hidden_excluded_dir/test_repo

Any idea what might be missing?
