### ISSUE TITLE
Named outputs in `deps`/`exported_deps` produce syntax error

### ISSUE THREAD

**Issue by chrisnovakovic** [thought-machine/please#2257]
```
genrule(
    name = "one",
    srcs = ["one"],
    outs = {
        "txt": ["one.txt"],
        "dat": ["one.dat"],
    },
    cmd = "for i in $OUTS; do cp $SRCS $i; done",
)

genrule(
    name = "two",
    srcs = {
        "onetxt": [":one|txt"],
        "two": ["two"],
    },
    outs = ["two.txt"],
    cmd = "cat $SRCS_ONETXT $SRCS_TWO > $OUTS",
)
```

`plz build :two` succeeds, but adding `deps = [":one|txt"],` or `exported_deps = [":one|txt"],` outputs the following error:

```
Build stopped after 30ms. 1 target failed:
    //[...]:two
misc_rules.build_defs:114:12: error: Invalid build label: :one|txt
        fail('Can\'t specify both "out" and "outs".')
    return build_rule(
           ^
        name = name,

Traceback:
misc_rules.build_defs:114:12:       return build_rule(

           test/BUILD: 11: 1:   genrule(
```

**Comment by peterebden** [comment]
This may actually be deliberate. I'm not sure it makes sense to say you depend on a rule but want specific outputs from it; that seems more appropriate for `srcs` which might want to get a particular set of output files.
Sort of feel like this is mixing up named outputs which are a file-y thing and deps which are a build label-y thing.

**Comment by chrisnovakovic** [comment]
Makes sense - I can work around it by adding the named output as a `src` of a `filegroup` that also collects the outputs of the target that had `exported_deps`, then depending on the `filegroup` instead, which is consistent with what you said about named outputs being about files and `deps` being about build targets. Thanks!
