### ISSUE TITLE
Specifying the set of hashing algorithms for outputs

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#2260]
It would be good to change the set of valid hashing algorithms that can be used for `hashes = [...]`

**Comment by peterebden** [comment]
+1 have seen some confusion internally where people think they can pick e.g. BLAKE3 because we present what it would be, but they actually can't (it's not supported by remote execution).

**Comment by Tatskaari** [comment]
@tiagovtristao this is done now isn't it?
