### ISSUE TITLE
Bug: Sandbox env vars exports for rex ordering not consistent 

### ISSUE THREAD

**Issue by tobyfielding1** [thought-machine/please#2271]
Builds are being repeated with remote execution enabled when the results should be cached.
for example:
`/opt/tm/toolchains/3.4.20/usr/bin/bash --noprofile --norc -u -o pipefail -c 'export TMP_DIR="`pwd`" && export HOME=$TMP_DIR && export SHARE_NETWORK="1" && export USER_NAMESPACE="root" && export OUT="$TMP_DIR/$OUT" && $TOOLS_BUILD_IMAGE'`
and
`/opt/tm/toolchains/3.4.20/usr/bin/bash --noprofile --norc -u -o pipefail -c 'export TMP_DIR="`pwd`" && export HOME=$TMP_DIR && export USER_NAMESPACE="root" && export SHARE_NETWORK="1" && export OUT="$TMP_DIR/$OUT" && $TOOLS_BUILD_IMAGE'`
Are two different command arguments and therefore two different actions on mettle, without anything having changed in the code.

It is not clear if this is just caused by passing env = {...} to a build rule where dicts are not ordered or if the problem is more general.

**Comment by peterebden** [comment]
Do you have any more info on the build rule you're invoking to get this behaviour?
Remote execution has its own first-class concept of environment variables (which I'm pretty sure is where `env` on a `build_rule` should go although haven't confirmed) and that is definitely sorted. I suspect maybe something else is creating these `export` statements but I'm not sure what that would be.

**Comment by Tatskaari** [comment]
Caught up offline. Turns out these variabels are set via `env = ` on the build rule. We fixed the ordering of these a while back.
