### ISSUE TITLE
Inject helper vars into sh_binary

### ISSUE THREAD

**Issue by nmpowell** [thought-machine/please#2284]
In shell scripts we often end up doing something like:
```
DIR=$( cd "$( dirname "${BASH_SOURCE[-1]}" )" && pwd )
source ${DIR}/path/to/library.sh
```
at the top of the script to provide the root directory of the calling script.

In a dep (e.g. an `sh_library` used as a dep of an `sh_binary` and `source`d), the above provides the root path of the calling script, i.e. the root of the unzipped directory tree.

It might be useful to create that variable [as part of the `sh_binary` rule](https://github.com/thought-machine/please/blob/c1a3c38a429c8be65cba21721e308f5d8c002a15/rules/sh_rules.build_defs#L7), e.g.
```
_SH_BINARY_TMPL_PREFIX = """
unzip -qo $0 -d $(dirname $0)
export _SH_BINARY_ROOT=$( cd "$(dirname $0)" && pwd )
""".replace('$', '\\\$').replace('"', '\\"')
```
would this be acceptable as a helper variable, or too custom?

**Comment by Tatskaari** [comment]
I think this makes sense. We have a higher than normal need to access the source dir because we're unpacking all our dependencies there. It might also be nice to have a helper function that will expand a path to one of the deps on the build rule:

```
source $(dependency_path path/to/library.sh)
source $(dependency_path $(location :some_sh_lib))
```

**Comment by nmpowell** [comment]
:/ no, stale bot, I still think this would be a good idea.

**Comment by Tatskaari** [comment]
Though we should probably move this over to the [shell rules](https://github.com/please-build/shell-rules) plugin
