### ISSUE TITLE
What is "literal" in BUILD language grammar?

### ISSUE THREAD

**Issue by moorara** [thought-machine/please#2297]
I'm wondering about the definition of `literal` in EBNF grammar of BUILD language here: https://github.com/thought-machine/please/blob/master/docs/grammar.txt#L6

Is `literal` another token or is it a non-terminal symbol? If latter, what's the production rule for it?

**Comment by Tatskaari** [comment]
I think it's meant to include string, number and boolean literals. @peterebden I suppose we should have a production rule for it, but it also looks like the `value` production rule would make sense there?

**Comment by Tatskaari** [comment]
Looking at the code, I think it can be any expression. I've updated the grammar to reflect that.

**Comment by moorara** [comment]
`Int` and `String` are defined as tokens for capturing numbers and strings. `True` and `False` are also defined as terminal symbols in the grammar. So, the only candidate for literals would be floating numbers.

**Comment by moorara** [comment]
Allowing `statement` to be `expression` also makes sense to me.

**Comment by Tatskaari** [comment]
We don't have floats in the build language, and this more closely represents what's actually implemented, so I think this makes the most sense.
