### ISSUE TITLE
What is the semantic of "&Ident" in BUILD language?

### ISSUE THREAD

**Issue by moorara** [thought-machine/please#2303]
In the BUILD language grammar defined [here](https://github.com/thought-machine/please/blob/master/docs/grammar.txt#L160),
what is the meaning of `&Ident` in the production rule for function argument.

Based on this rule, we can have something like `arg1 & arg2 & arg3 = expression`. What does this example sentence mean in BUILD language?

**Comment by peterebden** [comment]
They're aliases for the name; it can be passed by any of them (but only the first name can be used within the function). We use this to conveniently support slightly different dialects - e.g. what we call `test_only` Bazel names `testonly`.
