### ISSUE TITLE
Go GRPC Example

### ISSUE THREAD

**Issue by baranyildirim** [thought-machine/please#2316]
Hi,

I've been trying to get Go GRPC work with please for a few weeks now. It has been quite painful. I think I am fairly close at https://github.com/baranyildirim/please-go-grpc-example

Currently running into:
```
2022/02/25 06:29:10 failed to compile google.golang.org/grpc/cmd/protoc-gen-go-grpc: cannot find package "." in:
        /home/by/please-go-grpc-example/plz-out/tmp/third_party/go/google.golang.org/grpc/protoc-gen-go-grpc._build/third_party/go/google.golang.org/grpc/grpc_download/cmd
```

Any help or example would be appreciated. The ones in [https://github.com/thought-machine/please-examples/](https://github.com/thought-machine/please-examples/) are somewhat outdated. It would be nice to get a small self-contained example working.

**Comment by tiagovtristao** [comment]
Have you seen https://github.com/please-build/go-proto-rules? We are currently migrating to plugins, and this repo seems to contain what you are looking for. I'm not sure if you can use it straight away, but you can adjust the logic there to yours.

**Comment by baranyildirim** [comment]
Thanks for responding. I updated my example repo based go-proto-rules and it works now!
