### ISSUE TITLE
Support having python module root be something else than build root

### ISSUE THREAD

**Issue by sliedes** [thought-machine/please#2323]
Suppose we have the following Python files/targets:

```
//src/stuff1.py
//src/subdir/stuff2.py
//third_party/python/some_pip_lib
```

Currently, the stuff1 and stuff2 modules can be imported in Python code only as `src.stuff1` and `src.stuff2`.

It would be nice, especially for developing software that possibly is not intended to stay in a Please repository indefinitely but be packaged somewhere else, to be able to specify that the Python module root is the `src` directory, so that this Python code would work:

```python
# this currently works because of moduledir = third_party.python; would like to keep it working
import stuff_from_pypi

import stuff  # would like this to work instead of having to say src.stuff
import subdir.stuff2  # and this without saying src.subdir.stuff
```

**Comment by samwestmoreland** [comment]
Hey, sorry for the slow response. This seems like a totally sensible feature. We've currently got some language plugins for Please that are being developed in parallel, including one for [python](https://github.com/please-build/python-rules), which will be pushed out with the v17 release. This is something that we can look at implementing as part of the plugin.
