### ISSUE TITLE
Improvements to the hashes argument

### ISSUE THREAD

**Issue by Silic0nS0ldier** [thought-machine/please#2349]
Rules like `remote_file` accept an optional argument `hashes` to validate file integrity, however the hash type is not specified in docs.

SHA256 works, and on deliberately corrupting it the output from build suggests that SHA1 and BLAKE3 are also supported.

Side note, it would be nice if the hash type was made more explicit. https://www.w3.org/TR/SRI/ seems like a decent spec to follow here, if making the type more explicit is desirable.

I also noticed that providing a hash that is an empty string won't fail the validation. I'm not sure if this is by design, but it did go against what I was expecting (that is, build with the empty hash so it would error out and show the files actual hash).

**Comment by Tatskaari** [comment]
The hashes are checked against the configured algorithms defined by this config option: https://please.build/config.html#build.hashcheckers

The docs on the various build rules that use hashes should mention this though. I'll get that updated.  

> Side note, it would be nice if the hash type was made more explicit. https://www.w3.org/TR/SRI/ seems like a decent spec to follow here, if making the type more explicit is desirable.

You can specify the hash like so `hashes  = ["sha256: someshasumhashhere"]`, though I think Please still just checks it against all of the configured algorithms. This is a breaking change but might be something we can get to in the next major release. 

> I also noticed that providing a hash that is an empty string won't fail the validation. I'm not sure if this is by design, but it did go against what I was expecting (that is, build with the empty hash so it would error out and show the files actual hash).

The idea here is that you can add the empty hashes argument to the rule, and then populate it with `plz hash --update`. It would be better if it failed under normal usage though. Again this is a bit of a breaking change so we'll have to do it as part of the next major release. 

I'll rename this issue and add it to the v17 backlog. We're gearing up to start making breaking changes in the next month or so.

**Comment by Silic0nS0ldier** [comment]
Automatic hash upgrades. That sounds amazing! ❤️
Thanks for the speedy response.
