### ISSUE TITLE
Better define the distinction between test arguments and the tests you want to run

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#2415]
It seems we set `$TESTS` to the things we pass after `--` to `plz test`. This is also used to set `$TEST_ARGS`. Not many rules seem to use `$TEST_ARGS` so we might be able to sneakily stop populating it. `plz run` has a `--argument` flag that can be repeated to pass args to the binary. We can probably manage something like this for `plz test`.

**Comment by peterebden** [comment]
I'm not sure the `--argument` flag is so beautifully elegant that we want to duplicate it more than we need to?

**Comment by Tatskaari** [comment]
I think we have 3 options: 
1) Make the arguments be everything after `--` and have a `--test` flag. This is probably nicer but I think will be more disruptive to users 
2) Allow passing test arguments via `--argument` which is janky but at least doesn't break our current users workflow. 
3) Disable test arguments all together which isn't ideal as sometimes people want to disable parallelism or other things.
