### ISSUE TITLE
Make plz watch debounce duration configurable

### ISSUE THREAD

**Issue by RichardoC** [thought-machine/please#2422]
This could be done by adding a flag for waiting a certain time after the last change to that target before building, or just building this in by default.

This would be very helpful for avoid building things that are genuinely broken because I haven't finished typing the line yet 😅

**Comment by peterebden** [comment]
plz watch does have some debouncing, see https://github.com/thought-machine/please/blob/270c0ece7d2465ea20457afeae5056bfea243709/src/watch/watch.go#L67

It seems reasonable to make that configurable though.

> This would be very helpful for avoid building things that are genuinely broken because I haven't finished typing the line yet 

Curious, it only fires builds when the file actually gets written to disk; is that happening for you because you're saving as you go, or is your editor autosaving as you write?

**Comment by Tatskaari** [comment]
It might be that he was editing the file during the build, so when the build finishes it just starts the next build. If the target takes a while to link, this might happen but I'm not sure if we can really do anything about this.

**Comment by RichardoC** [comment]
> plz watch does have some debouncing, see
> 
> https://github.com/thought-machine/please/blob/270c0ece7d2465ea20457afeae5056bfea243709/src/watch/watch.go#L67
> 
> It seems reasonable to make that configurable though (currently it's a constant 100ms).
> 
> > This would be very helpful for avoid building things that are genuinely broken because I haven't finished typing the line yet
> 
> Curious, it only fires builds when the file actually gets written to disk; is that happening for you because you're saving as you go, or is your editor autosaving as you write?

I'm using vscode with autosave, and its saves every ~ 250ms leading to this behaviour

**Comment by peterebden** [comment]
> I'm using vscode with autosave, and its saves every ~ 250ms leading to this behaviour

OK, I'm fine with providing a flag to make this configurable to work around that then. Although I do think that is a little naive of VSCode to just do it on a hard timer - I'd expect it to be debouncing here as well.
