### ISSUE TITLE
Bootstrapping please requires Go1.9+ but your prebuilt Docker image has Go1.8

### ISSUE THREAD

**Issue by natpen** [thought-machine/please#243]
I'm new to your project, so hopefully I'm not messing up the setup process on my end :) please looks very cool though!

**Comment by peterebden** [comment]
Thanks!

Hmmmm, I think thoughtmachine/please_ubuntu has 1.9, but thoughtmachine/please is an older image and has 1.8. I'm pushing a new version of the latter, that should fix it.

**Comment by natpen** [comment]
Ahhh, okay. Is thoughtmachine/please_ubuntu a better version for people to use? There's a link on the README to former, which is how I ended up there.

**Comment by peterebden** [comment]
It seemed a little more structured, since I wanted to add images for other distributions as well eventually. Probably makes sense to keep that around as a default though.
Typical that I forgot to update the docs :)

Thanks for the heads up on this one!
