### ISSUE TITLE
Take remote execution metric pushes out of the critical path

### ISSUE THREAD

**Issue by isobelormiston** [thought-machine/please#2447]
If the push gateway is slow or unavailable, Please builds will be blocked or slow (as discovered in a recent incident). These metrics should be best-effort, and not impact the performance of plz commands.

**Comment by peterebden** [comment]
Looks like this was fixed in #2448 - there is now a timeout, if the pushgateway is down in a way that simply blackholes requests there will always be some impact but it will now be limited to that time.
