### ISSUE TITLE
16.20.1 release on homebrew is broken (missing libexec directory)

### ISSUE THREAD

**Issue by mateuszlewko** [thought-machine/please#2457]
After upgrading to latest version with `brew upgrade` please binary no longer exists. I also tried to fully uninstall and reinstall the package. 
I think the following warning printed by homebrew during upgrade or install is relevant:
> Warning: Tried to install empty array to /opt/homebrew/Cellar/please/16.20.1/libexec

The `libexec` directory is indeed empty. The `please` binary in /opt/homebrew/Cellar/please/16.20.1 points to a non-existent file in libexec directory.

My platform is darwin_arm64.

**Comment by th3fallen** [comment]
did you ever find a fix for this? im hitting the same issue on please 16.28.0
