### ISSUE TITLE
Support interactive debugging of Python test failures

### ISSUE THREAD

**Issue by natpen** [thought-machine/please#246]
You can do this with some other build systems, [like Pants](https://www.pantsbuild.org/python_readme.html#interactive-debugging-on-test-failure) - upon a test failure, it will drop you into an interactive debugger (looks like pdb in the Pants example above).

I think it's a very nice feature, so I started noodling on would be necessary to support that workflow with Please (I'm by no means a Python expert, but I couldn't figure out a way to get comparable behavior out of Please+unittest).

You're already accepting flags, so my first thought is that switching the test runner to [pytest](https://docs.pytest.org/en/latest/) would give access to the `--pdb` flag out of the box. I'm happy to continue messing around with it, but I wanted to see if this was something you considered before, and what your thoughts are.

**Comment by peterebden** [comment]
I've thought about it a little - some people here have asked for it. I agree it'd be great to have but it did seem tricky...

Off the top of my head, the tests would need to have stdin connected, and stdout/stderr would need to get redirected out to the terminal. Things could get a bit weird if there's more than one test that tries to drop into the debugger at the same time, but I guess you could just do it for the first failure and ignore the others.

Sounds like a great idea though - let me know if you have any questions about it all!
