### ISSUE TITLE
Provide support for CycloneDX

### ISSUE THREAD

**Issue by VinodAnandan** [thought-machine/please#2460]
OWASP CycloneDX is a lightweight Software Bill of Materials (SBOM) standard designed to use in the application security contexts and supply chain component analysis. CycloneDX is an OWASP flagship project ( [owasp.org/www-project-cyclonedx](https://owasp.org/www-project-cyclonedx) ). The Open Web Application Security Project is a non-profit foundation that works to improve the security of software.

CycloneDX is already supported by many security vendors and projects ( [cyclonedx.org/about/supporters](https://cyclonedx.org/about/supporters) ). It is also recommended in the Technology Radar Volume 26 ( [thoughtworks.com/radar/platforms?blipid=202203034](https://www.thoughtworks.com/radar/platforms?blipid=202203034) )

Related links:
https://cyclonedx.org/capabilities/
https://cyclonedx.org/use-cases/
https://cyclonedx.org/tool-center/

**Comment by peterebden** [comment]
This is likely something that would need to happen in the various language-specific plugins (https://github.com/please-build/go-rules, https://github.com/please-build/python-rules and friends).

Seems like it could be useful (we have some less standard BOM stuff internally) but I think we're unlikely to pick this up ourselves; I think the best way forward would be for someone to raise a PR demonstrating how this would work for one language as an example.
