### ISSUE TITLE
Can't use private registry with base_image

### ISSUE THREAD

**Issue by jnmoal** [thought-machine/please#2466]
Hello everyone,

Looks like we can't use a private registry inside a base_image.
Our use case is that some base images are provided with up to date OS and basic tools that we need.
Then, from those base images (built from another git repository), we want to create our application image.
But please fails because it can't access the registry (403 forbidden), where buildah itself can in the exact same context (same creds, same pipeline...).

Can you tell me how we are supposed to furnish those credentials so that please can pull the base image?

Thanks in advance!

**Comment by andrew-womeldorf** [comment]
[Buildah stores credentials in `${XDG_RUNTIME_DIR}/containers/auth.json`](https://www.mankier.com/1/buildah-login). `$XDG_RUNTIME_DIR` isn't available by default in the build environment, so it's looking for credentials in `/run/containers/$UID/auth.json`.

Try adding this to your plzconfig
```
[build]
passenv = XDG_RUNTIME_DIR
```

**Comment by Tatskaari** [comment]
Thanks Andrew! Going to close this issue. @jnmoal Let me know if you're still having problem.?
