### ISSUE TITLE
golang: how to use  please with absolute golang import paths?

### ISSUE THREAD

**Issue by fho** [thought-machine/please#247]
We are following in our Go applications the common approach to use absolute import paths, starting with a domainname.

For example we have in our git repository root the files:
`go/code/lib/log/log.go`
`go/code/myapp/cmd/myapp/main.go`

In the `main.go` file of myapp we import `example.com/go/code/lib/log`.
To make it build with `go build`, we check out the git repository into a directory called `example.com` and set the `$GOPATH` to the parent directory.

If I build myapp with please, it can't find the import `example.com/go/code/lib/log` because in please's temporarily build directory the package is located in `go/code/lib/log/` instead of in `example.com/go/code/lib/log`.

What is the common approach to solve it with please?
Is there a better way than putting the `.plzconfig` file into the parent directory of the checked out repository?

Bazel has an `importpath` directive for golang packages to specify an importpath that differs from the file location. 

**Update:**
With our layout Pyhthon builds are also broken.
`example.com` is used as part of the import path and python uses `.` as separator for directories in the import path.

```
|- .plzconfig
|- example.com/ (root of the cloned git repository)
    | - python/
        |- test/
            |- main.go
            |- BUILD
    |- go/
        | - vendor/
            |- BUILD
        |- code/
            |- lib/
                |- BUILD
                |- log/
                    |- log.go
            |- myapp/
                |- BUILD
                |- cmd/
                    |- myapp/
                        | cmd.go
```

**Comment by peterebden** [comment]
There isn't a good solution for this at present, unfortunately :(
It works for us because we fully specify import paths but only within the repository. I'm aware that having the domain name (and possibly project) above the repo is a pretty common structure for Go though, and of Bazel's option for it, so we should do something to support it.

I'm not sure offhand how easy it will be but will definitely give it some thought :)

**Comment by fho** [comment]
@peterebden that's a pitty, I hope it will be supported in the future. :-)
I'm currently trying build tools (bazel, pants, etc) that we could use for our monorepository and I like plz the most. 
It's fast, straightforward to use and having remote repositories as go deps simply works. 
Cool project! :-)

**Comment by peterebden** [comment]
Thanks! :) 
I'm a little busy with non-build-system work at the moment but I will try to get onto this one when I can.

**Comment by peterebden** [comment]
I think #249 should do what you want here; I'll release a new version containing that shortly.
Essentially it lets you set 
```
[go]
importpath = example.com
```
in your `.plzconfig` which I think will have the effect you want. Let me know if it's not enough or you have any problems.
