### ISSUE TITLE
Binaries for linux arm64 , aarch64

### ISSUE THREAD

**Issue by towe75** [thought-machine/please#2470]
We're moving towards AWS graviton instances and want to establish a full CI process there. Part of it is of course a working "please" environment. I was able to clone and bootstrap a binary without problems but i want to ask if we could get prebuilt binaries. 

I noticed a recent PR: #2411   I'm unsure about the impact of this PR because i could not find fitting binaries on github, also get.please.build and pleasew are unchanged. Note that the reported arch on graviton (uname -m) is "aarch64" whereas mac/darwin uses "arm64". 

Do you have any plans to move forward here? I could help with e.g. pleasew (like back in #2286) and with testing. 

This is not a showstopper for use because we can simply compile a binary but it would certainly be simpler for us and others to get a binary and pleasew support.

**Comment by Tatskaari** [comment]
I can't think of any good reason not to and it seems it could help a few people out. I'd be happy to collaborate on a PR to get this working. We can make pre-releases by adding `v16.20.2-beta.1` to the version to test this out.
