### ISSUE TITLE
Is there a way to download dependencies before build?

### ISSUE THREAD

**Issue by vlad-ivanov-name** [thought-machine/please#2473]
Dear developers,

would it be possible to pre-download all external dependencies during "configuration" stage to use them later during build stage? So that the actual build can be completely offline, and dependencies are cached in e. g. Docker layers.

![image](https://user-images.githubusercontent.com/2057191/169810382-86573ad0-9e7a-4f1f-99be-087da22bcf7a.png)

Thank you!

**Comment by Tatskaari** [comment]
Hey! I'm afraid there's nothing sophisticated that Please offers to do this. If you know which targets you need to build ahead of time, you can build them beforehand and share the directory cache between builds (defaults to `~/.cache/please` on linux, see [cache.dir](https://please.build/config.html#cache.dir)). 

All `remote_file()` rules are labelled with `remote` so you can `plz build --include remote` to build them.

**Comment by Tatskaari** [comment]
I'm not sure what the idea state would be here. We could probably implement something sensible for `remote_file()` to make it use a local cache, however other build actions can perform arbitrary requests. If you're using linux sandboxing, we can reason about this to some extent as targets have to opt out of the sandbox to make remote connections. I don't know how easy it would be to then redirect these arbitrary build actions to a local cache though. We could probably do something to the network interface in the namespace but that's probably further than I'd want to go with this.
