### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by fho** [thought-machine/please#248]
Hello,

is there an IRC-channel for please?
It would be great to have one for discussing issues, ideas, etc :-)

**Comment by peterebden** [comment]
There isn't; we've had a little discussion but are currently unsure what the best option is. I'd rather avoid something proprietary like Slack if possible, but it is popular...

In the meantime I've set up a mailing list: https://groups.google.com/forum/#!forum/please-build / please-build@googlegroups.com for general questions.

**Comment by agenticarus** [comment]
Something like Gitter could be a good option - while I like the idea of IRC it could be more of an impediment to new users.

**Comment by BNMetrics** [comment]
Please, let's have a community chat thingy for please!!!!

**Comment by peterebden** [comment]
We have a gitter now: https://gitter.im/please-build/Lobby

That will do for now; we can always add more / change later.
