### ISSUE TITLE
Pleasew does not handle relative paths correctly

### ISSUE THREAD

**Issue by cemeceme** [thought-machine/please#2498]
When a relative path is specified for the `location` under `[Please]` in the `.plzconfig` file, running please through pleasew will fail to create valid symlinks in the specified location.

For instance, if the path `location = ./.please` is given, then pleasew will create the correct `.please` directory in the current working directory and successfully download the requested version in another sub-directory within as expected. However, the symbolic links that it tries to create following this are invalid and point relative to the current working directory and not the newly created `.please` directory. Namely, the `please` link will point to `./.please/VERSION/please` instead of `./VERSION/please`.

As a workaround, I have been successful adding `LOCATION="${LOCATION/#\.\//$(pwd)/}"` right after line 49 in the pleasew file, however this assumes the path to begin with `./`.

**Comment by Tatskaari** [comment]
Thanks for the bug report! Will add this to the backlog but would also be very happy for a PR.
