### ISSUE TITLE
Config file hierarchy

### ISSUE THREAD

**Issue by natpen** [thought-machine/please#250]
:wave: hi again! I've been thinking about the config file hierarchy today. Copying from documentation, the current state is:

> Please looks in several locations for these files and builds it up bit by bit. In order (from lowest priority to highest):
> * `.plzconfig`
> * `.plzconfig_<arch>` (e.g. .plzconfig_linux_amd64)
> * `/etc/plzconfig`
> * `.plzconfig.local`

I get why `/etc/plzconfig` is higher-priority than the repo-specific configs, as you mention in documentation that this allows overriding repo-specific configuration in places like CI. Conceptually though, I was wondering if there would be a way to make increases in hierarchy correspond with increases in application breadth. Here was an idea I came up with, which I was curious what you thought of:

> Please looks in several locations for these files and builds it up bit by bit. In order (from lowest priority to highest):
> * `/etc/plzconfig`
> * `~/.please/plzconfig`
> * `.plzconfig`
> * `.plzconfig_<arch>` (e.g. .plzconfig_linux_amd64)
> * `.plzconfig.<env>` (where env is a string matching an env config set farther down in the config hierarchy)

The main ordering difference is that repo-specific configs would override lower-level configs, similar to how other major tools (e.g., [Git](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)) do config file prioritization. Additionally, it adds a user-specific config file. Lastly, to cover the CI use-case, it adds a repo-specific, environment-specific config file at the highest priority (`.plzconfig.<env>`). In the absence of a set env, it could default to `local` to maintain existing functionality with respect to `.plzconfig.local`, but on, say, a CI machine, you could set the env to something like `ci` in `/etc/plzconfig`, then check in a `.plzconfig.ci` to the repository.

This wouldn't necessarily be backwards compatible with everyone's use cases, which would make it trickier, but still curious what your thoughts are, and if you've talked through this before :)

**Comment by peterebden** [comment]
We've not really thought about this in a lot of depth - the current config setup appeared fairly early on to solve some immediate needs. I agree that the ordering is probably a bit unintuitive though since it doesn't match how other tools do it.

Our use has evolved a bit and I'm not sure we rely on the prioritisation so specifically any more, so it might be possible to simply reorder them.
I like the idea of adding `~/.please/plzconfig` although it interacts a little weirdly with the config file allowing you to define a different location for it. Again I'm not sure if there's really a lot of use to that any more though...

I'm 50/50 on the `.plzconfig.<env>` thing. I like the idea of it being checked in but it might be a little confusing to have other config files determining which ones get read. I might have a look at our CI setup in more detail and see if we can get away without.

**Comment by natpen** [comment]
Ooh... I just had an idea from the discussion in #256! Adding it here, as I don't think it's necessarily in scope for that PR. My suggestion can even be simplified further, by getting rid of the arch-specific config, as that could also be set dynamically in a lower-level config - e.g., in `/etc/plzconfig` a linux build machine sets `env = linux_build_machine` or something, then, e.g.,
* `.plzconfig`
* `.plzconfig.linux_developer_machine`
* `.plzconfig.linux_build_machine`

could all be checked in to the repo. This way you _only_ need system-level config, user-level config, repo-level config, and dynamic env ones, which users can tweak to their own workflows however they like. The resultant hierarchy would look like:

* `/etc/plzconfig`
* `~/.please/.plzconfig`
* `.plzconfig`
* `.plzconfig.<env>` (where env is a string matching an env config set farther down in the config hierarchy)

I totally get (and even share) your sentiment about being 50/50 on having other config files determine which ones get read... maybe there's a better way to be dynamic? I think the thing I really like most about this proposal is the sytem, user, repo, dynamic hierarchy, as it's simple, intuitive, and amenable to all kinds of custom overriding I can think of.

**Comment by peterebden** [comment]
> Adding it here, as I don't think it's necessarily in scope for that PR
Thanks, I think it'll be easier if that PR just covers the priority swap (which is breaking, so should land in a major version change). Adding new config mechanisms is easier, but I'd like to get them right first time if we can :)

I'm not sure I like dropping the arch config files; they're definitely useful for us to be able to set linux/mac specific things without having to provision root-level config on all machines. It's probably not going to be that common for others but it seems nice to be able to set that for a repo that might not control machine-level settings.

I do still like the idea of checking in configs for different "profiles" though. Maybe a command-line flag might be more explicit? Or possibly both...

**Comment by natpen** [comment]
That's a fair point - the arch thing could come up enough that keeping the arch configs means less manual work.

I like your idea for command-line flags more than my idea :stuck_out_tongue_winking_eye: that way you would get the benefit of nicely version-controlled, flexible, high-priority configuration files, but also with a much clearer, more explicit way of invoking them.
