### ISSUE TITLE
Feature Request: PHP build rules

### ISSUE THREAD

**Issue by kawtharmahboubi** [thought-machine/please#2520]
I'm considering using Please as a monorepos build tool , but I cannot figure out if it support php or not , I've taken a look into documentation but I couldn't figure it out. 
Please can you clarify?

**Comment by Tatskaari** [comment]
No, I'm afraid there are no PHP build rules. PHP is an interpreted language so you can "build" first party code with a simple filegroup, but there are no rules for third party code. 

We're unlikely to implement this in the immediate future, but it would be useful to know what you'd want Please to do for you here. I guess we'd need some rules to pull PHP dependencies and package them up in a directory structure so you can run a website out of there?

**Comment by qualeo** [comment]
PHP static builds can now be generated thanks to the https://frankenphp.dev/ project.

> No, I'm afraid there are no PHP build rules. PHP is an interpreted language so you can "build" first party code with a simple filegroup, but there are no rules for third party code.

With the advent of this new capability of PHP, what would be involved in Please supporting it as a first-class supported language?
