### ISSUE TITLE
Allow wildcards for `--include`

### ISSUE THREAD

**Issue by samwestmoreland** [thought-machine/please#2532]
As far as I can work out, at the moment it's not possible to do something like `plz query print //dir/... --include 'metadata*'`, but it might be nice to be able to do that.

This is potentially too narrow a use case and/or a misuse of `labels`...

**Comment by Tatskaari** [comment]
I think this could be very useful. There are targets that have labels like `go_package:github.com/thought-machine/please/src/core`, and it might be nice to do something like `plz query alltargets -i go_package:\*`

**Comment by peterebden** [comment]
Yup, seems useful and I don't think it will be particularly hard to do (we don't index by labels so it isn't a significant performance issue or anything)
