### ISSUE TITLE
Homebrew `please` vs `plz`?

### ISSUE THREAD

**Issue by orbiteleven** [thought-machine/please#2534]
Installing `please` via Homebrew gives me a binary of `please` but not `plz`. The [Quickstart](https://please.build/quickstart.html) and [Codelabs](https://please.build/codelabs/go_intro/) refer to using `plz`. While it's not a deal killer, it feels like either the binary install/alias should be added to Homebrew or the documentation should be updated.

**Comment by Tatskaari** [comment]
Yeah this seems like a bug with the homebrew install. 

I've raised this issue on that repo here:
https://github.com/thought-machine/homebrew-please/issues/15

Let me see if I can figure out how homebrew works.
