### ISSUE TITLE
`...` in target visibility doesn't range over subrepos

### ISSUE THREAD

**Issue by chrisnovakovic** [thought-machine/please#2548]
This might not be a bug, but the behaviour surprised me so I figured it'd be worth checking whether it's intended to work this way.

```
genrule(
    name = "test",
    # ...
    visibility = [
        "//dir/...",
    ],
)
```

This makes `//:test` visible to targets below `dir` that belong to the main repo, but subrepo boundaries aren't crossed - to make `//:test` visible to (e.g.) `///dir/subrepo//:target` too, it's necessary to add another visibility declaration explicitly referring to subrepos:

```
genrule(
    name = "test",
    # ...
    visibility = [
        "//dir/...",
        "///dir/...",
    ],
)
```

In the context of visibilities, should `//dir/...` mean "every target beneath `dir`", or "every target beneath `dir` that belongs to the main repo"?

**Comment by Tatskaari** [comment]
Sorry, missed this question. I think this probably is WAI, though it might not be the most useful. Hesitant to change it though as I've not got a good grapple on the various use cases here. I'll close this issue out but if you feel strongly, I'd be happy to chat more about it.
