### ISSUE TITLE
Kubernetes CodeLab issues with Apple M1 (arch=arm64, not amd64)

### ISSUE THREAD

**Issue by ziadsawalha** [thought-machine/please#2549]
[This line](https://github.com/thought-machine/please/blob/d04e97a0f574dffae8ff4f264348d2fd76a655c8/docs/codelabs/k8s.md?plain=1#L362) doesn't work on an Apple M1 machine.

`minikube-{CONFIG.OS}-amd64` should be `minikube-{CONFIG.OS}-{CONFIG.ARCH}` to work on an M1. Not sure if that breaks on other distros...

**Comment by Tatskaari** [comment]
Apologies! This one slipped through the gaps.
