### ISSUE TITLE
The github_repo moves the build file into a repository subdirectory named build

### ISSUE THREAD

**Issue by PeterBocan** [thought-machine/please#2595]
I am playing around with WASM and I have noticed that when I build this target, the build_file ends up in the subrepo's `build/` subfolder. 

```
github_repo(
    name = "wasmtime",
    repo = "bytecodealliance/wasmtime-go",
    revision = "v1.0.0",
    build_file="wasmtime.build",
)
```

**Comment by PeterBocan** [comment]
It looks like swapping the order in which BUILD files are generated in `.plzconfig` solves the problem.

```
[parse]
buildfilename = BUILD.plz
buildfilename = BUILD
```

**Comment by peterebden** [comment]
Seems like this will happen on a case-insensitive file system, yes; it attempts to move it to `BUILD` but if there's already a directory called `build` the two are considered the same name.

The workaround of swapping the order of the build file names is a neat fix!

**Comment by peterebden** [comment]
Closing this; I don't think there is anything specific we can do to improve this.
