### ISSUE TITLE
python_binary(strip=True) has no effect

### ISSUE THREAD

**Issue by elthariel** [thought-machine/please#2610]
Hi,

I was considering using the `strip = True` flag of the python_binary rule to reduce a bit the size of the binaries we ship, but it seems it doesn't do anything. I'm using `unzip -l` to list the content of the produced pex file and all the .py files are still alongside the `.pyc` files. Same behavior when adding it to a python_library rule.

From the logs, it seems the arcat tool is receiving the right argument:

````
$TOOL z -i . -s .pex.zip -s .whl --preamble_from="$SRC" --include_other --add_init_py --strict --strip_py
```

Do you want me to create a repo to reproduce ?

**Comment by Tatskaari** [comment]
Hmm yeah I can see it has _some_ effect:

```
➜  please git:(migrate-cc-rules) ✗ plz build //test/python_rules:strip_source 
Build finished; total time 320ms, incrementality 97.5%. Outputs:
//test/python_rules:strip_source:
  plz-out/bin/test/python_rules/strip_source.pex
➜  please git:(migrate-cc-rules) ✗ unzip -l plz-out/bin/test/python_rules/strip_source.pex
Archive:  plz-out/bin/test/python_rules/strip_source.pex
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2001-01-01 00:00   test/
        0  2001-01-01 00:00   test/python_rules/
      230  2001-01-01 00:00   test/python_rules/strip_source.pyc
    14626  2001-01-01 00:00   __main__.py
        0  2001-01-01 00:00   test/__init__.py
        0  2001-01-01 00:00   test/python_rules/__init__.py
---------                     -------
    14856                     6 files
```

Without it we have the additional `test/python_rules/strip_source.py` file, but it doesn't strip dependencies.

**Comment by Tatskaari** [comment]
We'd probably have to fix this in the arcat tool, so I've raised an issue here: 
https://github.com/please-build/arcat/issues/12
