### ISSUE TITLE
arcat not cached

### ISSUE THREAD

**Issue by shanelanan** [thought-machine/please#2612]
On version `16.20.4`, I am seeing outbound web requests to `arcat` which crashes ~1% of the time.

How to cache this during please install?

I see this is a `remote_file` defined in [`src/parse/internal.tmpl`](https://github.com/thought-machine/please/blob/27b63880d7c046d0aecf4f5c8b315718dad4f089/src/parse/internal.tmpl#L3) even in the latest release of please.  Any help would be much appreciated.

```
//_please:arcat: Build failed: 1 error occurred:
* Get "https://github.com/please-build/arcat/releases/download/v1.0.2/arcat-1.0.2-linux_amd64": net/http: TLS handshake timeout
```

**Comment by Tatskaari** [comment]
Build actions, including remote files, will be cached on the first build but this doesn't help you if you're running on a CI agent with no persistent cache. 

You can install arcat and other tools on the machine and configure them like so:
```
[Java]
JarcatTool = /opt/toolchain/bin/arcat # Can also just "arcat" if it's on the path 

[Go]
PleaseGoTool = /opt/toolchain/bin/please_go
EmbedTool = /opt/toolchain/bin/please_go_embed
FilterTool = /opt/toolchain/bin/please_go_filter
```

There's a little history as to why arcat under `java` which should be resolved in the next major. 

I've never see the TLS handshake timeout on our side before though. The Please website is backed by aws cloudfront so I would be surprised if that was on our end.
