### ISSUE TITLE
Adding Please to monorepo.tools

### ISSUE THREAD

**Issue by kachkaev** [thought-machine/please#2614]
Hey folks! I was researching monorepo tools and found a link to Please at https://turbo.build/repo/docs/acknowledgements#inspiration--prior-art

There exists [monorepo.tools](https://monorepo.tools) which is maintained by Nx authors. This website does not feature Please and I think it’s a shame because your tool is quite cool and so definitely deserves to appear in the comparison table. I saw [pantsbuild/pants](https://github.com/pantsbuild/pants) added recently and it’d be great if you could poke [someone from Nx](https://monorepo.tools/#monorepo-contributors) too! 🙂

Thanks for working on Please and making it open source! 🚀

**Comment by Tatskaari** [comment]
Hey! Thanks for the heads up! It would be great if we were added there. I wonder if i can just @alexeagle?

We met at the build meetup that codethink organised and had a brief chat about how to do Javascript rules in Please/Bazel. Any chance you'd be a good person to talk to about this?

**Comment by alexeagle** [comment]
You can just send a PR to the monorepo.tools source code https://github.com/nrwl/monorepo.tools if you want to tackle that.

**Comment by Tatskaari** [comment]
Looks like they have an issue open to add us actually! 

https://github.com/nrwl/monorepo.tools/issues/67

**Comment by kachkaev** [comment]
not stale

**Comment by Tatskaari** [comment]
Going to close this issue. We're just waiting on their end for an updated layout.
