### ISSUE TITLE
Please signing key possibly compromised as part of the circleci leak

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#2628]
In the recent [circleci leak](https://circleci.com/blog/january-4-2023-security-alert/), a number of our secrets have potentially been compromised. We have rotated all other secrets we use however the private key we use to sign releases can't be easily changed without breaking upgrades. This is because Please embeds the public key, and verifies new Please versions against it. If we change the private key, the signatures won't match so Please will no longer trust newer downloads. 

NB: We have checked the access logs for the Please website and have found no reason to believe that Please has actually been compromised at this time. 

The plan to mitigate this is as follows:

1. We migrate to use PEM based certificates that use a trust chain. This certificate will be issued from amazon or GCPs CA and be verified for the `releases.please.build` domain. 
2. We start signing new releases with both keys. Newer Please releases only trust the PEM key, and no longer trust the compromised key. This allows older Please versions to update to new Please versions which will then no longer be compromised. 
3. We sign all historic Please releases with the new PEM key. This means Please can still downgrade to older versions. We may want to log a warning when downgrading to a compromised Please version.  
4. We issue a notice to all Please users that old Please releases are compromised and they should upgrade as soon as possible. We can use the release milestone feature, post a message on gitter, and update the README in this repository. 
5. After some grace period, we remove all compromised signatures for Please releases. Users can still update/downgrade from old Please versions with `plz update --noverify` flag. 

PEM based certs mean that we will never have this problem going forward. The trust chain allows us to issue new certificates from a publicly trusted CA. We trust any certificate coming from the `releases.please.build` domain.

**Comment by andrewnicolalde** [comment]
In addition to the process outlined above by @Tatskaari, how do we feel about re-releasing old versions of Please with no changes other than that they trust the new key only? This would break post-download integrity checks, (i.e. when we're verifying a Please download's integrity [via a `remote_file`'s `hashes`](https://please.build/lexicon.html#remote_file)), but perhaps it's not too much work to update those hashes. Would that be feasible?

**Comment by peterebden** [comment]
> how do we feel about re-releasing old versions of Please with no changes other than that they trust the new key only?

**Comment by peterebden** [comment]
> how do we feel about re-releasing old versions of Please with no changes other than that they trust the new key only? 

I don't feel good about that. That will break anyone with `please.versionchecksum` set in their config (we have that on all relevant branches internally) which I don't consider acceptable. The expectation that field sets is that releases are immutable.

In a practical sense, it's not clear what set of Please versions we would have to update in this way (but it's not a small number) and we have no particular facility for doing it. If we did, there would be massive churn - e.g we would have to yank all the relevant Github releases, then rebuild them, pushing new commits and tags for them all.

**Comment by Tatskaari** [comment]
I think I'd rather just delete them from the bucket. I'd be comfortable releasing a new v15 and v16 patch version with the new verification. Theoretically updating to that version should work in all by the most pathological use cases, because we follow semver pretty well.

**Comment by peterebden** [comment]
Assume this is all done now?
