### ISSUE TITLE
Documentation pass

### ISSUE THREAD

**Issue by Tatskaari** [thought-machine/please#2629]
We are missing docs on subrepos, plugins, debug commands, and plz exec. These should probably form part of the advanced section. 

We also may want to document `breakpoint()`, which is quite useful. 

We need to update the language codelabs and write a new codlab for authoring plugins. 

Additionally `plz help` doesn't work with plugin config at the moment. 

It would be nice to merge all the docs into one page so you can `ctr-f` over them too. 

We should also give the plugin docs over in `please-build/x-rules`. We may want to have a way for plugin authors to include their plugin documentation in the Please website. We should be able to generate this from their plugin config and python doc strings.

**Comment by PeterBocan** [comment]
Maybe adding documentation on how to introduce custom toolchains would be also beneficial, no?
