### ISSUE TITLE
requires/provides and incrementality query

### ISSUE THREAD

**Issue by tiagovtristao** [thought-machine/please#2634]
Hey! I was working with some rules that make use of `requires` and `provides` and noticed that things aren't getting rebuilt as I would expect when a source/dependency is modified. For instance,

```python
filegroup(
    name = "file",
    srcs = ["file.txt"],
    visibility = ["PUBLIC"],
)

build_rule(
    name = "module",
    srcs = ["module.txt"],
    cmd = "cp $SRC $OUT",
    outs = ["module_out.txt"],
    # relevant part
    provides = {
        'rq': ':file'
    }
)

# main rule
build_rule(
    name = "project",
    srcs = [":module"],
    cmd = "touch project; sleep 4",
    outs = ["project"],
    requires = ['rq'],
)
```

I would expect the `:project` rule to be rebuilt when running `plz build :project` every time I changed `file.txt`, but it never gets rebuilt. Is this expected when making use of requires/provides?

**Comment by peterebden** [comment]
I'm not sure that this is specific to require/provide - it may be possible with something else between the two targets.
It looks like we're incorrectly setting xattrs on the filegroup outputs (which are the same files as the inputs). It's hard to see if anything relevant changed here but I think we checked this stuff when we first did xattrs (long time ago now though).
