### ISSUE TITLE
macbook M1 pro macos 13 Execution error

### ISSUE THREAD

**Issue by leididi** [thought-machine/please#2652]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/34613810/213455160-7027d839-5932-44c1-96ab-5b02b9196fc3.png">

What should I do?

**Comment by Tatskaari** [comment]
What does `file ~/.please/please` say? Could you try downloading the file directly here and see if that works for you:
https://github.com/thought-machine/please/releases/download/v16.27.1/please_16.27.1_darwin_arm64
