### ISSUE TITLE
Editor support for outputs

### ISSUE THREAD

**Issue by kevinsimper** [thought-machine/please#2655]
I have been trying and using bazel and please for some years now. 

However my biggest struggle in adoption for me and the teams I am in are editor support. I can't seem to figure it out and I think it is key for broader adoption 🎉

There are tools like turborepo which is not nearly as versitile and good as please.build, but it allows editors to provide good autocompletion for development. 

Right now outputs are stored in plz_outputs, that makes it hard for editors like VS Code to find the references. Would storing outputs locally relative to folders be the middle way and solution to editor support?

Thanks for all the help, inspiration so far!

**Comment by Tatskaari** [comment]
There's a few things we've done to try and make this better. The ideal solution is specific to the language, but you can use the link generated sources feature to link things back into the source tree as you suggest:
https://please.build/config.html#build.linkgeneratedsources

For Go there's a few things we can do. For IDEs that use LSP i.e. vs-code, vim and emacs, we can write a go package driver which will help the Go language server, and other standard tooling work with Please. We've started on this [here](https://github.com/please-build/go-rules/blob/master/tools/driver/main.go). For Intellij, we can write a go import resolver. Which is also on the roadmap for the end of this year.

**Comment by kevinsimper** [comment]
@Tatskaari Okay that is pretty interesting, I did not know about that config, I will try that out!
