### ISSUE TITLE
Cross compilation documentation outdated/missing

### ISSUE THREAD

**Issue by a7g4** [thought-machine/please#2661]
https://github.com/thought-machine/please/blob/master/test/cross_compile/README.md references a file `.plzconfig_linux_x86` that has been deleted.

Is cross-compilation still supported? Are there updated examples anywhere? (I looked in https://github.com/please-build/cc-rules but couldn't find anything)

**Comment by Tatskaari** [comment]
Yes! Very much so. The C/C++ rules have basic support for it. The Golang rules have good support. 

The `linux_x86` tuple is 32 bit, and is now unsupported by golang, so I deleted that file. You can the CircleCI config in this repo where we cross compile for freebsd, and M1 mac machines. 

It should mostly work for c++, however we don't have as much control over architecture as you might have in clang itself:
https://clang.llvm.org/docs/CrossCompilation.html

For c++, it's not quite as slick. You should be able to `plz build --arch linux_amd64 //some:target`, and set up the appropriate c/c++ flags or toolchain in `.plzconfig_linux_amd64`.

**Comment by a7g4** [comment]
Thanks for the pointers! I'll do some playing around and re-open this if I get stuck :)
