### ISSUE TITLE
Add support for double star / unpacking arguments list

### ISSUE THREAD

**Issue by janhancic** [thought-machine/please#2676]
Python supports the "double star" or more formally known [Unpacking Argument Lists](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists) syntax.

This can be used, for example, to call a function with named arguments based on a dict.

```python
def bob(a, b):
  print(a, b)

bob(**{"a": 1, "b": 2})
```

Note that the same works for lists (with a single star syntax).

This can make code easier to write / read and would be a welcome addition to the Please language.

**Comment by peterebden** [comment]
It's a deliberate decision not to include this in asp (Please's build language). There are many things in Python that aren't in it (e.g. floats, `map`, `filter`, exceptions, `async`, etc); a language for scripting a build system can (and should) be more minimal than a general-purpose programming language.

On Python's splat operator specifically, it does have utility, but it does also obscure what is going on. Specifically one thing I don't like is that it becomes very hard to understand what you can pass to a function when it just takes `**kwargs`; that prevents things like `plz help` from telling you anything useful about it; hence I'd argue that in most cases it makes code _harder_ to read or write. It feels like this is getting "too clever" in asp.

I strongly feel we shouldn't add this.

**Comment by janhancic** [comment]
If we were to implement this; would we have to implement both kwargs and the unpacking functionality? To clarify here I'm only proposing the latter, which only makes calling functions easier and I'm not proposing we implement the former. But appreciate they might be linked together in how asp is implemented.

**Comment by peterebden** [comment]
They're not, but if it's implemented just for unpacking, there will be an assumption that it "should" happen in the other case as well.

**Comment by janhancic** [comment]
I suppose some could. But then, _I_ assumed this already works :)

Don't feel strongly about this, so if you think this will create more trouble than it's worth I'm happy for this to be closed.
