### ISSUE TITLE
FYI: there's a Skylark interpreter in Go

### ISSUE THREAD

**Issue by alandonovan** [thought-machine/please#270]
I just learned of 'please' today, and I notice you're calling CPython 2.x in process.  You might be interested in a pure-Go implementation of Skylark here: github.com/google/skylark.  It has certain benefits relative to Python:
- no GIL, so you can execute multiple threads in parallel, which can make the loading phase (BUILD file execution) and dependency analysis (rule.implementation function execution) much faster.  
- restricted import, no OS access, etc
- control over mutability, so no possibility of a data race, despite familiar imperative paradigm.
- compatibility with Bazel.

I gave a talk on it: https://www.youtube.com/watch?v=9P_YKVhncWI

cheers
alan

**Comment by peterebden** [comment]
Thanks for the heads up! (and to @rsc also in the linked issue)

Indeed I would like a better solution; of the things you mention, `import` is already prohibited, but the GIL and speed issues from crossing the Go-C-Python boundary are pretty suboptimal - plus the build-time dependencies and requirement for C shims for some parser actions aren't ideal either.

I've got a replacement which is fairly close to being ready to meet the world, but wouldn't mind being able to borrow other work if it saves me effort :) I'm not that familiar with Skylark in detail (it post-dates my experience of Blaze) so would need to do some investigation to know how well it matches what we're after. I suspect I'm likely to pinch at least the parser to begin with...

Thanks again!

**Comment by peterebden** [comment]
After looking at Skylark in more depth and writing a bit of code, I've got a better understanding of how it fits.

Unsurprisingly, it's very similar to what we already support. Some notes on differences:

- The lambda and nested function flags are, of course, required. We could live without the former but the latter is pretty necessary (at least without some means of currying arguments...)

- The `raise` and `assert` statements aren't supported. I could live with replacing those with something akin to Bazel's `fail()` - given that those are going to become non-catchable anyway, `raise` is a bit of a misnomer, and being able to raise different types has no value without `except`.

- PEP-3107/484 style function annotations aren't supported. They only landed with our new engine a few days ago but I like them a lot better than the previous generated assert hackorama. Essentially what we want here is some way of giving users sensible error messages ("srcs needs to be a list, not a string") if they accidentally pass the wrong thing - and for that same mechanism to be available for additional rules too. It looks like Bazel does something along those lines with the `attrs` argument to `rule()`.

- `for` and `if` statements aren't allowed outside functions, which we do permit (and use) at present. It's certainly possible to move them into functions (or comprehensions, if your tastes run that way), but I guess there's some debate there about being able to "just do what you want" versus factoring out everything and having "clean" BUILD files.

- Implementing `subinclude()` seems difficult at present. The semantics are similar to `load()`, most of which I can deal with, but I really need to be able to invoke `load()` programmatically, which AFAICT can't be done at present. Probably this is best discussed as an upstream issue.

That's rather fewer issues than I expected, which is nice. Overall it seems fast and robust, although I still need to get the integration into a better state of workingness (particularly the lack of `subinclude` makes it tough to test many non-toy cases).

**Comment by alandonovan** [comment]
On 5 February 2018 at 08:42, Peter Ebden <notifications@github.com> wrote:

> After looking at Skylark in more depth and writing a bit of code, I've got
> a better understanding of how it fits.
>
> Unsurprisingly, it's very similar to what we already support. Some notes
> on differences:
>
>    -
>
>    The lambda and nested function flags are, of course, required. We
>    could live without the former but the latter is pretty necessary (at least
>    without some means of currying arguments...)
>
> I put the lambda and nested def features behind a flag for compatibility
with Bazel's Skylark, but IMHO the restriction goes against good taste in
language design and is overly restrictive in practice.

Nested def clearly subsumes most of the benefit of lambda, but it's much
easier to write good tests in Skylark itself if you can use
assert.fails(lambda: xxx), which is an important practical consideration.
If I had my way these would be first class features of the language. The
Skylark team is conservative about language features, but that conservatism
sometimes manifests as additional restrictions rather than simplicity (a
system completely describable in fewer rules).




>    - for and if statements aren't allowed outside functions, which we do
>    permit (and use) at present. It's certainly possible to move them into
>    functions (or comprehensions, if your tastes run that way), but I guess
>    there's some debate there about being able to "just do what you want"
>    versus factoring out everything and having "clean" BUILD files.
>
> Another example of the same phenomenon. The stated motivation for these
restrictions is that if/for statements at top level break the current
invariant that every module-level variable has exactly one definition,
which, it is claimed, helps users find what they are looking for.  But Bazel
already implements a static check on BUILD and *.bzl files to enforce
dialect differences such as "no def in BUILD files", and that seems like
the logical place to add the "no if/for at toplevel" check, rather than in
the core interpreter.  (I am not arguing against the benefits of Bazel
enforcing BUILD vs *.bzl dialect differences; they have been very valuable
in practice.)



>    -
>
>    Implementing subinclude() seems difficult at present. The semantics
>    are similar to load(), most of which I can deal with, but I really
>    need to be able to invoke load() programmatically, which AFAICT can't
>    be done at present. Probably this is best discussed as an upstream issue.
>
>
By "programmatically", do you mean conditionally, or with a computed
argument?  Requiring imports to be statically analyzable makes it possible
to parallelize and prefetch BUILD files during the loading phase.  It's
also easier to understand.  (Blaze went to a great deal of trouble to
remove "#include X", where X is a macro symbol, from the C++ code base, for
similar reasons.)



>    - That's rather fewer issues than I expected, which is nice. Overall
>    it seems fast and robust, [...]
>
> Glad to hear that.  Do let me know what the rest of your experience using
it is like.

**Comment by peterebden** [comment]
> But Bazel already implements a static check on BUILD and *.bzl files to enforce
> dialect differences such as "no def in BUILD files", and that seems like
> the logical place to add the "no if/for at toplevel" check, rather than in
> the core interpreter.
Does that argue in favour of "toplevel if/for" becoming an optional flag as well? Or is that too intrusive a change to be configurable that way?

> By "programmatically", do you mean conditionally, or with a computed
> argument?  Requiring imports to be statically analyzable makes it possible
> to parallelize and prefetch BUILD files during the loading phase.  It's
> also easier to understand.  (Blaze went to a great deal of trouble to
> remove "#include X", where X is a macro symbol, from the C++ code base, for
> similar reasons.)
The latter, really; I suppose technically it is possible for us to do the former at present but I'm pretty certain we never do (through, hopefully, good taste as well as just never needing to!).
The way it works in plz is 
```
subinclude("//build_defs:my_rules")
```
which takes the output of that target (building it if necessary) and adds its contents into the current environment. So it's roughly equivalent to a `load()` on a computed destination file which automatically loads all symbols, although in some ways more powerful because its contents can be generated from an arbitrary build action. I can see why the Bazel team might not want to do it this way, although it's an important part of the character of plz.

Hence the issue I have is that having gotten into my builtin and handled the is-it-built logic and computed the destination, I can't then go on to invoke `load()` on the result. Is that something you'd consider adding? Presumably the capability would be limited to builtin functions so the implementation could decide whether they wanted to allow something like that or not.

**Comment by alandonovan** [comment]
On 5 February 2018 at 11:18, Peter Ebden <notifications@github.com> wrote:

> Does that argue in favour of "toplevel if/for" becoming an optional flag
> as well?
>
> Not a flag, but a private feature of Bazel that runs between parsing and
execution.  I'd have to talk it through with the Skylark team though, as it
may have implications I haven't thought of.


> The latter [computed argument], really; I suppose technically it is
> possible for us to do the former at present but I'm pretty certain we never
> do (through, hopefully, good taste as well as just never needing to!).
> The way it works in plz is
>
> subinclude("//build_defs:my_rules")
>
> which takes the output of that target (building it if necessary) and adds
> its contents into the current environment. So it's roughly equivalent to a
> load() on a computed destination file which automatically loads all
> symbols, although in some ways more powerful because its contents can be
> generated from an arbitrary build action. I can see why the Bazel team
> might not want to do it this way, although it's an important part of the
> character of plz.
>
> Hence the issue I have is that having gotten into my builtin and handled
> the is-it-built logic and computed the destination, I can't then go on to
> invoke load() on the result. Is that something you'd consider adding?
> Presumably the capability would be limited to builtin functions so the
> implementation could decide whether they wanted to allow something like
> that or not.
>
Your application is free to provide whatever implementation of Load("string
literal", a="b", c="d") you like, so long as the first argument is a string
literal (as it is in your subinclude example) and the set of locally bound
names is explicit, which is *not* true of your example but perhaps could be
easily changed---after all, you need to know statically what names the
subinclude defines in order to write the code that follows.

**Comment by peterebden** [comment]
Hmmmm, so maybe I am missing something here; I am providing an implementation of Load which works fine for toy examples when I have a load statement in a BUILD file. The problem I have is that I can't access that in any other way; I can call my Load implementation but have no way of telling the Thread object to add the results of that to its locals.

**Comment by alandonovan** [comment]
On 7 February 2018 at 12:58, Peter Ebden <notifications@github.com> wrote:

> Hmmmm, so maybe I am missing something here; I am providing an
> implementation of Load which works fine for toy examples when I have a load
> statement in a BUILD file. The problem I have is that I can't access that
> in any other way; I can call my Load implementation but have no way of
> telling the Thread object to add the results of that to its locals.
>
The intrinsic behavior of a Skylark load statement is to fetch a module
identified by a string literal (e.g. by opening a file or database or
looking in a cache), to look up the specified names in the loaded module,
and to bind them to names in the loading module.  The Skylark program must
specify the module identifier, the set of names to look up, and the set of
names to bind, all in the load statement, but the application can control
how the module identifier is mapped to a module.

BTW, all of these names are "global" aka "module-level", not "local".

Please's 'subinclude' (which Bazel no longer supports) magically defines a
bunch of names in the current block without declaring them.  You can't do
that in a statically scoped language like Skylark.

**Comment by peterebden** [comment]
Thanks, I was hoping that the requirement of names on load() could be circumvented by reading the file and telling it to load all the top-level names from it, but I guess not.

**Comment by peterebden** [comment]
For now the work I've done on integrating it is on the `skylark` branch, if anyone's curious.

**Comment by alandonovan** [comment]
I added a few comments.

**Comment by laurentlb** [comment]
Migrating from subinclude to load is indeed a lot of work (I was in charge of the migration inside Google). But it has lot of benefits in terms of maintenance costs, tool-ability, and performance.

Note that Buck build system (from Facebook) is also doing the migration:
https://github.com/facebook/buck/issues/1750#issuecomment-363617385
