### ISSUE TITLE
pleasew detects incompatible architecture name on (my) Intel mac

### ISSUE THREAD

**Issue by cbwl** [thought-machine/please#2717]
I've noticed that `pleasew` doesn't seem to correctly infer a please-compatible architecture name on my Intel Mac. The result is that `pleasew` fails to correctly download please.

The problem seems to lie in the way that `ARCH` is inferred on Darwin systems:

```
if [ "${OS}" = 'Darwin' ]; then
    # switch between mac amd64/arm64
    ARCH="$(uname -m)"
else
    # default to amd64 on other operating systems
    # because we only build intel binaries
    ARCH='amd64'
fi
```

On my Intel Mac (2019 MBP running Ventura), the output of `uname -m` is is `x86_64`, which results in `pleasew` using an invalid URL to try to fetch please and getting a 403:

```
...
+ printf '%bDownloading Please %s to %s...%b\n' '\x1B[32m' 16.27.2 .../.please/16.27.2 '\x1B[0m'
Downloading Please 16.27.2 to .../.please/16.27.2...
+ mkdir -p ../.please/16.27.2
+ curl -fsSL https://get.please.build/darwin_x86_64/16.27.2/please_16.27.2.tar.xz
+ tar -xJpf- --strip-components=1 -C .../.please/16.27.2
curl: (22) The requested URL returned error: 403
...
```

Note that this seems to relate to the newer POSIX-rewrite of `pleasew`; the older version only had support for `amd64` and so doesn't suffer the same issue.

This should be a fairly trivial thing to fix, and I'm happy to raise an MR, but not sure if anyone has particular feelings about how they prefer it fixed.

**Comment by scheatkode** [comment]
Hey @cbwl. My apologies, this somehow flew under my radar. #2719 should fix this along with some other minor enhancements.
