### ISSUE TITLE
watch & run functionality?

### ISSUE THREAD

**Issue by natpen** [thought-machine/please#272]
Hello again! :wave: 

I see there is `plz watch` functionality built into please as a result of #118  - I don't see this covered in the documentation, but from reading through the code it looks like it will watch the filesystem for changes, rebuild, and test if possible.

One thing we've been playing with the past few days is running a python/flask web app through please (which has been its own fun adventure in the interplay between gunicorn and pexes), and we were wondering if you had given any thought to the viability/usefulness of `watch&run` type functionality, as opposed to the current `watch[&test]`?

**Comment by peterebden** [comment]
Ahhh, someone must have completely forgotten to add that to the docs :)

I have idly thought of watch&run in the past, it makes quite a bit of sense but just never got around to doing it. The current functionality autodetects whether to test or not which is a bit less trivial for run - but I'd not be against adding a flag for it. That shouldn't be very hard (just needs flags changing in `src/please.go` and plumbing into `src/watch/watch.go`).
