### ISSUE TITLE
Investigate glob() speed 

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#273]
Suggestion from alandonovan:

> FYI: in my own experiments I have found that glob is crucial to performance, and that you can do much better by avoiding filepath.Walk and even os.Readdir and doing the recursion yourself directly over the Linux or Darwin getdents system call, which gives you the name and isdir bit of every entry in an entire directory each file in a single system call.

I've not looked at optimising it in any detail, but if we can make it faster that would be cool. The returned values probably still need to be deterministic though (since srcs preserve their original order - we could also change that but I'm sure we rely on that somewhere).

**Comment by dgryski** [comment]
Upstream issue is https://github.com/golang/go/issues/16399
