### ISSUE TITLE
Go rules don't respect Go build constraints

### ISSUE THREAD

**Issue by tomlanyon** [thought-machine/please#275]
As far as I can tell, the current Go build rules in Please don't support filtering source files using Go's [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) because they directly call 'go tool compile', 'go tool link', etc.

Should be simple enough to filter the source files through [MatchFile](https://golang.org/pkg/go/build/#Context.MatchFile), but I couldn't see an appropriate way to hook this into the current rules.  Can you suggest the best place to hook in such a filter?

**Comment by peterebden** [comment]
Correct, they do not. We could pretty easily support the filename restrictions in the existing rule (in go_rules.build_defs) by comparing filenames to `CONFIG.OS` and `CONFIG.ARCH`.

Supporting tags inside the file is more work, we'd need another helper binary to perform that parsing and then `exec` into the real compiler. That's doable, we have a few such binaries already (e.g. one for templating Go test files), it's just more work to code it all up.
