### ISSUE TITLE
Propagation of cross-compilation parameter

### ISSUE THREAD

**Issue by mkiefel** [thought-machine/please#2763]
I am wondering if I am using `plz` wrong. I try to cross compile with the `cc` plugin. I set up the compilers in the respective config, but it seems the special architecture parameters are lost during the propagation through `plz`.

Example:

`.plzconfig`

```
[Plugin "cc"]
Target = //plugins:cc

CCTool = gcc
CPPTool = g++
LDTool = ld

DefaultOptCppFlags = --std=c++17 -O3 -pipe -DNDEBUG
DefaultDbgCppFlags = --std=c++17 -g3 -pipe -DDEBUG
```

`.plzconfig_linux_arm64`

```
[Plugin "cc"]
CCTool = this-executable-does-not-exist
CPPTool = this-executable-does-not-exist
LDTool = this-executable-does-not-exist
```

`BUILD`

```bazel
subinclude("///cc//build_defs:cc")

cc_binary(
  name = "magic_bin",
  srcs = [
    "magic_bin.cc",
  ]
)
```

`plugins/BUILD`

```bazel
plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.3.2",
)
```
`magic_bin.cc`

```cpp
#include <iostream>

int main() {
  std::cout << "magic happens here\n";
  return 0;
}
```

Building produces a binary for both the host architecture (that's `linux_amd64` for me) and the target architecture (`linux_arm64`). But it really should not, as the set compilers and linker in the architecture configuration do not exist. So the two call below succeed:

```
plz build //:magic_bin
plz build -a linux_arm64 //:magic_bin
```

I built `plz` from source and tried the distributed version. I was able to track the parameter loading throughout the code: it is loaded correctly and the plugin configs are merged into a specific arch state. But then somehow the build state seems to forget the plugin's extra values when it comes to creating the `CONFIG` context.

Does anybody have some more pointers for me on how to fix this?

**Comment by Tatskaari** [comment]
Looks like what you're doing should work. I can reproduce locally. Let me see if I can get a fix out.

**Comment by mkiefel** [comment]
Thank you!
