### ISSUE TITLE
Go: Can't embed with go:embed all:

### ISSUE THREAD

**Issue by mibzman** [thought-machine/please#2806]
When building a go project that uses the `//go:embed all:FOLDER` syntax, I get the following error:

```
failed to generate embed config: pattern all:FOLDER: no matching paths found
```

For a reproduction, check out [my fork](https://github.com/mibzman/please) and run `plz test //rules:rules_test`

Removing the `all` from the embed passes the test suite.

**Comment by peterebden** [comment]
This isn't stale but it's going to be handled in the issue created above (https://github.com/please-build/go-rules/issues/112)
