### ISSUE TITLE
--include doesn't work as expected with `plz gc`

### ISSUE THREAD

**Issue by RichardoC** [thought-machine/please#2812]
# What I expected to happen
plz gc will only show dangling targets which have the label provided in --include

# What actually happened
plz gc shows all dangling targets in that path, regardless of labels

Redacted example below
```console 
$ plz gc --include=some_label  //some/folder/... --targets_only
...
//some/folder:target_a

$ plz query print //some/folder:target_a
# //some/folder:target_a:
some_rule(
    name = 'target_a',
...
    labels = ["a-different-label",],
)
```

**Comment by peterebden** [comment]
I suspect what is happening here is that `--include` is used to determine the original set of targets to look at the dependencies of to GC and not to filter the list later on. Maybe that's unintuitive here but the `--include` / `--exclude` stuff is a general mechanism shared between all commands, so the meaning here isn't specific to GC.

You could probably still achieve what you want by piping through `plz query filter`.
