### ISSUE TITLE
What's the correct way to use the new proto rules?

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#2846]
Hi,

I created a new repo to repro this issue: https://github.com/linuxerwang/plz-exercise.

Running `plz build protos/data` it shows:

```
$ plz --version
Please version 17.1.0

$ plz build protos/data
Build stopped after 880ms. 1 target failed:
    ///go_proto//build_defs:go_proto
Parsed build file plz-out/subrepos/plugins/go_proto/build_defs/BUILD but it doesn't contain target go_proto (depended on by //:all)
```

It will be very helpful if there is a codelab for how to use proto rules.

Thanks!

**Comment by Tatskaari** [comment]
Ah, did you use `plz init plugin go-proto`? That plugin isn't meant to be used directly but it looks like it's added the preload for a build def using the naming convention `///plugin_name//build_defs:plugin_nam`. I suppose we should rename the build rule here from `:go` to `:go_proto`: 
https://github.com/please-build/go-proto-rules/blob/master/build_defs/BUILD

In the meantime, here's a patch that should be able to `git apply` get you going:

[fix.txt](https://github.com/thought-machine/please/files/11957432/fix.txt)

**Comment by Tatskaari** [comment]
BTW i see you're using `go_module()`. We're trying to phase that out slowly, replacing it with `go_repo()`. If you want to see how that works with grpc, and protobuf, you can have a look here:
https://github.com/thought-machine/please-servers

**Comment by linuxerwang** [comment]
Thank you, Tatskaari. It almost worked except requiring grpc-go plugin:

```
$ plz build protos/data:data 
Build stopped after 140ms. 1 target failed:
    //protos/data:_data#protoc_go
grpc_go_plugin not found in path ...
```

I'll make it work and try to create a codelab.

**Comment by Tatskaari** [comment]
> I'll make it work and try to create a codelab.

That would be very much appreciated :) I've been pulled into some vulnerability remediation workstream so I've not got much time to do it myself at the moment.
