### ISSUE TITLE
Subinclude with build_rule() causes runtime error

### ISSUE THREAD

**Issue by clintharrison** [thought-machine/please#287]
I came across this trying to write a rule that outputs `pip_library()`s from a `requirements.txt` file, but it seems to be a more fundamental issue. Now that we're using the new parser, using `subinclude()` to include build definitions with a `build_rule()` causes a runtime error:

```
$ ./pleasew build //bar/...
Build stopped after 40ms. 1 target failed:
    //bar:all
bar/BUILD:1:1: error: runtime error: invalid memory address or nil pointer dereference

subinclude('//foo')
^

Traceback:
plz-out/gen/foo/foo.build_defs:1:1:   build_rule(name = 'foo')
                     bar/BUILD:1:1:   subinclude('//foo')
```

In `foo/BUILD`:
```python
genrule(
    name = 'foo',
    outs = ['foo.build_defs'],
    cmd = 'echo "build_rule(name = \'foo\')" > $OUT',
    visibility = ['PUBLIC'],
)
```
`bar/BUILD`:
```python
subinclude('//foo')
```

**Comment by peterebden** [comment]
Thanks for the report! I like the idea of converting a requirements.txt to `pip_library` rules...

I've added a check for this case so it will fail with a more useful error. I don't think it will work directly though - a limitation of the implementation is that the subincluded file can't generate new build rules automatically. It should work if it defines a function that's called in the BUILD file though?

**Comment by clintharrison** [comment]
Cool, thanks for the change! The error looks good to me now :)

On the topic of the `pip_library` rules, I have an initial attempt that _works_, but I'm not confident it's ready to be used by a larger repo. There are some issues around separating different versions of pip dependencies between different packages in the same repo. (This is potentially related to the topic of workspaces/external dependencies that was mentioned in the Google group, so I will continue the conversation there 🙂).
