### ISSUE TITLE
Codelab for Go fails at Third Party Dependencies section for Go 1.20.7

### ISSUE THREAD

**Issue by pauldruce** [thought-machine/please#2891]
I'm working my way through the codelab for Go, and when I try running this command:
`plz run ///go//tools/please_go -- get github.com/stretchr/testify@v1.8.2`

I'm hitting this error: 
```
❯ plz run ///go/tools/please_go -- get github.com/stretchr/testify@
Build stopped after 60ms. 1 target failed:
    ///go/tools/please_go//:please_go
///go/tools/please_go//:please_go depends on //go/tools:all, but the directory go/tools doesn't exist: go/tools
```

I can't seem to find a resolution any where online. Can anyone assist me?

**Comment by samwestmoreland** [comment]
Hey Paul, can I ask what versions of the go plugin and please you are on? It looks like somewhere the wrong dependency is getting pulled in. It should be resolving `//go/tools` relative to the plugin and not relative to the host repo.

**Comment by pauldruce** [comment]
So this the content in my `plugins/BUILD'
```
plugin_repo(
  name = "go",
  revision = "v1.8.1",
  plugin = "go-rules",
  owner = "please-build",
)
```

I'm using please version 17.0.0.

**Comment by pauldruce** [comment]
So using please 17.3.0, this seems to have been fixed.

**Comment by canuck3141** [comment]
I realize this issue is closed but I'm seeing failures at this same step for please 17.8.3 [here](https://github.com/thought-machine/please/issues/3116).  Any ideas?

**Comment by Tatskaari** [comment]
This has been fixed here: https://github.com/thought-machine/please/pull/3118/files
