### ISSUE TITLE
get.please.build is missing the top-level redirect

### ISSUE THREAD

**Issue by robxu9** [thought-machine/please#2905]
Looks like in the past few days https://get.please.build doesn't return a script anymore and 404s - it returns "Access Denied" for me now.

edit: If I hit https://get.please.build/get_plz.sh directly, that works fine. But the instructions for please usually point to curling https://get.please.build directly, which now fails.

**Comment by peterebden** [comment]
cc @Tatskaari looks like a casualty of the switchover - we probably need a redirect at the root

**Comment by Tatskaari** [comment]
Ah oops! It's been fixed now. Thanks for raising.
