### ISSUE TITLE
Please LSP's autocompletion lost first character when inserting into neovim buffers

### ISSUE THREAD

**Issue by xulongwu4** [thought-machine/please#2906]
https://github.com/thought-machine/please/assets/16892446/4981e535-3bf4-4827-9119-dd53f6887e67

When using Please LSP with neovim (nvim-cmp or omni-complete), the selected completion item is not inserted correctly. As shown in the gif, I selected the item `check_config`, but got `heck_config` as the result. The first character `c` is lost.

**Comment by izissise** [comment]
I have the same issue using Kate editor.
Looking a bit at the source code, it seems that the dependency https://github.com/tliron/glsp isn't maintained anymore.
One of the issue there mention a compatible library https://github.com/tliron/glsp
Not sure it would solve the issue though
