### ISSUE TITLE
Allow emitting new genrules within genrule

### ISSUE THREAD

**Issue by izissise** [thought-machine/please#2908]
Description:
In certain large-scale projects, such as those with their own intricate build systems (e.g., Linux kernel), a challenge arises when incorporating Please for build automation. Specifically, whenever there is a need to modify specific configuration files the entire target faces a cache invalidation, leading to a complete recompilation. Adapting the existing build system to Please rules is often impractical and unfeasible.

Proposal:
To enhance Please's adaptability for diverse projects, it is proposed to introduce a feature that allows the dynamic emission of `genrule` within a `genrule`. This capability would allows users to incorporate their existing build systems into Please, avoiding the need for extensive rule rewrites.

Example:
```
genrule(
    name = 'example_rule',
    tools = {
        'GENRULE': [CONFIG.GENRULE_TOOL],
    },
    srcs = {
        'CONFIG': ['./config_file'],
    },
    outs = ['output_file'],
    cmd = """
        set -eux;
        # Custom logic to process 'CONFIG' and generate dynamic rules
        ...
          # Emit dynamic genrules
            export CC="$TOOLS_GENRULE cc"
            export AR="$TOOLS_GENRULE ar"
            export GCC="$TOOLS_GENRULE gcc"
            make
    )
""",
)
```

**Comment by peterebden** [comment]
I'm not quite sure I understand this one, sorry. What is it that doesn't work about the second example at present? You can create a genrule and attach its outputs as a tool to another action, I think I must be missing some subtlety about what you mean with it.

**Comment by izissise** [comment]
Sorry, I sometimes have ideas that I have hard time describing, I edited the text with the help of chatGPT, I hope it is clearer now

**Comment by izissise** [comment]
Actually it might be implementable using subinclude

**Comment by izissise** [comment]
Yes going deeper into the code, it is what plugins do. I just wish it would be doable for Makefiles aswell
