### ISSUE TITLE
Can plz be turned to a reusable go library from a go app ?

### ISSUE THREAD

**Issue by yassinm** [thought-machine/please#2964]
Hi all

Thank you so much for working on this tool.

Plz seems to be a standalone tool, and not necessarily something someone can import into their own app and (re)use it as a go library. I see 2 approaches in order of complexity

1)  expose code [here](https://github.com/thought-machine/please/blob/2ed5063b6fb7e846afd97e3b8f457278c82d925e/src/please.go#L1548)  as a public function . This would be the minimal approach

2) provide a way for plz to accept go's new fs.FS interface as input. This would make the tool (potentially) read/write to an in memory file system as opposed to the standard fs.

The tool i am writing currently depends on make :-(. At start up it generates a big make file then starts `make` as a forked process. Ideally i would want to not require someone to have make as a dependency. Also since all the files are generated before starting make/plz i was thinking that i could pass this generated file system to plz.

I am wondering if the team would accept patches that make plz reusable as a go library in any way possible ?

**Comment by Tatskaari** [comment]
You can in theory use the following function to run a please build:
https://github.com/thought-machine/please/blob/master/src/plz/plz.go#L28

For some unknown reason, `go get` doesn't get the latest version. You have to specify a commit like so:
`go get github.com/thought-machine/please@2ed5063b6fb7e846afd97e3b8f457278c82d925e`

Don't expect us to support this very well though. We may make breaking changes at any point in minor versions. The only thing covered by semver is the CLI and BUILD file API.

**Comment by yassinm** [comment]
>Don't expect us to support this very well though. We may make breaking changes at any point in minor versions. The only thing covered by semver is the CLI and BUILD file API.

Completely understand the above.

Thank you for that pointer i will see how i can use it.
