### ISSUE TITLE
Get parser to provide line number and source file etc. with errors like "Non-iterable type %s; must be a list"

### ISSUE THREAD

**Issue by samwestmoreland** [thought-machine/please#2998]
From a brief look at the code, I think this ought to be possible as we know what Expression we're parsing at the time of the error. It's just a question of whether we can get a FilePosition from the Expression's Pos.

**Comment by peterebden** [comment]
We should already do this, the parser has a bunch of error-handling code to provide line numbers & a (somewhat pseudo) stack trace etc.

**Comment by peterebden** [comment]
Yup it's a regression in 17.4.0:
```
$ plz query print //src:please
10:08:15.071   ERROR: //src:please failed:
Non-iterable type str; must be a list
Build stopped after 20ms. 1 target failed:
    //src:please
```
vs 17.3.0:
```
$ plz query print //src:please
10:08:29.870   ERROR: //src:please failed:
Non-iterable type str; must be a list
Build stopped after 20ms. 1 target failed:
    //src:please
src/BUILD.plz:52:1: error: Non-iterable type str; must be a list

for x in "abc":
^
    log.debug(x)
```
I suspect this might be a similar area to what I'm currently looking into.
