### ISSUE TITLE
.plzconfig key with empty value

### ISSUE THREAD

**Issue by izissise** [thought-machine/please#3095]
Before v17.8.1, I was able to have empty value for a key in .plzconfig and check its emptyness:

```.plzconfig
[buildconfig]
XXXX =
BBB = hello
```

```
if CONFIG.XXXX:
...
```

But now (v17.8.1) I get the following error:
```
error: Config has no such property XXXX
```

I this intended behavior? Is there a workaround to test if a key is present in config?

**Comment by peterebden** [comment]
No it's not intended, what you were doing is legit - this seems to be #3092 (which wasn't supposed to tag the release, but it looks like the build before flaked).

**Comment by izissise** [comment]
As a workaround
```
if ("XXXX" in CONFIG):
```

**Comment by izissise** [comment]
Thanks, I'll wait for 17.8.2 then :)

**Comment by peterebden** [comment]
Let's use this to track the fix :)
