### ISSUE TITLE
Third party dependencies fail to add with please_go

### ISSUE THREAD

**Issue by canuck3141** [thought-machine/please#3116]
I'm at [9. Third-party dependencies](https://please.build/codelabs/go_intro/index.html#8) and the step is failing:
```zsh
plz run ///go//tools/please_go -- get github.com/stretchr/testify@v1.8.2
Build stopped after 440ms. 1 target failed:
    ///go//tools/please_go/packageinfo:packageinfo
Error building target ///go//tools/please_go/packageinfo:packageinfo: exit status 1
tools/please_go/packageinfo/packageinfo.go, line 15, column 2: could not import slices (open : no such file or directory)
```

Any ideas why this is happening or how to fix this?  Thanks!

**Comment by canuck3141** [comment]
I wonder if this is related to [tools/please_go/packageinfo/packageinfo.go using slices here](https://github.com/please-build/go-rules/blob/master/tools/please_go/packageinfo/packageinfo.go#L15) because it looks like [slices only supports go 1.21 and higher](https://pkg.go.dev/slices?tab=versions) and in my please project I'm using go 1.20.14?

```go
// In third_party/go/BUILD
go_toolchain(
    name = "toolchain",
    version = "1.20.14",
)
```

Is it the case that `please_go` only supports go 1.21 and higher?

**Comment by canuck3141** [comment]
Yes, this seems to be it!  When I change my please go toolchain to go 1.22.1 things work:
```go
// In third_party/go/BUILD
go_toolchain(
    name = "toolchain",
    # version = "1.20.14",
    version = "1.22.1",
)
```

now I can run

```zsh
zsh> plz run ///go//tools/please_go -- get github.com/stretchr/testify@v1.8.2


go_repo(module="github.com/stretchr/objx", version="v0.5.0")
go_repo(module="gopkg.in/yaml.v3", version="v3.0.1")
go_repo(module="gopkg.in/check.v1", version="v0.0.0-20161208181325-20d25e280405")
go_repo(module="github.com/stretchr/testify", version="v1.8.2")
go_repo(module="github.com/davecgh/go-spew", version="v1.1.1")
go_repo(module="github.com/pmezard/go-difflib", version="v1.0.0")
```

But I still need to get please to work with go 1.20.14.  :-(

I am currently running please 17.8.3.  Does that only support go1.21 and higher?  And if so how can I get please_go to work with go 1.20.14?

Thanks!

**Comment by canuck3141** [comment]
This seems to be an issue with `please_go` [here](https://github.com/please-build/go-rules/pull/250/files) as slices wasn't added to go until 1.21 but that PR lists go 1.20?

**Comment by Tatskaari** [comment]
I think the codelab should be using `///go//tools:please_go` rathe than `///go//tools/please_go`. One uses the pre-built binary, and the other builds it from source. 

Though these days you can just use puku which should resolve this all for you with `puku sync -w`:
https://github.com/please-build/puku
