### ISSUE TITLE
Support for tab escape charcter missing.

### ISSUE THREAD

**Issue by cemeceme** [thought-machine/please#3163]
It is possible to create a string with a newline using `\n` in please strings, but not for a tab character with `\t`.
It is however still possible to use a literal tab character in string declarations to get the same effect, but saying that that is unreadable is putting it mildly.

For instance `stringWithTabs.lstrip(" 	")` is the current workaround to the missing tab escape character, which would much more legibly read `stringWithTabs.lstrip(" \t")` with the escape character.

**Comment by peterebden** [comment]
Yup agreed, this is just an oversight. Shouldn't be a hard fix - would be a nice small issue for someone newer to the codebase to pick up (either on our internal team or someone external)
