### ISSUE TITLE
Possible mistake in codelabs tutorial

### ISSUE THREAD

**Issue by brtn** [thought-machine/please#3304]
Maybe I am missing something but I don’t understand why “lines_words_and_chars” and “just_words” produce different results. They both seem to result in the same command to be executed.

https://github.com/thought-machine/please/blob/e8637eba7e4edaba3d0df8026ba2376d4d787dc7/docs/codelabs/genrule.md?plain=1#L285

**Comment by samwestmoreland** [comment]
`lines_words_and_chars` runs the default tool `wc` (`def word_count(name:str, file:str, wc_tool:str="wc") -> str`), whereas `just_words` passes `//tools:wc` as the tool to be used, which runs the `tools/wc.sh` bash script, which uses `wc -w`.

**Comment by brtn** [comment]
Oh, right. Sorry, I missed that in [step 5](https://please.build/codelabs/genrule/index.html#4) and was confused in [step 6](https://please.build/codelabs/genrule/index.html#5).

Thank you for the explanation.
