### ISSUE TITLE
Remove imp

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#356]
`imp` is deprecated and in Python 3.7 it issues warnings like:
```
plz-out/bin/test/python_rules/rule_main_pex.pex/__main__.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```
We use it for `imp.import_module`; see if we can replace it with `importlib`. Might be tricky since I don't think there's a direct equivalent; also think about how we handle python 2 - maybe that keeps using imp; one day we might rethink whether it's worth still supporting it.

**Comment by BNMetrics** [comment]
Resolved in [#358](https://github.com/thought-machine/please/pull/358)
