### ISSUE TITLE
Skylark support

### ISSUE THREAD

**Issue by ivucica** [thought-machine/please#357]
There's now a implementation of the [Skylark language] in Go: https://github.com/google/skylark

Would it make sense to support Bazel-like Skylark rule definitions, in addition to the existing Python-based `.build_defs`?

[Skylark language]: https://docs.bazel.build/versions/master/skylark/language.html

**Comment by peterebden** [comment]
Yup, this was brought up in #270 . Thanks for the suggestion!

Being able to support Bazel-like rule definitions would be nice, but I don't think porting in the Skylark interpreter achieves that. AFAIK we would still have to write the API to those (i.e. all the attributes & context stuff), Skylark would give us the interpreter but the language we support is very similar to that already.

The beginnings of a Skylark interpreter are still on a branch, although it is quite a ways from a working state still and is probably slowly bitrotting.
