### ISSUE TITLE
Support pkg-config for cflags only

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#361]
As discussed, `so_test` fails if compiled against a Python install that has static but not dynamic libaries available, as the ones distributed from python.org do.

Python extension modules don't actually need to be linked against libpython at all (because the symbols will already be provided by whatever loads them) and it is probably a better idea that they aren't. However this isn't easy to achieve right now - we need to use pkg-config to find the compiler flags (so we can `#include "Python.h"`) but then we use it at link time too.

Look at adding an option like `pkg_config_cflags` to `c_library` and `cc_library` which runs it just at compile time.

**Comment by BNMetrics** [comment]
This issue has been resolved with [#363](https://github.com/thought-machine/please/pull/363)
