### ISSUE TITLE
Coverage for python includes irrelevant files

### ISSUE THREAD

**Issue by BNMetrics** [thought-machine/please#364]
When running `plz cover`,  `coverage.json` report file currently includes files from `plz-out` directory, and it also includes generated file such as `__main__.py`.

Python coverage should be able to figure out which files to exclude from the coverage report.

**Comment by peterebden** [comment]
I think the plz-out part only applies to pytest; it seems fine for unittest (although the __main__.py still turns up and, as you say, it shouldn't).

**Comment by BNMetrics** [comment]
This ticket has been solved by [#367](https://github.com/thought-machine/please/pull/367).
