### ISSUE TITLE
--keep_workdirs is not honoured if the user interrupts a build

### ISSUE THREAD

**Issue by salimfadhley** [thought-machine/please#365]
**FAULT**

If please test --keep_workdir is allowed to complete normally, the work-dir is preserved as expected.

If the user interrupts please test, e.g. because he wishes to abort a non-terminating test, the work-dir is deleted even if the --keep_workdir option is specified.

**STEPS TO REPRODUCE**

Create a test which writes a file and then does time.sleep(99999)
Run please test --keep_workdir
Use CTRL-C to interrupt the test execution
Verify that the expected file is not present.

**EXPECTATION**

The --keep_workdir behaviour should be orthogonal to the manner in which the please test is terminated. In other words, the file should not be cleaned up.

**Comment by peterebden** [comment]
I can't reproduce this; the workdir remains for me whether I interrupt it or not. I'd expect that; there isn't any code to delete the workdir on Ctrl+C (i.e. it's not in a signal handler or something).
