### ISSUE TITLE
genrule tools does not use correct PATH when used with PassEnv

### ISSUE THREAD

**Issue by lewis6991** [thought-machine/please#375]
When `PassEnv = PATH`, genrule does not use the passed PATH when checking tools

```
genrule(
    name = 'sbt_jar',
    out = 'foo.jar',
    srcs = [...],
    cmd = ['sbt assembly'],
    tools = ['sbt'] # Causes error. Works when commented
)
```

**Comment by peterebden** [comment]
Fair. I suspect we apply the custom environment after PassEnv so any of them will get overridden (PATH, TMP_DIR, etc).
