### ISSUE TITLE
please build runs forever in case a dependency doesn't start with a coluimn

### ISSUE THREAD

**Issue by AlexPavy** [thought-machine/please#378]
In case we have : 
`go_library(
    name="mylib",
    srcs=[
        "mysrc.go",
    ],
    deps=[
        "//root/lib",
    ],
)`

a please build will run forever without an error shown

To fix it the dependency must be "//root:lib"

**Comment by peterebden** [comment]
I'm not quite sure I understand the issue here, sorry. With that example in a BUILD file I get:
```
Build stopped after 60ms. 1 target failed:
    //root/lib:lib
//src/cli:mylib depends on //root/lib:lib, but the directory root/lib doesn't exist
```
Is there some more context you can give? Maybe something else is affecting it and helping cause the hang?

**Comment by AlexPavy** [comment]
Yes, thanks and sorry, I  get the same message. 
 did get a build running forever before but I'm not sure what caused it so I close this.

**Comment by peterebden** [comment]
OK cool - will keep an eye out for that!
