### ISSUE TITLE
--nocolour is not respected

### ISSUE THREAD

**Issue by ruuda** [thought-machine/please#380]
Consider the following minimal `BUILD`:

```
new_http_archive(
    name = 'ghc_archive',
    urls = ['https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-deb8-linux.tar.xz'],
    hashes = ['sha1: 6a74b608bbe658d87c428304a42873cd2ad5f337'],
    build_file = "ghc.BUILD",
)
```

Output with and without `--nocolour`:

![nocolour](https://user-images.githubusercontent.com/506953/43800376-6d32d912-9a90-11e8-8d02-dd65f92b36e4.png)

This is using Please 13.0.3.

**Comment by peterebden** [comment]
Yup fair, some over-aggressive recolourising from the looks of it :)
