### ISSUE TITLE
Subrepos trying to register twice?

### ISSUE THREAD

**Issue by johnmarkwayve** [thought-machine/please#399]
I'm trying to use subrepos as documented [here](https://please.build/subrepos.html), but every time I try to build something using a subrepo, it tries to register the subrepo twice and dies with
```
CRITICAL: Subrepo [name] is already registered
```

The easiest way to reproduce this is using the pleasings repo (master at 9adc8f5b340ff517dd79048e724c40a0ed33bcae at time of writing):
```
git clone https://github.com/thought-machine/pleasings.git
cd pleasings
plz build @unittest_cpp//:unittest_cpp
```
This results in:
```
CRITICAL: Subrepo unittest_cpp is already registered
```
I get a similar effect with simple examples I write myself.

Version:
```
$ plz --version
Please version 13.1.1
```
(which is weird in and of itself, considering the latest version according to git is 13.1.0)

**Comment by johnmarkwayve** [comment]
Could somebody please confirm if this is a bug or if I am misunderstanding how to use subrepos?

**Comment by peterebden** [comment]
I've broken those changes out separately in #403 ; will do another release for that shortly.

**Comment by peterebden** [comment]
Whoops, not come back to this one for a while - but should all be more working now. Have tested the original example and it looks OK.
