### ISSUE TITLE
Allow aliases to run even if another please process is running

### ISSUE THREAD

**Issue by jameshiew** [thought-machine/please#400]
If there is an alias like so in `.plzconfig`
```ini
[alias "somecommand"]
cmd = run //commands/some:cli --
desc = Run a command
```

The following happens if doing `plz build` at the same time.
```
$ plz somecommand
12:28:15.467 WARNING: Looks like another plz is already running in this repo. Waiting for it to finish...
```

Ideally you could still run the alias.

**Comment by BNMetrics** [comment]
Hi @jameshiew,
If this is related to running two build simultaneously, this is not possible due to the lock we have in place. It is also not safe to run two builds at the same time due to possible shared dependencies.

Aliases are essentially a plz command as well.

**Comment by jameshiew** [comment]
Sometimes the alias is not related to plz or building e.g. it just reads logs from a container. Can we have it in that case?

**Comment by peterebden** [comment]
If it's not related to plz then they won't exclude one another.

The lock is acquired when a plz instance starts to build or test things. Your alias invokes `run //commands/some:cli` so it will need to acquire it as your other `plz build` does too. It will release it again before running the binary in question though.
