### ISSUE TITLE
Implement Language Server Protocol server

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#402]
https://langserver.org/

It's a protocol the vscode team came up with for providing IDE-agnostic completion / info / general smartness. We could provide that for BUILD files and get good support for a bunch of IDEs.

**Comment by BNMetrics** [comment]
I think this ticket can be closed as we are already in the process of making the language server! :)

**Comment by jpo-joyent** [comment]
@BNMetrics I see https://github.com/gtache/intellij-lsp/issues/40. Are you successfully using the language server with some Intellij IDE?
