### ISSUE TITLE
Issues with golang link support

### ISSUE THREAD

**Issue by agenticarus** [thought-machine/please#409]
Noticed a couple of little things that aren't working perfectly.

`go_binary`s do not get their sources linked. I don't have a particularly good solution for this as they are in package `main` and not anything more sensible.

`go_test`s get their sources linked twice, once in their directory and once in a subdirectory for the test name. The code in that directory doesn't work as it still has the original package name but no access to other files.

![image](https://user-images.githubusercontent.com/1618612/45689545-2eb01380-bb4c-11e8-8261-dfc7699fcb51.png)

**Comment by agenticarus** [comment]
Actually, thinking about it, just swapping the behaviour here (i.e. making that subdirectory for the `go_binary`s) would solve both problems at once

**Comment by peterebden** [comment]
I think the `go_binary`s should just get their sources linked into the same package they're originally in? It should be up to the user to structure their sources in a Go-like fashion (i.e. plz lets you mix packages with a little care but it's not really a great idea).

Not quite sure what's going on with the go_test thing but can look into it.
