### ISSUE TITLE
Q: genrule and gentest outputs

### ISSUE THREAD

**Issue by shomodj** [thought-machine/please#432]
Hi,

first of all I love this tool, I only wish there was a slack channel for community where I can ask some stupid questions :)

anyways, I'm trying to build and test infrastructure code in this case ansible and I have this

```
source = ['ansible.cfg']

genrule(
  name = 'build',
  cmd = [
    'for OUT in $OUTS; do cp ${PKG}/${OUT} $OUT; done',
  ],
  srcs = source,
  outs = source,
  visibility = ['PUBLIC']
)

gentest(
  name = 'lint',
  test_cmd = 'ansible-config view -c ansible.cfg',
  deps = [
    ':build'
  ]
)
```

now when I run `plz test //ansible:lint --shell` there are no files from `:build`
can someone `please` help me with this?

Thanks.

**Comment by peterebden** [comment]
Thanks! There is a [gitter channel](https://gitter.im/please-build/Lobby) although it's pretty quiet at the moment.

Adding `:build` to `deps` makes it a build-time dependency of the test. You want to add it to `data` instead, which makes it available to the test when it runs.

> can someone please help me with this?

I see what you did there... ;-)

**Comment by shomodj** [comment]
Thanks @peterebden
