### ISSUE TITLE
Is there any tool like Gazelle?

### ISSUE THREAD

**Issue by mishudark** [thought-machine/please#434]
I was wondering if there is a tool, to auto-generate BUILD files for Go projects like `gazelle` from bazel

**Comment by peterebden** [comment]
There's not. I imagine Gazelle might work for most things, but the third-party stuff might need some special attention.

I've also started prototyping out some code for external processes to provide this information - the concept being that something might "know" how to set up BUILD information for a repo and do the same thing but without having to actually write the files. There are definitely some complexities to get that working for real though.

**Comment by mishudark** [comment]
thanks for the clarify :)
