### ISSUE TITLE
jarcat missing -o option in pip_library rule?

### ISSUE THREAD

**Issue by packysauce** [thought-machine/please#436]
Using pip_library with a private pypi repo (pypicloud deployment, if I'm not mistakn), I'm coming up with this issue: pip outputs "successfully installed", but the command as a whole is returning error.

So far, I've run with -v debug, taken the environment + command to be run, tossed it into a script, and ran it with bash -x. That output is below.

Looking at the python build defs, it would appear there's no -o option, so that part kinda makes sense. The only oddity is that it works for public pypi stuff (aiozk and click so far) but not for my 2 private pypi things (even though the below command ends up with the correct stuff on disk). Only one dependency is shown - they both fail in the same manner.

Please don't hesitate in suggesting any additional debugging steps, or requesting more information.

Environment is docker thoughtmachine/please_ubuntu, pulling the tar.gz from github, extracting it to /root/.please.
```
+ LANG=en_GB.UTF-8
+ PATH=/usr/local/bin:/usr/bin:/bin
+ BUILD_CONFIG=opt
+ ARCH=amd64
+ GOARCH=amd64
+ GOOS=linux
+ OS=linux
+ XARCH=x86_64
+ XOS=linux
+ PKG=
+ PKG_DIR=.
+ NAME=_<company>-logging#wheel
+ CONFIG=opt
+ TMP_DIR=/tmp/code/plz-out/tmp/_<company>-logging#wheel._build
+ TMPDIR=/tmp/code/plz-out/tmp/_<company>-logging#wheel._build
+ SRCS=
+ OUTS=<company>-logging.whl
+ HOME=/tmp/code/plz-out/tmp/_<company>-logging#wheel._build
+ TOOLS=
+ PYTHONHASHSEED=42
+ OUT=/tmp/code/plz-out/tmp/_<company>-logging#wheel._build/<company>-logging.whl
+ TOOLS_PIP=/usr/bin/pip3
+ TOOLS_JARCAT=/root/.please/jarcat
+ '[' -f /etc/debian_version ']'
+ '[' /usr/bin/pip3 == /usr/bin/pip3 ']'
+ SYS_FLAG=--system
+ /usr/bin/pip3 install --no-deps --no-compile --no-cache-dir --default-timeout=60 --target=. --system -b build -f https://pypi.<company>.net/simple/<company>-logging --no-index --isolated <company>-logging==0.7.0
Collecting <company>-logging==0.7.0
  Downloading https://url redacted
Installing collected packages: <company>-logging
Successfully installed <company>-logging-0.7.0
+ find . -name METADATA -or -name PKG-INFO
+ grep -v '^./build/'
+ xargs grep -E 'License ?:'
+ cat
+ grep -v UNKNOWN
+ /root/.please/jarcat z -d --prefix . -i <company>-logging
<snip: jarcat help text omitted>

the required flag `-o, --output' was not specified

```

**Comment by peterebden** [comment]
Hmmm, I'm not quite sure what is wrong; the `-o` flag should inherit from the `$OUT` env var, as in:
```
[zip command options]
      -i, --input=                   Input directory
      -o, --output=                  Output filename [$OUT]
```
That looks to be being set correctly in the environment as well.

Might be useful to see the output from `plz build --shell //:_<company>-logging#wheel`, and could you please check that `echo $OUT` produces something sensible within that shell? Thanks!

**Comment by packysauce** [comment]
Phew. I sure am glad to have asked (build --shell is AWESOME). Got it fixed, though maybe error visibility could use some work, here's what I found:

The package name is <company>-logging, but what is extracted is in <company>_logging (note underscore vs hyphen). Simple enough, fix by setting `outs=["<company>_logging"]`

The licence grepping was failing silently, because these have UNKNOWN. Setting `licences=["UNKNOWN"]` took care of it. jarcat never even tried to run against the incorrectly named directories

Re: the original issue of "no output specified" I guess the build just got one step too far and I was confusing the end of one step with the start of another? In any event, I wasn't seeing the -o complaint this morning.

Was really unintuitive to find, until a good night's sleep and fresh eyes prompted me to use that build shell, and read over the pip_library code very closely.

If I were to make any suggestion, it would be to perhaps please could fail with errors that more directly pointing at what could be wrong. With licences correct, but outs wrong, we see: `CRITICAL: lstat <company>-exceptions: no such file or directory`, which is probably just this side of sufficient to track down the problem, but if licences is incorrect, even with `-v debug` to build, please just reports an error with the final message being pip's "successfully installed blah" message. Which, of course just incites anger involving expletives and "why did you fail, you just said it was successful"

**Comment by peterebden** [comment]
That's a fair point. The more complex build rules can indeed be a bit awkward to follow - it's a little hard to know how best to polish it since the commands are opaque to plz, but I'll have a think about it.
