### ISSUE TITLE
Roadmap/suggestions for adoption...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#440]
It is an understatement to say I'm pleased with the discovery `plz`, but I'm trying to come to terms with why I've never seen or heard of this build tool before now.  This looks like exactly what I've been searching for but at the same time, looks like there are few adopters.  Why is this not the new hotness that everyone is using?  I'm very confused.  Is this a lack of promotion of the utility or is there something that manifests itself as a mono repo grows?  As an adoption strategy, I'm considering the following:

1. `go run bootstrap.go` -- install `plz` and other required tools into `$GOPATH/bin/plz` or `./build` // inspired by `mage`'s [`bootstrap.go`](https://github.com/magefile/mage/blob/master/bootstrap.go) (we currently use `mage`)
2. `plz build`
3. Begin working from the edges of our build graph to our root, and eventually leaving only a `magefile.go` as a wrapper script around various `plz` targets

?  Short of going all-in and adopting everything all at once, is there a different, better way to begin incorporating `plz` into an existing repo?

Other questions include: why not use the standard `~/.config/please/config` path structure?  Mixing binaries with config files in `~/.please` gives me a little heartburn but isn't incurable.

Admittedly, I really want to like `plz`, but I'm running into a few rough edges around bootstrapping.

```
bash-3.2$ rm -rf .bootstrap/
bash-3.2$ ./bootstrap.sh
Installing Go dependencies...................
Compiling built-in rules...
Building Please...
Build stopped after 1s. 1 target failed:
    //src/help:config_json
Error building target //src/help:config_json: exit status 2
panic:  is not in dotted-tri format

goroutine 1 [running]:
github.com/coreos/go-semver/semver.Must(...)
	third_party/go/src/github.com/coreos/go-semver/semver/semver.go:64
github.com/coreos/go-semver/semver.New(0x0, 0x0, 0x12b9bc0)
	third_party/go/src/github.com/coreos/go-semver/semver/semver.go:48 +0x6f

exit status 255
```

Also, after downloading a new binary and giving it a twirl, I'm running into the following:

```
bash-3.2$ plz query changes
04:28:26.876   ERROR: All workers seem deadlocked, stopping.
Build stopped after 560ms. 3 targets failed:
04:28:26.876   ERROR: All workers seem deadlocked, stopping.
    //package:all
build_defs/signing.build_defs:12:16: error: Unknown argument to tarball: xzip
    """
    tar_rule = tarball(
               ^
        name = name,

Traceback:
build_defs/signing.build_defs:12:16:       tar_rule = tarball(

                package/BUILD:21: 1:   signed_tarball(
    //src/update:update
src/update/BUILD:61:1: error: Unknown argument to tarball: xzip

tarball(
^
    name = "test_tarball_xz",

    //test/cc_rules/gtest:all
test/cc_rules/gtest/BUILD:1:1: error: error calling package(): CC_TEST_MAIN is not a known config value

package(cc_test_main = "@gtest//:gtest_main")
^


04:28:26.877 WARNING: Package package does not exist in graph
04:28:26.877 WARNING: Package src/update does not exist in graph
04:28:26.877 WARNING: Package test/cc_rules/gtest does not exist in graph
04:28:26.880   ERROR: All workers seem deadlocked, stopping.
04:28:26.940   ERROR: //package:all failed:
Unknown argument to tarball: xzip
Build stopped after 630ms. 1 target failed:
    //package:all
build_defs/signing.build_defs:12:16: error: Unknown argument to tarball: xzip
    """
    tar_rule = tarball(
               ^
        name = name,

Traceback:
build_defs/signing.build_defs:12:16:       tar_rule = tarball(

                package/BUILD:21: 1:   signed_tarball(
```

I was able to work through most of that by commenting out various items:

```diff
diff --git a/build_defs/signing.build_defs b/build_defs/signing.build_defs
index 56b65234..e3a67de0 100644
--- a/build_defs/signing.build_defs
+++ b/build_defs/signing.build_defs
@@ -14,7 +14,7 @@ def signed_tarball(name:str, srcs:list, out:str, subdir:str, xzip:bool=False, vi
         srcs = srcs,
         out = out,
         subdir = subdir,
-        xzip = xzip,
+#        xzip = xzip,
         visibility = visibility,
     )
     return detached_signature(
diff --git a/src/update/BUILD b/src/update/BUILD
index a099202f..901366b4 100644
--- a/src/update/BUILD
+++ b/src/update/BUILD
@@ -65,5 +65,5 @@
     ],
     out = "please_test.tar.xz",
     subdir = "please",
-    xzip = True,
+#    xzip = True,
 )
diff --git a/test/cc_rules/gtest/BUILD b/test/cc_rules/gtest/BUILD
index 1a1cf1d2..f123c708 100644
--- a/test/cc_rules/gtest/BUILD
+++ b/test/cc_rules/gtest/BUILD
@@ -1,9 +1,9 @@
-package(cc_test_main = "@gtest//:gtest_main")
-
-cc_test(
-    name = "gtest_test",
-    srcs = ["gtest_test.cc"],
-    deps = [
-        "//test/cc_rules:lib2",
-    ],
-)
+#package(cc_test_main = "@gtest//:gtest_main")
+#
+#cc_test(
+#    name = "gtest_test",
+#    srcs = ["gtest_test.cc"],
+#    deps = [
+#        "//test/cc_rules:lib2",
+#    ],
+#)
```

and now `plz query alltargets` works, but the `query graph` target fails with its default target value (`plz query graph //src:please` works):

```
bash-3.2$ plz query graph
04:43:16.107 CRITICAL: Target @test_x86//src:please not found in build graph
```

I'm trying to baseline what the expectations are for what works vs what's unique about the `please` repository.  Thanks in advance.

**Comment by peterebden** [comment]
Thanks for the feedback!

> It is an understatement to say I'm pleased with the discovery plz, but I'm trying to come to terms with why I've never seen or heard of this build tool before now. This looks like exactly what I've been searching for but at the same time, looks like there are few adopters. Why is this not the new hotness that everyone is using? I'm very confused. Is this a lack of promotion of the utility or is there something that manifests itself as a mono repo grows?

I guess we can always do more to promote it. I intend to do so but it's a bit of a tradeoff with my day job :)
I am conscious that it's more work upfront than is demanded for some other languages (e.g. Go or Python) so the utility definitely increases in a larger monorepo.

> ? Short of going all-in and adopting everything all at once, is there a different, better way to begin incorporating plz into an existing repo?

The approach you propose sounds reasonable; I'm not very familiar with `mage` but it makes a lot of sense.

> Other questions include: why not use the standard ~/.config/please/config path structure? Mixing binaries with config files in ~/.please gives me a little heartburn but isn't incurable.

Fair. It would be easy to add a new location; I suppose we should be looking in appropriate places (e.g. using something like https://github.com/shibukawa/configdir to abstract platform details).

Fair points on the rest of it; the plz repo has lot of features in it for testing purposes. I suspect it is getting too far away from the latest "stable" release (too many betas!) which is causing most of your observations about things not working; hopefully we'll do 13.2.0 this week which should resolve those.

**Comment by agenticarus** [comment]
We have addressed the config location issue, Plz's adoption rate matches the level of support we can provide and we've made quite a few releases which have stabilised much of the underlying compilation features.
