### ISSUE TITLE
`plz hash --update` doesn't work if the name of the target is interpolated

### ISSUE THREAD

**Issue by macripps** [thought-machine/please#453]
```
maven_jar(
    name = "util-slf4j-api_%s" % SCALA_VERSION,
    hash  = "x",
    id = "com.twitter:util-slf4j-api_%s:%s" % (SCALA_VERSION, FINAGLE_VERSION),
)
```

then

 ```
$ plz hash  --update :util-slf4j-api_2.11                                                                   
Hashes calculated, total time 80ms:
  //third_party/java/com/twitter:util-slf4j-api_2.11: 734979164fa1d137bc0197a7da2911087fe35a0c
16:27:44.134 CRITICAL: Can't find target util-slf4j-api_2.11 to rewrite
```

**Comment by BNMetrics** [comment]
Thanks for flagging this.
I think this behaviour might be to prevent the hash being written twice, not 100% sure. 
However, I think you have got a good point, we should be able to update the hash if we wanted to.

thoughts? @peterebden

**Comment by peterebden** [comment]
It's not to prevent it being written twice, it's because the rewriter reads the AST to find the rule to update but does not interpret it so it can't understand non-trivial ways of generating the rule name.

Legit but probably not that easy to fix :(

**Comment by BNMetrics** [comment]
I can take a look if you'd like? @peterebden
