### ISSUE TITLE
Cross compilation Q's...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#454]
What's the right way to handle cross compilation?  I'm stumped on a few levels.  It looks like the intention is to *NOT* do the following (though this would be ideal on some level):

```python
go_library(
    name = "mypkg",
    srcs = [
        "foo.go",
        "@darwin_amd64:bar_darwin.go",
        "@linux_amd64:bar_linux.go",
    ],
    deps = [
        "//third_party/go:errors",
        "@linux_amd64//third_party/go:gopacket",
   ],
    visibility = ['PUBLIC'],
)
```

but instead something like the following appears to be expected to work:

```python
go_library(
    name = "linux",
    srcs = [
        "foo.go",
        "bar_linux.go",  # attempting to maintain go-getability
    ],
    deps = [
        "//third_party/go:errors",
        "@linux_amd64//third_party/go:gopacket",
   ],
    visibility = ['PUBLIC'],
)

go_library(
    name = "darwin",
    srcs = [
        "foo.go",
        "bar_darwin.go",
    ],
    deps = [
        "//third_party/go:errors",
   ],
    visibility = ['PUBLIC'],
)
```

with the caller using something like: `deps = ["@darwin_amd64/foo:darwin", "@linux_amd64//foo:linux"]`

But this results in:

```
% plz build //foo
Build stopped after 50ms. 1 target failed:
    @darwin_amd64//foo/bar:darwin
@darwin_amd64//foo/bar:darwin depends on //:all, but the directory  doesn't exist
```

The same is true when `-a linux_amd64` or `-a darwin_amd64` is passed to `plz build`.  Is there a better example of cross-compilation for a project using `plz` than the example?

**Comment by sean-** [comment]
@peterebden You're correct in that the above allows me to build a single project across environments (i.e. a user can type `plz build` on Linux or Darwin successfully).

What I really want to figure out is the syntax that allows me, on a a darwin host, to run the following `plz build -a linux_amd64` and have it produce a binary that has been cross-compiled for Linux.  We're currently doing this with a `mage` target that sets `GOOS` and `GOARCH` for all of our target architectures.  The problem is, it's not clear how we reflect that in our `BUILD` files, hence the contrived and broken example above.  If my entry-point into a BUILD file is the BUILD target named `foo`, how would I allow the `foo` target to include different `srcs` based on the target architecture?  I thought I could prefix a file name with `@linux_amd64` and have this work, but that's clearly not the case.  I tried using `foo` as a meta-target that would actually depend on a `foo_linux` and `foo_darwin` dependency, ala:

```python
go_library(
  name = "foo",
  deps = [
    "@linux_amd64:foo_linux",
    "@darwin_amd64:foo_darwin",
  ],
)

go_library(
  name = "foo_linux",
  src = [
    "foo_linux.go",
  ],
)

go_library(
  name = "foo_darwin",
  src = [
    "foo_darwin.go",
  ],
)
```

but that's sub-optimal, too.  Ideally there would be a lightweight lambda that I could use to mutate the list of `srcs` or `deps` based on the *target* architecture.

Thoughts?

**Comment by peterebden** [comment]
Ah I understand, thanks. You can tell that by interrogating bits of `CONFIG` like:
```
go_library(
    name = "foo",
    srcs = ["foo_linux.go" if CONFIG.OS == "linux" else "foo_darwin.go"],
)
```

(or potentially something like `f"foo_{CONFIG.OS}.go"` if you wanted to be more concise).

The BUILD file essentially gets re-parsed for the host & target architectures, so you can take different forks based on `CONFIG.OS` and `CONFIG.ARCH`. I initially tried to avoid that but it ended up being too hard, and I think the additional flexibility is worth having.

**Comment by sean-** [comment]
!  Thanks @peterebden, that was really helpful.  This feels a bit gross at times, but I think is Right Enough™.

If someone else stumbles across this issue and is curious, in addition to the above, you can do the following:

```python
% cat BUILD
if CONFIG.OS == "linux":
    go_library(
        name = "mypkg",
        srcs = [
            "foo.go",
            "bar_linux.go",
        ],
        deps = [
            "//third_party/go:errors",
            "//third_party/go:gopacket",
       ],
        visibility = ['PUBLIC'],
    )
```

The above two snippets in the cross-compile docs would have saved us a heap of time.
