### ISSUE TITLE
Finding out of date packages...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#456]
Has there been any thought with regards to having `plz` query repositories referred to via `go_get()` and having it report when there's a new version available?  One of the things that we get from `dep` is the ability to run `dep update -ensure` and have it report when there's a new version available.  Since we've copied git SHAs into various `BUILD` files, it would be really, *really* great if there were a way for `plz` to query the remote site and see if something has been updated or slipped.  For instance, right now we're pulling in `133` different externally referenced repositories via `go_get()`.  Are we expected to manage that by hand?

Has any thought gone into this particular problem?

Right now, I'm concerned that this is going to be a manual process to update every dependency by hand.  In the short term, since we just pinned everything, this isn't a huge problem, but I'd like to establish a periodic job to track updates to these libraries so we can stay current with everyone's updates.  I'm of half-a-mind to suggest that `plz-out/go/src/` be a symlink to `vendor/` so we can diff changes to our dependencies and still use `dep`, but that still leaves us with the problem of updating our `revision` SHAs.

Any commentary or light on this subject would be most appreciated.  Thanks in advance.

**Comment by BNMetrics** [comment]
Hi @sean- ,

Thanks for flagging this, and sorry for the late response.

I think it would be a great idea to allow automatic checking and upgrading of third_party packages. 

We could do the following:
1. having a plz command to upgrade package(s) to the latest version available. such as `plz upgrade //path/to/my/package:buildlabel`(upgrade the particular package) or `plz upgrade //path/to/my/package:all` (or all of them). This should upgrade all the SHAs or version numbers on the package.

2. As you mentioned earlier, you'd like `plz query deps` to have an option to check if there are any outdated thirdparty packages. I was thinking of having a flag like `plz query deps --outdated`, and this will output all the labels with outdated packages.

What do you think? and @peterebden, what's your thoughts?

**Comment by jpo-joyent** [comment]
I'm not sure about automatically updating the SHAs unless you store them in some separate location with a trivial format (see: e.g. Gopkg.lock).

Consider a BUILD of:
```
use_other_foo = True

if use_other_foo:
    foo_rev = "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33"
else
    foo_rev = "baadff03cf7417bbe3ce8e1fc4a7904833681878"

go_get(
    name = "foo",
    get = "github.com/example/foo",
    revision = foo_rev,
)
```

Knowing how to correctly patch such BUILD files (or any similarly irregular grammar) is non-trivial.

**Comment by peterebden** [comment]
Some thought has gone into this, & have had a couple of conversations here. I think it's a very useful feature, we would like it here too. Ideally something like `plz update //third_party/go:all` which suggests updates to relevant targets, and possibly does a best-effort rewrite of the file (am happy for it not to handle arbitrarily complex cases like the one above, that's very hard to solve and 99% of the time it won't be relevant).

The hard bit is how plz knows what the updates to each library are. To be satisfying it needs to work for Go, maven and pip, and be extensible to new languages that are introduced using the usual extension mechanism of the build language. Actually writing the implementation for those three languages at least (or two really, we have one for Maven already) is likely not hard. I wonder about something like a label on the rule which somehow tells plz what the update command for that language would be, but that is still pretty high-level and handwavey.

**Comment by csdigi** [comment]
Would it be possible to write this as a plz alias. I am thinking it might be possible to extend the output of something like `plz graph` to include the name of the build def (or language tags) as well as to contain a specific version (which we use in most third party build_defs). Then the alias could run a binary (perhaps with some plugins) that takes a filtered set of the graph targets (for example tagged with pip, maven) and knows how to check them. 

I think allowing plugins / custom binaries to do this would be neat as it would also work with people hosting private repos (or at least put the credential and access management of those repos into their hands).

**Comment by sean-** [comment]
I think the only way to have this work reliably would be to have a mark and sweep-like approach to GC'ing dependencies, where you refcount each rule, and if it's zero, you emit it's path in `plz`.  Something like:

```
% plz query unused --root-targets=//cmd/...
//third_party/go:rando-lib-that-is-unused
```

And then leave it up to the person invoking the command to remove `//third_party/go:rando-lib-that-is-unused`.  Having a conventional output like that makes it possible to potentially be used as the input into something that would actually rewrite please files:

```
% plz query unused --root-targets=//cmd/... | plz rewrite remove-targets --input -
```

Where `rewrite` could also be the future home of something like `buildifier` (e.g. `plz rewrite fmt`).

I'd use the unused targets as a CI linter rule:

```
% plz query unused --root-targets=//cmd/... --root-targets=//third_party/pinned_deps/...
```

Where `//third_party/pinned_deps/BUILD` is just a file that arbitrarily marks and holds onto various useful libraries that won't ever ship, but you want to keep in `//third_party` for convenience (e.g. `github.com/y0ssar1an/q` comes to mind).

**Comment by sean-** [comment]
I've recently stumbled across the package https://github.com/oligot/go-mod-upgrade which also has the noted link to:

```
go list -u -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all 2> /dev/null
```

But I think this is close, and it certainly solves some of my headaches.  I thought I'd pass this along in case any future person, including my future-self, is looking for a way to handle this without visiting every Go dependency by hand.
