### ISSUE TITLE
auto-complete target names

### ISSUE THREAD

**Issue by jpo-joyent** [thought-machine/please#469]
It would be nice if the bash/zsh completion would auto-complete target names for e.g. `plz build ...`, `plz test ...`, etc.

This could be done by checking if `GO_FLAGS_COMPLETION=1`, and if so, outputting a filtered list of targets starting with the supplied prefix (or matching the supplied pattern).

**Comment by RichardoC** [comment]
What do you mean? It currently has auto-completion in relation to the project root.
`$ plz test //`
[Much tabbing later]
`Display all 361 possibilities? (y or n)`

**Comment by jpo-joyent** [comment]
Hmm. That does not work for me unless I specify more, e.g. `plz build //t[TAB]` => `plz build //third_party/`. Not sure why. I think it should start working without having to specify an explicit valid prefix first.

**Comment by RichardoC** [comment]
Just tested and confirmed this with 13.3.3

**Comment by Tatskaari** [comment]
Looks like this is intentional because it's typically too slow to complete in the root of a project.
