### ISSUE TITLE
Include python_test sources in plz-out/gen?

### ISSUE THREAD

**Issue by matthen** [thought-machine/please#473]
One useful thing about the `pip_library`, `python_library` and `python_binary` rules is that they gather all the required source files in `plz-out/gen`. That means developers can `cd` into `plz-out/gen` and debug stuff, run ipython etc. @peterebden  mentioned that before.

I don't think `python_test` currently does the same- it creates a .pex for running the test, but does not copy the test source files into `plz-out/gen`.

Would it be good to make a change so it does, so that people could debug the tests inside `plz-out/gen`?

**Comment by BNMetrics** [comment]
Hi @matthen,

Thanks so much for flagging this! :)
I have noticed `go_test` actually copies the test files to `plz-out/gen` directory, and it would definitely be nice if `python_test` does the same as well. 

I'm happy to look into it and make changes accordingly, what do you think @peterebden ?

Thanks!

**Comment by peterebden** [comment]
Yup, makes sense!

**Comment by BNMetrics** [comment]
fixed with #475 ! :)
