### ISSUE TITLE
go_get() + extra_outs doesn't work well atm...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#483]
This took a while to dig through.  One of the things we've run into is importing `timestamp.proto` reliably.  Ideally we don't want to copy this file into our repo and pass an additional protoc flag around.  What we would like to do is do something like:

```python
go_get(
    name = "protobuf-gogo",
    get = "github.com/gogo/protobuf",
    revision = "07eab6a8298cf32fac45cceaac59424f98421bbc",
    install = [
        "gogoproto",
        "jsonpb",
        "proto",
        "protoc-gen-gogo/descriptor",
        "protoc-gen-gogo/generator",
        "protoc-gen-gogo/generator/internal/remap",
        "protoc-gen-gogo/plugin",
        "sortkeys",
        "types",
        "vanity",
    ],
    extra_outs = [
        "protobuf/protobuf/google/protobuf/timestamp.proto",
    ],
)
```

We've since backed away from this (we were trying to use `extra_outs` like an "`extra_files`" where we copy along source files from the `go_get()` and can then refer to them elsewhere), but one of the things that we ran into was `extra_outs` in `go_get()` does not work as expected.  We traced it back to the following:

https://github.com/thought-machine/please/blob/385108c0f025679e3b9fc894258c3c2df4aa8e4b/src/parse/rules/go_rules.build_defs#L516-L555

Specifically, https://github.com/thought-machine/please/blob/385108c0f025679e3b9fc894258c3c2df4aa8e4b/src/parse/rules/go_rules.build_defs#L516

is reused later:

https://github.com/thought-machine/please/blob/385108c0f025679e3b9fc894258c3c2df4aa8e4b/src/parse/rules/go_rules.build_defs#L554

and that obviously expands incorrectly.  `outs` needs to be looped over and append to `cmd` just like is happening to `outs` on line 555.

https://github.com/thought-machine/please/blob/385108c0f025679e3b9fc894258c3c2df4aa8e4b/src/parse/rules/go_rules.build_defs#L554-L555

---

Unrelated, but if there is an idiomatic way to include something like `timestamp.proto` without copying it around, I'm all ears.

**Comment by peterebden** [comment]
Thanks for the detail - makes sense to me. Would you mind taking a look please, Richard?

Re the proto thing, I have not come up with a great solution yet, but agree it would be nice to have one - it is fairly common to find situations like that these days. It's a bit hard to see a good way to dovetail `proto_library` and `go_get` nicely but would love to have one.

**Comment by goddenrich** [comment]
sure will take a look
