### ISSUE TITLE
Finding unused third_party packages

### ISSUE THREAD

**Issue by jpo-joyent** [thought-machine/please#500]
Hello,

I would like a query target which accepts a list of packages (e.g. "//third_party/go"), iterates their targets, and prints those without any reverse dependencies in the full build graph.

Essentially this:
```
plz query alltargets | grep ^//third_party/go: | while read dep; do
    test -z "$(plz -p query reverseDeps "$dep" 2>/dev/null)" && echo $dep
done
```

but inside a single plz invocation so that the dependency graph only has to be built once and then can just be queried in memory for all targets in the packages you are interested in, rather than shelling out to plz again for each target.

Is there some convenient way to already do this? Or would I need to write a new query command?

**Comment by jpo-joyent** [comment]
Or not necessarily accept a list of packages, but accept whatever the default thing is for build, query,etc. where you can flexibly specify e.g. `//foo/bar/...  //baz:quux`

**Comment by sean-** [comment]
I think you can get part of the way there just by parsing the output of `go list`:

```
% go list -f '{{.Deps}}' ./cmd/host-disk/
```

If you take that output and wrap it in some pipe goo:

```
% go list -f '{{.Deps}}' ./cmd/host-disk/ | perl -p -e 's# #\n#g' | sort | grep '^github.com/joyent-compute/railgun/vendor/' | perl -p -e 's#github.com/joyent-compute/railgun/vendor/##g'
```

You get a list of 3rd party dependencies that need to be examined.  From there, you need to uniquify its list with what we have in `third_party/go:BUILD`.

**Comment by jpo-joyent** [comment]
My comment is really about finding generic un-referenced build targets, which would be useful in non-go projects too.

**Comment by sean-** [comment]
I think you can get part of the way there just by parsing the output of `go list`:

```
% go list -f '{{.Deps}}' ./cmd/mycmd/
```

If you take that output and wrap it in some pipe goo:

```
% go list -f '{{.Deps}}' ./cmd/mycmd/ | perl -p -e 's# #\n#g' | sort | grep '^github.com/myorg/myrepo/vendor/' | perl -p -e 's#github.com/myorg/myapp/vendor/##g'
```

You get a list of 3rd party dependencies that need to be examined.  From there, you need to uniquify its list with what we have in `third_party/go/BUILD`.

**Comment by jpo-joyent** [comment]
@sean- My comment is really about finding generic un-referenced build targets, which would be useful in non-go projects too.

**Comment by csdigi** [comment]
Not sure if you have had a look at `plz gc` but it is an experimental attempt at doing something similar. https://please.build/commands.html 

A bit confusing perhaps that it is not exposed through the query command.

**Comment by sean-** [comment]
@jpo-joyent You could probably determine that out of `plz query graph` and maybe load the data into https://godoc.org/gonum.org/v1/gonum/graph/community#ReducedUndirectedMultiplex.Communities to find communities of dependency nodes and test to see what part of the graph can be pruned.  I haven't looked at `plz gc` yet, thanks @csdigi .

**Comment by peterebden** [comment]
Yup, `plz gc` should provide what you want.

Fair point @csdigi , it could probably be `plz query unused` or something, although it does actually do the deleting for you as well which is a little unusual for `query`.

Anyway gonna close this for now, feel free to reopen if `gc` isn't enough.
