### ISSUE TITLE
exec() from starlark considered harmful

### ISSUE THREAD

**Issue by jpo-joyent** [thought-machine/please#501]
With all due respect to @sean-, I think the addition of `exec()` in https://github.com/thought-machine/please/pull/492 is a mistake.

Part of the whole point of Starlark is that it takes precautions to ensure evaluation of the language is a closed system without side-effects, which (barring implementation bugs) makes it safe to evaluate untrusted build rules. With this change, a simple `plz query alltargets` (or even auto-completion of build rules from a shell) would be sufficient to compromise the machine if operating on untrusted BUILD rules.

The introduction of `exec()` breaks that (security-relevant!) promise, not to mention the whole host of reproducibility surprises it necessarily introduces.

Instead, I would strongly recommend that such powerful functionality with infinite unimagined (and possibly malicious) side-effects be limited to build execution time (bash) which can be subsequently sandboxed, rather than build graph evaluation (starlark) which currently goes to great lengths to maintain safety guarantees.

We can provide native implementations of `git_*()` rather than using `exec()` for them, and I'd be happy to send a PR for this next week when I'll have more time.

**Comment by sean-** [comment]
Hrm.  This issue spun off into a spirited discussion offline (thank you @jpo-joyent for raising a number of good points with me - this is what I get for answering the question, "when do we get tagged binaries again?" 😀).

I think there are a few things that need to happen:

- [ ] `exec()` needs to be removed from the public list of registered builtins in `src/parse/asp/builtins.go` that way there's no change in the usable API at the time of the next release.
- [ ] `build_rule` needs to accept an "extra_data" argument that `go_get()` and `go_test()` can use.  This value will contain an opaque string of data that is generated by `go_get()` and passed to `build_rule()` and used as input to `fs/PathHasher` (I'm almost done with this patch).  This is required for reproducibility.
- [ ] The existing `exec()` code can be used as the backend for a native collection of `git_*()` functions that are exported and generally available for use by the world.

There are two arguments that were made that really hit home for me:

1. The `safety of build rule evaluation seems like an obvious intended property` and `exec()` at graph-traversal time invalidates that property of `plz`.
2. I do have aspirations for seeing `plz` used more widely and in places not considering its use yet, and this function would reduce `plz`'s value to something closer to `make`, which is not an analogy or comparison I wish upon anyone.

Until point 2 was made, my sense of loss-aversion didn't kick in and I was content with relying on the *NIX argument of, "everything in UNIX is a foot-gun, don't shoot your foot off."

@peterebden , @BNMetrics , and @csdigi: can you hold off on a release for at least a few hours while I cobble something together to address most/all of these points?

**Comment by jpo-joyent** [comment]
Might consider making `extra_data` a dict rather than a string, exposed to the build rule similar to `tools = {"foo": "bar"}` => `env TOOLS_FOO=BAR`. Other than that, this plan sounds much better to me. +1

**Comment by sean-** [comment]
@jpo-joyent I can do `(str|dict)` and sort the keys in a `dict`.  `list` would not be permitted because order is significant.

**Comment by jpo-joyent** [comment]
@sean- thanks for following up with this. I think the current direction is a much brighter future for plz :)
