### ISSUE TITLE
Can't include root-level resources

### ISSUE THREAD

**Issue by soapergem** [thought-machine/please#508]
I have a couple of python binary packages under one repo with build rules for each. I was including a Certificate Authority file (PEM file) as a resource for one of these packages. When I went to include in a second package I discovered a problem. First, here's a rough outline of my package structure:

    .
    ├─ package1
    │    ├─ BUILD
    │    ├─ __init__.py
    │    └─ main.py
    ├─ package2
    │    ├─ BUILD
    │    ├─ __init__.py
    │    └─ main.py
    ├─ tests
    │    ├─ BUILD
    │    └─ ...
    ├─ ca_cert.pem
    ├─ .plzconfig
    └─ pleasew

As you can see I've got the `ca_cert.pem` file on the root. It used to be under `package1`. Previously my BUILD rules under package1 looked like this:

    python_library(
        name = "lib"
        srcs = glob(["*.py"], exclude=["main.py"]),
    )
    python_binary(
        name = "leadgen",
        main = "main.py",
        deps = [
            ":lib",
            "//tests:package1_test_library",
        ],
        resources = [
            "ca_cert.pem",
        ],
        zip_safe = False,
        visibility = ["PUBLIC"],
    )

When I had the `ca_cert.pem` stored inside the `package1` directory, this worked fine. Now that I've moved it out, I figured I could just update the `resources` line to say `"//ca_cert.pem"` instead of `"ca_cert.pem"`. However doing so results in this error from please:

> //package1:_package1#lib_zip depends on //ca_cert.pem:ca_cert.pem, but there's no BUILD file in ca_cert.pem/

Is this a bug? Or have I just got my formatting wrong? Is there any way I can make this work, and store the resource in the root (as shown in the diagram above)? Thanks!

**Comment by peterebden** [comment]
You can make it work, you just can't refer to files directly using that syntax. Instead, create a BUILD file in the root containing:
```
filegroup(
    name = "ca_cert",
    srcs = ["ca_cert.pem"],
    visibility = ["PUBLIC"],
)
```
and then your `resources` should say `//:ca_cert`.

**Comment by soapergem** [comment]
That worked perfectly! Thank you.
