### ISSUE TITLE
Scrolling on please.build

### ISSUE THREAD

**Issue by matthen** [thought-machine/please#526]
On my mac, scrolling the menu on the left of the website does not work well. I need to scroll the entire page to the bottom before the menu will scroll at all. On long pages like https://please.build/lexicon.html it makes it tricky to get to the bottom of the menu.

related:
https://stackoverflow.com/questions/47618271/position-sticky-scrollable-when-longer-than-viewport

**Comment by hnridder** [comment]
The same issue occurs on linux (firefox 60.4) and on windows (firefox latest version)
