### ISSUE TITLE
 I suggest to create home brew formula for please

### ISSUE THREAD

**Issue by harobed** [thought-machine/please#530]
Hi,

I suggest to create [home brew formula](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md) for `please`.

Best regards,
Stéphane

**Comment by peterebden** [comment]
Yep, good idea! I don't have a Mac handy to use for it but one is pending courtesy of our IT team... or very happy for someone else to take a look first.

**Comment by peterebden** [comment]
Have created a tap for it: https://github.com/thought-machine/homebrew-please
It's suggested as an option in the website & README (although I've not tested on Linux yet).
