### ISSUE TITLE
Support for go build flags...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#532]
This is pretty simple but I couldn't figure it out:

```go
// +build foo

package main

func main() {
}
```

How do I pass in the `foo` build tag when building a Go library/binary, etc?

**Comment by peterebden** [comment]
Hmmm good spot, we do seem to be missing that. How silly, we have the tool and it supports taking extra tags, they're just not plumbed through :) 
Should be easy to add.

**Comment by sean-** [comment]
It seemed curious and like I must have been missing something or it isn't supported. :)

**Comment by sean-** [comment]
Ick.  Hrm.  Could you add a visitor callback to the filegroup struct that reevaluates the filegroup everytime the list of srcs is queried?

This isn't a critical bug for us - I have removed all of our build tags for the time being and am relying on logic in `BUILD` instead.  This only flares up as an issue when someone `cd foo/bar && go build` and we have files with different build tags.  Currently we have different `BUILD` targets but we want to be able to `plz export` and have that workflow "just work."

**Comment by numbsafari** [comment]
With the move to the go plugins, would it be appropriate to move this issue to the [please-build/go-rules](https://github.com/please-build/go-rules) repo?

In particular, I am trying to use the `go_repo` rules and have need to set build flags/tags (e.g. `noasm`) for certain modules. I'd be happy to open a fresh/specific issue there and simply refer back to this one if that makes more sense.

**Comment by samwestmoreland** [comment]
Yeap I think it makes sense for this to be moved to go-rules if it hasn't been already. This may have already been implemented... or rather I made an attempt to implement it (in the go-rules repo), but saw something recently that suggested it wasn't working very well. I'll look into this.
