### ISSUE TITLE
Invalid build labels for BUILD targets in the top-level directory...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#533]
We have a top-level `BUILD` file that we use to bootstrap other tooling, etc.  If we have a package like `//foo/bar:bar` that is a dependency of `//:bootstrap`, how do we expose `//foo/bar:bar` to `//:bootstrap`?

```
% plz run //:bootstrap
Build stopped after 640ms. 1 target failed:
    //foo/bar:bar
src/parse/rules/go_rules.build_defs:95:16: error: Invalid build label: //
    # go_test and cgo_library need access to the sources as well.
    src_rule = filegroup(
               ^
        name = name,

Traceback:
                               src/parse/rules/go_rules.build_defs:95:16:       src_rule = filegroup(

$GOPATH/src/github.com/myorg/myrepo/foo/bar/BUILD: 1: 1:   go_library(
Exit 7
```

`foo/bar/BUILD`:

```
go_library(
    name = "bar",
    srcs = [
        "bar.go",
    ],
    visibility = [
        "//", # what can I put here?
    ],
    deps = [
        "//third_party/go:errors",
    ],
)
```

I've only figured out `//...` or `PUBLIC` as valid values for visibility.  What I'd like to be able to say is `//:bootstrap` or `//:_bootstrap#lib_srcs` but that blows up or can't be found, respectively.  Thoughts?

**Comment by peterebden** [comment]
How about `//:all`?

`//:bootstrap` *should* work, how does it blow up? Does it not allow some of those "internal" targets still?

**Comment by sean-** [comment]
`//:all` does work.  I agree that `//:bootstrap` should work, but it doesn't right now.  :)

**Comment by peterebden** [comment]
Yeah, just curious what the message is when it fails with `//:bootstrap`? Is it complaining about it not being visible to some of the others?

**Comment by sean-** [comment]
OOOH!  This can actually be closed.  #532 was actually the culprit for this issue: one of the files being referenced had a build tag.  Sorry for the noise!
