### ISSUE TITLE
plz clean -f should only clean the dependencies of the current directory...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#536]
I found myself running:

```
% cd foo/bar
% plz clean -f
```

and expected `plz clean` to implicitly clean `//foo/bar/...` and `//foo/bar`'s dependencies.  It doesn't appear as though running a `plz clean -f` in a sub-directory is actually the equivalent of `plz clean //...`. ?

**Comment by peterebden** [comment]
There's some special-casing on a bare `plz clean` whereby it doesn't bother going target-by-target and just wipes out everything. Easy enough to only do that if it started out at the root so it pairs with `plz build` etc.

**Comment by sean-** [comment]
Thank you!  This goes from a, "plz clean -f[enter] echo heh, not a biggie - it's only a few minutes" to "plz clean -f[enter] echo OH SH1TT!!!!!" moments when you find yourself at 35K ft flying over the pond and have to spend the next 60min re-downloading `.zip` files.  I'm not saying this happened to me yesterday \****cough***\* not true, it did \****cough***\*, but I suddenly developed a sensitivity to change in behavior between `build` and `clean`. :)
