### ISSUE TITLE
plz cover chokes on packages with hyphens in their name...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#537]
One of the protobuf files that we use has a hyphen in its name.  When we attempt
to run `plz cover` on this file, we run into a problem with coverage (but not
`plz test`).

```
% plz cover //foo/bar-baz/...
Build stopped after 4.11s. 1 target failed:
    //foo/bar-baz/service:_service_test#main_lib
Error building target //foo/bar-baz/service:_service_test#main_lib: exit status 1
foo/bar-baz/service/service_test_main.go, line 205: undefined: "github.com/myorg/myrepo/pb/int/bar-baz".GoCover_host
foo/bar-baz/service/service_test_main.go, line 205: undefined: net_pb_go in net_pb_go.Count
foo/bar-baz/service/service_test_main.go, line 205: undefined: "github.com/myorg/myrepo/pb/int/bar-baz".GoCover_host
foo/bar-baz/service/service_test_main.go, line 205: undefined: net_pb_go in net_pb_go.Pos
foo/bar-baz/service/service_test_main.go, line 205: undefined: "github.com/myorg/myrepo/pb/int/bar-baz".GoCover_host
foo/bar-baz/service/service_test_main.go, line 205: undefined: net_pb_go in net_pb_go.NumStmt
```

When I look in the generated file (`service_test_main.go`) at line 205, I see
the following:

```
  coverRegisterFile("pb/int/bar-baz/bar-baz_pb.go", _cover30.GoCover_bar-baz_pb_go.Count[:], _cover30.GoCover_bar-baz_pb_go.Pos[:], _cover30.GoCover_bar-baz_pb_go.NumStmt[:])
```

Which obviously doesn't compile.  In looking into
`tools/please_go_test/gotest/find_cover_vars.go` and at `coverVar()`, it looks
like there is no escaping and the raw filename is being used instead of the
package name itself.  Is there a helper method that we can use that will pull in
the right package here?

**Comment by peterebden** [comment]
It's escaping dots but not hyphens. Not sure if there is a good helper function - it also needs to match up with the invocations to `go tool cover` that generate the variable (although I do wonder about rolling that into the same tool to have something a bit more principled than Bash doing it).

**Comment by sean-** [comment]
+1 to slowly weaning functionality out of `bash`.
