### ISSUE TITLE
"plz init" not creating a .plzconfig file

### ISSUE THREAD

**Issue by bfqrst** [thought-machine/please#547]
_plz --version_
**Please version 13.4.0**

I've just installed please via the shell script, but symlinked all of the binaries to `/usr/local/bin/` and following the getting started guide, I ran a `plz init` expecting for a `.plzconfig` file to be created in the folder I was running the command in. Instead I'm getting the help screen.

Quote from the webpage:

> Run plz init at the root of your repo to create the .plzconfig file. There are many options that can be configured in this file but you can worry about them later - the defaults should be fine to begin with.

Either I've sort of completely missed the way please works or might this be a bug? Any hints are greatly appreciated. 

Cheers
Ralph

**Comment by peterebden** [comment]
Oops, yes, I think we broke it by adding the `config` subcommand. Will fix shortly...

**Comment by peterebden** [comment]
BTW in the meantime you can simply `touch .plzconfig` to get started, an empty file works fine.

**Comment by peterebden** [comment]
Fixed this in the latest release (13.4.2). Sorry about that!

**Comment by bfqrst** [comment]
..now _that_ was fast! 💯 

Awesome Peter, thanks a ton. I'll take it for a spin later...

Have a nice weekend!
