### ISSUE TITLE
xattrs not available in nix builds

### ISSUE THREAD

**Issue by pmahoney** [thought-machine/please#548]
This is more of a heads-up than an issue or feature request.

I wanted to try packaging "please" for [nixpkgs](https://nixos.org/nixpkgs), but it's going to be difficult since [nix disables xattrs within builds](https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L2531-L2537) It appears the reasons for disabling them would not apply to "please" (other than desire to support filesystems that lack xattrs), but they are disabled at any rate.

**Comment by peterebden** [comment]
Hmmmmm OK. Not sure what a good alternative would be; we used to use a separate file but moved to xattrs to avoid risks of it getting out of sync with the real ones.

Thanks for the heads up!

**Comment by georgegiovanni** [comment]
What about a way to at least create output (`plz-out`) elsewhere (not in the same dir as src)? AWS EFS also doesn't support `xattrs`.

**Comment by peterebden** [comment]
Have discussed that a bit; seems legit but just quite a bit of work to make everything aware of it.

**Comment by swills** [comment]
Also experiencing this issue on FreeBSD.

**Comment by katzdm** [comment]
This also impacts various MacOS virtualization systems (docker-on-mac, virtualbox).

**Comment by hzeller** [comment]
@pmahoney Did you consider packaging please for nix after this was resolved ?

**Comment by pmahoney** [comment]
@hzeller No, and I do not currently have plans to package `please`.
