### ISSUE TITLE
Create a mailing list

### ISSUE THREAD

**Issue by hnridder** [thought-machine/please#551]
I suggest creating a mailing list or some other community venue for discussions/questions on please. There users can learn from and help each other. Furthermore it can help establish and spread best practices, flatten the learning curve and help the maintainers to understand the tasks users are trying to accomplish.

**Comment by hnridder** [comment]
By reading old issues I found there is both a mailing list:
https://groups.google.com/forum/#!forum/please-build
and a gitter chat:
https://gitter.im/please-build/Lobby

So the issue should really become: Advertise these on the please.build website.

**Comment by peterebden** [comment]
Thanks for the suggestion! I've added them in a few places - should appear in a while once the caches update.
