### ISSUE TITLE
Does Please support using remote cache?

### ISSUE THREAD

**Issue by wangkuiyi** [thought-machine/please#553]
Thank you for creating Please! I have been using it as an elegant implementation of Bazel.

I am wondering how I could do distributed build. It seems that a solution could be that Please supports remote cache so that multiple users might benefit from the cache. For my use case, if I put the remote cache on a distributed filesystem accessible by Kubernetes, I suppose that all builds running on the cluster would be accelerated.

I tried Google and Github Search, but cannot find "Please remote cache", so I came here asking for help.

**Comment by peterebden** [comment]
It does, see https://please.build/cache.html.

The RPC cache is the most usable remote version; we're planning a significant upgrade to it soonish, but we still use the current one internally here. The HTTP cache is a bit unloved but at some point I'd like to make sure it's compatible with semi-standard things like https://cirrus-ci.org/examples/#remote-cache.

**Comment by wangkuiyi** [comment]
Thanks for the link! Shame on me that I didn't notice the link on the home page.  I followed the line and read the code. It is a delightful experience.

The [gRPC proto definition](https://github.com/thought-machine/please/blob/master/src/cache/proto/rpc_cache.proto) explains itself wells and guides me through the [cache implementation](https://github.com/thought-machine/please/blob/master/tools/cache/server/cache.go).

I tried to understand how the cluster works by reading the command line options definition:

https://github.com/thought-machine/please/blob/4c2b96085a5c05c6738a1e1db69e29d65116e7de/tools/cache/rpc_server_main.go#L45-L53

However, I think I either need a README.md of the design, in particular, seeding and advertising, or I'd have to dig into [details](https://github.com/thought-machine/please/blob/master/tools/cache/server/cache.go).

Do you have a plan to add a /tools/cache/README.md? If not, how about I read your code and try to add one under your review?

**Comment by peterebden** [comment]
The clustering stuff never really got tested properly in anger (for various reasons we never got that set up here)... would be interested in feedback. Both of your points are correct though.

FWIW the whole thing is slated for a rebuild sometime which I'm partway through; hence why I haven't put a lot of time into polishing the existing one.

**Comment by agenticarus** [comment]
Recent work has replaced the old RPC and HTTP caches with a better remote-execution framework which can be backed by any valid implementation (e.g. buildbarn)
