### ISSUE TITLE
Is Please compatible with Bazel

### ISSUE THREAD

**Issue by wangkuiyi** [thought-machine/please#557]
Is Please designed as an alternative to the "official implementation" of Bazel?  I ask because I am considering using Please to build TensorFlow, which, I think, customized Bazel a lot, e.g., to generate CUDA and ARM code. Should I report incompatibility if I find some and try to fix them?

**Comment by peterebden** [comment]
We try to be compatible at a superficial level, that is it usually works for fairly straightforward BUILD files (there's a Bazel compat setting that helps that too). I've had absl working in the past (although it's a bit of a moving target, I'm not sure it works now).

We're not compatible with deeper stuff such as complex rule definitions though, and I don't necessarily want to replicate every feature of Bazel anyway. So am happy to look at incompatibilities, but large features may be too much work to address.

**Comment by peterebden** [comment]
Oof, fairly quickly it runs into some issues with the `@bazel_tools` stuff. Can think about some options there... we pretty much have the builtins they need, probably just need to persuade it to use them.
