### ISSUE TITLE
bash error when using java_library.resources_root in repo root

### ISSUE THREAD

**Issue by hnridder** [thought-machine/please#559]
We have a bunch of gifs stored as data/images/*.gif that should be included as images/*.gif in a jar. To strip the path we created a special target:
```
java_library(
    name = 'gui_images',
    srcs = [],
    resources = glob(include = ['data/images/*.gif']),
    resources_root = 'data',
)
```
Building this target gives the error message:
```
Error building target //:gui_images: exit status 1
bash: line 0: cd: /data: No such file or directory
```
Checking out what's happening:
```
$ plz build --shell :gui_images
Temp directories prepared, total time 50ms:
  //:gui_images: plz-out/tmp/gui_images._build
    Command: cd ${PKG}/data && $TOOL z -d -o ${OUT} -i .

bash-4.4$ ls
data
bash-4.4$ echo $PKG

bash-4.4$ echo $PKG_DIR
.
bash-4.4$
```
It seems the command should use PKG_DIR instead of PKG

**Comment by peterebden** [comment]
I think you're right - the repo root tends to be a fertile source of little bugs like this :( Thanks for the diagnosis!
