### ISSUE TITLE
https://get.please.build repositories are down

### ISSUE THREAD

**Issue by AlexPavy** [thought-machine/please#569]
Hi at the moment we cannot download please using the script in curl https://get.please.build | bash
because the repositories under https://get.please.build are not available

**Comment by peterebden** [comment]
Thanks for the heads up - I've altered some of the DNS settings, but am not observing any issues here yet. Will investigate...

**Comment by peterebden** [comment]
Should be back up now, can you confirm if it works for you?

**Comment by AlexPavy** [comment]
Yes it works thanks

**Comment by Multiply** [comment]
This seems to have resurfaced, maybe in a different fashion:
```
It works!

This is the server's temporary default web page.
The web server software is running but no content has been added yet.
```

**Comment by peterebden** [comment]
Yeah it is a different fashion... think there wasn't a proper default document added. Can you confirm if it's fixed for you now?

**Comment by Multiply** [comment]
@peterebden It most definitely works now. Thanks :)

**Comment by peterebden** [comment]
No worries - hopefully this should be the last bit of disruption here, everything should be moved over to its new home now.
