### ISSUE TITLE
`plz query revdeps` only enumerates direct reverse-dependencies

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#570]
To reproduce, consider a simple `BUILD` file:

```
python_library(
    name = "root",
    srcs = [],
)

python_library(
    name = "intermediary",
    srcs = [],
    deps = [":root"],
)

python_library(
    name = "leaf",
    srcs = [],
    deps = [":intermediary"],
)
```

Running the command `plz query revdeps :root` yields only the output:
```//test:intermediary```

My understanding is that this query should return all transitive reverse-dependencies (i.e. the above example should also return `//test:leaf`).

**Comment by peterebden** [comment]
Hmmmm I agree... in my head it has always worked as you describe, but it doesn't look to me like it ever has 😕

Shouldn't be a hard fix though.

**Comment by csdigi** [comment]
It might be good to unify the query style with the deps command, which supports a level indicator (so that the default behaviour remains as is for any tooling currently using it) and people who want more depth can ask for it.

I guess the other options to deps (unique and hidden) make sense here too.

**Comment by katzdm** [comment]
@peterebden Thanks for addressing this the other day - Unfortunately, it seems to still not work in `13.5.0`. I took a look at your commit, and though I may be missing something, I think you forgot to integrate the `GetRevDepTransitiveLabels()` function that you wrote - It doesn't seem to be in use anywhere except for the unit-test! :-)

**Comment by peterebden** [comment]
Found some time to circle back to this... apologies, will fix!

@csdigi agreed, apart from `--unique` which I want to make the default on deps anyway (on repos of reasonable size there is way too much output without it)

**Comment by katzdm** [comment]
Works beautifully, thank you!
