### ISSUE TITLE
Any way to exclude certain nested dependencies in custom build rules? 

### ISSUE THREAD

**Issue by soapergem** [thought-machine/please#571]
We've written a custom `build_rule` for packaging Python lambdas, which are just ZIP files.

```python
def python_lambda(name, srcs, deps=None, out=None, visibility=None):
    """Build an AWS Lambda package (zip)."""
    lmb_rule = filegroup(
        name = '_%s#lmb' % name,
        srcs = srcs,
        visibility = visibility,
        output_is_complete = False,
        requires = ['py'],
        test_only = False,
    )
    cmd = '$TOOL z -i . -s .zip --include_other --add_init_py --strict'
    build_rule(
        name = name,
        srcs = [lmb_rule],
        deps = deps,
        outs = [out or name + '.zip'],
        cmd = cmd,
        needs_transitive_deps = True,
        output_is_complete = True,
        binary = True,
        building_description = 'Building lambda...',
        tools = [CONFIG.JARCAT_TOOL],
        visibility = visibility,
        test_only = False,
    )
```

For very simple Lambda functions, where we don't pass in anything to `deps`, this works great as it just packages the `*.py` files in the relevant directory and creates the ZIP file. However, for more complex builds where `deps` is specified, there's an interesting caveat that comes into play whenever [boto3](https://github.com/boto/boto3) is included as a nested dependency.

The funny thing about Lambda functions is that boto3 and botocore never need to be explicitly included as a dependency, since they're already baked into the base layer that runs Lambdas. I'm trying to find a way to exclude these two dependencies explicitly when building Lambda packages in Please, but I'm not sure if it's possible.

At the end of the day, my BUILD file for the Lambda itself might look something like this:

```python
package(default_visibility=["PUBLIC"])

python_lambda(name="myfunc", srcs=["handler.py"], deps=["//tools:lib"])
```

And the BUILD file for that tools library (which is used by more than just this Lambda) might look something like this:

```python
package(default_visibility=["PUBLIC"])

python_library(
    name="lib",
    srcs=glob(["**.py"]),
    deps=[
        "//third_party/python:boto3",
        "//third_party/python:botocore",
        "//third_party/python:tenacity",
    ],
)
```

When the tools library is packaged as part of a `python_binary` it needs to include all the nested dependencies. But when it's included in our custom `python_lambda` build_rule, as mentioned boto3 and botocore can safely be excluded. Strictly speaking, it doesn't harm anything to include them, but it just makes the final ZIP file a bit larger and therefore makes it a little more difficult to work with in the AWS console.

Based on the way Please is set up I'm not sure if it's even possible, but is it possible to modify our build_rule to exclude these two dependencies from the chain? I imagine this would effectively result in building the python_library differently depending on how it's invoked, which is why I question whether Please could even support this. Again, it's not strictly necessary, but I'm just wondering if it can be done?

**Comment by peterebden** [comment]
Right, as you observe it isn't exactly how plz wants to do things. It can be made to work using the (possibly poorly documented) require/provide setup like so:
```
python_binary(
    name = "provide_bin",
    main = "bin.py",
    deps = [":test_provide"],
)

python_test(
    name = "provide_test",
    srcs = ["test.py"],
    deps = [":test_provide"],
)

filegroup(
    name = "test_provide",
    provides = {
        "test": "//third_party/python:six",
    },
)
```
After building those, `provide_test` contains `third_party/python/six.py` but `provide_bin` doesn't. There is a minor local modification to `python_test` to make that work though - probably could make that a general feature if it's solving your problem.

**Comment by matthen** [comment]
A dumb hack would be to add something like `cmd  = "rm -rf boto3 && $TOOL ..."`. Of course it would still depend on the boto3 rule but it would be stripped from the zip

**Comment by soapergem** [comment]
@peterebden yes, I'm very interested in generalizing whatever it is you're doing there. What is the "minor local modification" you're referencing? Inquiring minds want to know!

**Comment by peterebden** [comment]
#574 was the local change; that hooks up the test to the third-party dep in that example but not the binary.

Pretty happy to merge that if this turns out to be useful
