### ISSUE TITLE
Subinclude of a file in the same directory causes infinite loop

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#573]
Given a directory with:
- `rules.build_def`
- `BUILD`

If the file `BUILD` begins with:
`subinclude(":rules.build_def")`

Then building will trigger an infinite loop.

**Comment by peterebden** [comment]
Yep, sorry about that; we used to ban them completely in the same package, now they're allowed but didn't account for the case where they happen in the wrong order.
