### ISSUE TITLE
Feature-request: Per-target whitelisting of environment passthroughs

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#575]
I would like to be able to write

```
genrule(
    name = "...",
    pass_env = ["RULE_SPECIFIC_ENV_VAR", "OTHER_VAR"],
    ...
)
```

To indicate that an environment-variable should be propagated when building an individual rule.

The current workaround appears to be to use `PassEnv` in the global `.plzconfig`. This works, but it means that a change to the environment variable requires rebuilding the whole source tree.

More specific use-case: I run the following:

`plz run //example_service:env`

to print the entire environment for the service `example_service`. By default, this prints the "development" environment, but I would like to also be able to print the `prod` environment, by writing:

`CLUSTER_OVERRIDE=prod plz run //example_service:env`

Since this only requires rebuilding of the leaf-node `//example_service:env` target, I would like to avoid needing to rebuild the entire source-tree.

Alternatively, of course, the "cluster" could be listed as an argument on the `//example_service:env` rule - But then it becomes possible to check a build-rule into versions control with `cluster=prod`, something I would like to avoid.

**Comment by peterebden** [comment]
Seems reasonable; generally I try to be a bit careful about adding per-target features since that structure is already pretty huge, but I think this is a pretty legit use-case.
