### ISSUE TITLE
Symlinks replaced by acutual files break npm node_modules

### ISSUE THREAD

**Issue by AlexPavy** [thought-machine/please#579]
Hi,

I think that symlinks are replaced by the copy of the files, when a dependency is moved from temporary folder.

We are using please to trigger front end build with npm.
But there are symlinks in npm's node_module/.bin folder, and the code inside has relative imports.

**Comment by peterebden** [comment]
Hmmmm we used to do this, but I think we mostly maintain symlinks as they are now (IIRC we had some npm related issues internally too which that fixed).

There's a fairly crude test [here](https://github.com/thought-machine/please/blob/b8f7ea8ec3f186ccfb089824571a018064c6cc56/test/BUILD#L396) around this behaviour. Maybe it's not picking up the issue you have - can you share any more details about it?

**Comment by AlexPavy** [comment]
Hi Peter, thank you for the answer, I will test again when we need it.

**Comment by sebastian-nowak** [comment]
Hey @peterebden,

FYI the issue still exists, I've run into the same problem with node_modules/.bin as Alex. I came up with more general repro steps and submitted it as a separate issue: https://github.com/thought-machine/please/issues/832

Cheers!
