### ISSUE TITLE
Location macro yields dependency-error when cross compiling

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#582]
Given a rule in package `//my_pkg` like:

```
genrule(
    name = "my_rule",
    cmd = "mycmd --file=$(location //path/to:target)",
    out = ["outfile"],
    deps = ["//path/to:target"],
)
```

Running `plz build --arch=linux_x86 //my_pkg:my_rule` will yield an error:

> ERROR: //production/keyrings:default failed:
> Rule //my_pkg:my_rule can't use //path/to:target; doesn't depend on target //path/to:target

However, changing the command to:

```
    cmd = "mycmd --file=$(location @linux_x86//path/to:target)",
```

appears to resolve the problem.

It furthermore doesn't seem possible (or, at least, straightforward) to resolve this in an `--arch`-neutral way: I tried changing this to:

```
    cmd = f"mycmd --file=$(location @{CONFIG.OS}_{CONFIG.ARCH}//path/to:target)",
```

which works for any given `--arch`, but then fails when `--arch` is omitted.

Final note - Sorry to open so many issues against you lately - I absolutely love all that you've already accomplished with `plz`, and am excited for the potential of the project! I'm super happy to have come across it. No expectation for all of these to be addressed right away; I'll try to loop back in the near future with some PRs to help.

**Comment by peterebden** [comment]
No worries - it's great to have someone using some of these features in anger! We ended up not using cross-compiling quite as much as I originally thought we would so as you can see there are still some rough edges :)
