### ISSUE TITLE
plz watch: --run flag is broken

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#599]
Running `plz watch --run <TARGET>`does not run the executable.

**Comment by katzdm** [comment]
Hey @peterebden , thanks for the quick turnaround on this! There's a small problem with your change - After killing the `plz watch` invocation with `CTRL+C`, the process(es) started by `plz` (i.e. the binary targets) continue to run.

This was especially problematic since the binary I'm testing with is a webserver, so the next time I ran `plz watch --run //example_service`, the program couldn't start because port 8080 was already in use (by the abandoned process). `kill -9` did the trick, but I'm sure `plz` can be smart enough to handle the signal and kill the process :)

**Comment by peterebden** [comment]
Yup fair - to be honest the current implementation isn't great for persistent processes (it really needs to kill them when changes happen). Was thinking about that as I wrote that fix but didn't have time for it then.

**Comment by peterebden** [comment]
594a0ec should improve this considerably. Somewhat surprisingly it now seems to terminate subprocesses although I've not done anything explicit for that.
