### ISSUE TITLE
plz watch can not trigger rebuild when the source code is in the same path as .plzconfig is.

### ISSUE THREAD

**Issue by awagelight** [thought-machine/please#618]
Hi team:

I think I find something strange when I use `plz watch`.

The cpp project structure is like this:
>find  | grep -v plz-.*
.
./.plzconfig
./test
./test/hello.cc
./test/hello1.h
./BUILD
./hello.h

Then I use `plz watch :hello`.

If I modify `./hello.h` **_can not_** trigger rebuild. 
If I modify `./test/hello1.h or ./test/hello.cc`  **_can_** trigger rebuild. 

Here is the BUILD file:
>cc_binary(
    name = 'hello',
    hdrs = ['hello.h','test/hello1.h'],
    srcs = ['test/hello.cc'],
)

I am running plz on Centos 7.

Hope this information is enough for you to address the bug.

Thank you for your help!

**Comment by awagelight** [comment]
BTW, I also test this case:
If I modify `BUILD` also **_can not_** trigger rebuild.

**Comment by katzdm** [comment]
@awagelight , the title of your issue seems to imply that everything works as intended when the package is anywhere except for repository-root. That is, if your files {`BUILD`, `hello.h`, `test/*`} instead belong to a subdirectory `my_app`, and you run `plz watch --run //my_app:hello`, does everything work correctly?

**Comment by awagelight** [comment]
> @awagelight , the title of your issue seems to imply that everything works as intended when the package is anywhere except for repository-root. That is, if your files {`BUILD`, `hello.h`, `test/*`} instead belong to a subdirectory `my_app`, and you run `plz watch --run //my_app:hello`, does everything work correctly?

yep, you get my point.
`plz watch` can monitor very well on any file change in subdirectory, but `except for repository-root`

**Comment by awagelight** [comment]
@katzdm 

yep, you get my point.
`plz watch` can monitor very well on any file change in subdirectory, but `except for repository-root`
