### ISSUE TITLE
Allow using local version of python library

### ISSUE THREAD

**Issue by matthen** [thought-machine/please#619]
For running tensorflow jobs, there are some useful docker containers that have optimized tensorflow packages pre installed, for GPUs etc.

Is there an easy way to tell the PEX to use the local library? I realise this makes the PEX not standalone, but it would be useful here. I suppose I could also write a build rule that copies the library from the machine into the build.

Thanks for any input.

**Comment by peterebden** [comment]
There isn't right now - we try to keep them separated from the system Python. I see the use case though and it's not really fundamentally different from doing `import os` anyway, to treat some things as system-provided.

I guess options are either add a flag to let the pex retain some of the system paths it normally would not allow, which is coarse-grained but relatively simple, or allow some way of doing that on a per-import basis (that's pretty handwavy though). Or as you say pull it in from the machine but that may be clunky, especially for things like TF that end up being non-zip-safe.

**Comment by peterebden** [comment]
The linked PR should deal with this - if you set `site = True` on a binary it will import site at startup, allowing imports of local packages. Let me know if that solves what you want here!
