### ISSUE TITLE
go_get targets can be compute-bounded by file hashing

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#639]
Original discussion is [here](https://gitter.im/please-build/Lobby?at=5cf14d57bf4cbd167c0a3370) on gitter.

For `go_get` rules with a very large number of files (which can balloon in the presence of git submodules in the downloaded repository), the fingerprinting of each individual file extracted from a downloaded archive can become the performance bottleneck while building. The motivating example is the target:

```python
go_get(
    name = "sops",
    repo = "github.com/mozilla/sops",
    get = "go.mozilla.org/sops",
    install = ["cmd/sops"],
    revision = "3.3.0",
    hashes = ["49c381381cea6ecc3a5f0bebb85d1108ceb566a9"],
    binary = True,
)
```

which takes more than a full minute to produce a hash of the outputs of an intermediate target. It should be noted that the compute bottleneck appears to be the _opening and reading_ of each individual file, rather than the actual hashing.

Some proposed workarounds include:
- Assign hashing workloads to a pool of goroutines (e.g. round-robin) rather than performing all work on a single thread; combine individual hashes afterwards.
- Implement a mechanism for indicating that a `build_rule` should not produce a hash of its own output, but should only be considered "changed" if one of its dependencies has changed (especially useful in this case, since the archive that the files were extracted from has already been hashed).

**Comment by peterebden** [comment]
So interestingly this doesn't happen on my machine, or at least not significantly; the target is bounded by compiling instead. Possibly there's some kind of machine-level issue that makes it notably slower in some setups.

Having said that, we should still try to mitigate it if that's the case; it might be hardware and effectively not possible to fix. In the meantime I will try to test on some other machines and see if that sheds more light.

**Comment by katzdm** [comment]
I'm no longer really impacted by this, since I'm pulling a `sops` binary release instead of building from source. Given that it might be a hardware issue anyway, and nobody else has indicated a problem, I think we can go ahead and close this for the time being.
