### ISSUE TITLE
Is there a way to bootstrap without network access?

### ISSUE THREAD

**Issue by dmgk** [thought-machine/please#645]
Is there a way to vendor all 3rd party dependencies to avoid requiring network access during bootstrapping? We are working on FreeBSD port and the build currently fails with

```
1 error occurred:
        * Get https://github.com/kevinburke/go-bindata/archive/46eb4c183bfc1ebb527d9d19bcded39476302eb8.zip: dial tcp: lookup github.com on 1.0.0.1:53: write udp 127.0.0.1:61403->1.0.0.1:53: write: permission denied

Build stopped after 40ms. 1 target failed:
    //third_party/go:_go-bindata-go-bindata#download
1 error occurred:
        * Get https://github.com/kevinburke/go-bindata/archive/46eb4c183bfc1ebb527d9d19bcded39476302eb8.zip: dial tcp: lookup github.com on 1.0.0.1:53: write udp 127.0.0.1:61403->1.0.0.1:53: write: permission denied
```

because network access is not allowed during build phase.

**Comment by swills** [comment]
I believe other package build systems have this restriction too.

**Comment by peterebden** [comment]
There isn't at present, I suppose we could think about a way of generically overriding `remote_file` rules to be able to look into a local directory possibly. I very much don't want to vendor dependencies into this repo.

How does one usually handle this for Go in FreeBSD? Typically `go build` etc will make network requests as needed to pull in dependencies?

**Comment by swills** [comment]
Normally, the resources will be fetched, checksums checked and then placed in the appropriate locations before the build starts.

**Comment by swills** [comment]
This is still an issue.

**Comment by swills** [comment]
That sounds fine, the orchestration on our side isn't a problem, it's fairly easy to do really. I didn't know you could build with `go build src/please.go` but I will look into that. (I was building with `go run -tags bootstrap src/please.go --profile bootstrap build //src:please`)

**Comment by swills** [comment]
Building with `go build src/please.go` solved my problem. Thanks for educating me and sorry for the noise! So I'm wondering about these other tools. I wanted to try the `curl https://get.please.build | bash` install, but it reports: `Unknown operating system FreeBSD
` despite [the quickstart](https://please.build/quickstart.html) saying that FreeBSD is supported.

**Comment by peterebden** [comment]
Yeah we don't do binary builds because it's on a different CI platform which doesn't do the releases. I don't _think_ it would be too hard to add that though (it'd just have to assume Circle updated the latest_release file).

**Comment by swills** [comment]
> FreeBSD is supported however we don't provide binary distributions for it. You'll have to build it from src.

Ah, I see, that's no problem, thanks for the explanation.

> The rest of the tools exist under //tools and you should be able to build them with go build much the same. These need to be in the please install location (~/.please?) alongside the main please binary. Some of them are language specific and we're thinking about ways to trim down the number of these tools that we have in our distribution.

Thanks, building them with go build worked great.

> I just realised there's generated code that is missing from go build: a go_bindata rule that contains all the built in rules. We would need to check the output of that in to make that work. Without it the please binary you created will be missing all the build definitions under //rules. The bootstrap profile adds these back in through configuration which is why I didn't notice before.

Hmm, I think we could possibly generate the file using go_bindata as well.

> Yeah we don't do binary builds because it's on a different CI platform which doesn't do the releases. I don't _think_ it would be too hard to add that though (it'd just have to assume Circle updated the latest_release file).

I am not sure Circle CI supports FreeBSD, but Cirrus does, I could help with that.

On another topic, tools/sandbox/main.c doesn't seem like it's going to really support FreeBSD.

But this issue is starting to get a bit off topic. Should I open another one or multiple separate ones?

**Comment by Tatskaari** [comment]
> I am not sure Circle CI supports FreeBSD, but Cirrus does, I could help with that.

Ah yeah we use that but it just runs our tests. Perhaps we can try and do a binary release from there too... though I think orchestrating the release across two CI platforms would be a pain. Hopefully your port is a good alternative to get.please.build for most FreeBSD users. 

>Hmm, I think we could possibly generate the file using go_bindata as well.

Don't worry, I just merged that into master (see above) 

>But this issue is starting to get a bit off topic. Should I open another one or multiple separate ones?

Yeah please do, I will close this now.

**Comment by Tatskaari** [comment]
Oh, just thought: We're planning on adding go toolchain rules so please can download and configure the go toolchain through the build langage rather than requiring the host machine. When I do this work I plan to put some effort into cross compilation. If I can get that to work, we would be able to produce a BSD binary from a linux host and therefore add a BSD distribution. Probably won't happen any time soon though.

**Comment by peterebden** [comment]
> On another topic, tools/sandbox/main.c doesn't seem like it's going to really support FreeBSD.

It does by virtue of ifdef'ing most of itself out...
Fundamentally the existing code won't ever work on non-Linux platforms since it relies on namespace support. Maybe a FreeBSD equivalent could do something using jails (not that I know much about them...).
