### ISSUE TITLE
Missing symlinks when copying from plz-out to tmp dir

### ISSUE THREAD

**Issue by paulannetts** [thought-machine/please#646]
I'm seeing some failures in my build due to symlinks being lost while being a dependency is copied from `plz_out` to `tmp` tree.

The scenario is for Javascript app building using `yarn`.

Repro steps are captured in a self-contained example at https://github.com/paulannetts/plz-yarn-symlink, this includes the custom build rules and full BUILD file.

### Repro steps:
There are two targets on a single source directory. These are custom build definitions built on top of `gen_rule`.

1. "packages" will generate a lot of files in a `node_modules` output directory which includes internal symlinks (none going outside the TMP directory). This completes fine and can be seen with symlinks present inside of `plz-out` tree.
2. "dist" (depends on "packages", with additional "srcs"). 

Expected behaviour:
"dist" step should see the same `node_modules` directory with symlinks present in its TMP directory.

Actual behaviour:
The `tmp` directory copy of `node_modules` has lost the symlinks, particularly those in `node_modules/.bin`. The files are present, but not symlinked which causes build breaks for `yarn build`.
`yarn build` runs fine inside of `.../plz-out/gen/test_app` which proves the symlinks are fine from the previous "packages" stage.

### System setup:
macOS 10.14.5
node 10.15.3
yarn 1.16.0
Tested on please 13.8.2 and 13.9.0-alpha4

### BUILD file extract
See  https://github.com/paulannetts/plz-yarn-symlink for full, self-contained repro.
```
subinclude("//:yarn")

filegroup(
    name = "src_files",
    srcs = glob([
        "public/**",
        "*.js",
        "src/*.js",
        "src/assets/**",
        "**/*.vue",
    ]),
)

yarn_install(name = "packages")

yarn_build(name = "dist",
           srcs=[":src_files"],
           deps=[":packages"])
```

**Comment by paulannetts** [comment]
I can simulate this by creating a two step build:
- First step, generates a relative symlink inside the tree, to a file in a parent directory `../test1.txt`. This directory is then specified as an output of this step.
- Second, dependent, step, then checks if this is a symlink or not inside the file tree it can see.

build_defs contains following targets:

```
def create_symlink(name, outs=None, srcs=None,
                deps=None, visibility=None):
    deps = (deps or []) 

    file_to_link = srcs[0]
    _, file_name_to_link = split_path(file_to_link)
    cmds = ["cd $PKG",
            "mkdir my_sub_dir/links",
            "cd my_sub_dir/links",
            "ln -s ../" + file_name_to_link + " " + file_name_to_link,
            "cd $TMP_DIR",
            "cd $PKG",
            "mv my_sub_dir $TMP_DIR/my_out_dir"]
    cmd_text = ' && '.join(cmds)
    log.info(f"command: {cmd_text}")

    return genrule(
        name = name,
        outs=outs,
        srcs=srcs,
        tools = ["ln"],
        cmd = cmds,
        visibility = visibility,
        deps = deps,
    )

def check_symlink(name, outs=None, srcs=None,
                deps=None, visibility=None):
    deps = (deps or []) 

    file_to_link = srcs[0]
    _, file_name_to_link = split_path(file_to_link)
    link_file = join_path("my_out_dir/links", file_name_to_link)
    cmds = ["cd $PKG",
            'if [[ -L ' + link_file + ' ]]; then echo "OK - is a symlink"; else echo "BAD - is not a symlink" && exit -1; fi',
            'cd $TMP_DIR',
            'touch ok.txt']
    cmd_text = ' && '.join(cmds)
    log.info(f"command: {cmd_text}")

    return genrule(
        name = name,
        outs=outs,
        srcs=srcs,
        tools = ["ln"],
        cmd = cmds,
        visibility = visibility,
        deps = deps,
    )
```

BUILD file:
```
create_symlink(name = "step1",
           srcs=["my_sub_dir/test1.txt"],
           outs=["my_out_dir"])


check_symlink(name = "step2",
           srcs=["my_sub_dir/test1.txt"],
           deps =[":step1"],
           outs=["ok.txt"])
```
step1 is successful, plz-out does contain a symlink, however, the `check_symlink` step2 fails.

**Comment by paulannetts** [comment]
I found a workaround to this. If you generate a `tar` archive of the desired outcome of step#1, then it will retain the symlinks internally to the tar archive.

At this point, if step#2 then starts by untar'ing the output from step#1, the symlinks are maintained as expected.

It introduces the overhead of the tar/untar, but that appears to be partially offset by Please having to do less work as it has a single file to transfer between build steps.

**Comment by sebastian-nowak** [comment]
Seems to be related: https://github.com/thought-machine/please/issues/832

**Comment by Tatskaari** [comment]
This has now been resolved in later versions of please.
