### ISSUE TITLE
Return stable version from `/latest_version`

### ISSUE THREAD

**Issue by steakunderscore** [thought-machine/please#664]
## Problem

Currently requesting `https://get.please.build/latest_version` returns `14.0.0-beta1`. It should really only be returning stable releases.

## Context

This url is being used for [automating updating](https://aur.archlinux.org/cgit/aur.git/tree/update-version.sh?h=please-bin) the version on [Arch AUR](https://aur.archlinux.org/packages/please-bin/). However this should be set to using a stable version only. Currently it can't be used for that as doesn't return stable releases only.

The other places `/latest_version` is being used is calling `plz update` and ruining `curl https://get.please.build | bash`. Both of these should also be using stable releases by default.

## Solution

- [ ] `/latest_version` should return stable versions only.
- [ ] A new `/latest_prerelease_version` should return stable, alpha and beta versions, whichever was most recently built.
- [ ] Update docs

**Comment by peterebden** [comment]
For bonus points, add a `--prerelease` flag or similar to `plz update` which lets it opt into updating to the `latest_prerelease_version`.

**Comment by agenticarus** [comment]
This seems to be working for latest_version at least.
