### ISSUE TITLE
"please run" not correctly passing through arguments

### ISSUE THREAD

**Issue by ThisGuyCodes** [thought-machine/please#669]
Related #338 ? At least it's certainly a shell quoting issue.

`plz run //external/binaries:hub -- "pr list"`

Expected output:
```
git: 'pr list' is not a git command. See 'git --help'.
```

Actual output:
```
      #2  pr 2
      #1  pr 1
```

The actual thing I'm struggling with is:
`pr list --format="%U %B%n"`, that space is causing the format param to not get passed through. But I thought this as an example was more communicative of what's happening.

**Comment by peterebden** [comment]
Not sure I quite understand what's going on here - for me it seems to work as expected:
```
$ plz run //tools/misc:hub -- "pr list"
error: invalid key: alias.pr list
git: 'pr list' is not a git command. See 'git --help'.
$ plz run //tools/misc:hub -- pr list
github.com username: 
```

What does your `hub` rule look like? Could there be something else between the two that's breaking the string?

**Comment by ThisGuyCodes** [comment]
I had written some local tests to validate this problem, and now they're all passing; IDK what changed.

There must have been some problem with my shell state. Sorry for the confusion.

**Comment by peterebden** [comment]
No worries, always good to confirm these things!
