### ISSUE TITLE
Please website looks ugly on mobile phone

### ISSUE THREAD

**Issue by JensRantil** [thought-machine/please#715]
The left menu spans body. See attached screenshot. 
![Screenshot_20190824-232800](https://user-images.githubusercontent.com/730342/63643150-c017f600-c6ca-11e9-8c13-aa592fbf90d0.png)

**Comment by Tatskaari** [comment]
Looks like we have "improved" things now and it displays like a desktop site. Would be nice if we had a proper mobile site however we're a small team and I doubt many people are browsing our documentation on mobile. Going to close this for now.
