### ISSUE TITLE
Add build-time environment variable...

### ISSUE THREAD

**Issue by ddseanc** [thought-machine/please#716]
When running `plz build --shell :foo` I want to recursively call `plz run` as part of my build steps, and therefore conditionalize passing the `--nolock` flag.

How can I detect that I'm running from inside of `plz` already in order to conditionally set this flag?  It seems like an environment variable could be set.

```sh
PLZFLAGS=""
if [ -n "$PLZ_PID" ]; then
  PLZFLAGS="-nolock"  
fi

plz run $PLZFLAGS -- :foo
```

Or should I just unconditionally use `plz run --nolock` from scripts that call `plz run`.  ?

**Comment by agenticarus** [comment]
Hi @ddseanc - why do you want to run `plz run` as part of the build step (as opposed to, say, depending on some other target in the build definition)?

**Comment by sean-** [comment]
We have a `plz gen-docs` alias that runs a shell script that generates README docs from the execution of the binaries in the repo and then these can be committed to Git. 

Effectively `plz gen-docs` calls a series of `plz run` commands, like `plz run //cmd/foo -- --make-docs > cmd/foo/README.md` that way we can capture the output outside of the `plz-out` directory (i.e. not `plz-out/bin/cmd/foo/README.md`).

Being able to harvest output and store it in git has been a problem for me a few times (e.g. auto-generated protobufs or other source files that need to be committed).

**Comment by peterebden** [comment]
I think the easiest answer here is to use the `buildenv` config property (`plz help buildenv` can explain it a bit more) to set some arbitrary env var which you can later read to detect its presence. Given that I'm not sure it's really necessary for us to add anything extra - shout if that doesn't do what you need though.
