### ISSUE TITLE
The current go rules do not support multiple go_import_paths

### ISSUE THREAD

**Issue by namtzigla** [thought-machine/please#740]
The current go build rules do not support multiple go_import_paths in the same repo. I've put together a sample repo where I test this: https://github.com/namtzigla/please-import-paths. 

Can you confirm this please?

For a permanent solution I think every go_library/go_get should generate an extra file that should contain the package import path. It might help with the generating the GOPATH in the build process but it might have some side effects that I'm not aware now.

**Comment by namtzigla** [comment]
For plz >= 4.1.0 since please_maven location has moved into pleasings because of the `importpath` of a referenced repository (pleasings in this case) or the lack of support of specifying the package name (or package import path) I'm getting this error:

```
$ plz build ///pleasings//java/maven:please_maven
Build stopped after 70ms. 1 target failed:
    ///pleasings//java/maven:_please_maven#lib
Error building target ///pleasings//java/maven:_please_maven#lib: exit status 1
java/maven/main.go, line 20, column 2: can't find import: "github.com/thought-machine/pleasings/java/maven/maven"
```

This is very easy to reproduce in any new initialized repo just run the above command.

I think there could be two solutions here:
1. Fix the subinclude/subrepo to load configs from the referenced repo.
2. Allow the go_library/go_get to be able to manipulate the package import path.

IMO the first option might create side effects in the existing projects but I would like to hear your opinion on this first before I will submit a PR on this.

Thanks!

**Comment by peterebden** [comment]
(1) is the "right" answer and is tracked in #744 - unfortunately when I last looked it did not look easy. Definitely happy if you want to have a look though!
