### ISSUE TITLE
Subrepos should honour default config files

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#744]
If you don't explicitly specify a config file for your subrepo, and the target repo has a `.plzconfig` in it, it should automatically get loaded.

This isn't very easy unfortunately; we set up the subrepo during parse of the BUILD file but do not have the config file until we build the relevant dependency. Don't have a plan about how to fix that but leaving this here to track the desired behaviour.

**Comment by Tatskaari** [comment]
@pebers I think this is still an issue. Maybe one for the plugin work?

**Comment by Tatskaari** [comment]
This has been done as part of the plugin work.
