### ISSUE TITLE
Building & testing npm/yarn based JS projects

### ISSUE THREAD

**Issue by brent-soles** [thought-machine/please#746]
I was combing the docs and unable to find anything relating to building for frontend code, and am curious if there is a way to build js using Please.?

Currently, I using a combination of the `genrule` and `gentest`, however, they are not running successfully due to the nature of how dependencies are handled in js development.

Any pointers or examples as to how to include these using Please? Or if it is not currently supported, is there any future plans for adding support for js?

Please let me know if there is any further information that is required. This isn't much an issue as it is a request for information. If there is another avenue I should pursue for answers, please let me know. Thanks!

**Comment by peterebden** [comment]
It certainly is possible; we have this set up internally (but unfortunately it doesn't generalise super well beyond our current repo). @namtzigla has been working on it too and may be in a better place (he's done some work on https://github.com/thought-machine/pleasings/blob/master/js/yarn.build_defs for example).

**Comment by namtzigla** [comment]
I'm working on a solution to help developing ui in js/ts but I'm far from ready to share it w/ the rest of the world.
