### ISSUE TITLE
Remove `plz follow`

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#750]
It's a cute feature and I like how non-intrusive it was, but we aren't using it right now; it probably wasn't popular enough to be worth us trying to bring it back.

Unless anyone else deeply cares I think it isn't pulling its weight as a top-level command and should probably be removed.

**Comment by macripps** [comment]
Noone has come out in support of this, I think it can go

**Comment by peterebden** [comment]
Agreed but we should time it right; it's a breaking change so should go in for v15 - since we don't maintain v14 as a separate branch as soon as we remove it we can't do any more releases in the v14 line.
