### ISSUE TITLE
cc_shared_object should prefix default output with lib

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#751]
For unclear but almost certainly silly reasons `cc_static_library` outputs `lib{name}.a` by default, but `cc_shared_object` outputs `{name}.so`. In general giving them a `lib` prefix is a lot more usual and linkers obviously prefer it that way.

This is clearly a breaking change...

**Comment by micahcc** [comment]
Close?

**Comment by peterebden** [comment]
Ah yeah thanks, I forgot to write the correct incantation in the PR :)
