### ISSUE TITLE
Question on Windows support

### ISSUE THREAD

**Issue by wjk** [thought-machine/please#757]
Greetings! I was thinking of attempting to get Please (at least somewhat) working on Windows, as I target that platform frequently. I understand having read #227 that Please takes numerous dependencies on bash and the GNU coreutils. Would it be an acceptable workaround if I was to create tools with the same name, written in Go, that perform their expected tasks in a Windows-compatible way? Please would then set the PATH to find those tools first when invoking a command. The tools I foresee needing to write are as follows:

* `bash`. This is a biggie, but since Please (AFAIK) only uses a tiny subset of bash's syntax, and in particular does not invoke it interactively, I can implement only the subset of bash that is needed. Specifically, I will support splitting a command-line into several subcommands (using `&&` as the delimiter), running each subcommand one at a time and testing the exit code of each before running the next. I will also need to implement output redirection using `>`; `|` is AFAICT only used in unit test code.
* `cp`, `mv`, `which`, and `echo`: These are simple.
* `find` and `xargs`: Used only in test code AFAICT.

Since FreeBSD includes a compatible implementation of `find` and `xargs`, I can simply port them from there instead of writing them from scratch. FreeBSD's shell implementation could also help me implement output redirection using `>`, `>>`, and `|`. Also, please let me know if I missed any required coreutils tools above.

Does this sound like a good plan? Thanks!

**Comment by peterebden** [comment]
I've not had much opportunity to even test it; I don't actually have access to a Windows dev machine (I suppose I could spin up a VM in the cloud but have never gotten around to it). I've heard that others have had some luck using WSL though which I was meaning to look into (and hopefully get working on CircleCI if possible as well).

In regard to your plan about replacements, I think it's a little harder than you describe for Bash - we use variables in some places too, for example. I'd rather reduce that where possible, admittedly (have idly thought about letting rules specify a shell and by default having something minimal or even just a straight exec where possible).
There are definitely some uses of find / xargs that are not test code too (looks like at least the Python and Go rules invoke them).

I'd have some concern about the work & ongoing maintenance of us shipping something of that complexity. For a first step it'd be nice to have it working by the user bringing their own environment - either via WSL or something like gnuwin32, and only writing our own if we find that's not tenable for whatever reason. Does that sound good to you?

**Comment by wjk** [comment]
In all honesty, I now have a lot less spare time available to work on side-projects such as this one than I had when I submitted this issue. Your mention of gnuwin32 is a very good idea, and I will most likely pursue that avenue if/when I return to this project. Feel free to close this issue if you want. Thanks!
