### ISSUE TITLE
use different workers for the same test if n > 1

### ISSUE THREAD

**Issue by goddenrich** [thought-machine/please#761]
Currently if the test target is run more than once (either if it is marked as flaky or if the -n flag > 1) then the runs are done in series on the same worker. When a few tests are dramatically longer than the rest of the suite the duration of the test is dramatically longer waiting for the single worker to complete all runs of that long test. It would be significantly faster if we could run them on different workers.

**Comment by peterebden** [comment]
To speed it up they'd also have to be run in parallel, right? Which is not currently an option even with -n.

Sounds legit but could be quite a bit of internal work (especially around how the multiple workers get managed / assigned to).

**Comment by goddenrich** [comment]
Well yes not necessarily in parallel But whenever a worker becomes free. Yes seems like quite a bit to do this but some of our sat tests take 5mins or more. Running them 100 times (for flake detection) makes the build Over 8 hours long. If we could share over eg 10 workers the build could take about 1hr instead so I think it's worth the work.

**Comment by peterebden** [comment]
This was shipped a while back now (in #966).
