### ISSUE TITLE
`please_sanbox` error with unprivileged user

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#763]
After setting owner to `root` and add `setuid` to `please_sandbox` binary.
Running `please_sandbox` with an unprivileged user lead to an error like:

    fclose: Operation not permitted

Tested on Debian 10, Ubuntu 18.04 and Fedora 30.

**Comment by peterebden** [comment]
You shouldn't need to `setuid` the sandbox binary; an older version needed that but newer kernels with user namespace support should be able to run it as an unprivileged user.

**Comment by sfirmery** [comment]
Thanks, it works fine without `setuid`.
