### ISSUE TITLE
Creating a target with the same name as a previously deleted one causes build errors

### ISSUE THREAD

**Issue by perpetualjourney** [thought-machine/please#766]
To reproduce:
Create a file `example_test.go` and build rule
```
go_test(
    name = "example_test",
    srcs = [
        "example_test.go",
    ],
)
```
Build the target, then delete `example_test.go` and the relevant BUILD file and create a folder named `example_test` with any buildable in it (even the same `example_test/example_test.go`).

Trying to build the contents of `example_test/...` fails with the following error:
```
Error preparing directories for //example_test:example_test: mkdir example_test: not a directory
```

This is due to an orphaned output in `plz-out/example_test` that doesn't get cleaned after the original rule is removed.

To solve this, perhaps plz should determine the contents of `plz-out` and clean any outputs for deleted targets.

**Comment by agenticarus** [comment]
Agreed that this should not cause an error.

**Comment by Tatskaari** [comment]
Going to close this as I think that change fixes your issue. There's an issue that has always been there that could potentially manifest where a file gets deleted when it shouldn't however the cost of having this particular case manifest on a  CI agent is problem higher.
