### ISSUE TITLE
Can we release, plz?

### ISSUE THREAD

**Issue by jbarcsfx** [thought-machine/please#769]
Hi @peterebden, recently we merged this PR: https://github.com/thought-machine/please/pull/762
Is there any news when will please release? We have workarounds in place that are quite bothering for most of my team and having this all nice and fixed would help us tremendously.
Thanks!

**Comment by peterebden** [comment]
Done!

FYI this is managed by the `VERSION` and `ChangeLog` files; if you require a new version you can also send a PR to update those.
