### ISSUE TITLE
Go build failing

### ISSUE THREAD

**Issue by ginty** [thought-machine/please#772]
I'm new to Please (which looks great!), so possibly this could be user error...

I have the following third party Go build dependency defined:

~~~python
go_get(
    name = 'cobra',
    get = 'github.com/spf13/cobra/cobra',
    revision = 'v0.0.5',
    deps = [
        ':go-homedir',
        ':viper',
    ],
)
~~~

However, this target produces the following build error:

~~~
Build stopped after 250ms. 1 target failed:
    //third_party/go:cobra
Error building target //third_party/go:cobra: exit status 1
third_party/go/src/github.com/spf13/cobra/cobra/cmd/add.go, line 21, column 2: no Go files in <repo>/plz-out/tmp/third_party/go/cobra._build/third_party/go/src/github.com/spf13/cobra
~~~

Here is the offending line in the code:

https://github.com/spf13/cobra/blob/master/cobra/cmd/add.go#L21

It seems like Please is adding an additional directory which is causing the problem, the Go compiler is looking for:

~~~
plz-out/tmp/third_party/go/cobra._build/third_party/go/src/github.com/spf13/cobra/main.go
~~~

but what Please has created is (note the additional cobra dir at the end):

~~~
plz-out/tmp/third_party/go/cobra._build/third_party/go/src/github.com/spf13/cobra/cobra/main.go
~~~

Not sure if there is anything I should do differently in my application to resolve this, or if it is a bug?

Thanks!

**Comment by sean-** [comment]
Try the following if you want just the library:

```python
go_get(
    name = 'cobra',
    get = 'github.com/spf13/cobra',
    revision = 'v0.0.5',
    deps = [
        ':go-homedir',
        ':viper',
    ],
)
```

if you're trying to build the cobra command as a build-time dependency, you probably need to do something like:

```python
go_get(
    name = 'cobra',
    get = 'github.com/spf13/cobra',
    revision = 'v0.0.5',
    deps = [
        ':go-homedir',
        ':viper',
    ],
)

go_get(
    name = 'cobra-bin',
    binary = True,
    get = [],
    install = ["github.com/spf13/cobra/cmd/cobra"],
    deps = [
        ':cobra',
    ],
)
```

There's probably more to it than that, but that should get you started.

**Comment by ginty** [comment]
@sean-, thank you!

I guess the problem was that I had 'cobra/cobra' in the get reference when it should have just been 'cobra', I'm not sure how I ended up with that but I looked right past it several times when trying to work out what was going on here.

I now have it building, thanks a lot for taking the time to read and answer this.
