### ISSUE TITLE
Using pleasew gives error on apline

### ISSUE THREAD

**Issue by steakunderscore** [thought-machine/please#774]
I have a docker file which I want install plz in. The plan is to later use this container as a build base from which to build my code in.

```Dockerfile
FROM golang:alpine AS builder

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add bash curl && \
    rm -rf /var/cache/apk/*

# Install please build system
ADD plzconfig .plzconfig
ADD pleasew pleasew
RUN ./pleasew
```

However when I try to build the docker file I get "No such file or directory" from pleasew

```
Sending build context to Docker daemon  1.738kB
Step 1/11 : FROM golang:alpine AS builder
 ---> 3024b4e742b0
Step 2/11 : WORKDIR /app
 ---> Running in 955073e9342d
Removing intermediate container 955073e9342d
 ---> 05e4b1e1091a
Step 3/11 : RUN apk update &&     apk upgrade &&     apk add bash curl &&     rm -rf /var/cache/apk/*
 ---> Running in c8f01d01f708
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.3-39-g3eab7ec650 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.3-43-gcc200417b2 [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10339 distinct packages available
(1/2) Upgrading busybox (1.30.1-r2 -> 1.30.1-r3)
Executing busybox-1.30.1-r3.post-upgrade
(2/2) Upgrading ssl_client (1.30.1-r2 -> 1.30.1-r3)
Executing busybox-1.30.1-r3.trigger
OK: 6 MiB in 15 packages
(1/8) Installing ncurses-terminfo-base (6.1_p20190518-r0)
(2/8) Installing ncurses-terminfo (6.1_p20190518-r0)
(3/8) Installing ncurses-libs (6.1_p20190518-r0)
(4/8) Installing readline (8.0.0-r0)
(5/8) Installing bash (5.0.0-r0)
Executing bash-5.0.0-r0.post-install
(6/8) Installing nghttp2-libs (1.39.2-r0)
(7/8) Installing libcurl (7.66.0-r0)
(8/8) Installing curl (7.66.0-r0)
Executing busybox-1.30.1-r3.trigger
OK: 16 MiB in 23 packages
Removing intermediate container c8f01d01f708
 ---> b954940861de
Step 4/11 : ADD plzconfig .plzconfig
 ---> 8a8cd54bab94
Step 5/11 : ADD pleasew pleasew
 ---> e43f76950a16
Step 6/11 : RUN ./pleasew
 ---> Running in 1065a91c3f7d
Can't determine version, will use latest.
Downloading Please 14.1.9 to /root/.please/14.1.9...
Should be good to go now, running plz...
./pleasew: line 69: /root/.please/please: No such file or directory
The command '/bin/sh -c ./pleasew' returned a non-zero code: 127
```

I would guess that this is an issue with running plz on alpine. This issue doesn't happen if I use `golang:stretch` instead as a base image.

**Comment by wuhkuh** [comment]
I think `pleasew` in your image is built against `gcc`, which is not supported out of the box on Alpine Linux. To make sure, try the following:

1. `apk add file`
2. `file pleasew`

and see what it is built against.

**Comment by steakunderscore** [comment]
I agree `pleasew` likely to be assuming glibc is there, but instead on alpine there's musl.

The file `pleasew` is a bash script, so. I would assume it's this: https://github.com/thought-machine/please/blob/master/tools/misc/pleasew :
```
pleasew: Bourne-Again shell script, ASCII text executable
```

**Comment by peterebden** [comment]
It is indeed that file, yes.

At present the Linux binary distributions of Please are compiled for glibc, which I strongly suspect is the issue as @wuhkuh suggests above (that "no such file or directory" can appear because the requested dynamic linker is not available).

We could fix either by distributing Alpine Linux binaries as well or (possibly better) statically linking the standard one (which may itself need to be built in Alpine...)

**Comment by peterebden** [comment]
Turns out this is easily fixed by `apk add libc6-compat`. I think that's sufficiently easy (and users of Alpine likely aware enough of these issues) that there isn't much more we should do here.
