### ISSUE TITLE
Requires golang 1.12+

### ISSUE THREAD

**Issue by wuhkuh** [thought-machine/please#781]
As Please depends on [bazelbuild/remote-apis-sdks](https://github.com/bazelbuild/remote-apis-sdks), which in turn introduced https://github.com/bazelbuild/remote-apis-sdks/commit/0f29ab331fb9dcdbc3f484ecc742e96fed77b909, Please now requires Go 1.12 or later during bootstrapping: `strings.ReplaceAll` is not available in earlier versions of Go.

The easiest (temporary) solution would be to update the documentation and images to require Go 1.12+.

**Comment by peterebden** [comment]
Thanks - nice spot! The images are already at 1.13 / 1.12 but I will update the documentation - I think there's little issue there given that older versions are unsupported upstream anyway.

Would be nice if go modules gave more hints around this... 🤔
