### ISSUE TITLE
Unable to bootstrap on linux arm

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#796]
$ ./bootstrap.sh 
Building Please...
Build finished; total time 1.19s, incrementality 100.0%. Outputs:
//src:please:
  plz-out/bin/src/please
Building the tools...
Build stopped after 2.42s. 6 targets failed:
    //tools/sandbox:_please_sandbox#lib_cc
Error building target //tools/sandbox:_please_sandbox#lib_cc: exit status 1
tools/sandbox/main.c: In function 'mount_tmp':
tools/sandbox/main.c, line 103, column 23: error: 'MS_LAZYTIME' undeclared (first use in this function)
     const int flags = MS_LAZYTIME | MS_NOATIME | MS_NODEV | MS_NOSUID;
                       ^
tools/sandbox/main.c, line 103, column 23: note: each undeclared identifier is reported only once for each function it appears in

    //third_party/python:_coverage#2
1 error occurred:

* Error retrieving https://get.please.build/third_party/python/py34/coverage-4.3.4-linux_arm.whl: 404 Not Found
    //third_party/python:_coverage#4
1 error occurred:

* Error retrieving https://get.please.build/third_party/python/py36/coverage-4.3.4-linux_arm.whl: 404 Not Found
    //third_party/python:_coverage#1
1 error occurred:

* Error retrieving https://get.please.build/third_party/python/py27/coverage-4.3.4-linux_arm.whl: 404 Not Found
    //third_party/python:_coverage#3
1 error occurred:

* Error retrieving https://get.please.build/third_party/python/py35/coverage-4.3.4-linux_arm.whl: 404 Not Found
    //third_party/python:_coverage#5
1 error occurred:

* Error retrieving https://get.please.build/third_party/python/py37/coverage-4.3.4-linux_arm.whl: 404 Not Found

**Comment by peterebden** [comment]
Interesting... AFAIK the MS_LAZYTIME issue is not ARM-specific but does require Linux > 4.0ish, could you have an older version than that?

The coverage wheels indeed won't have an ARM version. The "real" solution is probably to do less in the core plz repo - in the short term we can probably build & upload versions of them.

**Comment by linuxerwang** [comment]
Hi, Peter

You are right, the kernel version is 3.4. Thank you!

**Comment by peterebden** [comment]
Thanks for confirming - that flag is not very crucial so will try a simple workaround if it's not there.

In general there might be a few places internally that don't generalise well beyond amd64 - we haven't looked at plz running on other architectures in much detail.

**Comment by linuxerwang** [comment]
Please let me know if there's anything I can help. I have a couple of such devices to test on and I can do it in my spare time.

**Comment by linuxerwang** [comment]
After synced from the latest commit, I got this error:

```
Build stopped after 1.99s. 1 target failed:
    //third_party/proto:_protoc#download
1 error occurred:
        * Error retrieving https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-arm.zip: 404 Not Found
```

Thanks.

**Comment by peterebden** [comment]
Ah right - looks like we name the architecture differently to that protobuf binary. In the medium term I'd like to lose proto compiling from the bootstrap process but it's easy enough to do a quick fix for now.

Haven't had a chance to look at the wheel situation yet but will hopefully have some time when I'm back at work in the next couple of days.

**Comment by peterebden** [comment]
Hmmm, I was hoping I could get the wheels from upstream, but there are no prebuilt ones for ARM. Producing them for all the Python versions could be a pain; I might have a look at making them optional instead (they're only a speedup for coverage, the binary bits aren't a hard requirement really).

**Comment by linuxerwang** [comment]
@peterebden 7 months later, today I tried it again, and found most of please can be bootstrapped. First I synced up to the latest commit, and ran bootstrap.sh in my small arm box with kernel 3.4:

```bash
$ ./bootstrap.sh 
Building Please...
Build stopped after 2.8s. 1 target failed:
    //src/cache/tools:tools
Error building target //src/cache/tools:tools: exit status 1
src/cache/tools/hash.go, line 12, column 18: constant 4294967295 overflows int

exit status 2
```

So I changed src/cache/tools/hash.go, line 12 to the following line:

```go
return uint32(uint64(i) * math.MaxUint32 / uint64(n))
```

Then it passed until the tests step:

```bash
$ ./bootstrap.sh 
Building Please...
Build finished; total time 46.7s, incrementality 66.0%. Outputs:
//src:please:
  plz-out/bin/src/please
Building the tools...
Build finished; total time 21.41s, incrementality 92.0%. Outputs:
//package:installed_files:
  plz-out/bin/package/build_langserver
  plz-out/bin/package/jarcat
  plz-out/bin/package/javac_worker
  plz-out/bin/package/junit_runner.jar
  plz-out/bin/package/please
  plz-out/bin/package/please_go_filter
  plz-out/bin/package/please_go_test
  plz-out/bin/package/please_pex
  plz-out/bin/package/please_sandbox
Running tests...
python3 includes not found, excluding py3 API tests
Clang not found, excluding Clang tests
32-bit gcc libraries not found, excluding cross-compile tests
Build stopped after 2m12.64s. 3 targets failed:
    //third_party/proto:_protoc#download
1 error occurred:

* Error retrieving https://github.com/google/protobuf/releases/download/v3.12.2/protoc-3.12.2-linux-arm.zip: 404 Not Found
    //test/go_rules/asm:_asm#asm
Error building target //test/go_rules/asm:_asm#asm: exit status 1
test/go_rules/asm/add.s, line 3: unrecognized instruction "MOVQ"
test/go_rules/asm/add.s, line 4: unrecognized instruction "MOVQ"
test/go_rules/asm/add.s, line 5: unrecognized instruction "ADDQ"
test/go_rules/asm/add.s, line 6: unrecognized instruction "MOVQ"
asm: assembly of test/go_rules/asm/add.s failed

    //test/config_rules:all
/home/ubuntu/please-arm/test/config_rules/BUILD:5:13: error: None of the select() conditions matched
    srcs = ["config_test.py"],
    flags = select({
            ^
        "//test/config_rules/config:x86_64": "--arch=x86_64",

Traceback:
/home/ubuntu/please-arm/test/config_rules/BUILD:5:13:       flags = select({
/home/ubuntu/please-arm/test/config_rules/BUILD:2: 1:   python_test(
```

Since the build worked, I ignored the tests failure and ran install.sh:

```
$ ./install.sh 
Please installed
```

Very nice!

It can't download the protoc for arm, but I can work around it by providing my own build.

**Comment by peterebden** [comment]
Great news! FWIW FreeBSD has a similar issue with not being able to download the protoc and we just point it at the system one (in `.plzconfig_freebsd_amd64`).

I actually think that cache/tools package might be obsolete now... sorry for the trouble! Will check if it can be deleted.
