### ISSUE TITLE
go_binary requires gcc

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#797]
We attach gcc (or whatever's configured) as a tool to pass to `-extld` in case it's linking in external mode. However if we're not it always fails fast if gcc isn't installed.

Not very obvious how we fix since it's hard for us to know which link mode will be needed. Could have a config option but it seems fiddly.

**Comment by Tatskaari** [comment]
Seems reasonable that if your project requires an external linker you must add it to the go config:
```
[go]
extld = clang
```
We then only pass in the link too if this is set. 

@peterebden thoughts?

**Comment by peterebden** [comment]
I guess that is reasonable. It seems slightly fiddly to have `go.extld` as well as `cpp.ldtool` but I guess it is more flexible and explicit.

**Comment by Tatskaari** [comment]
Seems like we can unify all the go CC config into a single `go.cctool` as described in #1736. Going to push this back to v17 though.

**Comment by Tatskaari** [comment]
Duplicate of https://github.com/thought-machine/please-issues/issues/40
