### ISSUE TITLE
--nocache is not respected

### ISSUE THREAD

**Issue by binhonglee** [thought-machine/please#799]
![nocache](https://user-images.githubusercontent.com/16726210/71550150-8a3b9480-297e-11ea-8af0-80c0c7c233b0.png)

Even when I use the `--nocache` tag, it would still show cached test results.

**Comment by agenticarus** [comment]
This is expected (if not obvious) behaviour - all `--nocache` does is disable the artifact caches (i.e. the build step). In order to disable test caching you can run your tests with `-n 2` (which will run the test twice and disable result caching)
