### ISSUE TITLE
How to go_get repos having cyclic dependency?

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#801]
These repos have cyclic dependency:

```
github.com/prometheus/client_golang      <==
==> github.com/prometheus/common           |
    ==> github.com/mwitkow/go-conntrack  ===
```

Does anyone know how to go_get them correctly?

Thanks!

**Comment by agenticarus** [comment]
You have two options - either have multiple `go_get` rules for the sub packages (see https://github.com/thought-machine/please/blob/master/third_party/go/BUILD#L501-L533 - a similar approach might work for you) or you can make use of the `strip` and `install` arguments and cut out parts that would cause a loop or that depend on packages you don't care about.
