### ISSUE TITLE
Symlinks not preserved when passing a folder through deps

### ISSUE THREAD

**Issue by sebastian-nowak** [thought-machine/please#832]
There seems to be an issue with passing a folder through deps, if the folder includes symlinks. The symlinks are replaced with copies of target files.

I've encountered the issue multiple times in real world scenarios and it's super painful - it's breaking `node_modules` and the prebuilt nodejs binaries (https://nodejs.org/en/download/).

Here's a simplified repro script:

```python
genrule(
  name = 'check_link',
  deps = [':data'],
  outs = ['success.txt'],
  cmd = [
    'test -L some_folder/bin/link.js',
    'echo asd > success.txt'
  ]
)

genrule(
  name = 'data',
  srcs = [],
  outs = ['some_folder/'],
  cmd = [
    'mkdir $OUT/bin',
    'mkdir $OUT/src',
    'echo asd > $OUT/src/file.js',
    'cd $OUT/bin',
    'ln -s ../src/file.js link.js'
  ]
)
```

Just put it in the plz root and run `plz build` - it will fail on the `test -L some_folder/bin/link.js`.

**Comment by sebastian-nowak** [comment]
Is there any chance it will get fixed soon?

**Comment by Tatskaari** [comment]
Sorry for the delay, it appears this has been resolved at some point: 
```
$ plz build //symlinks:check_link
Build finished; total time 60ms, incrementality 50.0%. Outputs:
//symlinks:check_link:
  plz-out/gen/symlinks/success.txt
```
