### ISSUE TITLE
jarcat core dumped on Centos 8

### ISSUE THREAD

**Issue by awagelight** [thought-machine/please#847]
OS: `Centos 8`
Please version: `14.3.2`
Issue: `[1]    14424 segmentation fault (core dumped) jarcat -h`

jarcat in `Please version 14.3.2` package can not run on Centos 8.

some other relate build error
> Error building target //cc:_sum_lib#cc: exit status 139
   bash: line 1: 14475 Segmentation fault      (core dumped)  ar -r

but jarcat in `Please version 14.0.0` package works well.

Please help me check this issue.

Thank you very much.

**Comment by peterebden** [comment]
I can't reproduce this one. I have a Docker container running Centos 8 in which Please and its attendant binaries run fine. They have very few system dependencies (really just libc6, libpthread, vdso and the dynamic linker) and it seems unlikely those would differ significantly between a Ubuntu install that we build in and a Centos one.

I feel like this may be a property of the system you're running it on; if you're getting segfaults from `ar` as well that suggests things might not be in good shape...

**Comment by awagelight** [comment]
@peterebden 

Thank you for your time, I will try to build in dock Centos 8 to make sure my development environment clean.

BTW, please is an awesome tool, my team loves it so much. `Thank you for your team's work! `

**Comment by peterebden** [comment]
You're welcome! Hope your investigation can shed a bit more light onto this one :)
