### ISSUE TITLE
Please fails if the repo has spaces anywhere in the path

### ISSUE THREAD

**Issue by airbornemint** [thought-machine/please#849]
```
$ mkdir "a b"
$ cd "a b"
$ please init
$ touch BUILD
$ please build
Build stopped after 200ms. 1 target failed:
    //:pleasings
error moving outputs for target //:pleasings: rule //:pleasings failed to create output plz-out/tmp/pleasings._build/pleasings
```

Giving up on please completely; proper shell quoting is a non-negotiable feature of a build tool as far as I am concerned.

**Comment by macripps** [comment]
Hi @airbornemint - thanks for reporting this issue. I have made an initial attempt at fixing the build rules, please let us know if this solves your problem!
