### ISSUE TITLE
no coverage on java_test target

### ISSUE THREAD

**Issue by michael-the-grey** [thought-machine/please#851]
I'm trying to get test coverage working for a`java_test` target, and I'm wondering if there is some setup in the repo that isn't quite right.

build file found at `foo/bar/baz`

```
java_test(
    name = "test",
    srcs = glob(["src/test/**/*.java"]),
    deps = [
        ':lib',
    ],
    test_package = "com.company.namespace.bar.baz",
)
```

```
./pleasew cover foo/bar/baz:test --shell
Temp directories prepared, total time 7.99s:
  //foo/bar/baz:test: /path/to/project/plz-out/tmp/foo/bar/baz/test._test
    Command: java -Dbuild.please.testpackage=com.company.namespace.bar.baz  -jar foo/bar/baz/test.jar
bash-3.2$ ls
test.jar
```

A few things that I notice here 

- java on the host machine is used rather than the java tools found in `$HOME/.please`
- in the command `-jar foo/bar/baz/test.jar` doesn't match the actual path of the jar which is `test.jar`

Additionally, when I'm in the shell and I manually change the command to reference the `test.jar`, there are test results output to the directory `test.results` rather than the file `test.coverage`

```
bash-3.2$ tree
.
├── test.coverage
├── test.jar
└── test.results
    ├── TEST-com.company.namespace.bar.baz.ATest.xml
    └── TEST-com.company.namespace.bar.baz.BTest.xml
```

The best idea I have at the moment is would be to figure out how to update the `.plzconfig` to reference the already installed tools under `$HOME/.please` for building and running these tests rather than what is found on the host machine. I look forward to any advice you have to offer. Thanks.

**Comment by Tatskaari** [comment]
1) You can now use the java_toolchain rule to define a java version to download and use for building and testing your java code. There's no jdk/jre in .please, so this is the only way to use a jre that isn't on the host machines path.
2) There's is a known issue with plz cover --shell and plz test --shell. The location of the test jar isn't set correct when printing the command that should be executed. It's quite a tricky bit of code to fix and isn't really bothering anybody too much so it's on the back burner. 
3) test.coverage should have your coverage results. Test results still go in test.results.
