### ISSUE TITLE
Error installing please in MAC

### ISSUE THREAD

**Issue by zztop** [thought-machine/please#866]
I am getting following error when I install please in Mac.
```WARNING: Downgrading to Please version 14.1.6 (currently 14.3.4)```

It tries to download 14.1.6 version

I installed it both from Brew as well as running the installation script.
Please help

**Comment by macripps** [comment]
You should check (or remove) the version of plz in your .plzconfig file.

**Comment by Tatskaari** [comment]
As mentioned, please will self-upgrade/downgrade to the version specified in the .plzconfig.
