### ISSUE TITLE
unsatisfiable subincludes lock up please

### ISSUE THREAD

**Issue by hnridder** [thought-machine/please#875]
Initialize a new repository and create empty files a/BUILD and b/BUILD. Create a toplevel BUILD file with the following contents:
```
subinclude('//a:something.build_defs')
subinclude('//b:something.build_defs')

filegroup(
   name = 'one',
   srcs = ['x'],
)
```
Now run the command `plz build //...'. Please will lock up indefinitely (or in any case longer than the standard 10min timeout). If you interrupt please and then run the same command again, please will immediately return with the message that a/BUILD doesn't contain the target something.build_defs.
Expected behaviour:

1. Please shouldn't lock up the first time and immediately report the error.
2. Please should behave the same in both invocations. After all, the build failed, so what output is there for please to reuse the second time?

**Comment by Tatskaari** [comment]
This has been fixed in #1116
