### ISSUE TITLE
Pass CLI args to build_rule

### ISSUE THREAD

**Issue by DavidGamba** [thought-machine/please#951]
I am able to pass cli args to filegroup when binary is defined.

```python
def test_script(name, build_args=[]):
  # Build script
  cmds = []
  for e in build_args:
    cmds += [ f'echo "build arg: {e}, cli args: \\\$@"' ]
  cmd = ' && '.join(cmds)
  # Create script file
  sh_cmd (
      name = f'script#{name}',
      shell = "/bin/bash",
      cmd = cmd,
      visibility = [], # TODO: How do I do private so it doesn't show in query.
      )
  return filegroup (
      name = name,
      srcs = [f':script#{name}'],
      binary = True,
      deps = [f':script#{name}'],
      )

test_script(
    name = "ts",
    build_args = ["a", "b"],
    )
```

```
$ plz run //:ts -- cli-a cli-b
build arg: a, cli args: cli-a cli-b
build arg: b, cli args: cli-a cli-b
```

How do I pass CLI args directly to a build rule? Something like:

```python
def test_build_rule(name, srcs, deps=[], *args):
  arg = args[0]
  build_rule (
    name = name,
    srcs = srcs
    deps = deps,
    cmd = " && ".join([
        f'echo {arg})',
        ])
    )
```

So I can declare the rule with a name:

```
test_build_rule(
    name = "ts",
    )
```

And run it without an intermediary shell file?

```
$ plz run //:ts -- cli-a cli-b
cli-a
```

I might be super wrong into how to go about giving people the ability to run arbitrary tasks from the CLI.

**Comment by Tatskaari** [comment]
Yeah you probably don't want to do it this way. It would make building that rule non-deterministic. I would suggest that you create a python_binary, go_binary, sh_cmd or whatever that does what you want. You can then alias them in you plzonfig. In please we have done something similar for calling the bootstrap.sh command:

```
[alias "bootstrap"]
desc = Bootstraps Please from scratch
cmd = run //:bootstrap --
```

The `--` is important here as any additional non-positional arguments will be passed to your python/go/sh binary.
