### ISSUE TITLE
pip_library from repo

### ISSUE THREAD

**Issue by henrym6003** [thought-machine/please#952]
Hi all, trying to understand what I might be doing wrong here:
```
pip_library(
    name = "fhirclient",
    version = "4.0.0",
    use_pypi = False,
    repo = "git+https://github.com/smart-on-fhir/client-py.git@master#egg=fhirclient"
)
```

When i build this, it will result in:
```
Build stopped after 680ms. 1 target failed:
    //third_party/python:_fhirclient#wheel
Error building target //third_party/python:_fhirclient#wheel: exit status 1
Looking in links: git+https://github.com/smart-on-fhir/client-py.git@master#egg=fhirclient
Collecting fhirclient==4.0.0
  Could not find a version that satisfies the requirement fhirclient==4.0.0 (from versions: )
No matching distribution found for fhirclient==4.0.0
13:52:53.289 CRITICAL: lstat fhirclient: no such file or directory
```

running a simple pip install works
```
pip install git+https://github.com/smart-on-fhir/client-py.git@master#egg=fhirclient
```

How do I get this to work in plz?

Thanks in advance

**Comment by Tatskaari** [comment]
Repo there refers to a pip repo. It's actually passed to `pip install --find-links` which tried to search the page you linked to for any .tar.gz or .whl files for the specified package. As what you liked to is a git repository, it failed. 

Perhaps we can have a nice way to create a .whl from a git repo that can then be libraried into python_library and python_binary rules. I'm going to close this issue but if this is still important to you feel free to reply and we can consider making that enhancement.
