### ISSUE TITLE
How to list filegroup changed files

### ISSUE THREAD

**Issue by DavidGamba** [thought-machine/please#957]
I am using a filegroup rule to group files toguether

The output in debug shows:

```
15:39:47.965   DEBUG: Need to rebuild //:system_manifest, //:terraform_dev has changed
15:39:47.965    INFO: [5/7 tasks] //:terraform_dev: Built [0.0s]
```

How do I know what files changed in the filegroup? Is there a way to enable further output?
Basically it changes on every run and I need to improve my excludes to ensure it only captures the right thing.

**Comment by Tatskaari** [comment]
You can use `plz hash --detailed //:terraform_dev` to get more information on how the hash is currently built up. You can probably use that to observe what's changing manually. 

Unfortunately, when determining if a rule needs to be rebuilt, please doesn't actually know what changed. We just have a hash of all of the inputs. When we come to build it again, we re-hash it's inputs and check that against the stored hash.
