### ISSUE TITLE
Question: how to build a Go program with race detector?

### ISSUE THREAD

**Issue by advisory-lock** [thought-machine/please#964]
As title. Thanks!

**Comment by Tatskaari** [comment]
Looks like we'd need to allow additional compiler flags to be passed through from `go_library` to the `go tool compile` invocation. If you still need this feature, can you raise another issue as an enhancement.

**Comment by peterebden** [comment]
This also needs the stdlib to be cross-compiled for the race detector AFAIK (related to #1108 )
