### ISSUE TITLE
Please will not auto-download pleasings if not manually included  as sub-repo

### ISSUE THREAD

**Issue by northdpole** [thought-machine/please#965]
According to [documentation](https://please.build/pleasings.html), you can subinclude pleasings using the following in BUILD files
`subinclude("@pleasings//rust")`

Moreover same documentation page mentions:

> As noted the above solution is nice and lightweight, and Please will take care of deduplicating & caching the download from github, so it works fairly well for straightforward cases.

which matches the [code](https://github.com/thought-machine/please/blob/1c720f2ba6744e9b3ea449e92bf1cadeae8b0cc7/src/core/config.go#L349):

However, trying to build:

` subinclude("@pleasings//docker")
docker_image(
    name = "test-builder",
    dockerfile = "Dockerfile-test-builder",
    image = "test-builder-go",
)
`
errors out with the following error
`18:11:28.606 CRITICAL: No BUILD file owns file pleasings_master.zip`

It can be worked around by including pleasings as a subrepo in //third_party
but it does not match config or docs which clearly state that if pleasings are not found they will be downloaded.

**Comment by Tatskaari** [comment]
I believe this was fixed 14.6.0. Let me know if you have any further problems.
