### ISSUE TITLE
How to correctly supply information that binaries normally expect to find under $HOME?

### ISSUE THREAD

**Issue by rulatir** [thought-machine/please#972]
Since please overrides $HOME, what should I do when a binary I want to use in a build command expects some configuration to be present under $HOME?

I am aware that out-of-source configuration can introduce untracked dependencies, but I want to be in charge of deciding the correctnes vs. convenience tradeoff in this particular case. Something like AWS credentials isn't really an "input"; it is a prerequisite.

**Comment by peterebden** [comment]
You could use the `secrets` attribute of a build target, for example:
```
genrule(
    name = "myrule",
    secrets = ["~/.aws/credentials"],
    cmd = "AWS_CONFIG_FILE=$SECRETS aws ...",
)
```
