### ISSUE TITLE
Investigate -trimpath flag

### ISSUE THREAD

**Issue by peterebden** [thought-machine/please#989]
Go 1.13+ has a `-trimpath` flag on `go install` that would seem ideal to improve determinism. I tried this in #986 but unfortunately it seems to force rebuilds of the whole Go runtime (which in some cases fails, for unknown reasons).

See if we can find a way to get it working, or otherwise mimic what it would do.

**Comment by Tatskaari** [comment]
Looks like you got around to this in #1025. Should we close this issue?

**Comment by peterebden** [comment]
Yep!
